### ISSUE TITLE
Crash in callLOH with NCBI-style chromosome names (1,2,...X,Y)

### ISSUE THREAD

**Issue by lima1** [lima1/PureCN#10]
Error message:
Error in `$<-.data.frame`(`*tmp*`, "arm", value = "p") :
  replacement has 1 row, data has 0
Calls: write.csv ... callLOH -> .getArmLocations -> $<- -> $<-.data.frame
Execution halted

Problem is data(centromeres) is not converted.

**Comment by rghu** [comment]
I was wondering if this has been fixed in the current version on github?

**Comment by lima1** [comment]
Yep, should work. The other bug is fixed too. I was planning to keep these tickets open until the build problems in Bioconductor 3.6 are solved.

**Comment by lima1** [comment]
Fixed in 1.7.53. For older versions, one needs to provide the correct centromeres data.frame as runAbsoluteCN argument as workaround.
