### ISSUE TITLE
Failed preprocessIntervals (IntervalFile.R)

### ISSUE THREAD

**Issue by hoonghim** [lima1/PureCN#105]
Dear Markus,

Hello, I failed to generate an interval file from a BED file containing baits coordinates.

Could you help me how to solve it?

Below is the code.

library(PureCN)

#To read reference file
reference.file <- "/BiO/Share/Tools/gatk-bundle/2.8/b37/human_g1k_v37_decoy.chr.fasta"

#The reference file looks like this

![image](https://user-images.githubusercontent.com/42195952/66191208-c08fad80-e6c8-11e9-944d-be60741ef508.png)

#To read bed file specifying the intervals
bed.file <- "/BiO/Share/Database/agilent/SureSelect_V6_hg19/S07604514_Regions.nochr.bed"

#To read mappability file to annotate intervals with mappability score
mappability.file <- "/BiO/Share/Tools/gatk-bundle/2.8/b37/wgEncodeCrgMapabilityAlign100mer.bigWig"

#To read replication timing score to annotate intervals with replication timing score
reptiming.file <- "/BiO/Share/Tools/gatk-bundle/2.8/b37/hg19/wgEncodeUwRepliSeqK562WaveSignalRep1.bigWig"

intervals <- import(bed.file)
mappability <- import(mappability.file)
reptiming <- import(reptiming.file)

![image](https://user-images.githubusercontent.com/42195952/66186832-48bc8580-e6be-11e9-9b04-8b2366dbf1c0.png)

![image](https://user-images.githubusercontent.com/42195952/66186856-55d97480-e6be-11e9-9962-374f1a288267.png)

![image](https://user-images.githubusercontent.com/42195952/66186863-5ffb7300-e6be-11e9-9809-d66b7e6d97b3.png)

preprocessIntervals(intervals, reference.file,
                    mappability=mappability,
                    reptiming=reptiming,
                    output.file = "/BiO/Share/Tools/gatk-bundle/2.8/b37//baits_agilent_v6_hg19_intervals.txt")

#################################################################
#This is an error message
![image](https://user-images.githubusercontent.com/42195952/66186928-86211300-e6be-11e9-8a0c-8ee5a093089e.png)

#################################################################

I also tried to follow the quick manual (http://bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/Quick.pdf)
#############
#This is an example

#Generate an interval file from a BED file containing baits coordinates:
#specify path where PureCN should store reference files
$ export OUT_REF="reference_files"
$ Rscript $PURECN/IntervalFile.R --infile baits_hg19.bed \
--fasta hg19.fa --outfile $OUT_REF/baits_hg19_intervals.txt \
--offtarget --genome hg19 \
--export $OUT_REF/baits_optimized_hg19.bed \
--mappability wgEncodeCrgMapabilityAlign100mer.bigWig \
--reptiming wgEncodeUwRepliSeqK562WaveSignalRep1.bigWig

#############
#This is my trial
Rscript /BiO/Live/seunghoon/.Renv/versions/3.6.0/lib64/R/library/PureCN/extdata/IntervalFile.R --infile /BiO/Share/Database/agilent/SureSelect_V6_hg19/S07604514_Regions.nochr.bed \
--fasta /BiO/Share/Tools/gatk-bundle/2.8/b37/human_g1k_v37_decoy.fasta \
--outfile /BiO/Share/Tools/gatk-bundle/2.8/b37//baits_agilent_v6_hg19_intervals.txt \
--offtarget --genome hg19 \
--export /BiO/Share/Tools/gatk-bundle/2.8/b37//baits_agilent_v6_optimized_hg19.bed \
--mappability /BiO/Share/Tools/gatk-bundle/2.8/b37/wgEncodeCrgMapabilityAlign100mer.bigWig \
--reptiming /BiO/Share/Tools/gatk-bundle/2.8/b37/hg19/wgEncodeUwRepliSeqK562WaveSignalRep1.bigWig

#######################################################################

But the same error occurs: 

![image](https://user-images.githubusercontent.com/42195952/66187079-eadc6d80-e6be-11e9-8d1c-e85fb2591704.png)

#######################################################################
#Plus, I changed the chromosome format: All chr1~chr22, chrX
#Still, there is same error

![image](https://user-images.githubusercontent.com/42195952/66187969-08aad200-e6c1-11e9-87ce-35b38b22dac0.png)

#######################################################################

I appreciate any comments to solve this.

Sincerely,

Seung-hoon

**Comment by lima1** [comment]
Hi Seung-hoon,

I think this is related to a change in IRanges. Try updating to the latest GitHub! 

Unfortunately I changed the normal database slightly recently, so I would recommend to re-run NormalDB.R with same parameters as before.

**Comment by lima1** [comment]
Here the quick vignette for devel/Github: http://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/Quick.html

**Comment by hoonghim** [comment]
Dear Markus,

Thank you for your kind and helpful comment!

I just noticed that I removed "chr" from the original bed file. I think that made an error.

When I removed the header information from the original bed file for agilent SureSelect V6 region, this problem was solved!

Here is the code I used

Rscript /BiO/Live/seunghoon/.Renv/versions/3.6.0/lib64/R/library/PureCN/extdata/IntervalFile.R \
--infile /BiO/Share/Database/agilent/SureSelect_V6_hg19/S07604514_Regions.wo_header.bed \
--fasta /BiO/Share/Tools/gatk-bundle/2.8/b37/human_g1k_v37_decoy.fasta \
--outfile /BiO/Share/Tools/gatk-bundle/2.8/b37//baits_hg19_agilent_v6_intervals.txt \
--offtarget --genome hg19 \
--export /BiO/Share/Tools/gatk-bundle/2.8/b37//baits_optimized_hg19_agilent_v6.bed \
--mappability /BiO/Share/Tools/gatk-bundle/2.8/b37/wgEncodeCrgMapabilityAlign100mer.bigWig \
--reptiming /BiO/Share/Tools/gatk-bundle/2.8/b37/hg19/wgEncodeUwRepliSeqK562WaveSignalRep1.bigWig

Could I give one more question?
![image](https://user-images.githubusercontent.com/42195952/66360005-4d31b880-e9b4-11e9-9cb5-6d5a3213f0bc.png)

This is the result from PureCN.R using the recent PureCN version (1.15.22)

When I look through the output log message, there was a warning:

INFO [2019-10-08 02:17:54] Tumor/normal noise ratio: Inf
WARN [2019-10-08 02:17:54] Extensive noise in tumor compared to normals.

I think this warning is reasonable and doesn't make any problem

But there was an error message in another error log.:
![image](https://user-images.githubusercontent.com/42195952/66360216-3475d280-e9b5-11e9-9ce5-a0a752f2e362.png)

Error in ecdf(calls$gene.mean) :
  'x' must have 1 or more non-missing values
Calls: callAmplificationsInLowPurity -> ecdf
Execution halted

The resulting files including dnacopy.seg file were generated at the time this error log was created.


I'm not sure why this problem happened. 

Is it okay for me to continue using these result files?

Here is my script:
![image](https://user-images.githubusercontent.com/42195952/66360341-bc5bdc80-e9b5-11e9-93e4-99c4e7c44d74.png)

I followed your suggestion, "--funsegmentation PSCBS"

Thanks in advance for helping resolve the issue.

Sincerely,

Seung-hoon

**Comment by lima1** [comment]
Hi Seung-hoon,

the error happens in a new function https://github.com/lima1/PureCN/blob/master/R/callAmplificationsInLowPurity.R. Not sure why. Can you share the command you used to generate the normalDB.rds file? How many normal coverage files do you have? 

As workaround, you can simply copy the PureCN.R file and comment out the callAmpcallAmplificationsInLowPurity lines.

Markus

**Comment by hoonghim** [comment]
> Hi Seung-hoon,
> 
> the error happens in a new function https://github.com/lima1/PureCN/blob/master/R/callAmplificationsInLowPurity.R. Not sure why. Can you share the command you used to generate the normalDB.rds file? How many normal coverage files do you have?
> 
> As workaround, you can simply copy the PureCN.R file and comment out the callAmpcallAmplificationsInLowPurity lines.
> 
> Markus

Here is my command to generate the normalDB.rds

Rscript $PURECN/NormalDB.R \
--outdir /BiO/Research/UNIST-CML_MDS-HTK-2019-07/Analysis/hg37/PureCN/NormalDB \
--coveragefiles /BiO/Research/UNIST-CML_MDS-HTK-2019-07/Analysis/hg37/PureCN/Coverage/CML_to_MDS_normal.list \
--normal_panel /BiO/Research/UNIST-CML_MDS-HTK-2019-07/Analysis/hg37/PureCN/NormalDB/normals_merged_min2.vcf.gz \
--genome hg19 --assay agilent_v6

I have two normal coverage files due to the rarity of the samples.
![image](https://user-images.githubusercontent.com/42195952/66362133-83733600-e9bc-11e9-8902-b9a5684447c3.png)

Okay, I will try PureCN.R again with commenting out the callAmpcallAmplificationsInLowPurity line.

Thank you very much for your help!

Sincerely,

Seung-hoon

**Comment by lima1** [comment]
Hi Seung-hoon, 

would you be able to help me understand the callAmplificationsInLowPurity bug?

Can you update to latest GitHub (devtools::install_github("lima1/PureCN")) and then run the following code:

```
library(PureCN)
library(futile.logger)
flog.threshold("DEBUG")
x <- readRDS("/path/to/KRCMC00092_T2-D.rds")
normalDB <- readRDS("/path/to/normalDB_agilent_v6_hg19.rds")
callAmplificationsInLowPurity(x, normalDB)
```

And paste the output? This will help me to narrow the origin of the error.

Thanks,
Markus

**Comment by hoonghim** [comment]
> Hi Seung-hoon,
> 
> would you be able to help me understand the callAmplificationsInLowPurity bug?
> 
> Can you update to latest GitHub (devtools::install_github("lima1/PureCN")) and then run the following code:
> 
> ```
> library(PureCN)
> library(futile.logger)
> flog.threshold("DEBUG")
> x <- readRDS("/path/to/KRCMC00092_T2-D.rds")
> normalDB <- readRDS("/path/to/normalDB_agilent_v6_hg19.rds")
> callAmplificationsInLowPurity(x, normalDB)
> ```
> 
> And paste the output? This will help me to narrow the origin of the error.
> 
> Thanks,
> Markus

Yes, I removed the previous PureCN package from R and reinstall the newest one.

![image](https://user-images.githubusercontent.com/42195952/66716484-1a028580-ee09-11e9-8729-971695d6080b.png)

But I couldn't utilize devtools. So I followed the suggestion on github

################################################
If you want the latest and greatest from the developer branch:

BiocManager::install("lima1/PureCN")
################################################

Therefore, the following process is the result of using PureCN version 1.15.24.

![image](https://user-images.githubusercontent.com/42195952/66716554-dceac300-ee09-11e9-84b4-facf5881006e.png)

When I make normal panel vcf, I followed this manual, gatk3 SelectVariants and CombineVariants

![image](https://user-images.githubusercontent.com/42195952/66716661-3b647100-ee0b-11e9-9ede-4297eeb47c49.png)


![image](https://user-images.githubusercontent.com/42195952/66716677-6c44a600-ee0b-11e9-83bc-1b1f07324c3e.png)

[interval_weights_agilent_v6_hg19.png]

This is the result from NormalDB.R

I don't know why the all interval width values have 0 log2 ratio sd.

Below are the coverage_loess.png files from my two normal samples.

![image](https://user-images.githubusercontent.com/42195952/66716853-9c8d4400-ee0d-11e9-8b5a-4e7930ca281e.png)

![image](https://user-images.githubusercontent.com/42195952/66716867-b890e580-ee0d-11e9-980a-a5c9fa5d4184.png)

Thank  you for your consideration.

Sincerely,

Seung-hoon

**Comment by lima1** [comment]
That helps a lot. Is it possible that the two normals are identical? I think that’s the reason the log ratios are all 0.

**Comment by hoonghim** [comment]
> That helps a lot. Is it possible that the two normals are identical? I think that’s the reason the log ratios are all 0.

Oh, when I checked the normal list for --coveragefiles option in NormalDB.R, I just noticed that I used same normal coverage_loess.txt file!

![image](https://user-images.githubusercontent.com/42195952/66717401-8bdfcc80-ee13-11e9-990f-ca10f46cd148.png)
[interval_weights_agilent_v6_hg19.png]

I think I have to run PureCN.R again using this correct NormalDB!

Thank you so much for your help!

Sincerely,

Seung-hoon

**Comment by lima1** [comment]
Great, I'll add a check in createNormalDatabase for that ;-)

Yes, I would re-run, it might reduce the noise a bit. If you can get a few more normals in the future, that would probably be a significant improvement. But the log-file you sent looks in general good.
 
I'm closing now, feel free to add a new issue when something comes up.
