### ISSUE TITLE
interval_weights.txt File

### ISSUE THREAD

**Issue by sbagg** [lima1/PureCN#110]
Is the interval_weights file that was produced with NormalDB.R in previous builds no longer produced in runs.  When looking in the "NEWS" file in PureCN, where you implying that the interval file is now created within another function and no longer produces the interval_weights text file output and only the PNG output?

**Comment by lima1** [comment]
Correct, the weights are now included in the normalDB.rds file. The PureCN.R log file should tell you that it is using the weighted DNAcopy/PSCBS.

**Comment by lima1** [comment]
Closing now, but feel free to add something in case you run into problems with 1.16.
