### ISSUE TITLE
Provide Version Flexibility

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#111]
We want to be able to use different versions of PureCN for different projects (e.g. continue using the older version for an older project that has already been established with an older version of PureCN, while using a newer version for a new project).

It is possible in R to install different versions of the same package under different names.  One way is to use the lib argument to install.packages, so for example, instead of:

`install.packages("PureCN")`

you can do:

`install.packages("PureCN", lib=file.path(.libPaths(), "PureCN_1.15.27"))`

Then, to use that package:

`library("PureCN", lib.loc=file.path(.libPaths(), "PureCN_1.15.27")`

The problem we have is that some of the .R programs within PureCN contain `library("PureCN")`, causing them to access the wrong library.

I'd like to see some mechanism to allow the PureCN package version to be selected by the user.  One way would be to add arguments to specify the lib.loc to be used for the PureCN package, to be used in any "library()" calls.  Or, perhaps there is already a well-established way to do this.  Ideally, the .R program would look to see what directory it is running out of, and infer the lib.loc from that.  For example, if PureCN.R detected that it was file `xxxx/library/PureCN_1.15.27/PureCN/extdata/PureCN.R`, it would use `lib.loc=PureCN_1.15.27`.

**Comment by lima1** [comment]
Yes, that's possible. See for example "Managing multiple versions" in https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html for recommendations how to realize that.

**Comment by tedtoal** [comment]
As I read that, it seems that the entire library of all installed packages must be duplicated for each different version one wants to use.  So, if I had three versions of PureCN I wanted to use, and 4 versions of some other package, I'd need to have 12 copies of the library directory, each with all packages in it.  Or am I misunderstanding it?

**Comment by lima1** [comment]
You can provide multiple library paths in R_LIBS_USER, so you could have your default without PureCN and then create a library directory containing only PureCN. You can also use something like modules (http://modules.sourceforge.net/).

**Comment by tedtoal** [comment]
Ahh, okay, that makes sense now, I can see how to do it.  Thanks!
