### ISSUE TITLE
_genes.csv seg.mean for wrong segment

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#112]
In PureCN version 1.13.21 (haven't yet been able to test it in later versions), I have a case where the _genes.csv file shows a seg.mean value that is for segment ID 103 even though the seg.id column contains value 104.  In this case, the gene, DDX5, overlaps both segments 103 and 104.  In that case I would think that maybe the _genes.csv file would have two entries for that gene, but if it only has one entry, I would expect consistency between the seg.mean value and the seg.id value.

**Comment by lima1** [comment]
Yeah, that's a tricky case. These genes are essentially flagged by the breakpoints column, so you know that various segments overlap. The seg.id points to the smallest overlapping segment, idea being that the longer one is more likely normal. Agree that the seg.mean should be the same, it currently is the median of all overlapping segments. I'll change that.

**Comment by tedtoal** [comment]
Great!
