### ISSUE TITLE
default ignored types for filterVcfMuTect2

### ISSUE THREAD

**Issue by liuxq0707** [lima1/PureCN#116]
ignore = c("clustered_events", "t_lod", "str_contraction", "read_position", "fragment_length", "multiallelic", "clipping", "strand_artifact")

for these types ignored by default for filterVcfMuTect2, does that mean items with any of these types from Mutect-2 are less likely to be sequencing artifact?

**Comment by lima1** [comment]
No, variants with those flags are ignored. This list might be outdated, let me know if the list is not complete.

Proper support for Mutect2 will be available in the next release (out in April), stay tuned!

**Comment by liuxq0707** [comment]
Thanks, Markus. Look forward to the new version.

**Comment by mgfield** [comment]
Great news.  Looking forward to it as well.  Any update on when the version will be released? Thanks!

**Comment by lima1** [comment]
Sorry guys, very soon! Should be available this month.

**Comment by lima1** [comment]
I think this should be vastly improved in 1.19.2 now.

**Comment by lima1** [comment]
Closing now, please let me know in case 1.19.2 did not sufficiently address this.
