### ISSUE TITLE
Can processMultipleSamples be used for hg38-aligned data by using the centromeres paramter? 

### ISSUE THREAD

**Issue by vedellpt** [lima1/PureCN#118]
Hi. I am wondering if processMultipleSamples can be used for hg38-aligned data by using the centromeres parameter. In the documentation, there is an indication that the genome parameter is used to get centromere positions. I tried using processMultipleSamples using hg38 as the value for the genome but an empty result was returned. I noticed that the copynumber package multipcf function upon which I understand that processMultipleSamples depends has the statement that only  "hg19", "hg18", "hg17" and "hg16" are allowed options for its assembly parameter. I noticed that multipcf has an arms parameter which can be used to override arms as determined by its assembly parameter. Might  the centromeres parameter of processMultipleSamples be used to appropriately populate the arms parameter of multipcf, thereby allowing for use for hg38-algned data? Thanks for your consideration of this inquiry.

**Comment by lima1** [comment]
I think this centromeres argument requires the actual coordinates. These should be available in data(centromeres, package="PureCN"). But I see how this is confusing and should probably support the genome version. Let me know if this works with the hg38 centromeres and I'll add this soon.

**Comment by vedellpt** [comment]
Hi,

Thanks for your reply and recommendation. Yes, using centromeres$hg38 as the centromeres argument worked after loading centromeres using the command you recommended.  I just left the genome argument unpopulated. I compared the processMultipleSamples example from the vignette both ways (using genome=”hg19” and using centromere=centromeres$hg38) and was able to see an appropriate difference as shown below:

> seg <- processMultipleSamples(tumor.coverage.files,
+ sampleids = c("Sample1", "Sample2"),
+ normalDB = normalDB,
+ genome = "hg19", verbose = FALSE)
…
> class(seg)
[1] "data.frame"
> dim(seg)
[1] 120   6
> data(centromeres, package="PureCN")
> seg_v3_2 <- processMultipleSamples(tumor.coverage.files,
+ sampleids = c("Sample1", "Sample2"),
+ normalDB = normalDB,
+ centromeres=centromeres$hg38, verbose = FALSE)
…
> all.equal(seg, seg_v3)
[1] "Component \"loc.start\": Mean relative difference: 0.02688715" "Component \"num.mark\": Mean relative difference: 0.005128205" "Component \"seg.mean\": Mean relative difference: 0.00419972"
> sum(seg$chrom==seg_v3$chrom)
[1] 120
> sum(seg$loc.start==seg_v3$loc.start)
[1] 118
> which(seg$loc.start!=seg_v3$loc.start)
[1]  57 117
> seg[c(57,117),]
         ID chrom loc.start  loc.end num.mark seg.mean
57  Sample1    20  29978226 62610730      195   0.1261
117 Sample2    20  29978226 62610730      195   0.0882
> seg_v3[c(57,117),]
         ID chrom loc.start  loc.end num.mark seg.mean
57  Sample1    20  30784255 62610730      194   0.1264
117 Sample2    20  30784255 62610730      194   0.0888
> centromeres$hg19[20]
GRanges object with 1 range and 0 metadata columns:
     seqnames            ranges strand
        <Rle>         <IRanges>  <Rle>
  22    chr20 26369569-29369569      *
  -------
  seqinfo: 31 sequences from an unspecified genome; no seqlengths
> centromeres$hg38[20]
GRanges object with 1 range and 0 metadata columns:
     seqnames            ranges strand
        <Rle>         <IRanges>  <Rle>
  22    chr20 26436232-30038348      *
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths
>

Thanks again for your help. I appreciate it.

**Comment by lima1** [comment]
I tried to reproduce this. Looks like genome = "hg38" works for me.
