### ISSUE TITLE
behavior of undo.SD for PSCBS segmentation

### ISSUE THREAD

**Issue by vedellpt** [lima1/PureCN#119]
Hi,

I have a question with regard to the "--undosd" parameter for the PureCN.R script when used in combination with "--funsegmentation=PSCBS". When I populate this by, for example, "--undosd=1.125", I have noticed, from the log file, that the undo.SD parameter can still be changed within the algorithm. I think it is nice to have this as a way to set the initial undo.SD as the current behavior is, but sometimes it would be nice to fix the undo.SD parameter. For example, I am wanting to compare results across a set of values for undo.SD. Is there a way to force the value of undo.SD to stay the same? Thanks.

**Comment by lima1** [comment]
I think this happens when the number of segments exceeds the maximum. Try setting this value higher and it should keep it constant.

**Comment by vedellpt** [comment]
OK. Thanks for this information. I will increase "--maxsegments=MAXSEGMENTS" sufficiently.

**Comment by lima1** [comment]
Closing for now, feel free to reopen if you run into issues here.

**Comment by vedellpt** [comment]
I had meant to verify that, yes, that worked. When, I increased max.segments to 2000, which is well above the range I am seeing, then the undo.SD value stayed equal to the input parameter value. Thanks for that recommendation!
