### ISSUE TITLE
tumor.coverage.file and normalDB do not align.

### ISSUE THREAD

**Issue by Shenglai** [lima1/PureCN#125]
Hi,

I have created normalDB with PureCN 1.14.3, and was trying to proceed with the GATK4 tumor only VCF.

```
    Rscript \
    /usr/local/lib/R/site-library/PureCN/extdata/PureCN.R \
    --cores \
    8 \
    --force \
    --genome \
    hg38 \
    --intervals \
    /var/lib/cwl/stg04036b18-89e0-459b-8b47-ad66d5ed54f6/GRCh38.d1.vd1.S04380110_Covered.hg38.txt \
    --normaldb \
    /var/lib/cwl/stgd62d1ce3-86d2-4daf-aef9-ff409aa61ad6/normalDB.sureselectxthumanallexonv5.tcga-meso.hg38.rds \
    --out \
    . \
    --outvcf \
    --postoptimize \
    --vcf \
    /var/lib/cwl/stg78adfe65-14c9-4984-b083-e7eadc80e38d/ba299f88-ab40-402e-afe5-7753dea249ba.wxs.tumor_only.gatk4_mutect2.raw_somatic_mutation.vcf.gz \
    --sampleid \
    c40c577a-e52d-4dc9-9b2c-327c70400b6b \
    --seed \
    150 \
    --tumor \
    /var/lib/cwl/stg304644f5-59dd-4ee0-a74b-21cc7afe6b43/c40c577a-e52d-4dc9-9b2c-327c70400b6b_gdc_realn_coverage_loess.txt
[1] "/var/spool/cwl"
INFO [2020-05-28 05:20:03] Loading PureCN 1.14.3...
FATAL [2020-05-28 05:20:12] tumor.coverage.file and normalDB do not align.

FATAL [2020-05-28 05:20:12]

FATAL [2020-05-28 05:20:12] This is most likely a user error due to invalid input data or

FATAL [2020-05-28 05:20:12] parameters (PureCN 1.14.3).

Error: tumor.coverage.file and normalDB do not align.

This is most likely a user error due to invalid input data or
parameters (PureCN 1.14.3).
```

It seems there is something wrong in the normalDB, so I'm wondering how I can debug in this situation.

Sorry if it's a repetitive issue.

Thanks.

**Comment by lima1** [comment]
Hi,

this simply means that --normaldb and --tumor were most likely generated with different interval files. Is this possible?

Also, can you update to latest stable version?

`BiocManager::install("lima1/PureCN", ref = "RELEASE_3_11")
`

Markus

**Comment by Shenglai** [comment]
Thanks Markus,

I just checked they are using the same bait file, at least the same from the documents. Is there a way I could see in the normaldb? Do we have command line store in the normaldb that I could check?

Will the latest stable version be compatible with old normaldb?

**Comment by lima1** [comment]
It's compatible, but you'll get some improvements when you re-run. 

I think I store the normaldb parameters, yes. Load it in R with readRDS and check attr(rds),

For tumor-only, you should get a huge improvement when you generate a mapping bias file (first generate a multi-sample VCF with all normals, see vignette, then provide this VCF in NormalDB.R via --normal_panel. The resulting mapping_bias.rds file is then used in PureCN.R via --mappingbiasfile).

I would quickly re-run NormalDB.R and see if the error disappears. Pretty sure it will.

**Comment by Shenglai** [comment]
Oh, I accidentally closed it, but I guess it should.

So, I have checked the `myRDS$intervals` and compared with the intervals from my run, it is different. I will check to see if I could retrieve the old intervals, otherwise, I probably will re-create the normaldb. Thanks for your help!

For the mappingbiasfile, I need to check our implementation, b/c I vaguely remember we have it in the workflow if it's not the new feature from the latest stable version.

**Comment by lima1** [comment]
Good. Yes, the mappingbiasfile was introduced a while back:

https://github.com/lima1/PureCN/blob/master/NEWS

**Comment by Shenglai** [comment]
Hi Markus,

Sorry to reopen the issue. I have checked the successful run from my side using, different bait file and normaldb, it seems the `$intervals` from normalDB is also not the same as the bait file. So I'm wondering if I have misunderstood something here.

So I _think_ the `tumor.coverage.file` will inherit the same intervals from the PureCN intervals output, which has the same intervals from the bait file input. So I'm comparing the `$intervals` from normalDB with the bait file to see if they are the same, and it seems it's not even from a successful run.

My question is if I'm doing the right comparison, or if I should check whether `$intervals` is a subset of the bait file.

Also, I'm curious about your previous comment. So I checked the Panel of Normal I have from GATK3 and GATK4, none of them has AD field unfortunately. Are you suggesting the error will go away if I use the latest stable version of PureCN with a PoN?

**Comment by lima1** [comment]
Hi,

normalDB.R should point you to the list of normal coverage files that were used to build the database. You can compare them if they have the provide the same intervals. But yes, turn the baits BED file into an interval file with IntervalFIle.R, re-run Coverage.R on the normals, build the database with NormalDB.R and you should be fine.

Possible that $intervals in normalDB are filtered, can't remember right now.

Yes, the SNP pool of normals is currently a bit of a pain to generate - working on it. 

For now, run Mutect 1/2 on the normals (as you probably already have) and generate a multi-sample VCF, for example with GATK3 as described in the vignette FAQ. I'm looking into taking GATK4 GenomicsDB files as input, but I would not wait for that. Once you have the multi-sample normal VCF, you can provide it NormalDB.R with --normal_panel.

**Comment by Shenglai** [comment]
Hi,

I think I have found the issue why PureCN complains. It seems I did not set `mintargetwidth` when creating the intervals for normalDB runs, but have that set to 100 when creating the intervals for PureCN. 

Thanks for all the information and help again.
