### ISSUE TITLE
Conda package outdated

### ISSUE THREAD

**Issue by slavnycoder** [lima1/PureCN#128]
Please update this package https://anaconda.org/bioconda/bioconductor-purecn

**Comment by lima1** [comment]
Hi @slavnycoder,

The latest stable requires an updated R 4.0 or higher, which impacts lots of packages and might conflict with some in your environment.

So I would suggest starting from a fresh environment and requesting the latest stable version - this should tell you any conflicts.

`conda install -c bioconda bioconductor-purecn=1.18.0`

If you are planning to use Mutect2/GATK4, you unfortunately need to use the current GitHub master branch. I try to keep everything stable, but it won't be as thoroughly tested as stable, obviously.

Cheers,
Markus
