### ISSUE TITLE
Error: logical subscript contains NAs

### ISSUE THREAD

**Issue by srhvng** [lima1/PureCN#131]
I'm getting the errror - 'logical subscript contains NAs'. I know the problem is with my VCF, but I don't understand why my VCF is not compatible. Please help me understand where my VCF is failing.

INFO [2020-07-31 16:10:44] Loading PureCN 1.18.0...
INFO [2020-07-31 16:10:46] Mean coverages: chrX: 1972.98, chrY: 1488.86, chr1-22: 3972.70.
INFO [2020-07-31 16:10:46] Sample sex: M
INFO [2020-07-31 16:10:46] ------------------------------------------------------------
INFO [2020-07-31 16:10:46] PureCN 1.18.0
INFO [2020-07-31 16:10:46] ------------------------------------------------------------
INFO [2020-07-31 16:10:46] Arguments: -tumor.coverage.file ~/$SAMPID_coverage_loess.txt.gz -log.ratio  -seg.file  -vcf.file ~/$SAMPID_SmallVariants.genome.dbsnp.vcf.gz -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.segmentation NULL,0.005,NULL -sampleid TMB-31_L2.UP04 -min.ploidy 1 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file ~/baits_hg19_intervals.txt -max.segments 300 -plot.cnv TRUE -DB.info.flag DB -POPAF.info.field POP_AF -model beta -post.optimize FALSE -BPPARAM  -log.file ~/$SAMPID.log -normal.coverage.file <data> -normalDB <data> -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2020-07-31 16:10:46] Loading coverage files...
INFO [2020-07-31 16:10:47] Mean target coverages: 3892X (tumor) 3893X (normal).
INFO [2020-07-31 16:10:47] Mean coverages: chrX: 1972.98, chrY: 1488.86, chr1-22: 3972.70.
INFO [2020-07-31 16:10:47] Mean coverages: chrX: 1973.71, chrY: 1488.75, chr1-22: 3976.02.
INFO [2020-07-31 16:10:49] Removing 70 intervals with missing log.ratio.
INFO [2020-07-31 16:10:49] Removing 27 low/high GC targets.
INFO [2020-07-31 16:10:49] Removing 482 intervals excluded in normalDB.
INFO [2020-07-31 16:10:49] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2020-07-31 16:10:49] Removing 1419 low coverage (< 0.0015X) intervals.
INFO [2020-07-31 16:10:49] Using 23766 intervals (10002 on-target, 13764 off-target).
INFO [2020-07-31 16:10:49] Ratio of mean on-target vs. off-target read counts: 6.97
INFO [2020-07-31 16:10:49] Mean off-target bin size: 193706
INFO [2020-07-31 16:10:49] AT/GC dropout: 1.02 (tumor), 1.02 (normal).
INFO [2020-07-31 16:10:49] Loading VCF...
INFO [2020-07-31 16:11:12] Found 1983575 variants in VCF file.
WARN [2020-07-31 16:11:14] vcf.file has no DB or POP_AF info field for membership in germline databases. Guessing it based on available dbSNP ID.
INFO [2020-07-31 16:11:15] 3356 (0.2%) variants annotated as likely germline (DB INFO flag).
INFO [2020-07-31 16:12:08] Sample.stitched.bam is tumor in VCF file.
INFO [2020-07-31 16:12:18] 7 homozygous and 2 heterozygous variants on chrX.
INFO [2020-07-31 16:12:18] Sex from VCF: NA (Fisher's p-value: 0.009, odds-ratio: 6.82).
INFO [2020-07-31 16:13:56] Initial testing for significant sample cross-contamination: unlikely
Error: logical subscript contains NAs
Execution halted

**Comment by lima1** [comment]
Hi, I assume you get the same error with the latest Github version 1.19.10? 

Can you share what variant caller you are using?

You have a lot of variants in the VCF, I would recommend to do more stringent artfiact filtering upstream. PureCN won't do standard filtering like strand bias etc. 

PureCN fails in the depth/allelic fraction filtering, I assume you have some variants with 0 coverage or allelic fraction? It obviously shouldn't crash, but please let me know if removing those fixes it.

**Comment by srhvng** [comment]
I haven't tried the latest Github version yet. I believe Illumina is the variant caller being used. I will try these options out and follow up.

**Comment by srhvng** [comment]
I am still getting the same error removing them and with the latest Github version.

**Comment by lima1** [comment]
Okay, let me check where it could happen.

**Comment by lima1** [comment]
The latest commit probably won't fix it, but would you mind trying anyways? This checks for missing values in allelic fractions.

If you cannot share a minimal VCF for reproducing this crash, can you run following:


vcf <- PureCN:::.readAndCheckVcf("SAMPID_SmallVariants.genome.dbsnp.vcf.gz", "hg19")
debug(filterVcfBasic)
filterVcfBasic(vcf)

And then press enter until the crash and tell me the line?

**Comment by srhvng** [comment]
It crashed on line 36 - .checkVcfNotEmpty(vcf).

I'm not familiar with the commit. Do I just copy it over into R? I'm getting the error that ".addFaField" function is not found.

**Comment by lima1** [comment]
You can install it with: BiocManager::install("lima1/PureCN").

How many variants do you now have? There should not be much more than 1000 to 1500 per megabase.

**Comment by srhvng** [comment]
I've installed lima1/PureCN and called the library, but I'm still not able to run the commit. Function .addFaField and test_that not found.

**Comment by lima1** [comment]
If you ran BiocManager::install("lima1/PureCN"), you're all good. That will include the latest changes.

**Comment by srhvng** [comment]
Ok. I reran the the PureCN script and am still having the same error. What did you mean with "How many variants do you now have?"? Is that something the latest changes should tell me? I'm sorry. I am so lost now.

**Comment by lima1** [comment]
This line here tells you how many variants you have in your input VCF:

`INFO [2020-07-31 16:11:12] Found 1983575 variants in VCF file.
`

If you don't use Mutect 1 or 2, make sure that basic quality filtering is performed upstream of PureCN. That should reduce the number of variants dramatically.

**Comment by srhvng** [comment]
I see. The log is slightly different now, but I still have 1983575 variants in my VCF.

INFO [2020-07-31 19:11:07] Mean coverages: chrX: 1972.98, chrY: 1488.86, chr1-22: 3972.70.
INFO [2020-07-31 19:11:07] Sample sex: M
WARN [2020-07-31 19:11:08] Recommended to provide --funsegmentation PSCBS.
INFO [2020-07-31 19:11:09] ------------------------------------------------------------
INFO [2020-07-31 19:11:09] PureCN 1.19.10
INFO [2020-07-31 19:11:10] ------------------------------------------------------------
INFO [2020-07-31 19:11:12] Arguments: -tumor.coverage.file ~\$SAMPID_coverage_loess.txt.gz -log.ratio  -seg.file  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.segmentation 0.005,NULL -sampleid $SAMPID -min.ploidy 1 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file ~/baits_hg19_intervals.txt -max.segments 300 -plot.cnv TRUE -DB.info.flag DB -POPAF.info.field POP_AF -model beta -post.optimize FALSE -BPPARAM  -log.file ~/$SAMPID.log -normal.coverage.file <data> -vcf.file <data> -normalDB <data> -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2020-07-31 19:11:13] Loading coverage files...
INFO [2020-07-31 19:11:31] Mean target coverages: 3892X (tumor) 3893X (normal).
INFO [2020-07-31 19:11:31] Mean coverages: chrX: 1972.98, chrY: 1488.86, chr1-22: 3972.70.
INFO [2020-07-31 19:11:32] Mean coverages: chrX: 1973.71, chrY: 1488.75, chr1-22: 3976.02.
INFO [2020-07-31 19:11:35] Removing 70 intervals with missing log.ratio.
INFO [2020-07-31 19:11:35] Removing 27 low/high GC targets.
INFO [2020-07-31 19:11:36] Removing 482 intervals excluded in normalDB.
INFO [2020-07-31 19:11:36] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2020-07-31 19:11:37] Removing 1419 low coverage (< 0.0015X) intervals.
INFO [2020-07-31 19:11:37] Using 23766 intervals (10002 on-target, 13764 off-target).
INFO [2020-07-31 19:11:38] Ratio of mean on-target vs. off-target read counts: 6.97
INFO [2020-07-31 19:11:38] Mean off-target bin size: 193706
INFO [2020-07-31 19:11:39] AT/GC dropout: 1.02 (tumor), 1.02 (normal). 
INFO [2020-07-31 19:11:39] Loading VCF...
INFO [2020-07-31 19:11:40] Found 1983575 variants in VCF file.
WARN [2020-07-31 19:11:43] vcf.file has no DB or POP_AF info field for membership in germline databases. Guessing it based on available dbSNP ID.
INFO [2020-07-31 19:11:46] 3356 (0.2%) variants annotated as likely germline (DB INFO flag).
INFO [2020-07-31 19:11:53] Sample.stitched.bam is tumor in VCF file.
INFO [2020-07-31 19:12:02] 7 homozygous and 2 heterozygous variants on chrX.
INFO [2020-07-31 19:12:02] Sex from VCF: NA (Fisher's p-value: 0.009, odds-ratio: 6.82).
INFO [2020-07-31 19:14:28] Initial testing for significant sample cross-contamination: unlikely
Error: logical subscript contains NAs

**Comment by lima1** [comment]
If you can share a test VCF, I’m happy to have a look. But I would still recommend starting with a VCF filtered following recommendations of the variant callers documentation. Make sure that germline variants are not filtered out.

**Comment by srhvng** [comment]
Do you have an email I send to?

**Comment by lima1** [comment]
Markus.riester at Novartis dot com

**Comment by srhvng** [comment]
Somehow, when I reran the script this morning, my vcf is going through. Thank you! I am closing this issue.
