### ISSUE TITLE
Threshold for supporting reads

### ISSUE THREAD

**Issue by Admera2020** [lima1/PureCN#133]
Hello Markus, 

I am running PureCN with Pisces VCF and with tumor only mode, and I observed that the supporting reads threshold is varied across the samples, I am curious to know if there is a way to control that or what goes into the calculation for setting the threshold. The reason I am bringing this up is that we have a known true positive somatic variant (very critical one) that is being filtered out due to the "supporting reads" threshold and I was hoping to rescue it by adjusting parameters. 

Best, 
Nihir

**Comment by lima1** [comment]
Hi Nihir,

you can lower the error rate in PureCN.R --error.  That should fix it. 

In case you observe that your on-target noise is significantly lower than off-target, try the current GitHub., btw. We noticed a good boost in sensitivity of detecting small deletions that were missed due to the off-target noise.

Markus

**Comment by lima1** [comment]
I should add this is something I was planning to change, instead of using a predefined error rate, using the BQ field. Not sure this will make it in the fall release though.

**Comment by Admera2020** [comment]
Hello Marcus, 

Thank you for the quick responses.  I will test with the -error and will also test the latest github version. Currently, I am at 1.19.9. 
Regarding BQ, that will be useful for Mutect2, but Pisces doesn't seem to generate BQ tag. But still, I will look forward to the release as we are planning to switch Mutect2 for all samples anyways. 

Thanks,
Nihir

**Comment by lima1** [comment]
Sounds good. There were some rather extensive code cleanups after 1.19.9 that so far didn't seem to break anything, but let me know if something is weird - probably not your fault.

**Comment by Admera2020** [comment]
I will certainly do so.
