### ISSUE TITLE
Error in PredictSomatic

### ISSUE THREAD

**Issue by Admera2020** [lima1/PureCN#134]
Hello Markus, 

I think I have hit the blocker. I am getting the below error, that I didn't see till 1.19.10. 
```
Error in predictSomatic(ret, return.vcf = TRUE, vcf.field.prefix = "PureCN.") :
  unused argument (vcf.field.prefix = "PureCN.")
Execution halted

```
Best, 
Nihir

Sounds good. There were some rather extensive code cleanups after 1.19.9 that so far didn't seem to break anything, but let me know if something is weird - probably not your fault.

_Originally posted by @lima1 in https://github.com/lima1/PureCN/issues/133#issuecomment-668690397_

**Comment by lima1** [comment]
That argument was moved to runAbsoluteCN. Is this in your code or did some of the command line tools fail?

**Comment by Admera2020** [comment]
I found the issue I was running PureCN through the command line and the RScript was still using the script from 1.19.9. 
Sorry for the confusion.
