### ISSUE TITLE
Resizing small target regions: IRanges 'width(x)' cannot contain negative integers

### ISSUE THREAD

**Issue by dongjoban17** [lima1/PureCN#135]
Hello,

I have installed PureCN from the master branch and am running into following error when running `IntervalFile.R`:
```
WARN [2020-08-09 18:49:10] Coverage data contains single nucleotide intervals.
WARN [2020-08-09 18:49:11] Found small target regions (< 100bp). Will resize them.
Error in validObject(x) : invalid class “IRanges” object:
    'width(x)' cannot contain negative integers
Calls: preprocessIntervals ... end<- -> end<- -> end<- -> .set_IRanges_end -> validObject
```
This seems to be caused by input target region `.bed` file for `--infile` option. After removing the target regions of length < 100bp, it seemed to run okay. However, it does throw out a decent number of lines in the `.bed` file and I was wondering if resizing process can be modified to avoid omitting them.

As a reference, I'm trying to use Agilent SureSelect V7 target regions.

**Comment by lima1** [comment]
You are using official v7 baits BED files? Can you share the file name so I can download and reproduce? Make sure to use the baits, not targets. I thinks baits is called covered. But either way, it should not crash.

**Comment by dongjoban17** [comment]
I downloaded covered instead of regions `.bed` file and it seemed to work fine. Do you know what the difference is between the two aside from annotation column? They seem to have similar number of lines.

**Comment by lima1** [comment]
Covered are the baits, regions are the exons. For copy number calling, it makes more sense to look at the baits.
