### ISSUE TITLE
Attempted adding gene symbols to intervals. Heuristics have been used to pick symbols for overlapping genes.

### ISSUE THREAD

**Issue by starz77** [lima1/PureCN#139]
Hello, I use 'pureCN/IntervalFile.R' for my geneset for research

There's an error message.

Attempted adding gene symbols to intervals. Heuristics have been used to pick symbols for overlapping genes.

Let me know the reason.

thank you.

**Comment by lima1** [comment]
Just a warning that’s pretty normal. You can double check that the symbol picked match with your expectations.
