### ISSUE TITLE
Error in pdf(paste0(out, "_segmentation.pdf"), width = 10, height = 11)

### ISSUE THREAD

**Issue by starz77** [lima1/PureCN#140]
Hello,

there's an error message while running pureCN.R

Error in pdf(paste0(out, "_segmentation.pdf"), width = 10, height = 11) :
  cannot open file '/P16_segmentation.pdf'
Execution halted

P16 is one of our sample names.

I haven't seen '.pdf' file in pureCN best practices.

why are these errors came from?

Thank you.

**Comment by lima1** [comment]
Hi, make sure that your output directory points to the correct location.
e.g,  --out purecn_results/$SAMPLEID . Looks like you set --out to "/P16", thus it tried to generate output in the root directory /.
