### ISSUE TITLE
FATAL: Only tiny segments

### ISSUE THREAD

**Issue by starz77** [lima1/PureCN#141]
Hello,

I'll report an error.

I wonder what 'tiny segments' means.

Error:

FATAL [2020-09-07 10:25:16] Only tiny segments.

FATAL [2020-09-07 10:25:16]

FATAL [2020-09-07 10:25:16] This runtime error might be caused by invalid input data or parameters.

FATAL [2020-09-07 10:25:16] Please report bug (PureCN 1.16.0).

Error: Only tiny segments.

This runtime error might be caused by invalid input data or parameters.
Please report bug (PureCN 1.16.0).
Execution halted

Thank you.

**Comment by lima1** [comment]
Hi, this means that the segmentation did not find any slightly larger region in the genome without copy number breakpoints. This is highly unlikely real and points to wrong input. To help you find the issue in your setup, you would need to post all the command lines you executed including their output.

**Comment by starz77** [comment]
My script is 

PURECN=/bio/home/starz77/R/x86_64-redhat-linux-gnu-library/3.6/PureCN/extdata
REF=/bio/scratch/starz77/Reference
OUT_REF=/bio/scratch/starz77/sylee/pureCN/pureCN_Ref
INPUT=/bio/scratch/starz77/sylee
OUTPUT=/bio/scratch/starz77/sylee/pureCN/pureCN_Result
BAM=/bio/scratch/starz77/sylee/samples
i=$1

Rscript $PURECN/PureCN.R --out $OUTPUT/$i \
    --tumor $OUTPUT/$i/$i"_T"/$i"_T.bwamem.sorted.dedup.realn.recal.dedup_coverage_loess.txt.gz" \
    --normal $OUTPUT/$i/$i"_N"/$i"_N.bwamem.sorted.dedup.realn.recal.dedup_coverage_loess.txt.gz" \
    --sampleid $i \
    --vcf /bio/scratch/starz77/sylee/Mutect2_result/$i/$i".somatic.mutect2.vcf" \
    --intervals $OUT_REF/WES_GeneList_hg19_intervals.txt \
    --genome hg19

'$i' is the sample number.

Thank you.

**Comment by lima1** [comment]
Can you also post the output? Should be in a file $OUTPUT/${i}.log

**Comment by starz77** [comment]
Here's .log file


INFO [2020-09-07 10:20:16] ------------------------------------------------------------
INFO [2020-09-07 10:20:16] PureCN 1.16.0
INFO [2020-09-07 10:20:16] ------------------------------------------------------------
INFO [2020-09-07 10:20:16] Arguments: -normal.coverage.file /bio/scratch/starz77/sylee/pureCN/pureCN_Result/P42/P42_N/P42_N.bwamem.sorted.dedup.realn.recal.dedup_coverage_loess.txt.gz -tumor.coverage.file /bio/scratch/starz77/sylee/pureCN/pureCN_Result/P42/P42_T/P42_T.bwamem.sorted.dedup.realn.recal.dedup_coverage_loess.txt.gz -log.ratio  -seg.file  -vcf.file /bio/scratch/starz77/sylee/Mutect2_result/P42/P42.somatic.mutect2.vcf -normalDB  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.segmentation NULL,0.005,NULL -sampleid P42 -min.ploidy 1 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file /bio/scratch/starz77/sylee/pureCN/pureCN_Ref/WES_GeneList_hg19_intervals.txt -max.segments 300 -plot.cnv TRUE -DB.info.flag DB -POPAF.info.field POP_AF -model beta -post.optimize FALSE -BPPARAM  -log.file /bio/scratch/starz77/sylee/pureCN/pureCN_Result/P42/P42.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2020-09-07 10:20:16] Loading coverage files...
INFO [2020-09-07 10:20:21] Mean target coverages: 8X (tumor) 4X (normal).
WARN [2020-09-07 10:20:21] Allosome coverage missing, cannot determine sex.
WARN [2020-09-07 10:20:21] Allosome coverage missing, cannot determine sex.
INFO [2020-09-07 10:20:24] Removing 27999 intervals with missing log.ratio.
INFO [2020-09-07 10:20:24] Removing 22 low/high GC targets.
INFO [2020-09-07 10:20:24] Removing 7826 intervals with low total coverage in normal (< 150.00 reads).
WARN [2020-09-07 10:20:24] No normalDB provided. Provide one for better results.
INFO [2020-09-07 10:20:24] Removing 45472 low coverage (< 15.0000X) intervals.
INFO [2020-09-07 10:20:24] Using 3863 intervals (3850 on-target, 13 off-target).
INFO [2020-09-07 10:20:24] Ratio of mean on-target vs. off-target read counts: 0.00
INFO [2020-09-07 10:20:24] Mean off-target bin size: 198231
INFO [2020-09-07 10:20:24] AT/GC dropout: 0.61 (tumor), 0.56 (normal).
WARN [2020-09-07 10:20:24] High GC-bias in normal or tumor. Is data GC-normalized?
INFO [2020-09-07 10:20:24] Loading VCF...
INFO [2020-09-07 10:21:56] Found 2331555 variants in VCF file.
INFO [2020-09-07 10:22:04] Removing 7779 triallelic sites.
WARN [2020-09-07 10:22:41] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2020-09-07 10:22:45] 2323776 (100.0%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-07 10:24:25] P42_T is tumor in VCF file.
INFO [2020-09-07 10:24:46] 1115 homozygous and 511 heterozygous variants on chrX.
INFO [2020-09-07 10:24:46] Sex from VCF: NA (Fisher's p-value: < 0.0001, odds-ratio: 3.99).
INFO [2020-09-07 10:25:03] Removing 2259762 non heterozygous (in matched normal) germline SNPs.
INFO [2020-09-07 10:25:11] Initial testing for significant sample cross-contamination: unlikely
INFO [2020-09-07 10:25:13] Removing 17040 variants with AF < 0.030 or AF >= 1.000 or less than 4 supporting reads or depth < 15.
INFO [2020-09-07 10:25:13] Removing 0 low quality variants with BQ < 25.
INFO [2020-09-07 10:25:13] Total size of targeted genomic region: 1.53Mb (1.78Mb with 50bp padding).
INFO [2020-09-07 10:25:14] 10.4% of targets contain variants.
INFO [2020-09-07 10:25:14] Removing 46538 variants outside intervals.
INFO [2020-09-07 10:25:14] Found SOMATIC annotation in VCF.
INFO [2020-09-07 10:25:14] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2020-09-07 10:25:14] Found SOMATIC annotation in VCF. Setting mapping bias to 0.978.
INFO [2020-09-07 10:25:14] Excluding 0 novel or poor quality variants from segmentation.
INFO [2020-09-07 10:25:14] Sample sex: ?
INFO [2020-09-07 10:25:14] Segmenting data...
INFO [2020-09-07 10:25:14] Loading pre-computed boundaries for DNAcopy...
INFO [2020-09-07 10:25:14] Setting undo.SD parameter to 1.000000.
INFO [2020-09-07 10:25:16] Setting prune.hclust.h parameter to 0.200000.
INFO [2020-09-07 10:25:16] Found 73 segments with median size of 14.46Mb.
INFO [2020-09-07 10:25:16] Removing 1 variants outside segments.
INFO [2020-09-07 10:25:16] Using 435 variants.
FATAL [2020-09-07 10:25:16] Only tiny segments.

FATAL [2020-09-07 10:25:16]

FATAL [2020-09-07 10:25:16] This runtime error might be caused by invalid input data or parameters.

FATAL [2020-09-07 10:25:16] Please report bug (PureCN 1.16.0).


Thank you

**Comment by lima1** [comment]
Is this really low coverage data? The reported on-target average coverage in tumor is 8X and 4X in normal.  The intervals making it through the filters add up to a 1.5Mb panel. Does this sound right?

If the coverage and panel is way too low for what you expect, maybe the BAMs were aligned against hg38? If this is low coverage data, then unfortunately PureCN is probably not going to work for you.  We recommend at least 80X.

**Comment by starz77** [comment]
You mean coverage of our bam file is the reason?

I used hg19.fa reference for alignment.

I think somethings wrong with our data. coverage of our data is not so low like 8X or 4X.  

Maybe 100X or 200X if my memory is correct

I'll check what is wrong with our data.

Thank you.

**Comment by lima1** [comment]
Closing for now since the data quality or setup is likely the culprit.
