### ISSUE TITLE
trying to set metadata columns of length

### ISSUE THREAD

**Issue by starz77** [lima1/PureCN#145]
Hello,

I want to make a new interval for pureCN.

there's an error
: Error in S4Vectors:::normarg_mcols(mcols, Class, ans_len) :
  trying to set metadata columns of length 462471 on an object of length
  0
Calls: preprocessIntervals ... .readCoverageGatk3 -> GRanges -> new_GRanges -> <Anonymous>
Execution halted

when I use the previous bed file there's no error.

why is this happening?

Thank you.

**Comment by lima1** [comment]
Can you share the exact command line and BED? Feel free to send by email if you don't want to share publicly. You can also restrict the BED file to chromosome 1. Thanks.

**Comment by starz77** [comment]
Hello,

here's my script and bed file

#!/bin/bash
PURECN=/bio/home/starz77/R/x86_64-redhat-linux-gnu-library/3.6/PureCN/extdata
REF=/bio/scratch/starz77/Reference
OUT_REF=/bio/scratch/starz77/sylee/pureCN/pureCN_Ref
INPUT=/bio/scratch/starz77/sylee
OUTPUT=/bio/scratch/starz77/sylee/pureCN/pureCN_Result
BAM=/bio/scratch/starz77/sylee/samples

# specify path where PureCN should store reference files
Rscript $PURECN/IntervalFile.R --infile S04380110_AllTracks_ex.bed \
    --fasta $REF/hg19/hg19_1-22-X-Y-M.fa --outfile $OUT_REF
/S04380110_AllTracks.interval.txt \
    --offtarget --genome hg19 \
    --export $OUT_REF/S04380110_AllTracks_interval_optimized_hg19.bed
 S04380110_AllTracks.bed
<https://drive.google.com/file/d/1_iy_9QDR0uhJDXlP0dKPz5gtlLih2dTO/view?usp=drive_web>
 S04380110_AllTracks_2.bed
<https://drive.google.com/file/d/1mDihos7rOBSUyvAhlefadDajVLXMV3md/view?usp=drive_web>

and I tried using 'S04380110_AllTracks.bed' first.

and tried again 'S04380110_AllTracks_2.bed' which the same format as I ran
successfully last time.

thank you
ᐧ

2020년 9월 16일 (수) 오후 10:37, Markus Riester <notifications@github.com>님이 작성:

**Comment by lima1** [comment]
Looks like there are 2 files concatenated.

```
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 230419 did not have 4 elements

```
I removed everything below this line and it seems to work.

This should probably die more gracefully.

**Comment by lima1** [comment]
I would also recommend downloading a mappability file. Google for wgEncodeCrgMapabilityAlign100mer.bigWig

**Comment by starz77** [comment]
Thanks for your help and suggestions

It works well with the mappability file.
ᐧ

2020년 9월 17일 (목) 오후 1:00, Markus Riester <notifications@github.com>님이 작성:
