### ISSUE TITLE
RFE: Provide a function to plot only segmentation results

### ISSUE THREAD

**Issue by lbeltrame** [lima1/PureCN#146]
PureCN.R produces, as part of the `RunAbsoluteCN` call, plots of segments with total copy number, without BAF and the other plots, the one that are saved with the name `<sampleid>_segmentation.pdf`. <strike>As far as my cursory look in the code suggests, there is no way to plot them otherwise.</strike>

It would be useful to have a function to plot the segments and the individual copy number bins.  Use case: produce some of the plots as part of reports/figures, when you're not interested in the BAF but you are interested in the copy number and segments alone, especially if you have PureCN handle the segmentation (otherwise you could use CNVkit or the GATK to do the plots).

**Comment by lbeltrame** [comment]
I see that the plots depend on the segmentation function done, so it might be hard to do that.

**Comment by lima1** [comment]
Hi Luca, 

it does make sense, it's a bit of a hack right now and bothers me too. I was planning  (#87) to replace most plots with an external package, most likely https://doi.org/doi:10.18129/B9.bioc.CopyNumberPlots. This will likely come in the spring 2021 release. Stay tuned. Closing now, but referencing the corresponding ticket.
