### ISSUE TITLE
% SNP using bcbio mutect2 pipeline

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#147]
Hi MArkus,

I am now running using a padded exome bed, ive included both a PON for mutect and for purecn. It looks like this resolved the off target SD issues but the known germline are lower:

extracts from a few logs:

INFO [2020-09-16 16:45:33] Mean standard deviation of log-ratios: 0.34
INFO [2020-09-16 16:45:33] Mean standard deviation of on-target log-ratios only: 0.32
INFO [2020-09-16 16:45:33] Mean standard deviation of off-target log-ratios only: 0.70
INFO [2020-09-16 16:52:11] Mean standard deviation of log-ratios: 0.30
INFO [2020-09-16 16:52:11] Mean standard deviation of on-target log-ratios only: 0.28
INFO [2020-09-16 16:52:11] Mean standard deviation of off-target log-ratios only: 0.66
INFO [2020-09-16 16:52:46] Mean standard deviation of log-ratios: 0.33
INFO [2020-09-16 16:52:46] Mean standard deviation of on-target log-ratios only: 0.32
INFO [2020-09-16 16:52:46] Mean standard deviation of off-target log-ratios only: 0.55

For germline:

INFO [2020-09-16 16:50:54] 45063 (52.1%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:44:13] 50029 (37.7%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:52:08] 46201 (55.9%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:51:10] 47388 (53.2%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:50:55] 47164 (54.5%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:51:10] 47518 (51.8%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:50:55] 48162 (55.1%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:51:09] 47762 (55.3%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:51:10] 47584 (53.2%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:51:09] 46565 (56.6%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:44:10] 47370 (51.6%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:50:54] 47146 (57.7%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-16 16:51:10] 47319 (54.0%) variants annotated as likely germline (DB INFO flag).

Could this be because I'm using bcbio mutect version?

**Comment by lima1** [comment]
How many on-target intervals have a variant (the percentage listed below?). This should be ideally between 12-15%. Is bcbio using the whole genome gnomAD reference? The exome one might miss some (not sure how much padding they use).

**Comment by waemm** [comment]
Here are the stats, looks like around 10% 

INFO [2020-09-16 16:51:06] 9.9% of targets contain variants.
INFO [2020-09-16 16:44:29] 11.4% of targets contain variants.
INFO [2020-09-16 16:52:20] 10.5% of targets contain variants.
INFO [2020-09-16 16:51:22] 10.4% of targets contain variants.
INFO [2020-09-16 16:51:06] 10.7% of targets contain variants.
INFO [2020-09-16 16:51:22] 10.5% of targets contain variants.
INFO [2020-09-16 16:51:07] 10.8% of targets contain variants.
INFO [2020-09-16 16:51:20] 10.6% of targets contain variants.
INFO [2020-09-16 16:51:23] 10.7% of targets contain variants.
INFO [2020-09-16 16:51:22] 10.4% of targets contain variants.
INFO [2020-09-16 16:44:22] 11.0% of targets contain variants.
INFO [2020-09-16 16:51:08] 10.5% of targets contain variants.
INFO [2020-09-16 16:51:22] 10.7% of targets contain variants.

**Comment by lima1** [comment]
probably fine. Does your old sample look better now? Will look into the bcbio workflow soon.

**Comment by waemm** [comment]
Look much better, thanks Markus!
