### ISSUE TITLE
Only tiny segments.

### ISSUE THREAD

**Issue by starz77** [lima1/PureCN#148]
Hello,

I already posted about this issue before.

The previous issue was due to low coverage.

So I changed the '.bed' file and checked the coverage of '.bam' file

but the same error happened.

Here's my log.

INFO [2020-09-21 10:32:01] PureCN 1.16.0
INFO [2020-09-21 10:32:01] ------------------------------------------------------------
INFO [2020-09-21 10:32:01] Arguments: -normal.coverage.file /bio/scratch/starz77/sylee/pureCN/pureCN_Result/P42/P42_N/P42_N.bwamem.sorted.dedup.realn.recal.dedup_coverage_loess.txt.gz -tumor.coverage.file /bio/scratch/starz77/sylee/pureCN/pureCN_Result/P42/P42_T/P42_T.bwamem.sorted.dedup.realn.recal.dedup_coverage_loess.txt.gz -log.ratio  -seg.file  -vcf.file /bio/scratch/starz77/sylee/Mutect2_result/P42/P42.somatic.mutect2.vcf -normalDB  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.segmentation NULL,0.005,NULL -sampleid P42 -min.ploidy 1 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file /bio/scratch/starz77/sylee/pureCN/pureCN_Ref/S04380110_AllTracks.interval.txt -max.segments 300 -plot.cnv TRUE -DB.info.flag DB -POPAF.info.field POP_AF -model beta -post.optimize FALSE -BPPARAM  -log.file /bio/scratch/starz77/sylee/pureCN/pureCN_Result/P42/P42.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2020-09-21 10:32:01] Loading coverage files...
INFO [2020-09-21 10:32:17] Mean target coverages: 143X (tumor) 69X (normal).
INFO [2020-09-21 10:32:18] Mean coverages: chrX: 72.67, chrY: 5.83, chr1-22: 134.52.
INFO [2020-09-21 10:32:18] Mean coverages: chrX: 34.95, chrY: 35.31, chr1-22: 66.01.
INFO [2020-09-21 10:32:38] Removing 690 intervals with missing log.ratio.
INFO [2020-09-21 10:32:38] Removing 84 intervals with low total coverage in normal (< 150.00 reads).
WARN [2020-09-21 10:32:38] No normalDB provided. Provide one for better results.
INFO [2020-09-21 10:32:38] Removing 36845 low coverage (< 15.0000X) intervals.
INFO [2020-09-21 10:32:38] Using 235197 intervals (235190 on-target, 7 off-target).
INFO [2020-09-21 10:32:38] Ratio of mean on-target vs. off-target read counts: 0.03
INFO [2020-09-21 10:32:38] Mean off-target bin size: 91089
INFO [2020-09-21 10:32:39] AT/GC dropout: 0.99 (tumor), 0.98 (normal).
INFO [2020-09-21 10:32:39] Loading VCF...
INFO [2020-09-21 10:34:02] Found 2331555 variants in VCF file.
INFO [2020-09-21 10:34:11] Removing 7779 triallelic sites.
WARN [2020-09-21 10:34:54] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2020-09-21 10:35:04] 2323776 (100.0%) variants annotated as likely germline (DB INFO flag).
INFO [2020-09-21 10:37:19] P42_T is tumor in VCF file.
INFO [2020-09-21 10:37:46] 1115 homozygous and 511 heterozygous variants on chrX.
INFO [2020-09-21 10:37:46] Sex from VCF: NA (Fisher's p-value: < 0.0001, odds-ratio: 3.99).
INFO [2020-09-21 10:38:03] Removing 2259762 non heterozygous (in matched normal) germline SNPs.
INFO [2020-09-21 10:38:14] Initial testing for significant sample cross-contamination: unlikely
INFO [2020-09-21 10:38:16] Removing 17040 variants with AF < 0.030 or AF >= 1.000 or less than 4 supporting reads or depth < 15.
INFO [2020-09-21 10:38:16] Removing 0 low quality variants with BQ < 25.
INFO [2020-09-21 10:38:16] Total size of targeted genomic region: 47.77Mb (66.82Mb with 50bp padding).
INFO [2020-09-21 10:38:17] 11.4% of targets contain variants.
INFO [2020-09-21 10:38:17] Removing 15801 variants outside intervals.
INFO [2020-09-21 10:38:18] Found SOMATIC annotation in VCF.
INFO [2020-09-21 10:38:18] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2020-09-21 10:38:18] Found SOMATIC annotation in VCF. Setting mapping bias to 0.978.
INFO [2020-09-21 10:38:18] Excluding 0 novel or poor quality variants from segmentation.
INFO [2020-09-21 10:38:18] Sample sex: M
INFO [2020-09-21 10:38:18] Segmenting data...
INFO [2020-09-21 10:38:18] Loading pre-computed boundaries for DNAcopy...
INFO [2020-09-21 10:38:18] Setting undo.SD parameter to 1.000000.
INFO [2020-09-21 10:39:01] Setting undo.SD parameter to 1.500000.
Setting multi-figure configuration
INFO [2020-09-21 10:40:01] Setting prune.hclust.h parameter to 0.200000.
INFO [2020-09-21 10:40:02] Found 271 segments with median size of 0.90Mb.
INFO [2020-09-21 10:40:02] Removing 20 variants outside segments.
INFO [2020-09-21 10:40:02] Using 31153 variants.
FATAL [2020-09-21 10:40:04] Only tiny segments.

FATAL [2020-09-21 10:40:04]

FATAL [2020-09-21 10:40:04] This runtime error might be caused by invalid input data or parameters.

FATAL [2020-09-21 10:40:04] Please report bug (PureCN 1.16.0).

Error: Only tiny segments.

This runtime error might be caused by invalid input data or parameters.
Please report bug (PureCN 1.16.0).
Execution halted

--------------------------------------------------------------------------------------------------------------------

Mean target coverages: 143X (tumor) 69X (normal).

I think the coverage is high enough, is it still low for pureCN?

Thank you

**Comment by lima1** [comment]
Not sure if this is the reason for the crash, but you only have 7 off-target regions. This indicates an issue with the interval file. Are you using a commercial WES capture kit? If yes, which BED file were you using? If this is a custom design, make sure to provide the actual bait positions, not the exons. Then off-target is not really necessary for whole exome, you can try without, especially when off-target count is less than 10% of on-target (in your case: INFO [2020-09-21 10:32:38] Using 235197 intervals (235190 on-target, 7 off-target).

**Comment by starz77** [comment]
Hello,

Here's my bed file.

It is SureSelect.V5 bed file.

I can't understand what you saying about off-target and on-target.

Should I remove off-target region before running pureCN?

thank you.

 S04380110_AllTracks.bed
<https://drive.google.com/file/d/1_iy_9QDR0uhJDXlP0dKPz5gtlLih2dTO/view?usp=drive_web>

ᐧ

2020년 9월 21일 (월) 오후 12:49, Markus Riester <notifications@github.com>님이 작성:

**Comment by lima1** [comment]
Can you try the GitHub master branch?  You can easily install it with BiocManager::install("lima1/PureCN"). There were a few bug fixes in IntervalFile.R since 1.16.0.

Then maybe try the S04380110_Covered.bed instead (remove the first two header lines since rtracklayer gets confused by them)? 

With SureSelectV5, off-target does not gain much, I would first try without. You can later easily experiment adding it.

**Comment by starz77** [comment]
Finally, I run completely for one sample.

It was bed or interval problem.

Thank you for your help.

Now, how can I check copy number changes by genes?

There's no information about the output file, meaning of the header and threshold.

Could you give me some guidelines?

Thank you

**Comment by lima1** [comment]
Check out section 6 of https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/PureCN.pdf that describes all the output files. I realize it's a lot, so take your time to read.

If your interval file contains gene symbols (should be by default for hg19, for others, IntervalFile.R will tell you to install annotation packages to get them), PureCN.R will generate a Sampleid_genes.csv file.

I would also highly recommend to generate a normal database with NormalDB.R and provide that one instead of --normal in PureCN.R. This way you get the powerful denoising method that removes noise observed in all normal samples.
