### ISSUE TITLE
Question about gender prediction

### ISSUE THREAD

**Issue by yisu-li** [lima1/PureCN#152]
Hi,
I am running a sample with high purity in WGS result but low in pureCN.  I noticed that for the Sex column, it has "Coverage: M VCF: F".  For the analysis, I used the seg file from cnvkit, and VCF was generated using Mutect1.1.4 with matched tumour-normal pair without additional filtering.    Reading the readme, I assume I don't need to filter the VCF generated by Mutect.  Is it correct?  Thanks in advance for your help.

**Comment by lima1** [comment]
Yes, with third-party  tools, the sex classifier from coverage might be inaccurate. It assumes that regions not uniquely mapping to ChrY are filtered out. Not sure what’s the best way to do that in Cnvkit.

Yes, no filtering necessary, but the runtime can be pretty long with more than 100000 variants. So you might want to filter more aggressively for higher quality.

**Comment by yisu-li** [comment]
Thanks Markus for your suggestion.  I will try to filtering down the variants and try to run again.  If cnvkit segmentation is too noisy, would you recommend to re-segment using pureCN?

**Comment by lima1** [comment]
Don’t have any experience with WGS. You could try GATK4 and compare against CNVkit. PureCN 1.20.0 supports both CNVkit and GATK.

**Comment by yisu-li** [comment]
Sorry Markus.  I might have confused you.  
I am trying to predict purity and ploidy for large target panel with high depth.  Luckily, WGS data is available for the same DNA, so I am using the sample as a control to validate the pureCN result.  Battenberg estimated high purity using the WGS data, but pureCN estimated low purity based on the panel.  I am trying to tune the pureCN steps to achieve better purity prediction on the target panel data.  So far, I am using the general approach for pureCN prediction, and would appreciate any suggestion that you could provide based on your experience.   
Thanks!

**Comment by lima1** [comment]
Feel free to post a log-file and a screenshot of the b-allele frequency plot. For panels, we use our normalization with the patched Pscbs segmentation.

**Comment by lima1** [comment]
Closing for now, feel free to add comments if necessary

**Comment by yisu-li** [comment]
Thank you Markus for closing this issue.  I will create another issue about cnvKit.
