### ISSUE TITLE
Question about using cnvKit output

### ISSUE THREAD

**Issue by yisu-li** [lima1/PureCN#155]
Hi Markus, 

I have a few questions with regards to using CNVkit output. 
1) I would like to make a normal panel of VCF.  How many samples will you recommend to include for the VCF generation?  Do they have to be all in one VCF or each sample has a separate VCF?
2) Should we use CNVKit result run against its matched germline or a panel of normal?  Which method is preferred?

Thanks,
Yisu

**Comment by lima1** [comment]
Hi Yisu,

1: Great :-) As many as you have, even a small number is better than nothing. You have two possibilities: Either generate a multi-sample VCF will all samples merged (PureCN will read the AD field, that's the only requirement). Or alternatively if you use GATK4, install https://github.com/GenomicsDB/GenomicsDB and https://github.com/lima1/PureCN/issues/155, latest PureCN 1.20.0 and then you can use the GenomicsDB you use in Mutect2 (see the latest Best Practices vignettes).

2: Panel of normal is almost always better. I might implement an extension of our method for using both PoN and matched normal, but I won't expect it to be a major improvement. PoN works great for somatic alterations! 

Best,
Markus

**Comment by yisu-li** [comment]
Thank you very much Markus! I will give them a try.

Yisu
