### ISSUE TITLE
some errors occur

### ISSUE THREAD

**Issue by jeongmeani** [lima1/PureCN#157]
Hi, 

using PureCN, i want to analyze WES data.

but when i try installing it and running, it makes error.
i use **cnvkit output!** and **Mutect 1.1.7**

first
i have installed PureCN like below

` Install patched PSCBS:`
`if (!requireNamespace("BiocManager", quietly=TRUE))`
`>install.packages("BiocManager")`
`BiocManager::install("lima1/PSCBS", ref="add_dnacopy_weighting")`
`BiocManager::install("lima1/PureCN")`

but when i run PureCN. 
returns 
> Error: object 'segmentationHclust' not found

second.

when run without --funsegmentation, it also makes error
> Error: vcf.file has no %s or %s info field for membership in germline
> databases.DBPOP_AF

can you tell me something to fix it?

Best Regards

Jeongmin

**Comment by lima1** [comment]
Hi Jeongmin,

can you do BiocManager::install("lima1/PureCN", ref = "RELEASE_3_12") to make sure the latest stable version is installed?

Cheers,
Markus

**Comment by jeongmeani** [comment]
Great!

it works!

i got one more question.

actually, i have never used mutect 1.1.7 
and i can't find tumor only mode option.

could you recommend to run tumor only mode of mutect?

Best Regards.

Jeongmin

**Comment by lima1** [comment]
For Mutect 1.1.7, if you don't provide a normal BAM file, only tumor, it should work:

```
$JAVA7 -Xmx6g -jar $MUTECT \
--analysis_type MuTect -R $REFERENCE \
--dbsnp $DBSNP_VCF \
--cosmic $COSMIC_VCF \
-I:tumor $BAM_TUMOR \
-o $OUT/${ID}_bwa_mutect_stats.txt \
-vcf $OUT/${ID}_bwa_mutect.vcf
```

I would need to see the complete output of PureCN.R call (should be generated in a Sampleid.log file) to help you with the filtering issue. Likely an issue with the input VCF.

**Comment by jeongmeani** [comment]
Oh, sorry.

because of first time, i put wrong mutect.vcf.

it work perfectly.

Thank you for helping me 👍 
Have a nice day.

Jeongmin
