### ISSUE TITLE
Re: targeted sequencing with much smaller interval lengths

### ISSUE THREAD

**Issue by yls2g13** [lima1/PureCN#158]
Hi Markus,

My objective is to obtain copy number profiles from targeted-sequencing data. Our interval lengths are quite small (between 9-9500bp) and we have high sequencing depths - when I run PureCN, it does not throw any errors, but I believe more optimising can be done.

From the best practices page:
Small panels with high coverage: --padding 100 (or higher), requires running the variant caller with this padding or without interval file. Use the same settings for the panel of normals VCF so that SNPs in the flanking regions have reliable mapping bias estimates. The `--maxhomozygousloss` parameter might also need some adjustment for very small panels with large gaps around captured deletions.

My questions are:
1. Would you have any suggestions on how to optimise the `--maxhomozygousloss` parameter here?
2. Should my target BED file include padding when creating the interval file with IntervalFile.R? 
3. And following question 2, would you recommend that the `--padding` parameter in PureCN.R be set to default or `--padding` 200?

My code is currently as follows:
```
DIR=/software/R/4.0.2/bin
PURECN=~/R/x86_64-pc-linux-gnu-library/4.0/PureCN/extdata
OUT_DIR=~/PureCN
PON=~/PureCN/MuTect2_PON.vcf.gz

#creates interval file
$DIR/Rscript $PURECN/IntervalFile.R \
--infile ~/PureCN/targetbed.sorted.bed.gz \
--fasta /resources/fdb/GRCh38_HPV/Sequence/BWAIndex/GCA_000001405.15_GRCh38_no_alt_analysis_set_HPV.fa \
--outfile $OUT_DIR/2_baits_hg38_intervals.txt \ 
--genome hg38 --mintargetwidth 10 \
--export $OUT_DIR/2_baits_optimized_hg38.bed \
--mappability $OUT_DIR/GCA_000001405.15_GRCh38_no_alt_analysis_set_100.bw

#calculate and GC-normalize coverage from a list of BAM files 
$DIR/Rscript $PURECN/Coverage.R \
--outdir $OUT_DIR/Tumors \
--bam $OUT_DIR/tumors.list \
--intervals $OUT_DIR/2_baits_hg38_intervals.txt \
--cores 4

$DIR/Rscript $PURECN/Coverage.R \
--outdir $OUT_DIR/Normals \
--bam $OUT_DIR/normals.list \
--intervals $OUT_DIR/2_baits_hg38_intervals.txt \
--cores 4

#build a normal database for coverage normalization
$DIR/Rscript $PURECN/NormalDB.R \
--outdir $OUT_DIR \
--coveragefiles ~/PureCN/normal.loess.list \
--genome hg38 --normal_panel $PON

$DIR/Rscript $PURECN/PureCN.R \
    --out $OUT_DIR \
    --sampleid "$tumorname" \
    --tumor $OUT_REF/Tumors/"$tumorname".realign.recal_coverage_loess.txt.gz \
    --normal $OUT_REF/Normals/"$normalname".realign.recal_coverage_loess.txt.gz \
    --vcf $VCF_DIR/"$foldername"/"$foldername".HaplotypeCaller.Variants.vcf \
    --intervals $OUT_REF/2_baits_hg38_intervals.txt \
    --mappingbiasfile $OUT_REF/mapping_bias_hg38.rds \
    --normaldb $OUT_REF/normalDB_hg38.rds \
    --genome hg38 --force --postoptimize --cores 4 --padding 200
```

**Comment by lima1** [comment]
Hi,

Do you have access to the actual baits BED file? These should be more even in width. Looks like what you provide are the targeted exons. Did you run into problems with the default --mintargetwidth? I think it is 100. This will resize the intervals to cover at least 100bp, which is likely what you actually have in the data with good coverage and standard bait sizes.

The padding parameter will make PureCN simple include all variants in the flanking regions of the intervals. If you have 1000X coverage, even 200bp away you might get sufficient coverage to get accurate allelic fractions of SNPs.

So yes, try running HC with --interval_padding of 200 and add --padding 200. This should increase your SNPs quite a bit.

Hope that helps,
Markus

**Comment by yls2g13** [comment]
Yes the baits file is much more even in width (100-400bp).
`--mintargetwidth` does not throw errors.
I am running `--padding` 200 right now.

Do you mind elaborating more on the `--maxhomozygousloss` parameter?

**Comment by lima1** [comment]
This setting was introduced to avoid clearly wrong solutions with too many and too large homozygous deletions. With small panels, you might get very large deletions because you have huge gaps between genes. The default is quite large, but if you have large gaps around common  deletions like CDKN2A, RB1 and PTEN,  maybe play it save and increase it even more, so that those are not ignored. You can compare the gene log2 ratios against segment log2 ratios. If there is a drop in coverage at the gene level, but the segment is normal, the homozygous deletion was ignored. Hope that helps.
