### ISSUE TITLE
low purity estimate for what should be a highly pure sample

### ISSUE THREAD

**Issue by briandiamondage-sema4** [lima1/PureCN#161]
I was curious about how much trust we should put into the tumor purity estimates, and so I ran what should be a highly pure normal sample through PureCN to examine the purity result.

Below is the local optima plot for ploidy ~ purity.

<img width="632" alt="Screen Shot 2020-12-26 at 3 58 44 PM" src="https://user-images.githubusercontent.com/56320955/103159141-b6594380-4793-11eb-96a3-160507211231.png">

The optimal purity estimate was reported at 27%:

<img width="566" alt="Screen Shot 2020-12-26 at 4 02 56 PM" src="https://user-images.githubusercontent.com/56320955/103159160-e9033c00-4793-11eb-907c-664efdff880e.png">

However, based on this local optimal plot, you can see that any candidate purity value at the ploidy=2 provides a very high likelihood, and so there is really little support for low vs. high purity at this ploidy level.   

I'm wondering if there's another way we should be extracting the purity estimates from the 2D-grid search rather than relying on the single value reported in the .csv output file as the max likelihood solution.

Thx in advance for any advice.

**Comment by lima1** [comment]
Hi,

PureCN requires somatic events to estimate purity. Normal samples have 0% tumor. So the correct tumor purity would be 0, not 100. If you look at the output log files, it warned you that it found no copy number events and the purity estimate is unreliable. 

In general, it’s pretty obvious if a solution is correct, but needs a bit of experience. I will probably add a tutorial for that soon, stay tuned.

Markus

**Comment by briandiamondage-sema4** [comment]
Terrific!  Thanks for the quick response!  I look forward to learning more.
