### ISSUE TITLE
Troubleshooting the reason for poor purity estimate of high purity samples with clonal CNV loss segments

### ISSUE THREAD

**Issue by Huan-Wang-S4** [lima1/PureCN#165]
Hi, 

Recently I tried PureCN on a couple of samples for estimating tumor purity using the tumor only mode. Below is the code that I used, with the input files attached here.

[PureCN_test.zip](https://github.com/lima1/PureCN/files/6091620/PureCN_test.zip)

```
Rscript $PURECN/PureCN.R \
--out OUTDIR/Run999_Pair045_Tumor_tumorNormal_gatk4cnv \
--tumor input_gatk4seg/tumorNormal/Run999_Pair045_Tumor.dedup.recal.counts.hdf5 \
--sampleid Run999_Pair045_tnVcf_tumorNormal_gatk4ncv \
--logratiofile input_gatk4seg/tumorNormal/Run999_Pair045_Tumor.dedup.recal.denoisedCR.tsv \
--segfile input_gatk4seg/tumorNormal/Run999_Pair045_Tumor.dedup.recal.modelFinal.seg \
--mappingbiasfile reference_files/mapping_bias_TwistExomeAll152_hg19.rds \
--vcf vcfs_PureCN/tumorVcf/Run999_Pair045_Tumor.Run999_Pair045_Normal.mutect2.twicefiltered.hg19.vcf_wDB.vcf \
--genome hg19 \
--funsegmentation Hclust \
--force --postoptimize --seed 123
```

Here the segmentation data is from GATK4 via tumor normal mode, which clearly shows clonal CNV loss segment and purity should be 100%, which is expected given this is a tumor cell line sample. And the vcf file is mutect2 with minimal post-processing to make it compatible with PureCN. However, PureCN is estimating purity of only 0.45. 

[Run999_Pair045_toVcf_tumorNormal_gatk4ncv_local_optima.pdf](https://github.com/lima1/PureCN/files/6091574/Run999_Pair045_toVcf_tumorNormal_gatk4ncv_local_optima.pdf)

Could you please help out here and figure out how to improve it?

Thanks

Huan

**Comment by lima1** [comment]
Hi Huan,

can you also share the B-allele frequency plot in Sampleid.pdf?

There are cell line specific arguments explained in the best practices vignette, but they aren't as critical for tumor/normal. So I suspect they won't change too much.  But they will make sure that there is a high purity solution you can select as correct.
 
But yes, high purity samples with heterogeneity currently aren't working as well as they could/should, I noticed that a while back when I looked at cell lines: https://github.com/lima1/PureCN/issues/9

I have a couple of improvements already implemented, like a test for allelic imbalance (segments in allelic imbalance can't have a balanced, normal copy number). The likelihood model is not yet using this though. Hopefully soon!

What I did in the past was using the cell line parameters and do a manual curation. Cell lines are much easier to curate than typical low purity clinical samples.

Markus

**Comment by Huan-Wang-S4** [comment]
Thanks for quick reply! So it wouldn't work as well for cell lines. I will find a high tumor purity cancer patient sample (perhaps a heme sample), and see how PureCN returns result on that. I will get back to you when I have updates. Thanks again!

**Comment by lima1** [comment]
If you use the cell line recommendations in the best practices, it should at least provide useable output for manual curation. Heme usually works beautifully. I’ll close now, but feel free to watch #9 for progress here.

**Comment by Huan-Wang-S4** [comment]
Hi, Markus

I have tried using a heme samples with purity close to 100% (please see the tumor normal GATK4 segmentation plot attached here, which actually agrees with segmentation output from PureCN, and they both showed clonal CNV loss on chr17). 
 
![ISM288761-2 ISM288800-2 cnvSomaticGenomeWide](https://user-images.githubusercontent.com/31801668/110972024-8993e180-8329-11eb-90ac-9ea71b0b0778.png)


When I used the tumor normal GATK4 segmentation data as input, the PureCN output still gives me only 0.36 purity. Any idea why? All the needed input and output files are in the attachment. 

[input.zip](https://github.com/lima1/PureCN/files/6131576/input.zip)
[output.zip](https://github.com/lima1/PureCN/files/6131578/output.zip)


Here is the command I used

```
Rscript $PURECN/PureCN.R \
--out OUTDIR/ISM288761-2_tumorNormal_gatk4cnv \
--tumor input_gatk4seg/tumorNormal/ISM288761-2.dedup.recal.counts.hdf5 \
--sampleid ISM288761-2_tumorNormal_gatk4cnv \
--logratiofile input_gatk4seg/tumorNormal/ISM288761-2.dedup.recal.denoisedCR.tsv \
--segfile input_gatk4seg/tumorNormal/ISM288761-2.dedup.recal.modelFinal.seg \
--mappingbiasfile reference_files/mapping_bias_TwistExomeAll152_hg19.rds \
--vcf vcfs_PureCN/tumorVcf/ISM288761-2_HNYGJDSXX.mutect2.twicefiltered.hg19.vcf_wDB.vcf \
--genome hg19 \
--funsegmentation Hclust \
--force --postoptimize --seed 123
```

I would really appreciate your feedback here. 

Thanks

Huan

**Comment by lima1** [comment]
Hi @Huan-Wang-S4 , this looks pretty noisy for heme. What did you use as reference set for coverage normalization? Are you sure the normals are from exactly the same assay?

**Comment by Huan-Wang-S4** [comment]
Yes I'm sure the normals used in our GATK4 somatic CNV workflow are from exactly the same assay as the tumor. And we included ~ 150 normals that pass QC. I would say our panel of normal is robust. 

Could you please educate me on why you think the data is noisy? I thought the segmentation plot from both GATK4 and PureCN (named as "ISM288761-2_tumorNormal_gatk4cnv.pdf" in my previously attached output) look clean enough to conclude there is a clonal CNV loss on short arm of chr17, which is also seen in heme samples from literature. That should indicate a pure tumor, right?

**Comment by lima1** [comment]
Your segmentation lists over 500 segments, but your segmentation plot indicates a fairly stable genome, except for this gain of 11q and loss of 17p.  Then there is this drop in coverage (log2 ratio of -27) on 6p in the PureCN plot. Lastly, the log ratio noise is 

INFO [2021-03-12 15:46:21] Mean standard deviation of log-ratios: 0.47

For high quality heme data, where duplication rates should be low, I expect it to be around 0.2 for 300-400X.

I would maybe load all the tumor and normal coverage files in R via PureCN::readCoverageFile and then do a PCA. Maybe you can see a subset of normals that look weird or that tumors look completely different from normals, even the CIN stable hemes. GATKs (PureCN uses a 1:1 reimplementation + support for chrX/Y and off-target reads; latter not needed for WES) normalization should be fairly robust to outliers, but worth checking. Something is fishy.
