### ISSUE TITLE
Version error 

### ISSUE THREAD

**Issue by jennyp76** [lima1/PureCN#169]
Hi Markus,

I'm struggling to use PureCN.R with cnvkit. I have used PureCN 1.18 before the advanced versions were out and had no problem running with it. 
Recently, I downloaded PureCN 1.20.0.tar.gz from bioconductor page and ran PureCN.R in linux command line with the same code and got the following error. 

INFO [2021-03-26 13:55:06] Loading PureCN 1.18.1...
Error in runAbsoluteCN(normal.coverage.file = normal.coverage.file, tumor.coverage.file = tumor.coverage.file,  : 
  unused argument (vcf.field.prefix = "PureCN.")

Rscript $PURECN/PureCN.R --out $OUT/$SAMPLEID  \
    --sampleid $SAMPLEID \
    --tumor $OUT/$SAMPLEID/${SAMPLEID}_cnvkit.cnr \
    --segfile $OUT/$SAMPLEID/${SAMPLEID}_cnvkit.seg \
    --vcf ${SAMPLEID}_mutect.vcf \
    --statsfile ${SAMPLEID}_mutect_stats.txt \
    --genome hg19 \
    --funsegmentation Hclust \
    --force --postoptimize --seed 123

As you can see even though I have downloaded 1.20.0, it's loading PureCN 1.18.1. I have erased PureCN 1.18 before I downloaded the new one. I read that the "unused argument" in the error was moved to runAbsoluteCN since version 1.20.

Thank in advance for any advice.

**Comment by lima1** [comment]
Hi,

the best way of installing PureCN is first upgrading R to the latest version (https://www.r-project.org/) and then upgrading Bioconductor. If your R version is outdated, you won't get the latest PureCN from Bioconductor:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()
```

Then simply install PureCN with BiocManager::install("PureCN")

If for some reason you cannot upgrade R/Bioconductor, you try BiocManager::install("lima1/PureCN")

This will install 1.21.3 (including minor fixes over current stable) it directly from GitHub.

Best,
Markus

**Comment by jennyp76** [comment]
Thank you for the quick advice! but still stuck...

I upgraded R version to 4.0.4, BiocManager to 3.12. Also I used "BiocManager::install("lima1/PureCN")" to install PureCN on Rstudio. Package version 1.21.3 was installed as you have mentioned. 
Since I using a server(not local)with xshell , I had to xftp the  whole PureCN folder from the local ~/R/win-library/4.0/PureCN.
The following code was used in BASH "Rscript home/tools/PureCN/extdata/PureCN.R ~~~~~~~". 
But came across the same error as before. 

INFO [2021-03-28 16:05:00] Loading PureCN 1.18.1...
Error in runAbsoluteCN(normal.coverage.file = normal.coverage.file, tumor.coverage.file = tumor.coverage.file,  : 
  unused argument (vcf.field.prefix = "PureCN.")
Execution halted

To recheck the version I used "Rscript PureCN.R --verison " but it was 1.18.1....

I am sorry for the lack of knowledge. I am new to this field.
Thank you in advance for any advice.

**Comment by lima1** [comment]
Hi Jen,

You will need to install it directly on the server. So log into your server, run R, and install it directly there. Looks like 1.18.1 is installed on the server already. Since this is relatively new, I would simply install the GitHub version with BiocManager::install("lima1/PureCN"). 

Markus
