### ISSUE TITLE
Crash While Generating Output Files

### ISSUE THREAD

**Issue by drmrgd** [lima1/PureCN#171]
I'm running PureCN version `1.20.0` on segmentation files generated with cnvkit.  Although it's taken several days to generate the output, everything seems OK.  However, during the "Generating output files..." phase, I'm getting the following error (similar to issue #10 ):

```
INFO [2021-04-12 10:37:52] Generating output files...
Error in `$<-.data.frame`(`*tmp*`, "arm", value = "p") :
  replacement has 1 row, data has 0
Calls: write.csv ... <Anonymous> -> .getArmLocations -> $<- -> $<-.data.frame
Execution halted
```

The log only contains a few warnings, which seem innocuous enough (though I can't be sure!):

```
WARN [2021-04-09 15:20:39] log2-ratio contains outliers < -8, ignoring them...
WARN [2021-04-09 15:20:42] Found GERMQ info field with Phred scaled germline probabilities.
WARN [2021-04-09 15:20:42] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
WARN [2021-04-09 15:20:43] Found 88 variants with missing allelic fraction starting with 1:13669008_A/C. Removing them.
WARN [2021-04-09 15:20:44] MuTect stats file lacks contig and position columns.
WARN [2021-04-09 15:20:45] Variant ids contain NAs at filter step BQ.
WARN [2021-04-09 15:20:46] Provided sampleid (MATCH-B44A) does not match MATCH-Z1D-B44A found in segmentation.
```

Many of the output files have been generated, but it does seem that I'm missing:

1. *.vcf.gz
2. *_loh.csv
3. *_chromosomes.pdf

I really have no idea what may be causing this error or how to dig into it much deeper.  I'm happy to provide any information that may help uncover the problem with my data.  Please let me know.

**Comment by lima1** [comment]
Hm, not sure. Do you the the *.seg file? Anything fishy in it, like non-standard chromosomes (1,...,X,Y)?

If looks good, would you be able to send the rds file by email? If large, I'm happy to send you a secure link for upload.

**Comment by drmrgd** [comment]
Actually....maybe?  I checked it to see if chrM was still in there since I forgot to remove that when I ran cnvkit.  I didn't find any instances of that, and so I thought all was well.  But, running a simple cut | sort | uniq kind of strat, I see there are entries for '23', '24', and '25' in the .seg file:

```
❯ cut -f2 MATCH-Z1D-B44A.seg | sort -Vu
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
chrom

```
Is it possible that's the problem?  Should 23 = X, 24 = Y, and 25 = M in the segmentation file, causing this error?  

Happy to send both the segmentation and rds file if you think it helpful.  The rds file is about 44MB, though, and I think that may be too large for email.

**Comment by lima1** [comment]
Yep, I think that might be it. I would recommend removing chrM before feeding it to PureCN. 

I'll add a sanity check for that soon, but I'm guessing PureCN assumed it is non-human genome and treated chrM as another regular chromosome. So you would need to re-run anyways.

**Comment by drmrgd** [comment]
Ahh, what a silly mistake.  I removed the decoy seqs and other contigs and completely forgot about chrM.  OK, let me give that a crack.  To be sure, if I just remove chrM from the .cns files from cnvkit, re-export to .seg files, and then re-run PureCN, that should solve it?

**Comment by lima1** [comment]
It should deal with that automatically (it does with the PureCN internal normalization and segmentation, but obviously not with CNVkit input). Might be sufficient to remove from .cns.

**Comment by drmrgd** [comment]
OK, I've tried to remove MT entries from the .cns (and resultant .seg file), .cnr, and the VCF file, but I'm still getting the same error at, I think, the same exact point.  The only thing that seems somewhat suspicious to me is that the seg file has chromosome entries {1..24} - I guess that's what the `enumerate-chroms` arg to cnvkit export does? - and the others have entries of {1..22,X,Y}.  Could that be the disconnect?

**Comment by drmrgd** [comment]
I think I've got this sorted.  I looked through the .rds file and noticed that there were references to the UCSC style chromosome notations (i.e. chr1, chr2, etc.).  However, my reference is b37 / GRCh37, and so I didn't have the 'chr' string prepending the chromosome number.  I edited the input files (.seg, .cnr, .cns, .vcf) to add back the chr strings, and this time I got it to complete.  I probably should have guessed as much when the only close option for genome was `hg19`, but I didn't really consider this closely since I wasn't specifically putting any references in.  Now the run completed with only a warning:

```
INFO [2021-04-13 15:02:47] Done.
INFO [2021-04-13 15:02:47] ------------------------------------------------------------
Warning messages:
1: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
2: In .checkSeg(seg, sampleid, model.homozygous, verbose) :
  NAs introduced by coercion
INFO [2021-04-13 15:02:52] Generating output files...
```

Perhaps a check for this or an error message would be useful for others?  At any rate, I think this is solved now, and I think I am able to run PureCN. Thanks for all of your help!

**Comment by lima1** [comment]
Hi Dave, can you help me reproduce this? PureCN should automatically convert the chromosome style.

**Comment by drmrgd** [comment]
Absolutely!  How is best to help?  Can I send you a set of cnr, cns, seg, vcf, and the rds file (and anything else you think is helpful)?

**Comment by lima1** [comment]
if you can send me all the files and the command line resulting in the crash, that would be great. send me an email to markus.riester@novartis.com and I'll send you a link to upload them. Thanks a lot.

**Comment by lima1** [comment]
Seems fixed now.
