### ISSUE TITLE
error in Coverage.R

### ISSUE THREAD

**Issue by Josephhungyi** [lima1/PureCN#172]
Hello,

When I ran the Coverage.R, I got the error:

Error in predLoess(object$y, object$x, newx = if (is.null(newdata)) object$x else if (is.data.frame(newdata)) as.matrix(model.frame(delete.response(terms(object)),  :
  NA/NaN/Inf in foreign function call (arg 5)
Calls: .gcNormalize ... eval -> eval -> predict -> predict.loess -> predLoess
In addition: Warning messages:
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  zero-width neighborhood. make span bigger
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at 0.4
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.0042553
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  2.0397e-16
Execution halted

I ran the IntervalFile.R with hg38, so I did not provide the --reptiming because I cannot find the file on UCSC genome browser.
If that's the reason for the error,  where I can download the reptiming file.

Thanks

**Comment by lima1** [comment]
Hi Joseph,

--reptiming isn't that important at all.

Does this happen with all or just some samples? If only some, are these maybe low coverage?
 
The error message usually happens when the input interval file has some weird GC-value distribution that confuses the loess GC-normalization. Essentially it does not find GC-values in some regions, which should not happen.

Did you use as input to IntervalFIle.R the baits BED file (the one that has the actual bait coordinates, not the genes they are targeting). These are usually between 100 and 150bp and the resulting GC values are thus less discrete.

How large is your panel?

**Comment by Josephhungyi** [comment]
Hi lima1,

The coverage of samples is very high, up to 3000X and the baits bed file is ok, but the bam files only detect the target genes. 
The smallest bait region is around 100 bp and the total is around 0.2M. Is the reason for the error?   

Thanks

**Comment by lima1** [comment]
It's a very small panel, yes, might be the issue why the Loess normalization does not see enough GC values.

How many normal samples do you have? You might not need the GC-normalization if you have a sufficient number. Probably 10 or more should be ok.

**Comment by Josephhungyi** [comment]
I have 10 more precessed-matched normals, but how to change my analysis. 

Thanks

**Comment by lima1** [comment]
Coverage.R should produce a Sampleid_coverage.txt.gz file before it crashes. Simply use that one instead of the coverage_loess.txt.gz and follow https://bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/Quick.html . I'll add an option to skip the GC normalization, but for now you could ignore the error.

**Comment by Josephhungyi** [comment]
Hi, I got an error in NormalDB.R, no matter I provided the Mutect2/GATK4 normal panel GenomicsDB or not.

INFO [2021-04-26 09:10:42] Loading PureCN 1.20.0...
INFO [2021-04-26 09:10:57] Creating mapping bias database.
FATAL [2021-04-26 09:10:57] Install the genomicsdb and jsonlite R packages for GenomicsDB import.

FATAL [2021-04-26 09:10:57]

FATAL [2021-04-26 09:10:57] This is most likely a user error due to invalid input data or

FATAL [2021-04-26 09:10:57] parameters (PureCN 1.20.0).

Error: Install the genomicsdb and jsonlite R packages for GenomicsDB import.

This is most likely a user error due to invalid input data or
parameters (PureCN 1.20.0).
Execution halted

**Comment by lima1** [comment]
Importing GenomisDB requires:

https://github.com/GenomicsDB/GenomicsD
(if you have trouble installing it, https://github.com/nalinigans/GenomicsDB-Install might help you)

https://github.com/nalinigans/GenomicsDB-R
https://cran.r-project.org/web/packages/jsonlite/index.html

**Comment by Josephhungyi** [comment]
Hi, I got an error in PureCN.R.

FATAL [2021-04-27 14:09:11] No gc_bias column in interval.file.

FATAL [2021-04-27 14:09:11]

FATAL [2021-04-27 14:09:11] This is most likely a user error due to invalid input data or

FATAL [2021-04-27 14:09:11] parameters (PureCN 1.20.0).

Error: No gc_bias column in interval.file.

This is most likely a user error due to invalid input data or
parameters (PureCN 1.20.0).
Execution halted

Based on the small panel, I cannot normalize the GC bias. How to skip it?

Thanks

**Comment by lima1** [comment]
So looks like we are getting closer. Did you follow PureCN's best practices from beginning to start?

What's the complete output of IntervalFile.R when you run it on your baits BED file?

https://bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/Quick.html#prepare-environment-and-assay-specific-reference-files

**Comment by Josephhungyi** [comment]
Hi, I ran the all scripts from the beginning to the end via following the Quickstart 
and got some files.

![test](https://user-images.githubusercontent.com/61561578/116371604-2eb53b80-a83e-11eb-9c2a-3d92b5adfd02.png)

However, how do I know the gene with CNV.

Thanks

**Comment by lima1** [comment]
Would be in _genes.csv labelled as "AMPLIFICATION" or "DELETION".

Post the content of the .log file and I'll double check that it looks fine now.

**Comment by Josephhungyi** [comment]
INFO [2021-04-28 15:19:52] ------------------------------------------------------------
INFO [2021-04-28 15:19:52] PureCN 1.20.0
INFO [2021-04-28 15:19:52] ------------------------------------------------------------
INFO [2021-04-28 15:19:52] Arguments: -tumor.coverage.file /home/joseph/data/BaseCalls/purecn/cnv_BSQR_20CM10541_S2/cnv_BSQR_20CM10541_S2_coverage.txt.gz -log.ratio  -seg.file  -vcf.file /home/joseph/data/BaseCalls/gatk/cnv_tumor/cnv_BSQR_20CM10541_S2.bam_filtered.sur.vcf -genome hg38 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf /home/joseph/data/hg38_ref/purecn_DB/mapping_bias_hg38.rds -args.segmentation 0.005,NULL -sampleid cnv_BSQR_20CM10541_S2 -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 5e-04 -interval.file /home/joseph/data/hg38_ref/purecn_interval -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -DB.info.flag DB -POPAF.info.field POP_AF -model beta -post.optimize TRUE -BPPARAM  -log.file /home/joseph/data/BaseCalls/purecn/cnv_BSQR_20CM10541_S2/cnv_BSQR_20CM10541_S2.log -normal.coverage.file <data> -normalDB <data> -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2021-04-28 15:19:52] Loading coverage files...
INFO [2021-04-28 15:19:53] Mean target coverages: 8058X (tumor) 8004X (normal).
WARN [2021-04-28 15:19:53] Allosome coverage missing, cannot determine sex.
WARN [2021-04-28 15:19:53] Allosome coverage missing, cannot determine sex.
INFO [2021-04-28 15:19:55] Removing 172 intervals with missing log.ratio.
INFO [2021-04-28 15:19:55] Removing 62 low/high GC targets.
INFO [2021-04-28 15:19:55] Removing 448 intervals excluded in normalDB.
INFO [2021-04-28 15:19:55] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2021-04-28 15:19:55] Removing 1654 low coverage (< 0.0015X) intervals.
INFO [2021-04-28 15:19:55] Using 29591 intervals (3870 on-target, 25721 off-target).
INFO [2021-04-28 15:19:55] Ratio of mean on-target vs. off-target read counts: 30.46
INFO [2021-04-28 15:19:55] Mean off-target bin size: 99259
INFO [2021-04-28 15:19:55] AT/GC dropout: 0.98 (tumor), 0.98 (normal). 
INFO [2021-04-28 15:19:55] Loading VCF...
INFO [2021-04-28 15:19:56] Found 218 variants in VCF file.
INFO [2021-04-28 15:19:56] Removing 11 triallelic sites.
INFO [2021-04-28 15:19:56] Maximum of POPAP INFO is > 1, assuming -log10 scaled values
WARN [2021-04-28 15:19:56] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2021-04-28 15:19:56] 120 (58.0%) variants annotated as likely germline (DB INFO flag).
INFO [2021-04-28 15:19:56] 20CM10541_S2 is tumor in VCF file.
INFO [2021-04-28 15:19:56] 1 homozygous and 4 heterozygous variants on chrX.
INFO [2021-04-28 15:19:56] Sex from VCF: F (Fisher's p-value: 0.647, odds-ratio: 0.36).
WARN [2021-04-28 15:19:56] MuTect stats file lacks contig and position columns.
INFO [2021-04-28 15:19:56] Initial testing for significant sample cross-contamination: maybe
INFO [2021-04-28 15:19:56] Removing 38 variants with AF < 0.002 or AF >= 0.998 or less than 11 supporting reads or depth < 15.
WARN [2021-04-28 15:19:57] Variant ids contain NAs at filter step BQ.
INFO [2021-04-28 15:19:57] Removing 0 low quality variants with BQ < 25.
INFO [2021-04-28 15:19:57] Total size of targeted genomic region: 0.18Mb (0.23Mb with 50bp padding).
INFO [2021-04-28 15:19:57] 8.7% of targets contain variants.
INFO [2021-04-28 15:19:57] Removing 27 variants outside intervals.
INFO [2021-04-28 15:19:57] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2021-04-28 15:19:57] Loading mapping bias file mapping_bias_hg38.rds...
INFO [2021-04-28 15:19:57] Imputing mapping bias for 0 variants...
INFO [2021-04-28 15:19:57] Excluding 62 novel or poor quality variants from segmentation.
INFO [2021-04-28 15:19:57] Excluding 0 variants not in pool of normals from segmentation.
INFO [2021-04-28 15:19:57] Sample sex: ?
INFO [2021-04-28 15:19:57] Segmenting data...
INFO [2021-04-28 15:19:57] Interval weights found, will use weighted CBS.
INFO [2021-04-28 15:19:57] Loading pre-computed boundaries for DNAcopy...
INFO [2021-04-28 15:19:57] Setting undo.SD parameter to 0.750000.
INFO [2021-04-28 15:20:00] Setting prune.hclust.h parameter to 0.150000.
INFO [2021-04-28 15:20:00] Found 39 segments with median size of 54.79Mb.
INFO [2021-04-28 15:20:00] Using 142 variants.
INFO [2021-04-28 15:20:00] Mean standard deviation of log-ratios: 0.16
INFO [2021-04-28 15:20:00] Mean standard deviation of on-target log-ratios only: 0.08
INFO [2021-04-28 15:20:00] Mean standard deviation of off-target log-ratios only: 0.16
INFO [2021-04-28 15:20:00] 2D-grid search of purity and ploidy...
INFO [2021-04-28 15:20:31] Local optima: 0.2/2.2, 0.2/2, 0.38/2.4, 0.32/2, 0.3/2.6, 0.48/3,
0.35/3, 0.45/3.4, 0.58/3.2, 0.24/1.8, 0.35/1.6, 0.85/5.4, 0.82/3.6,
0.65/4.6, 0.95/3.8, 0.52/2, 0.78/2
INFO [2021-04-28 15:20:31] Testing local optimum 1/17 at purity 0.20 and total ploidy 2.20...
INFO [2021-04-28 15:20:33] Testing local optimum 2/17 at purity 0.20 and total ploidy 2.00...
INFO [2021-04-28 15:20:35] Testing local optimum 3/17 at purity 0.38 and total ploidy 2.40...
INFO [2021-04-28 15:20:36] Testing local optimum 4/17 at purity 0.32 and total ploidy 2.00...
INFO [2021-04-28 15:20:37] Testing local optimum 5/17 at purity 0.30 and total ploidy 2.60...
INFO [2021-04-28 15:20:39] Testing local optimum 6/17 at purity 0.48 and total ploidy 3.00...
INFO [2021-04-28 15:20:40] Testing local optimum 7/17 at purity 0.35 and total ploidy 3.00...
INFO [2021-04-28 15:20:42] Testing local optimum 8/17 at purity 0.45 and total ploidy 3.40...
INFO [2021-04-28 15:20:43] Testing local optimum 9/17 at purity 0.58 and total ploidy 3.20...
INFO [2021-04-28 15:20:45] Testing local optimum 10/17 at purity 0.24 and total ploidy 1.80...
INFO [2021-04-28 15:20:46] Testing local optimum 11/17 at purity 0.35 and total ploidy 1.60...
INFO [2021-04-28 15:20:47] Recalibrating log-ratios...
INFO [2021-04-28 15:20:47] Testing local optimum 11/17 at purity 0.35 and total ploidy 1.60...
INFO [2021-04-28 15:20:47] Recalibrating log-ratios...
INFO [2021-04-28 15:20:47] Testing local optimum 11/17 at purity 0.35 and total ploidy 1.60...
INFO [2021-04-28 15:20:48] Recalibrating log-ratios...
INFO [2021-04-28 15:20:48] Testing local optimum 11/17 at purity 0.35 and total ploidy 1.60...
INFO [2021-04-28 15:20:49] Testing local optimum 12/17 at purity 0.85 and total ploidy 5.40...
INFO [2021-04-28 15:20:50] Testing local optimum 13/17 at purity 0.82 and total ploidy 3.60...
INFO [2021-04-28 15:20:52] Testing local optimum 14/17 at purity 0.65 and total ploidy 4.60...
INFO [2021-04-28 15:20:54] Testing local optimum 15/17 at purity 0.95 and total ploidy 3.80...
INFO [2021-04-28 15:20:57] Testing local optimum 16/17 at purity 0.52 and total ploidy 2.00...
INFO [2021-04-28 15:20:58] Testing local optimum 17/17 at purity 0.78 and total ploidy 2.00...
INFO [2021-04-28 15:21:00] Skipping 4 solutions that converged to the same optima.
INFO [2021-04-28 15:21:00] Skipping 1 solutions exceeding max.non.clonal (0.20).
INFO [2021-04-28 15:21:00] Fitting variants with beta model for local optimum 2/17...
INFO [2021-04-28 15:21:00] Fitting variants for purity 0.22, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:02] Fitting variants for purity 0.18, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:05] Fitting variants for purity 0.19, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:07] Fitting variants for purity 0.20, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:10] Fitting variants for purity 0.21, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:12] Fitting variants for purity 0.23, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:15] Fitting variants for purity 0.24, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:17] Fitting variants for purity 0.25, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:19] Fitting variants for purity 0.26, tumor ploidy 3.10 and contamination 0.01.
INFO [2021-04-28 15:21:22] Optimized purity: 0.22
INFO [2021-04-28 15:21:22] Fitting variants with beta model for local optimum 3/17...
INFO [2021-04-28 15:21:22] Fitting variants for purity 0.39, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:24] Fitting variants for purity 0.35, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:26] Fitting variants for purity 0.36, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:28] Fitting variants for purity 0.37, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:31] Fitting variants for purity 0.38, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:33] Fitting variants for purity 0.40, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:35] Fitting variants for purity 0.41, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:38] Fitting variants for purity 0.42, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:40] Fitting variants for purity 0.43, tumor ploidy 3.07 and contamination 0.01.
INFO [2021-04-28 15:21:42] Optimized purity: 0.38
INFO [2021-04-28 15:21:42] Fitting variants with beta model for local optimum 4/17...
INFO [2021-04-28 15:21:42] Fitting variants for purity 0.33, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:21:45] Fitting variants for purity 0.29, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:21:47] Fitting variants for purity 0.30, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:21:49] Fitting variants for purity 0.31, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:21:52] Fitting variants for purity 0.32, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:21:54] Fitting variants for purity 0.34, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:21:56] Fitting variants for purity 0.35, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:21:59] Fitting variants for purity 0.36, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:22:01] Fitting variants for purity 0.37, tumor ploidy 2.09 and contamination 0.01.
INFO [2021-04-28 15:22:03] Optimized purity: 0.33
INFO [2021-04-28 15:22:03] Fitting variants with beta model for local optimum 5/17...
INFO [2021-04-28 15:22:03] Fitting variants for purity 0.27, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:06] Fitting variants for purity 0.23, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:08] Fitting variants for purity 0.24, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:10] Fitting variants for purity 0.25, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:13] Fitting variants for purity 0.26, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:15] Fitting variants for purity 0.28, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:17] Fitting variants for purity 0.29, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:20] Fitting variants for purity 0.30, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:22] Fitting variants for purity 0.31, tumor ploidy 3.99 and contamination 0.01.
INFO [2021-04-28 15:22:24] Optimized purity: 0.26
INFO [2021-04-28 15:22:24] Fitting variants with beta model for local optimum 6/17...
INFO [2021-04-28 15:22:24] Fitting variants for purity 0.48, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:27] Fitting variants for purity 0.44, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:29] Fitting variants for purity 0.45, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:31] Fitting variants for purity 0.46, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:34] Fitting variants for purity 0.47, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:36] Fitting variants for purity 0.49, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:38] Fitting variants for purity 0.50, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:41] Fitting variants for purity 0.51, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:43] Fitting variants for purity 0.52, tumor ploidy 4.07 and contamination 0.01.
INFO [2021-04-28 15:22:45] Optimized purity: 0.47
INFO [2021-04-28 15:22:45] Fitting variants with beta model for local optimum 7/17...
INFO [2021-04-28 15:22:45] Fitting variants for purity 0.37, tumor ploidy 4.94 and contamination 0.01.
INFO [2021-04-28 15:22:48] Rare karyotype solution. Skipping post-optimization.
INFO [2021-04-28 15:22:48] Optimized purity: 0.37
INFO [2021-04-28 15:22:48] Fitting variants with beta model for local optimum 8/17...
INFO [2021-04-28 15:22:48] Fitting variants for purity 0.45, tumor ploidy 5.10 and contamination 0.01.
INFO [2021-04-28 15:22:50] Rare karyotype solution. Skipping post-optimization.
INFO [2021-04-28 15:22:50] Optimized purity: 0.45
INFO [2021-04-28 15:22:50] Fitting variants with beta model for local optimum 9/17...
INFO [2021-04-28 15:22:50] Fitting variants for purity 0.58, tumor ploidy 4.06 and contamination 0.01.
INFO [2021-04-28 15:22:53] Poor goodness-of-fit (0.730). Skipping post-optimization.
INFO [2021-04-28 15:22:53] Optimized purity: 0.58
INFO [2021-04-28 15:22:53] Fitting variants with beta model for local optimum 12/17...
INFO [2021-04-28 15:22:53] Fitting variants for purity 0.85, tumor ploidy 5.98 and contamination 0.01.
INFO [2021-04-28 15:22:55] Rare karyotype solution. Skipping post-optimization.
INFO [2021-04-28 15:22:55] Optimized purity: 0.85
INFO [2021-04-28 15:22:55] Fitting variants with beta model for local optimum 13/17...
INFO [2021-04-28 15:22:55] Fitting variants for purity 0.71, tumor ploidy 3.95 and contamination 0.01.
INFO [2021-04-28 15:22:57] Poor goodness-of-fit (0.662). Skipping post-optimization.
INFO [2021-04-28 15:22:57] Optimized purity: 0.71
INFO [2021-04-28 15:22:57] Fitting variants with beta model for local optimum 14/17...
INFO [2021-04-28 15:22:58] Fitting variants for purity 0.64, tumor ploidy 5.95 and contamination 0.01.
INFO [2021-04-28 15:23:00] Rare karyotype solution. Skipping post-optimization.
INFO [2021-04-28 15:23:00] Optimized purity: 0.64
INFO [2021-04-28 15:23:00] Fitting variants with beta model for local optimum 17/17...
INFO [2021-04-28 15:23:00] Fitting variants for purity 0.59, tumor ploidy 2.22 and contamination 0.01.
INFO [2021-04-28 15:23:02] Poor goodness-of-fit (0.446). Skipping post-optimization.
INFO [2021-04-28 15:23:02] Optimized purity: 0.59
INFO [2021-04-28 15:23:02] Done.
INFO [2021-04-28 15:23:02] ------------------------------------------------------------
INFO [2021-04-28 15:23:03] Generating output files...
INFO [2021-04-28 15:23:20] Tumor/normal noise ratio: 17.986
WARN [2021-04-28 15:23:20] Extensive noise in tumor compared to normals.
WARN [2021-04-28 15:23:29] No variants to plot
WARN [2021-04-28 15:23:29] No variants to plot
WARN [2021-04-28 15:23:29] No variants to plot

**Comment by lima1** [comment]
Looks pretty good. I would just change 2 things: run Mutect with a larger interval padding of about 200 bp and specify that padding in PureCN..R. This should increase the number of SNPs a bit. Make sure to do the same with your normals. If you don’t run Mutect with an interval file, you should only need to specify the padding in PureCN.R.

Then try —funsegmentation PSCBS in Rscript R after installing:

# patched PSCBS with support of interval weights
BiocManager::install("lima1/PSCBS", ref="add_dnacopy_weighting")

**Comment by lima1** [comment]
You can also try —model betabin, which might provide some benefit in your high coverage data. But not 100% sure how well this works with small panels.

**Comment by bioxu** [comment]
@lima1 Hello, I also got the same error when run Coverage.R. 

(1) generate an interval file:
Rscript IntervalFile.R --in-file target.bed --genome hg19 --fasta hg19.fa --out-file target_hg19_intervals.txt --off-target --mappability wgEncodeCrgMapabilityAlign100mer.bigWig --reptiming wgEncodeUwRepliSeqK562WaveSignalRep1.bigWig --export target_optimized_hg19.bed

(2) generate coverage file:
Rscript Coverage.R --bam tumor.bam --out-dir coverage/tumor/ --interval target_hg19_intervals.txt --cores 36 --force

my panel target size about 7Mb, and sequencing depth is more than 200X.

this error happens in only some samples, how to solve it?
