### ISSUE TITLE
better pureCN estimates when not using the M1 stats as input

### ISSUE THREAD

**Issue by briandiamondage-sema4** [lima1/PureCN#174]
Hi,

In our evaluations of tumor purity estimates using vs. not using the Mutect1 stats file as input, we're seeing much better agreement when not using the stats file as opposed to including it - which is in contrast to the usage recommendations.
<img width="1185" alt="Screen Shot 2021-04-24 at 9 16 00 AM" src="https://user-images.githubusercontent.com/56320955/115960161-c7b22280-a4dd-11eb-9e57-2322e2e93bbe.png">

(the magenta line is the identity line, slope=1, intercept=0)

I was curious about your thoughts here and whether we should just continue not using the M1 stats file as input.

Many thanks!

(tagging collaborator @Huan-Wang-S4)

**Comment by lima1** [comment]
Hi, yes, that's a bit odd.  Can you maybe post the log file and B-allele frequency plot of one of the cases where you think not using the stats file should fix it?

This function is essentially just removing what Mutect thinks are artifacts. In out experience it's incredibly good at it. If you do your own artifact filtering upstream you are happy with, it's safe to run without.

Here the code: https://github.com/lima1/PureCN/blob/master/R/filterVcfMuTect.R

**Comment by briandiamondage-sema4** [comment]
will do. I need to first confirm with @huan-wang-s4 wrt what I can share first.  thx for the quick response

**Comment by lima1** [comment]
You can do by email if you prefer not having it here.

**Comment by briandiamondage-sema4** [comment]
Hi Markus - I've been given approval to share the info privately.  My email is brian@diamondage.com - can you send me an email and I'll respond with the details?  TIA

**Comment by lima1** [comment]
Likely reason: Mutect 1.1.7 called with --normal_panel that did not include dbSNP annotation resulting in common SNPs flagged as "seen_in_panel_of_normals". Now ignoring this flag when found in >20% of variants.
