### ISSUE TITLE
Filtering input Mutect2 variant files for low AF artefacts

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#176]
Hi Markus,

We have recently seen some samples  with poor quality input material and this and other factors seem to generate lots of artefacts around 0 - 0.1 AF. As expected I guess PureCN believes many of these to be somatic. I was considering just making a hard cutoff to remove all variants below ~0.1 in these cases. From your perspective could this improve identification of somatic variants ? Would it be better to be more selective in attempted removal of these artefacts?

Thanks again for a great tool!
Warren

**Comment by lima1** [comment]
Hi Warren, 

I don’t have a ton of experience with this kind of filtering - we mostly do plasma sequencing these days. Do you see any patterns when you apply GATKs filtering tools, they ship with filters for common artifacts like seen in FFPE.

Low allelic artifacts should not confuse PureCN too much, but yes, always makes sense to clean up the VCFs upstream. 

Cheers,
Markus

**Comment by waemm** [comment]
Thanks Markus, even after filtering with the mutect filter we're still getting a great deal of low AF noise. My guess is this is due at least partially to low input. We'll try filter more aggressively and see if it helps the outcome.
