### ISSUE TITLE
Create a Docker image

### ISSUE THREAD

**Issue by lwaldron** [lima1/PureCN#178]
Would be nice to have a custom docker image with everything needed to run PureCN. Some implementation suggestions:
* Could use https://github.com/seandavi/BuildABiocWorkshop/blob/master/Dockerfile as a template, but:
    + don't need to set CRAN repo
    + may want to start from a rocker image rather than bioconductor/bioconductor_docker (which can install all Bioconductor packages but has a lot of unnecessary system dependencies installed as a result and is a big image)
* See https://github.com/seandavi/BuildABiocWorkshop/blob/master/.github/workflows/basic_checks.yaml for auto-updating GitHub Action
    + again skip setting CRAN repo
    + maybe better to do `usethis::use_github_action()` et al and just add the Docker push action, will be more up-to-date

**Comment by boyangzhao** [comment]
I have created my own docker, that I am using for PureCN. They're also on dockerhub as `zhaob1/purecn:1.22.2`. Below is the Docker file, in case it's helpful. 

```
FROM bioconductor/bioconductor_docker:RELEASE_3_13

# install base packages
RUN Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)){install.packages("BiocManager")}; \
BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")'
RUN Rscript -e 'install.packages(c("optparse", "R.utils")); BiocManager::install("remotes");'

# install PureCN
RUN Rscript -e 'BiocManager::install("lima1/PureCN", ref = "RELEASE_3_13")'

ENV PURECN=/usr/local/lib/R/site-library/PureCN/extdata

CMD ["/bin/bash"]
```

**Comment by lima1** [comment]
Thanks @boyangzhao . Are you planning to add GenomicsDB-R there as well? Let me know if you do and I’ll see how to best maintain an “official” Docker file.

**Comment by boyangzhao** [comment]
Yes I have made a docker with GenomicsDB-R (also installed PSCBS). See my current docker below. There a few temporary bits: 

1) There was a bug in the GenomicsDB in the official release version (latest 1.4.1) (as the maven package install url recently changed and was not reflected in the install shell files); so I've pulled from their develop branch at a particular commit. I've have also raised the issue to them https://github.com/GenomicsDB/GenomicsDB/issues/169 and they have fixed it (but still on develop branch). Once they merge into the master and make a new release, the docker can be updated to reflect the stable release.

2) For testing to get the latest pull from PureCN, I temporary added `COPY marker /dev/null` and was installing PureCN from master branch. It'll be better to install from official stable releases.

All the tests I've been doing on PureCN were with using dockers, so they all work fine. I haven't tested importing variant calls from GATK4 GenomicsDB. 

I'd be happy to help amend the docker, clean up a bit, to have a more finalized version and share it (via here) or pull request if you plan to include Docker as part of this repo (or as separate).


```
FROM bioconductor/bioconductor_docker:RELEASE_3_13

# install base packages
RUN Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)){install.packages("BiocManager")}; \
BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")'
RUN Rscript -e 'install.packages(c("optparse", "R.utils")); \
BiocManager::install(c("remotes", "PSCBS", "raerose01/deconstructSigs"));'

# install GenomicsDB
# need to fix the url for downloading maven package
USER root
RUN mkdir /GenomicsDB
ENV GENOMICSDB_PATH=/GenomicsDB
ENV INSTALL_PREFIX=$GENOMICSDB_PATH
ENV PREREQS_ENV=$GENOMICSDB_PATH/genomicsdb_prereqs.sh
WORKDIR /tmp
RUN git clone -b develop https://github.com/GenomicsDB/GenomicsDB && \
	cd GenomicsDB && \
	git checkout 820a3b42af009451970492925a2719011f5d115a
RUN cd GenomicsDB/scripts/prereqs && \
	sed -i 's/www-us.apache.org\/dist/downloads.apache.org/g' install_prereqs.sh && \
	./install_prereqs.sh
RUN chmod +x $GENOMICSDB_PATH/genomicsdb_prereqs.sh && \
	$GENOMICSDB_PATH/genomicsdb_prereqs.sh

RUN cmake -DCMAKE_PREFIX_INSTALL=$GENOMICSDB_PATH ./GenomicsDB
RUN make && make install

# install GenomicsDB R bindings
RUN Rscript -e 'library(remotes);\
remotes::install_github("nalinigans/GenomicsDB-R", ref="master", configure.args="--with-genomicsdb=/GenomicsDB/")'

# install PureCN
# RUN Rscript -e 'BiocManager::install("lima1/PureCN", ref = "RELEASE_3_13")' 
# marker /dev/null is added so as to force pull. Run date > marker && docker build ...
COPY marker /dev/null 
RUN Rscript -e 'library(remotes); remotes::install_github("lima1/PureCN", ref="master")'
ENV PURECN=/usr/local/lib/R/site-library/PureCN/extdata

CMD ["/bin/bash"]
```

**Comment by lima1** [comment]
That's awesome. We can start providing polished Docker images with the next Bioconductor release in fall.

Just a small suggestion: I'm using a patched version of PSCBS that supports weights. That makes PureCN down-weight intervals with high variance in the pool of normals. Usually reduces artifacts a bit.

# patched PSCBS with support of interval weights
BiocManager::install("lima1/PSCBS", ref="add_dnacopy_weighting")

**Comment by boyangzhao** [comment]
I've added a Dockerfile https://github.com/boyangzhao/PureCN/blob/add_docker/Dockerfile. Currently fixated to the official releases RELEASE_3_13

**Comment by lima1** [comment]
Thanks so much @boyangzhao .

**Comment by lima1** [comment]
Just a minor thing, @boyangzhao . Not sure if I did something wrong, and I don't understand why looking at the code, but somehow it installed genomicsdb in /usr/local for me when testing the Dockerfile in the RELEASE_3_13 branch. Do you see why this could be?
