### ISSUE TITLE
Questions about 3 columns in PureCN output

### ISSUE THREAD

**Issue by Huan-Wang-S4** [lima1/PureCN#181]
[PoN.ISM259430-2_gatk4cnv.csv](https://github.com/lima1/PureCN/files/6512144/PoN.ISM259430-2_gatk4cnv.csv)

Hi, Markus

I have a silly question regarding the interpretation of 3 fields in PureCN output file `$sampleName.csv` (example attached), namely "Flagged", "Failed", and "Curated". I have gone through the document here (https://www.bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/PureCN.pdf ), but I'm still a bit unclear. For example it says "Curated" field shall be set as TRUE, yet in my example output I got "FALSE" from PureCN run. 

Could you please clarify more how to interpret each field here?

Thanks

Huan

**Comment by lima1** [comment]
Hi Huan,

If you manually change the purity and ploidy in this file, you can set Curated to TRUE. This way PureCN will not overwrite the file in case you rerun it. Flagged is frankly not super useful. I’ll plan to revisit the flagging hopefully soon. Set Failed TRUE when you think none of the solutions are correct. It will then ignore purity and ploidy when calling amplifications. Instead will use similar cutoffs used in GISTIC.

Markus

**Comment by Huan-Wang-S4** [comment]
Hi, Markus

In what situation would the user need to rerun PureCN on the same samples (when set the Curated to True) ?My purpose of running PureCN is just for purity estimate, not calling amplifications or anything else. Thus I wonder if I ever need to rerun PureCN?

Thanks

Huan

**Comment by lima1** [comment]
With a little bit of experience, you can check if PureCN picked the correct purity/ploidy combination. It is pretty good at it, but it sometimes gets it wrong, especially in more difficult cases like lung cancer with lots of sub-clonal copy number events. If you don't want to bother with this, you don't need to run this. The purity should not be dramatically wrong even if ploidy is wrong, so if you only run it for purity, you should be fine.

**Comment by Huan-Wang-S4** [comment]
Got it. In the case of not needing to rerun PureCN with the purpose of purity estimate only, I guess "Flagged", "Failed", and "Curated" fields are not informative?

**Comment by lima1** [comment]
Correct.
