### ISSUE TITLE
Issue running normalDB

### ISSUE THREAD

**Issue by Admera2020** [lima1/PureCN#183]
Hello Markus,

I've been running PureCN without error for a long time. Recently started working on a new dataset and got stuck on the NormaDB step. I didn't see an error before neither could find any similar issues reported. The data that I am working on includes about 340 genes with ~80X-200X coverage. 

I tried running without GC corrected coverage and got the same error. 
Here are my commands
```
ls PureCN_Coverage_Control/*loess.txt.gz > normal_coverages.list
Rscript $PURECN_DIR/NormalDB.R --outdir purecn_reference_files_hg38_344Genes --coveragefiles normal_coverages.list --genome hg38 --assay SeqCap_VCRome --normal_panel Combined_PON_Filter_AC3.vcf.gz 

```

Here is the error I am getting. 
```
INFO [2021-06-21 09:52:12] Loading PureCN 1.22.1...
INFO [2021-06-21 09:52:26] Creating mapping bias database.
INFO [2021-06-21 09:52:27] Processing variants 1 to 5000...
WARN [2021-06-21 09:53:36] Found 4238 variants in mapping bias database.
INFO [2021-06-21 09:53:36] Creating normalDB...
Error in (function (fmt, ...)  :
  invalid format '%i'; use format %f, %e, %g or %a for numeric objects
Calls: createNormalDatabase ... flog.info -> .log_level -> layout -> do.call -> <Anonymous>
Execution halted
```

Thanks, 
Nihir

**Comment by lima1** [comment]
Just to make sure, you get the error also without the --normal_panel ?

**Comment by Admera2020** [comment]
Yup tried that too and just re-ran. Here is the log

```
INFO [2021-06-21 10:15:39] Loading PureCN 1.22.1...
INFO [2021-06-21 10:15:49] Creating normalDB...
Error in (function (fmt, ...)  :
  invalid format '%i'; use format %f, %e, %g or %a for numeric objects
Calls: createNormalDatabase ... flog.info -> .log_level -> layout -> do.call -> <Anonymous>
Execution halted

```

**Comment by lima1** [comment]
Then looks an issue with the coverage files. You sure that

ls PureCN_Coverage_Control/*loess.txt.gz > normal_coverages.list

works as expected, i.e. lists the paths to the files, one sample per line?

**Comment by Admera2020** [comment]
Yes, the list includes one file per line. To be sure I provide the full path to files. 
Also thought that may be one of the files is corrupted so tried a different set of files as well but the same error (Also re-ran coverage on all the files) . 
If it helps, here are a few lines from one of the files. 


```
Target total_coverage counts on_target duplication_rate
chr1:501-197168 0 0 0 NA
chr1:197169-393836 0 0 0 NA
chr1:393837-590505 0 0 0 NA
chr1:590506-787173 0 0 0 NA
chr1:787174-983841 0 0 0 NA
chr1:983842-1180510 0 0 0 NA
chr1:1180511-1377178 0 0 0 NA
chr1:1377179-1573847 0 0 0 NA
chr1:1573848-1770515 0 0 0 NA
chr1:1770516-1967183 0 0 0 NA
chr1:1967184-2163852 0 0 0 NA
chr1:2163853-2360520 0 0 0 NA
chr1:2360521-2557189 0 0 0 NA
chr1:2557690-2557884 59097.7347166776 708.569258325414 1 0.0770252324037185
chr1:2558352-2558504 15023.7744561826 190.889394101633 1 0.0531400966183575
chr1:2559824-2559987 35695.6808445429 483.361917232912 1 0.0769230769230769
chr1:2560581-2560766 34717.247884892 395.103394591787 1 0.0451127819548872
chr1:2561426-2561584 25628.6181280921 324.207121744426 1 0.0217983651226158
chr1:2561665-2561851 13708.4229173423 175.985265305308 1 0.0103626943005182

```

**Comment by lima1** [comment]
Hmm, ok. I'll dig deeper where this could happen. Not sure, never seen it before.

**Comment by Admera2020** [comment]
Thanks for your help and prompt response. 
I will try on my end too and will keep you posted. If you want I can email few files to you for debugging

**Comment by lima1** [comment]
Can you load the first sample in this file with 
x <- PureCN::readCoverageFile(files[1])

**Comment by Admera2020** [comment]
Loads without any error, here is the output of X

```
> x
GRanges object with 20945 ranges and 5 metadata columns:
          seqnames              ranges strand |  coverage average.coverage
             <Rle>           <IRanges>  <Rle> | <numeric>        <numeric>
      [1]     chr1          501-197168      * |         0                0
      [2]     chr1       197169-393836      * |         0                0
      [3]     chr1       393837-590505      * |         0                0
      [4]     chr1       590506-787173      * |         0                0
      [5]     chr1       787174-983841      * |         0                0
      ...      ...                 ...    ... .       ...              ...
  [20941]     chrX 155041021-155240895      * |         0                0
  [20942]     chrX 155240896-155440770      * |         0                0
  [20943]     chrX 155440771-155640645      * |         0                0
  [20944]     chrX 155640646-155840520      * |         0                0
  [20945]     chrX 155840521-156040395      * |         0                0
             counts on.target duplication.rate
          <numeric> <logical>        <numeric>
      [1]         0     FALSE               NA
      [2]         0     FALSE               NA
      [3]         0     FALSE               NA
      [4]         0     FALSE               NA
      [5]         0     FALSE               NA
      ...       ...       ...              ...
  [20941]         0     FALSE               NA
  [20942]         0     FALSE               NA
  [20943]         0     FALSE               NA
  [20944]         0     FALSE               NA
  [20945]         0     FALSE               NA
  -------
  seqinfo: 23 sequences from an unspecified genome; no seqlengths

```

**Comment by lima1** [comment]
Ok, running out of ideas. If you are willing to share some minimal example data for me to reproduce, let me know by email and I'll share a link to upload (unless it  fits in an attachment).

**Comment by lima1** [comment]
Run it on the whole bam files and then extract your regions of interest downstream. PureCN will benefit a lot from the additional data.

No need for off-target with WES, so simply generate the interval file for the WES baits file without --offtarget and follow the best practices.

**Comment by lima1** [comment]
(if the additional runtime of WES is an issue and parallelization isn't an option, you can filter the VCF to contain only 10,000 or so heterozygous SNPs on average. Keep a high density of SNPs close to your genes of interest. You can for example filter SNPs in baits with high and low GC-content outside those ROIs. That should provide high quality coverage and still an even tiling of SNPs.)

**Comment by Admera2020** [comment]
Thank you for the suggestion
