### ISSUE TITLE
Tumor purity estimation

### ISSUE THREAD

**Issue by kokyriakidis** [lima1/PureCN#186]
Hi!

Is there a way to estimate tumor purity on Tumor-only exome samples using PureCN? I mean without having matched normals.

**Comment by lima1** [comment]
Hi,

you'll need some normals from the same capture kit, but they don't need to be patient matched. 

There are FAQs in the vignette, but the more normals the better, ideally from multiple batches. PureCN will work with a minimum of 2 process-matched normals, but I would consider combined 5 from 2 batched the minimum. 

Markus

**Comment by kokyriakidis** [comment]
Thank you for your comment! Can PON samples come from the same kit but different sequencing machines?

**Comment by lima1** [comment]
Different read lengths might add some noise, but it’s probably not too terrible. Give it a try! The cleaner the data, the lower the purity you can reliably call copy number.  Eventually get a few Novaseq normals though, even just 2-3, and include them with the others.

**Comment by kokyriakidis** [comment]
So, using 13 Novaseq Normal samples processed with the same kit will give me accurate **"Contamination by Normals"** in my Tumor only samples? Sorry for asking so many times but calculating the tumor purity is essential for the analysis I want to make.

**Comment by lima1** [comment]
Yep
