### ISSUE TITLE
low coverage or single chr tests fail on run 

### ISSUE THREAD

**Issue by boyangzhao** [lima1/PureCN#192]
PureCN version: 1.23.7

This is perhaps not an urgent issue (as it deals with less realistic scenarios) and mostly corner cases. I often have unit tests using either downsampled fastq's or a single chr6 fastq as part of a quick run on entire workflows for quick validation purposes. All these runs (including cnvkit workflows) works fine, except when I use them also on PureCN downstream. PureCN just crashes, I guess whether by design should be left as such or should it fail more gracefully, or still output some results (albeit with a lot of noise). PureCN tested on full input data runs to completion without error.

Both examples below are providing to PureCN CNVkit coverage and segmentation files,

With 1M reads inputs, PureCN generated error while on the fitting step (?), with the following error,

```
Error in apply(C.likelihood[queryHits(ov), ], 1, which.max) : 
  dim(X) must have a positive length
Calls: runAbsoluteCN ... .fitSNV -> lapply -> lapply -> FUN -> .calcSNVLLik -> apply
In addition: Warning messages:
1: In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
2: In (function (fmt, ...)  :
  one argument not used by format 'Fitting variants with %s model for local optimum %i/%i...'
Execution halted
```

With a high coverage chr6-only input, PureCN generated error while on the 2D grid search step, with the following error,

```
Error in if (subclonal.f > max.non.clonal) return(-Inf) : 
  missing value where TRUE/FALSE needed
Calls: runAbsoluteCN ... .optimizeGrid -> lapply -> lapply -> FUN -> lapply -> lapply -> FUN
In addition: Warning messages:
1: In .bcfHeaderAsSimpleList(header) :
 duplicate keys in header will be forced to unique rownames
2: In .Seqinfo.mergexy(x, y) :
 The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
3: In .Seqinfo.mergexy(x, y) :
The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
4: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
5: In .Seqinfo.mergexy(x, y) :
 The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
6: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
Execution halted
```

While I can (and will) have separate unit tests for PureCN that would work, right now the unit tests (and happy flow tests) I use for the whole workflows would crash PureCN.

**Comment by lima1** [comment]
Thanks, agree it should die more gracefully. Feel free to upload the files to reproduce to Dropbox and I’ll fix.

**Comment by boyangzhao** [comment]
Thanks for the fixes (and your responses in the email)! The low coverage tests run fine to completion.
