### ISSUE TITLE
VCF from Mutect2.2 tumor-only calling throws error

### ISSUE THREAD

**Issue by ntbeileh** [lima1/PureCN#194]
I am trying to run PureCN using a VCF from Mutect2's tumor-only variant calling. And I get the following error.

Error: VCF either contains no germline variants or variants are not properly 
annotated. 
 
This is most likely a user error due to invalid input data or 
parameters (PureCN 1.22.2).

I ran Mutect2 using the following parameters:
gatk Mutect2 -R hg38.analysisSet.fa -I tumor.bam -O tumor.vcf.gz --genotype-germline-sites true --genotype-pon-sites true

And this is the header of my vcf file without the contig descriptions: 

##fileformat=VCFv4.2
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic   depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AF,Number=A,Type=Float,Description="Allele   fractions of alternate alleles in the tumor"> |  
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate   read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=F1R2,Number=R,Type=Integer,Description="Count   of reads in F1R2 pair orientation supporting each allele">
##FORMAT=<ID=F2R1,Number=R,Type=Integer,Description="Count   of reads in F2R1 pair orientation supporting each allele">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype   Quality"> |   |   |  
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype"> |   |   |   |  
##FORMAT=<ID=PGT,Number=1,Type=String,Description="Physical   phasing haplotype information, describing how the alternate alleles are   phased in relation to one another; will always be heterozygous and is not   intended to describe called alleles">
##FORMAT=<ID=PID,Number=1,Type=String,Description="Physical   phasing ID information, where each unique ID within a given sample (but not   across samples) connects records within a phasing group">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized,   Phred-scaled likelihoods for genotypes as defined in the VCF   specification">
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Phasing   set (typically the position of the first variant in the set)">
##FORMAT=<ID=SB,Number=4,Type=Integer,Description="Per-sample   component statistics which comprise the Fisher's Exact Test to detect strand   bias.">
##GATKCommandLine=<ID=Mutect2,CommandLine="Mutect2   --genotype-pon-sites true --genotype-germline-sites true --output   CR550mutect.vcf.gz --input ../02.Bam/CR550T.final.bam --reference   /Volumes/workstuff/hg38.analysisSet/hg38.analysisSet.fa --f1r2-median-mq 50   --f1r2-min-bq 20 --f1r2-max-depth 200 --af-of-alleles-not-in-resource -1.0   --mitochondria-mode false --tumor-lod-to-emit 3.0 --initial-tumor-lod 2.0   --pcr-snv-qual 40 --pcr-indel-qual 40 --max-population-af 0.01   --downsampling-stride 1 --callable-depth 10   --max-suspicious-reads-per-alignment-start 0 --normal-lod 2.2   --ignore-itr-artifacts false --gvcf-lod-band -2.5 --gvcf-lod-band -2.0   --gvcf-lod-band -1.5 --gvcf-lod-band -1.0 --gvcf-lod-band -0.5   --gvcf-lod-band 0.0 --gvcf-lod-band 0.5 --gvcf-lod-band 1.0   --minimum-allele-fraction 0.0 --independent-mates false   --disable-adaptive-pruning false --kmer-size 10 --kmer-size 25   --dont-increase-kmer-sizes-for-cycles false --allow-non-unique-kmers-in-ref   false --num-pruning-samples 1 --min-dangling-branch-length 4   --recover-all-dangling-branches false --max-num-haplotypes-in-population 128   --min-pruning 2 --adaptive-pruning-initial-error-rate 0.001   --pruning-lod-threshold 2.302585092994046 --pruning-seeding-lod-threshold   9.210340371976184 --max-unpruned-variants 100 --linked-de-bruijn-graph false   --disable-artificial-haplotype-recovery false   --enable-legacy-graph-cycle-detection false --debug-assembly false   --debug-graph-transformations false --capture-assembly-failure-bam false   --num-matching-bases-in-dangling-end-to-recover -1   --error-correction-log-odds -Infinity --error-correct-reads false   --kmer-length-for-read-error-correction 25   --min-observations-for-kmer-to-be-solid 20 --base-quality-score-threshold 18   --dragstr-het-hom-ratio 2 --dont-use-dragstr-pair-hmm-scores false   --pair-hmm-gap-continuation-penalty 10   --expected-mismatch-rate-for-read-disqualification 0.02   --pair-hmm-implementation FASTEST_AVAILABLE --pcr-indel-model CONSERVATIVE   --phred-scaled-global-read-mismapping-rate 45 --disable-symmetric-hmm-normalizing   false --disable-cap-base-qualities-to-map-quality false   --enable-dynamic-read-disqualification-for-genotyping false   --dynamic-read-disqualification-threshold 1.0 --native-pair-hmm-threads 4   --native-pair-hmm-use-double-precision false --bam-writer-type   CALLED_HAPLOTYPES --dont-use-soft-clipped-bases false   --min-base-quality-score 10 --smith-waterman JAVA --emit-ref-confidence NONE   --max-mnp-distance 1 --force-call-filtered-alleles false   --soft-clip-low-quality-ends false --allele-informative-reads-overlap-margin   2 --min-assembly-region-size 50 --max-assembly-region-size 300   --active-probability-threshold 0.002 --max-prob-propagation-distance 50   --force-active false --assembly-region-padding 100 --padding-around-indels 75   --padding-around-snps 20 --padding-around-strs 75   --max-extension-into-assembly-region-padding-legacy 25   --max-reads-per-alignment-start 50 --enable-legacy-assembly-region-trimming   false --interval-set-rule UNION --interval-padding 0 --interval-exclusion-padding   0 --interval-merging-rule ALL --read-validation-stringency SILENT   --seconds-between-progress-updates 10.0   --disable-sequence-dictionary-validation false --create-output-bam-index true   --create-output-bam-md5 false --create-output-variant-index true   --create-output-variant-md5 false --lenient false   --add-output-sam-program-record true --add-output-vcf-command-line true   --cloud-prefetch-buffer 40 --cloud-index-prefetch-buffer -1   --disable-bam-index-caching false --sites-only-vcf-output false --help false   --version false --showHidden false --verbosity INFO --QUIET false   --use-jdk-deflater false --use-jdk-inflater false --gcs-max-retries 20   --gcs-project-for-requester-pays    --disable-tool-default-read-filters false --max-read-length 2147483647   --min-read-length 30 --minimum-mapping-quality 20   --disable-tool-default-annotations false --enable-all-annotations   false",Version="4.2.0.0",Date="August 16, 2021 11:31:19   PM PDT">
##INFO=<ID=AS_SB_TABLE,Number=1,Type=String,Description="Allele-specific   forward/reverse read counts for strand bias tests. Includes the reference and   alleles separated by \|.">
##INFO=<ID=AS_UNIQ_ALT_READ_COUNT,Number=A,Type=Integer,Description="Number   of reads with unique start and mate end positions for each alt at a variant   site">
##INFO=<ID=CONTQ,Number=1,Type=Float,Description="Phred-scaled   qualities that alt allele are not due to contamination">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate   read depth; some reads may have been filtered"> |  
##INFO=<ID=ECNT,Number=1,Type=Integer,Description="Number   of events in this haplotype"> |   |  
##INFO=<ID=GERMQ,Number=1,Type=Integer,Description="Phred-scaled quality that alt alleles are not germline variants">
##INFO=<ID=MBQ,Number=R,Type=Integer,Description="median   base quality"> |   |   |  
##INFO=<ID=MFRL,Number=R,Type=Integer,Description="median   fragment length"> |   |   |  
##INFO=<ID=MMQ,Number=R,Type=Integer,Description="median   mapping quality"> |   |   |  
##INFO=<ID=MPOS,Number=A,Type=Integer,Description="median   distance from end of read"> |   |  
##INFO=<ID=NALOD,Number=A,Type=Float,Description="Negative   log 10 odds of artifact in normal with same allele fraction as   tumor">
##INFO=<ID=NCount,Number=1,Type=Integer,Description="Count   of N bases in the pileup"> |   |   |  
##INFO=<ID=NLOD,Number=A,Type=Float,Description="Normal   log 10 likelihood ratio of diploid het or hom alt genotypes">
##INFO=<ID=OCM,Number=1,Type=Integer,Description="Number   of alt reads whose original alignment doesn't match the current   contig.">
##INFO=<ID=PON,Number=0,Type=Flag,Description="site   found in panel of normals"> |   |   |  
##INFO=<ID=POPAF,Number=A,Type=Float,Description="negative   log 10 population allele frequencies of alt alleles"> |  
##INFO=<ID=ROQ,Number=1,Type=Float,Description="Phred-scaled   qualities that alt allele are not due to read orientation artifact">
##INFO=<ID=RPA,Number=R,Type=Integer,Description="Number   of times tandem repeat unit is repeated, for each allele (including   reference)">
##INFO=<ID=RU,Number=1,Type=String,Description="Tandem   repeat unit (bases)"> |   |   |  
##INFO=<ID=SEQQ,Number=1,Type=Integer,Description="Phred-scaled   quality that alt alleles are not sequencing errors">
##INFO=<ID=STR,Number=0,Type=Flag,Description="Variant   is a short tandem repeat"> |   |   |  
##INFO=<ID=STRANDQ,Number=1,Type=Integer,Description="Phred-scaled   quality of strand bias artifact"> |  
##INFO=<ID=STRQ,Number=1,Type=Integer,Description="Phred-scaled   quality that alt alleles in STRs are not polymerase slippage errors">
##INFO=<ID=TLOD,Number=A,Type=Float,Description="Log   10 likelihood ratio score of variant existing versus not existing">
##MutectVersion=2.2 

I noticed in the example VCF file provided that field that provides germline information is 
##INFO=<ID=P_GERMLINE,Number=A,Type=Float,Description="Posterior   probability for alt allele to be germline variants">

while the VCF file I have from Mutect2 has an info field of 
##INFO=<ID=GERMQ,Number=1,Type=Integer,Description="Phred-scaled quality that alt alleles are not germline variants">

Could this be the problem?

**Comment by lima1** [comment]
Hi, 

can you follow the best practices closely (add the germline genotype flags though as you did): https://gatk.broadinstitute.org/hc/en-us/articles/360035531132--How-to-Call-somatic-mutations-using-GATK4-Mutect2

I think once you added the GnomAD annotation in should work. Also run the other tools including FilterMutectCalls. This will make PureCN ignore variants that are likely artifacts.

Markus

**Comment by ntbeileh** [comment]
Ah that was the problem can't believe I missed that. Thank you.

**Comment by lima1** [comment]
Feel free to post here a log file of a final test run and I'll double check that everything looks good.
