### ISSUE TITLE
More consistency in output directory for Dx.R?

### ISSUE THREAD

**Issue by boyangzhao** [lima1/PureCN#196]
(sorry for yet another post, my unit testing ran into another error) For Dx.R, there is the argument `--out` that allows user to specify the location (and prefix) the output files go. However, if the input rds file does not come with a curation .csv file, `createCurationFile` is called to create a csv file, into the same folder directory as where the input rds file is located. This may cause some unexpected behaviors. When this code is run with dockers and in self-contained workflows, the origination folder (where rds is located) is often read-only, so trying to write will cause a write permission error. Also from an expected behavior perspective, I guess you wouldn't expect the method to mess with the origination folders when `--out` is specified. Perhaps either write curation csv file that respect the location of the `--out` or allow user to specify as separate argument to define location of the curation file when calling `Dx.R`?

**Comment by lima1** [comment]
Yeah, with this one I'm struggling a bit. The curation file tells which solution in the RDS file is correct, so you can see them as a pair. If you move the RDS, move the CSV as well, as you would with bam.bai or vcf.idx.

But yes, this maybe should not error out when the CSV file is not strictly needed.

**Comment by boyangzhao** [comment]
Thanks! It worked!
