### ISSUE TITLE
PureCN fails with segments too short

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#200]
Hi Markus, 

I have two problematic samples I was hoping to get some advice on. Not sure if you have seen this before or if there is some way to salvage either of these cases?

1. 
I have been trying to analyse a tumor only sample which looks like it has some serious issues with regard to its CNV data - strangely the general metrics look great - 300x+ coverage, multiqc metrics are all nominal but the CNV data looks horrendous.

I was wondering if there is anyway to save this sample to get something out of it or infact if you've seen something like this before and have any idea what happened.

I processed initially with CNVKIT and then provided the SEG file to PureCN. 

CNV plot chr1 (with good sample on left)
![image](https://user-images.githubusercontent.com/71687/134372441-7afb7baa-d2d5-45d8-aac3-52754a4a6910.png)

Is it possible this is close to 100% purity and that is why it looks so messy? 

2. I have a different issue with another tumor only sample, this one at least produces a segmentation plot but it looks like there are no CNV alterations accross the entire sample ( I just plot chr1 but all of them look the same). This sample also has  good coverage and general qc metrics. To me this looks like the purity is much lower than the estimated 0.28, is it possible the purity here is really much lower ? The pathology estimate was around 0.4 but don't have much faith in that. 

![image](https://user-images.githubusercontent.com/71687/134373096-c15e3123-2795-4e89-802f-11f0b2db6bb1.png)

Thanks!

**Comment by lima1** [comment]
Hmm, difficult to diagnose. Healthy coverage with bad segmentation hints at something being different. Are off-target regions ok (like try plotting off- and on-target log2 ratios separately and see if they are not aligned, or one super noisy)? 

No copy number is a good sign that purity is very low, unless you look at heme or pediatric cancers. CNVkit is quite aggressive in their default segmentation. This can result in overfitting of noise, resulting in too high purity. Look at the predicted somatic mutations, might give you more hints.

**Comment by waemm** [comment]
Thanks for the reply Markus!  Yes, its hard to explain to collaborators as the metrics look really decent. Off target look fine to me. Is it possible this is very high purity and for some reason it is being incorrectly identified? Could it be some kind of contamination event? 

![image](https://user-images.githubusercontent.com/71687/134481917-042c2313-2eeb-462d-93d5-7754ff63d9c7.png)

For the CNVkit results, are there any tweaks you can reccomend to reduce this behaviour? I assume running all these steps through purecn would be the best, this would involve a fair bit of change to our workflow, just curious if you believe the change would be worth the effort? ultimately the most important to us is accurate somatic variant prediction rather than purity estimation.

**Comment by lima1** [comment]
Contamination is usually obvious: you will see two bands of SNPs close to 0 and close to 1 (SNP alts or refs only present in contamination, respectively).

Off-target I mean if you do the CNVkit plot  yourself, if you mark on- and off-target, do you see that they disagree? It's a long shot.

You checked other QC metrics in Picard?

If it looks that bad, I don't think any tweaking will help. There is something different compared to the normals. If this is old FFPE, it happens. Degraded DNA results in smaller fragments, resulting in weird profiles when normalized against controls with longer fragment sizes.

**Comment by waemm** [comment]
Thanks mate, your help is much appreciated! When you mention contamination - I was just looking at a different project, this is a different sample that has the pattern you mention, is this almost certainly contamination?

I assume the large scale CNV across the right arm of chr1 is still legitimate though?

![image](https://user-images.githubusercontent.com/71687/134534102-2cc4e839-ad6e-429a-8bb1-f17ad134c6c6.png)


![image](https://user-images.githubusercontent.com/71687/134533482-a441143d-ecf6-4abf-a1cb-95917aa6356e.png)

**Comment by lima1** [comment]
Yes, and PureCN should hopefully flag this one.
