### ISSUE TITLE
Error in Coverage.R with WGS samples

### ISSUE THREAD

**Issue by jennyp76** [lima1/PureCN#205]
I'm trying to run PureCN with a family WGS samples( Mum, Dad and 2 children). 
Since, purecn doesn't require a matched normal, I was planning to use mum and dad's coverage data to run normalDB with the joint_germline.vcf (only mum&dad) to input as normal panel. 
So, it would be child1 vs normalDB(Mum&Dad) , child2 vs normalDB(Mum&Dad).

But I happen to face different errors when running Coverage.R with the children and parents. Since,  I had no problem running it with WES samples before, I probably think it has something to do with  WGS samples but I couldn't solve it by myself.  Just in case, the code I  used to calculate coverage is the same for all 4 wgs datas. 

What would be the problem here? Also, if there are suggestion about running trio samples. please let me know. 
 Thank you 

[Children]
Rscript $PURECN/Coverage.R \
        --out-dir $PureCN_Path/ \
        --bam $Aligned_Path/$INPUT \
        --intervals $INTERVAL
<Log File>

![image](https://user-images.githubusercontent.com/77954045/140299074-6095f38c-c4a6-4a84-ae68-6461890f917f.png)

<Error File>

![image](https://user-images.githubusercontent.com/77954045/140299118-16537af0-8cde-468b-ad55-3d5608a9d21a.png)

[Parents as Normal]
Rscript $PURECN/Coverage.R \
        --out-dir $PureCN_Path/normals \
        --bam $Aligned_Path/$INPUT \
        --intervals $INTERVAL
<Log File>

![image](https://user-images.githubusercontent.com/77954045/140318327-dcaa10bd-29f2-4250-84bf-4bd745db4f17.png)

<Error File>

![image](https://user-images.githubusercontent.com/77954045/140318370-d0592879-cb07-4183-bc9a-835f97eb0c3a.png)

**Session Info**
Please start R, type sessionInfo() and paste the output.
![image](https://user-images.githubusercontent.com/77954045/140298446-6d71d088-ffb2-4271-86f7-9b199366049c.png)

**Comment by lima1** [comment]
With WGS, you can safely skip GC normalization (Coverage.R --skipgcnorm IIRC). Then just use coverage.txt.gz instead of coverage_loess.txt.gz.

I would probably look into the GATK4 copy number workflow for WGS though. PureCN's normalization is a close reimplementation with tweaks for gene panels. You can always feed PureCN GATK output if the child is tumor data (PureCN is not made for germline).

**Comment by lima1** [comment]
Closing now since this appears to be an out of memory crash. Feel free to open a new issue when something comes up.

**Comment by jennyp76** [comment]
I have managed to finish coverage.R as you recommended( skipping normalization) and currently running normalDB.R. This [INFO] keeps on showing. Is it okay? Can I ignore it or do I have to adjust something?
Thank you in advance. 

![image](https://user-images.githubusercontent.com/77954045/140744903-9243710d-bdaa-4931-af3e-5e8b56f4650c.png)

**Comment by lima1** [comment]
That's fine for your case, it's explained in more detail in 4.2.1 of https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/PureCN.pdf

This function calculates the deviation of heterozygous SNP allelic fractions from the expected 0.5. With only 2 normals, we can't do a lot of fancy modelling of allelic fraction distributions, but better than nothing.

**Comment by maxanes** [comment]
HI, [jennyp76](https://github.com/jennyp76)
I am interested in running WGS data, may I ask how you made the interval file for WGS?
Thanks
