### ISSUE TITLE
Question related to reading results

### ISSUE THREAD

**Issue by maxanes** [lima1/PureCN#207]
Hi,
Could you please help me to correctly read the result file?
I am not sure what is the meaning of 2m1 or 4m2 on this graph below, is the first number, number of copies and if so what is m (multiplicity?) and the second number (number of chromosomes harboring the mutations)?
![image](https://user-images.githubusercontent.com/92018021/143460650-5e98774b-f3e7-4529-96b4-ff83541a2f08.png)

and for sex I get this but not predicted as XY or XX
INFO [2021-11-24 11:14:48] 1720 homozygous and 1093 heterozygous variants on chrX.
INFO [2021-11-24 11:14:48] Sex from VCF: NA (Fisher's p-value: < 0.0001, odds-ratio: 3.57).

This Is the final .csv file saying, how should I curate that?
Sampleid	 Purity       Ploidy    Sex   Contamination	 Flagged	    Failed	   Curated	Comment
X1737	0.62	     2,12739	M	           0            FALSE	      FALSE	      FALSE        NA

Thank you.

**Comment by lima1** [comment]
2m1 means total copy number 2, one of the copies mutated. So 2m1 is a normal heterozygous variant, in your case the expected allelic fraction is about 0.32 for that.

Have a look at the output section of
https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/PureCN.pdf#page11

Curation is useful when you think PureCN got the ranking wrong. Also described in the documentation.

**Comment by lima1** [comment]
Sex predicted from coverage us more reliable. In your case I think you have still a bunch of artifacts, confusing the VCF genotyper.
