### ISSUE TITLE
Conda installation for hg38 with dependencies

### ISSUE THREAD

**Issue by DanielAndreasen** [lima1/PureCN#208]
Hi,

I am trying to install PureCN with conda (`conda install -c bioconda bioconductor-purecn=2.0.1`), but I have some concerns:
- Is this for hg38? If not, how is this possible with conda?
- Is this the latest version? I know it is currently the latest version available with conda
- Is it possible to install with dependencies (e.g. optparse) since I use the CLI?

## Solution (Not ready yet)
```
conda install -c bioconda bioconductor-purecn=2.0.1
conda install -c conda-forge r-optparse
conda install -c bioconda bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
conda install -c conda-forge r-r.utils
```

**Comment by lima1** [comment]
Hi Daniel,

fair question, I only recently started using coda myself and I will go back and add the additional conda steps to the README.

For now, yes, 2.0.1 is the latest version (we have a stable release every 6 months and conda is only lagging for a week or two).

All additional dependencies are in conda. CRAN packages I get from the conda-forge channel, e.g.

`conda install -c conda-forge r-optparse`

Bioconductor from the bioconductor one:

`conda install -c bioconda bioconductor-txdb.hsapiens.ucsc.hg38.knowngene`

PureCN will tell you if an hg38 annotation file is missing.

And yes, you should definitely use the CLI. Feel free to post a log file of an example run when you think you have it up and running and I can double check that it's ready for production.

Markus

**Comment by DanielAndreasen** [comment]
I will make a fresh conda env to test this

**Comment by DanielAndreasen** [comment]
I will leave work soon, but is the error I get:
```
Error in fread(file) :
  To read gz and bz2 files directly, fread() requires 'R.utils' package which cannot be found. Please install 'R.utils' using 'install.packages('R.utils')'.
Calls: .gcNormalize ... correctCoverageBias -> readCoverageFile -> .readCoverageGatk3 -> fread
Execution halted
```
I guess it has to do with the vcf-file being `.vcf.gz`. Do you know if there is a conda package to install for this?

**Comment by lima1** [comment]
r-r.utils from conda-forge should do the trick.

**Comment by naumenko-sa** [comment]
This is how we conda (well mamba) purecn in bcbio:

https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/purecn_mappability.yaml

please note that the latest r-deconstructsigs is also released in conda - no need to CLI install it
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/r-deconstructsigs/meta.yaml

**Comment by lima1** [comment]
@naumenko-sa , GenomicsDB is still a bit of a pain to install. Since I know you tried it yourself, you are not aware, by any chance, of efforts to get it into conda? I have some bandwidth next week and can have a look, but thought I ask since I have you here...

**Comment by naumenko-sa** [comment]
No, we are still aggregating call with gatk3 in bcbio before PureCN.
I've tried GenomicsDB when prototyping the PureCN workflow in bcbio, but it was too complicated.
I don't think it is in conda - they offer R remotes or docker https://github.com/GenomicsDB/GenomicsDB-R.
Basically, we are downstream of conda in bcbio.

**Comment by lima1** [comment]
Thanks. I have it in our own docker image, but would be nice to add in conda. I'll see what I can do here.

**Comment by DanielAndreasen** [comment]
Hi, I managed to get PureCN running after the installed packaged above, so I will close this issue. Thanks for the help and for this nice tool
