### ISSUE TITLE
callAlterations() - type column

### ISSUE THREAD

**Issue by yls2g13** [lima1/PureCN#212]
Hi Markus! I was wondering, for `callAlterations(ret)`, it generates an object with a `type` column.
In the manual, it only explains that the column is either AMPLIFICATION or DELETION.
https://bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/PureCN.pdf

What does NA mean for this column? I've included a screenshot as well.

[screenshot.pdf](https://github.com/lima1/PureCN/files/7725448/screenshot.pdf)

**Comment by lima1** [comment]
That’s simply no call. Amplification cutoffs are tricky anyways and ideally should be determined for each gene. But those are the clear calls.
