### ISSUE TITLE
Question regarding output "

### ISSUE THREAD

**Issue by maxanes** [lima1/PureCN#215]
Hi Markus,
I have run some FFPE samples where I got summary results like below:
![image](https://user-images.githubusercontent.com/92018021/149495188-67f1e2ee-ad56-41f3-9de2-2988e1222811.png)
Done by WES  mean target coverages for this sample: 388X (tumor) 90X (normal). And the mean standard deviation of log-ratios: 0.61 (MAPD: 0.35) looks quite high? 
Can you help to understand why it has such output? Is it because it has a big difference between T and N? Also, I have seen  in guide that might be if exieeds the max. segments, but how do I check that?
![image](https://user-images.githubusercontent.com/92018021/149514956-e34ff941-ed9f-495b-a3b1-8784fcd26ffd.png)
![image](https://user-images.githubusercontent.com/92018021/149515193-017e4b92-034c-4c8c-903e-e66e9c0a4915.png)

Thank you

**Comment by lima1** [comment]
Yeah, that looks bad. Can you post log file as well? You using the normal coverage database for normalization? 90X for normals isn't bad at all.

Have a look at all the short segments with log ratio < -1. What are those? GC-outliers? Then you have a big GC/AT dropout, resulting in too low tumor coverage. In off-target regions? Maybe ignore them.

You can also make the segmentation more stringent or use the GATK4 segmentation, which usually takes better care of such obvious fragmentation.

If this is a male sample, VCF: F from VCF indicates many heterozygous variants on chrX. Your artefact filtering might be not optimal. You followed the GATK4/Mutect 2 best practices? Do you see any patterns in those SNP calls on chrX? Are those flagged and PureCN does include them anyways?

**Comment by maxanes** [comment]
Hi Markus,
Thank you for your quick response and sorry for the delay. Also thank you for the good advice. Yes, I do use pon of 35 for normalization, but this sample is run together with pon and its normal match sample.
Here is a log file:
[C15T09668D_ffpe.log](https://github.com/lima1/PureCN/files/7877740/C15T09668D_ffpe.log)
Also, I have run it only with a pon but it doesn't get much better, please find below the output files:
[9668.log](https://github.com/lima1/PureCN/files/7877794/9668.log)
[9668.csv](https://github.com/lima1/PureCN/files/7877795/9668.csv)
![image](https://user-images.githubusercontent.com/92018021/149675532-0f3cdcbb-6371-40d3-bc0b-e8ce0b979c5c.png)

How you have seen GC/AT dropout from posted data? How can I check those GC outliers?
"_Have a look at all the short segments with log-ratio < -1. What are those? GC-outliers? Then you have a big GC/AT dropout, resulting in too low tumor coverage. In off-target regions? Maybe ignore them._"

Unfortunately, I can't check sex until tomorrow, and yes we follow the Mutect 2 best practices.
BR
Marijana

**Comment by lima1** [comment]
Hi Marijana,

normal database normalization should always be better, and if you look at the log ratio standard deviations, it's definitely better, still terrible though.

You use the standard segmentation that does not use SNPs. Switch to GATK4 or PSCBS in PureCN.R --fun-segmentation. Your SNPs are much cleaner, so could rescue some.

What do you normally use to check for QC failures? If you use Picard, they provide AT and GC dropout metrics. Everything above 20-ish is pretty bad and makes copy number calling difficult.

To check in PureCN, not implemented by default, but the interval file lists the GC contents, so you could overlap the noisy segments with that.

Markus

**Comment by maxanes** [comment]
Hi Markus,
Ok I have tried another sample which is FFPE and quite nosy running with PSCBS and only with a normal database and still got quite bad output
[C14T09754D_ffpe.csv](https://github.com/lima1/PureCN/files/7887515/C14T09754D_ffpe.csv)
[C14T09754D_ffpe.log](https://github.com/lima1/PureCN/files/7887516/C14T09754D_ffpe.log)
![image](https://user-images.githubusercontent.com/92018021/149902294-3f2f423e-e601-411f-a5f4-b59ea3feaff7.png)

for QC I am checking parameters in log file such as for this sample AT/GC dropout: 1.06 (tumor), 1.00 (normal), 1.05 (coverage log-ratio), and mean standard deviation of log-ratios: 0.60 (MAPD: 0.32)
I didn't get this:
_"To check in PureCN, not implemented by default, but the interval file lists the GC contents, so you could overlap the noisy segments with that."_
This is my interval list with GC contents, do you mean to see GC content of noisy segments in the output file?
[baits_hg38_intervals.txt](https://github.com/lima1/PureCN/files/7887564/baits_hg38_intervals.txt)

Thank you for your assistance and sorry for the long posts and a lot of questions  :)

**Comment by lima1** [comment]
Try the GATK4 segmentation, it's usually less sensitive to noise.

AT/GC dropout in the log file is after GC-normalization, so not helpful so see if there is a too dramatic GC bias resulting in low coverage for large parts of the exons.  Btw, with a normal database, GC-normalization is not strictly necessary (good to benchmark actually) since the pool of normal learns GC bias automatically. Instead of using coverage_loess.txt.gz, one would use coverage.txt.gz for both tumor and normals when building the database. 

But Coverage.R generates a figure that plots coverage vs GC-content. So you can easily compare your cleanest samples vs bad samples and see if that looks drastically different.

**Comment by maxanes** [comment]
Hi Markus,

Thank you. I will try GATK. here are plots coverage vs GC-content for sample above (C14T09754D_ffpe)
C14T09754D_ffpe tumor alignment_coverage_loess
![C14T09754D_ffpe tumor alignment_coverage_loess](https://user-images.githubusercontent.com/92018021/150006004-84afb2b3-bf83-4ed9-9e68-c953f631c6e0.png)
C11A09754D_buffycoat normal alignment_coverage_
![C11A09754D_buffycoat normal alignment_coverage_loess](https://user-images.githubusercontent.com/92018021/150006006-3b8b0e05-3164-4d8d-b558-a5a5c3f706cb.png)
Seems as less GC content in off-target? 
And regarding the normalDB, you suggest to try to build it with pool of  coverage.txt.gz from normals, just to make sure I understood? and then when run PureCN to use coverage.txt.gz of tumor and pon with built normalsDB?

**Comment by lima1** [comment]
The GC-content of off-target is not that reliable since the regions are MUCH larger than the reads. Ideally GC-content should be read-based, but it's interval based.

But that first one looks really bad. Worse than I expected. I'm fairly certain our pipeline would fail those based on Picards CollectHsMetrics (not sure if this is still the name with recent version). The second looks kind of normal.

Yupp, you would not use the loess_coverage.txt.gz at all anywhere. With FFPE, GC-normalization might be still beneficial and you could see even worse results, but worth a shot. I don't use GC-normalization anymore, but we do mostly cfDNA and have lots of high quality normals. It's slightly better without GC-normalization, but YMMV.

**Comment by maxanes** [comment]
Hi Markus,
Sorry for a bit late response, Both figures are from the same pt the first one is a tumor and the second is from a normal WES sample. So the FFPE sample from the tumor has a problem because it has this peak of coverage between 50-75 on on-target?

I will give a shot to coverage.txt.gz for normals and let you know :) though I have problems mainly with FFPEs and low coverage of FRFR, but for those, I know that coverage below 100x is a problem.
Thank you.

**Comment by lima1** [comment]
You need to use either always coverage_loess.txt.gz or always coverage.txt.gz. In both NormalDB.R and PureCN.R and don’t provide —normal in PureCN. So don’t mix GC-normalized tumor coverages with non-GC-normalized normal databases. The more normal samples you have, the less important GC-normalization becomes. But this won’t rescue bad samples like this.

The main reasons for noise are high duplication or AT/GC dropout. High duplication is due to insufficient input material. Low unique coverage is a symptom here. Checkout the Picard QC tools and talk to the lab, they can tell you more. An AT dropout like this is pretty extreme and the lab might be able to explain why this happened.

**Comment by maxanes** [comment]
Thanks, I am taking care of that :)

I just created a PoN of 44 samples, non-GC normalized (coverage.txt.gz), and interval_weights looks like this:
Pon for same samples like below, though here 44 using coverage.txt.gz
![image](https://user-images.githubusercontent.com/92018021/150799130-e1de660f-4092-4c07-b53b-57375ee15b13.png)
Pon of 35 samples using coverage_loess.txt.gz
![image](https://user-images.githubusercontent.com/92018021/150799408-fa368113-0036-46cc-b503-79e982fcbf3b.png)

Does this look noisy, though not much more than GC normalized?

**Comment by lima1** [comment]
Try running it on a few representative tumor samples and compare the log ratio standard deviations, MAPD values as well as the number of segments of GC normalized vs not GC normalized.

**Comment by maxanes** [comment]
Hi,
Just update on the discussion above :)
I have run the same sample from above (C14T09754D_ffpe) using PoN of 44 samples without GC normalization and using coverage.txt and got I think worse results:

(PoN without GC norm)
Mean standard deviation of log-ratios: 0.62 (MAPD: 0.35)
![image](https://user-images.githubusercontent.com/92018021/151235331-eaa8b997-5e89-413e-ba22-814481591ec2.png)

(PoN with GC norm)
Mean standard deviation of log-ratios: 0.60 (MAPD: 0.32) 
![image](https://user-images.githubusercontent.com/92018021/151235627-aa663a9d-f052-4e3f-827f-3f98465103e0.png)
with comment on the end of log file WARN:Extensive noise in tumor compared to normals.

**Comment by lima1** [comment]
was worth a try! you could check some of your cleanest samples and see if it works better there. so if only the probably clear failures, at least for copy number calling, are worse, that might be not that relevant... 44 normal samples is good.

**Comment by maxanes** [comment]
I agree, but it is also only one sample try, and yes clear failure comments as you said due to GC/AT dropout, and probably those samples are not trustable results for cancer cell fractions, right?
I have also checked our samples in hs_metrics and for this sample looks like this
![image](https://user-images.githubusercontent.com/92018021/151240395-cb5627d3-f86a-4c70-9243-2cbc21dc0cb2.png)
Also, other FFPEs look similar.

**Comment by lima1** [comment]
Depends what you want to do with CCFs. If you have specific hypotheses for a given set of genes, you might be able to see that. The purity might be clearly in the right ballpark. It takes a bit of experience though. Like assume purity is 50% and allelic fraction is 0.25% and copy number in that region while noisy looks normal,  clearly mono-clonal. Much lower fraction -> likely sub-clonal.

Talk to the lab, sometimes a dataset is pretty bad for various reasons outside their control and they sequence precious samples anyways. If they tell you their lab QC metrics look fine and you get high dropout values like that across multiple different projects , then maybe something else is going wrong. Can’t think of anything though…

**Comment by maxanes** [comment]
Yes, I am looking that way, but still when I have all the other warnings and flags don't feel confident to say that mutation is clonal though have CCF 1. Thank you so much for your help and good advice!

**Comment by lima1** [comment]
Closing this issue now, but feel free to add or open a new one when something comes up.
