### ISSUE TITLE
Use PureCN in combination with HRDetect

### ISSUE THREAD

**Issue by kristianunger** [lima1/PureCN#216]
**Describe the issue**
Missing information in output/question about possibility to create output to be used in HRDetect

I am using PureCN for all my tumor WES analyses and now would like to apply the HRDetect pipeline https://github.com/eyzhao/hrdetect-pipeline and work out HRD scores. However, HRDetect requires the input as described here

https://github.com/eyzhao/hrdetect-pipeline#example-pipeline

so, for instance for LOH the LOH type is required. Is it possible to generate the LOH-types using the categories?

ASCNA: Allele-specific copy number amplification
BCNA: Balanced copy number amplification
HET: Heterozygous (normal)
NLOH: Neutral LOH (loss of heterozygosity, but 2 copies present)
DLOH: Deletion LOH
ALOH: Amplification LOH

Any help would be appreciated!

**Comment by lima1** [comment]
Yep, all you need is in the loh output file from PureCN.R. LOH is when M = 0 (M = minor copy number). So the different types are based on the C column (total copy number, minor + major copy number = total copy number).
C = 2: NLOH
C = 1 or 0: DLOH
C > 2: ALOH
BCNA: M > 1; C = M * 2
ASCNA: M > 1; C > 2
HET: M= 1; C = 2

Those classifications are sensitive to ploidy. So important to check cases with high ploidy if they are true genome duplications.

**Comment by kristianunger** [comment]
Thank you so much! I will try out and let you know how if it worked.
