### ISSUE TITLE
missing DB info field

### ISSUE THREAD

**Issue by kristianunger** [lima1/PureCN#217]
When calling variants using Mutect2 using the following code as part of a snakemake pipeline on paired tumor/normal mouse data

gatk --java-options '-Xmx32G' Mutect2 \
        -reference {params.reference_genome} \
        -L /home/zyto/unger/MoCaSeq/ref/GRCm38.p6/GRCm38.SureSelect_Mouse_All_Exon_V1.bed \
        -ip 75 \
        -input {input.tumor_filepath} \
        -input {input.normal_filepath} \
        --f1r2-tar-gz {output.tar} \
        --native-pair-hmm-threads 1 \
        --tmp-dir /home/zyto/unger/tmp \
        --genotype-germline-sites true \
        --genotype-pon-sites true \
        -output {output.vcf}) 2> {log}"

followed by annotation with VEP and I try to use the resulting vcf in PureCN I get the error/messages:

"WARN [2022-01-21 15:06:24] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2022-01-21 15:06:24] 0 (0.0%) variants annotated as likely germline (DB INFO flag).
FATAL [2022-01-21 15:06:24] VCF either contains no germline variants or variants are not properly 

FATAL [2022-01-21 15:06:24] annotated. 

FATAL [2022-01-21 15:06:24]  

FATAL [2022-01-21 15:06:24] This is most likely a user error due to invalid input data or 

FATAL [2022-01-21 15:06:24] parameters (PureCN 1.22.2). 

Error: VCF either contains no germline variants or variants are not properly 
annotated."

Any ideas what could go wrong here?

**Comment by lima1** [comment]
Hm, yes, I guess this should not error out when a matched normal is available. But adding a DB INFO flag should fix it. I'm not a mouse person, but this flag is for flagging SNPs in common germline databases.

**Comment by lima1** [comment]
If you are able to share the VCF (by email if there are concerns to put it here even temporarily), I'm happy to make it work without adding the DB flag. You can just provide a single chromosome, no need for the whole file.

**Comment by kristianunger** [comment]
Hi! That would be super great. Here you can find the file and drop any if necessary: https://medunimuenchende-my.sharepoint.com/:f:/g/personal/kristian_unger_med_uni-muenchen_de/Eid4UQVNM9xGoIG-ul2KzbYBthg5SvsG6193nhDa__mriA?e=EB5tIT

**Comment by lima1** [comment]
Thanks, will have a look!

**Comment by lima1** [comment]
Not 100% sure, but is it possible that you need to provide the normal sample id via  -normal? I think the way you called it, Mutect is running the two BAMs in tumor-only mode, but not sure. We don't do matched normals, so my experience is limited. The VCF does not have germline probabilities (GERMQ is NA for all variants).

Make sure to follow the complete best practices if you haven't. 
https://gatk.broadinstitute.org/hc/en-us/articles/360035531132

Installing genomicsdb is painful, but you could use our Docker image if needed to load the GATK4 genomicsdb when running NormalDB.R. It's only used to generate the mapping_bias.rds file.

**Comment by kristianunger** [comment]
Thanks for this! This actually did the trick! Many thanks - this saved me a lot of time!
