### ISSUE TITLE
Result interpretation

### ISSUE THREAD

**Issue by jennyp76** [lima1/PureCN#222]
Thanks to your help, I'm now trying to interpreate the results, but I have a basic question to ask regarding it.
You made a criteraia to define non-focal amplification when the copy number >= 7.
Would this mean that don't you see copy-netural LOH(2-0) or LOH(1-0) damaging???or are these two totally different concept?

**Comment by lima1** [comment]
Depends, LOH is important for tumor suppressor genes. You, for example, will almost always observe LOH when TP53 is mutated. For other loci it’s usually not as easy to show pathogenicity. There is after all another copy of the gene. It’s a bit like broad gains of 4 or 5 copies; for some genes that might have a significant effect, for others it’s just random chromosome instability.
