### ISSUE TITLE
 unable to find an inherited method for function ‘seqnames’ for signature ‘"list"’_ and extensive noise in tumours versus normals

### ISSUE THREAD

**Issue by rbell-img** [lima1/PureCN#224]
I am running PureCN with a panel of normals which contains only 3 samples. I am incurring an error which I have debugged using the commands provided from prev. issues. From what I understand this may not be a PureCN issue itself and could be a non-purecn issue, please find a screenshot of the error attached and also below:

_Error in '$ <- data.frame '('*tmp*, "arm", value="p") : 
replacement has 1 row, data has 0_ 

PureCN seems to complete producing the output files and there are no error in the logs themselves. However, I am seeing the following 'Extensive noise in tumours compared to normals' 

Previous error which relates to this: https://github.com/lima1/PureCN/issues/107

I debugged using the commands you provide and the rds file: 

_Error in (function (classes, fdef, mtable)  : 
 unable to find an inherited method for function ‘seqnames’ for signature ‘"list"’__

My command for running PureCN is: 

### Run PureCN 

while read b; do

        # download the bam file
        aws s3 cp s3:/***/${b} ${INPUT_DIR}/tumour_bams
        aws s3 cp s3://***/${b}.bai ${INPUT_DIR}/tumour_bams

        echo "Calculating coverage"
        # calculate the coverage
        Rscript $PURECN/Coverage.R --outdir ${OUT_DIR}/coverage/tumour \
                --bam  ${INPUT_DIR}/tumour_bams/${b##*/} \
                --intervals ${OUT_REF}/baits_hg19_intervals.txt \
                --cores 4 --force

        echo "Run PureCN"
        # get the sample name itself
        bam=${b##*/}
        samp=${bam%.final.bam}
        # run PureCN on the bam file
        mkdir ${OUT_DIR}/purecn/${samp}
        Rscript $PURECN/PureCN.R --out ${OUT_DIR}/purecn/${samp}  \
        --tumor $OUT_DIR/coverage/tumour/${samp}.final_coverage_loess.txt.gz \
        --sampleid ${samp} \
        --vcf ${INPUT_DIR}/tumour_bams/${samp}.final-filtered.vcf \
        --funsegmentation PSCBS \
        --normaldb ${OUT_DIR}/normalDB/normalDB_agilent_v7_hg19.fa.rds \
        --mappingbiasfile ${OUT_DIR}/normalDB/mapping_bias_agilent_v7_hg19.rds \
        --intervals ${OUT_REF}/baits_hg19_intervals.txt \
        --genome hg19 --force --postoptimize --seed 123
        #--model betabin \

done < "$bam_list"

## Log File: 

 Arguments: -tumor.coverage.file /home/rbell/PureCN/output_CNA/coverage/tumour/10300136701-IB200169-P0.final_coverage_loess.txt.gz -log.ratio  -seg.file  -vcf.file /home/rbell/PureCN/inputs/tumour_bams/10300136701-IB200169-P0.final-filtered.vcf -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf /home/rbell/PureCN/output_CNA/normalDB/mapping_bias_agilent_v7_hg19.rds -args.segmentation 0.005,NULL -sampleid 10300136701-IB200169-P0 -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file /home/rbell/PureCN/output_CNA/reference_files/baits_hg19_intervals.txt -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -DB.info.flag DB -POPAF.info.field POP_AF -model beta -post.optimize TRUE -BPPARAM  -log.file /home/rbell/PureCN/output_CNA/purecn/10300136701-IB200169-P0/10300136701-IB200169-P0.log -normal.coverage.file <data> -normalDB <data> -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2022-02-23 17:41:19] Loading coverage files...
INFO [2022-02-23 17:41:22] Mean target coverages: 62X (tumor) 60X (normal).
INFO [2022-02-23 17:41:23] Mean coverages: chrX: 39.14, chrY: 78.22, chr1-22: 58.12.
INFO [2022-02-23 17:41:23] Mean coverages: chrX: 32.00, chrY: 78.12, chr1-22: 56.14.
INFO [2022-02-23 17:41:36] Removing 830 intervals with missing log.ratio.
INFO [2022-02-23 17:41:36] Removing 8277 intervals excluded in normalDB.
INFO [2022-02-23 17:41:36] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2022-02-23 17:41:36] Removing 7665 low coverage (< 0.0015X) intervals.
INFO [2022-02-23 17:41:37] Using 211445 intervals (211445 on-target, 0 off-target).
INFO [2022-02-23 17:41:37] No off-target intervals. If this is hybrid-capture data, consider adding them.
INFO [2022-02-23 17:41:37] AT/GC dropout: 1.02 (tumor), 1.06 (normal).
INFO [2022-02-23 17:41:37] Loading VCF...
INFO [2022-02-23 17:41:39] Found 90032 variants in VCF file.
INFO [2022-02-23 17:41:39] Removing 439 triallelic sites.
INFO [2022-02-23 17:41:40] Maximum of POPAP INFO is > 1, assuming -log10 scaled values
WARN [2022-02-23 17:41:40] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2022-02-23 17:41:40] 35418 (39.5%) variants annotated as likely germline (DB INFO flag).
WARN [2022-02-23 17:41:42] Found 4 variants with missing allelic fraction starting with 6:32489856_C/A. Removing them.
INFO [2022-02-23 17:41:42] 10300136701 is tumor in VCF file.
INFO [2022-02-23 17:41:42] 328 homozygous and 82 heterozygous variants on chrX.
INFO [2022-02-23 17:41:42] Sex from VCF: M (Fisher's p-value: < 0.0001, odds-ratio: 7.56).
INFO [2022-02-23 17:41:42] Detected MuTect2 VCF.
INFO [2022-02-23 17:41:43] Removing 56930 Mutect2 calls due to blacklisted failure reasons.
INFO [2022-02-23 17:41:44] Initial testing for significant sample cross-contamination: unlikely
INFO [2022-02-23 17:41:44] Removing 16306 variants with AF < 0.030 or AF >= 0.970 or less than 3 supporting reads or depth < 15.
WARN [2022-02-23 17:41:44] Variant ids contain NAs at filter step BQ.
INFO [2022-02-23 17:41:45] Removing 0 low quality variants with BQ < 25.
INFO [2022-02-23 17:41:45] Total size of targeted genomic region: 40.82Mb (59.17Mb with 50bp padding).
INFO [2022-02-23 17:41:45] 7.1% of targets contain variants.
INFO [2022-02-23 17:41:45] Removing 628 variants outside intervals.
INFO [2022-02-23 17:41:45] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2022-02-23 17:41:45] Loading mapping bias file mapping_bias_agilent_v7_hg19.rds...
INFO [2022-02-23 17:41:46] Imputing mapping bias for 6934 variants...
INFO [2022-02-23 17:43:23] Excluding 3502 novel or poor quality variants from segmentation.
INFO [2022-02-23 17:43:23] Sample sex: M
INFO [2022-02-23 17:43:23] Segmenting data...
INFO [2022-02-23 17:43:23] Interval weights found, will use weighted PSCBS.
INFO [2022-02-23 17:43:24] Setting undo.SD parameter to 1.000000.
INFO [2022-02-23 17:44:09] Found 501 segments, exceeding max.segments threshold of 300.
INFO [2022-02-23 17:44:09] Setting undo.SD parameter to 1.500000.
INFO [2022-02-23 17:44:47] Setting prune.hclust.h parameter to 0.200000.
INFO [2022-02-23 17:44:49] Found 279 segments with median size of 1.39Mb.
INFO [2022-02-23 17:44:49] Using 15725 variants.
INFO [2022-02-23 17:44:49] Mean standard deviation of log-ratios: 0.42
INFO [2022-02-23 17:44:49] 2D-grid search of purity and ploidy...
INFO [2022-02-23 17:47:55] Local optima: 0.31/2.2, 0.38/2, 0.42/2.4, 0.52/3, 0.78/3.2, 0.92/3.4,
0.68/4, 0.52/2, 0.78/2
INFO [2022-02-23 17:47:55] Testing local optimum 1/9 at purity 0.31 and total ploidy 2.20...
INFO [2022-02-23 17:48:25] Recalibrating log-ratios...
INFO [2022-02-23 17:48:25] Testing local optimum 1/9 at purity 0.31 and total ploidy 2.20...
INFO [2022-02-23 17:49:00] Testing local optimum 2/9 at purity 0.38 and total ploidy 2.00...
INFO [2022-02-23 17:49:41] Recalibrating log-ratios...
INFO [2022-02-23 17:49:41] Testing local optimum 2/9 at purity 0.38 and total ploidy 2.00...
INFO [2022-02-23 17:50:16] Testing local optimum 3/9 at purity 0.42 and total ploidy 2.40...
INFO [2022-02-23 17:50:58] Recalibrating log-ratios...
INFO [2022-02-23 17:50:58] Testing local optimum 3/9 at purity 0.42 and total ploidy 2.40...
INFO [2022-02-23 17:51:42] Testing local optimum 4/9 at purity 0.52 and total ploidy 3.00...
INFO [2022-02-23 17:52:18] Testing local optimum 5/9 at purity 0.78 and total ploidy 3.20...
INFO [2022-02-23 17:52:39] Testing local optimum 6/9 at purity 0.92 and total ploidy 3.40...
INFO [2022-02-23 17:52:59] Testing local optimum 7/9 at purity 0.68 and total ploidy 4.00...
INFO [2022-02-23 17:53:31] Testing local optimum 8/9 at purity 0.52 and total ploidy 2.00...
INFO [2022-02-23 17:53:57] Testing local optimum 9/9 at purity 0.78 and total ploidy 2.00...
INFO [2022-02-23 17:54:16] Skipping 3 solutions that converged to the same optima.
INFO [2022-02-23 17:54:16] Fitting variants with beta model for local optimum 1/9...
INFO [2022-02-23 17:54:17] Fitting variants for purity 0.36, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 17:55:32] Fitting variants for purity 0.32, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 17:56:45] Fitting variants for purity 0.33, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 17:57:54] Fitting variants for purity 0.34, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 17:59:06] Fitting variants for purity 0.35, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 18:00:18] Fitting variants for purity 0.37, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 18:01:31] Fitting variants for purity 0.38, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 18:02:51] Fitting variants for purity 0.39, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 18:04:06] Fitting variants for purity 0.40, tumor ploidy 4.16 and contamination 0.01.
INFO [2022-02-23 18:05:21] Optimized purity: 0.37
INFO [2022-02-23 18:05:21] Fitting variants with beta model for local optimum 4/9...
INFO [2022-02-23 18:05:22] Fitting variants for purity 0.57, tumor ploidy 4.61 and contamination 0.01.
INFO [2022-02-23 18:06:37] Rare karyotype solution. Skipping post-optimization.
INFO [2022-02-23 18:06:37] Optimized purity: 0.57
INFO [2022-02-23 18:06:37] Fitting variants with beta model for local optimum 5/9...
INFO [2022-02-23 18:06:38] Fitting variants for purity 0.80, tumor ploidy 3.68 and contamination 0.01.
INFO [2022-02-23 18:07:53] Poor goodness-of-fit (0.728). Skipping post-optimization.
INFO [2022-02-23 18:07:53] Optimized purity: 0.80
INFO [2022-02-23 18:07:53] Fitting variants with beta model for local optimum 7/9...
INFO [2022-02-23 18:07:54] Fitting variants for purity 0.78, tumor ploidy 5.39 and contamination 0.01.
INFO [2022-02-23 18:09:08] Rare karyotype solution. Skipping post-optimization.
INFO [2022-02-23 18:09:08] Optimized purity: 0.78
INFO [2022-02-23 18:09:08] Fitting variants with beta model for local optimum 8/9...
INFO [2022-02-23 18:09:09] Fitting variants for purity 0.48, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:10:23] Fitting variants for purity 0.44, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:11:37] Fitting variants for purity 0.45, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:12:51] Fitting variants for purity 0.46, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:14:06] Fitting variants for purity 0.47, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:15:20] Fitting variants for purity 0.49, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:16:34] Fitting variants for purity 0.50, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:17:47] Fitting variants for purity 0.51, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:19:04] Fitting variants for purity 0.52, tumor ploidy 3.28 and contamination 0.01.
INFO [2022-02-23 18:20:18] Optimized purity: 0.44
INFO [2022-02-23 18:20:18] Fitting variants with beta model for local optimum 9/9...
INFO [2022-02-23 18:20:20] Fitting variants for purity 0.59, tumor ploidy 2.69 and contamination 0.01.
INFO [2022-02-23 18:21:32] Poor goodness-of-fit (0.712). Skipping post-optimization.
INFO [2022-02-23 18:21:32] Optimized purity: 0.59
INFO [2022-02-23 18:21:33] Done.
INFO [2022-02-23 18:21:33] ------------------------------------------------------------
INFO [2022-02-23 18:21:37] Generating output files...
INFO [2022-02-23 18:21:53] Tumor/normal noise ratio: 15.846
WARN [2022-02-23 18:21:53] Extensive noise in tumor compared to normals.

## Panel of normals

I prepared the panel of normals using bcftools as I had a lot of problems retaining the 'AD' tag. I used a docker image of PureCN to create a genomicsDB which did not retain the flag and I also used the createsomaticpanelofnormals command which also did not retain the tag.

This is the bcftools command, I suspect this may be causing my issues: 

for vp in $v_pon
do

bcftools filter \
    --include 'FORMAT/AD[0:1]>1' \
    ${vp} | \
    sed -e 's/ID=RU,Number=1/ID=RU,Number=A/' -e 's/ID=AD,Number=R/ID=AD,Number=./' |
    bcftools norm \
    --fasta-ref ${OUT_REF}/hg19.fa \
    --check-ref s \
    --multiallelics -both \
    --output-type z \
    --output ${bcftools_dir}/${vp##*/}
done

bcftools merge \
    --merge none \
    --output-type z \
    --output ${bcftools_dir}combined_pon.vcf.gz \
    ${bcftools_dir}/*vcf.gz

tabix -p vcf  ${bcftools_dir}combined_pon.vcf.gz

I would like to:

a) Determine whether the original issue, not in the logs but displayed on stdout is a PureCN issue 
b) Determine whether my panel of normals is suitable. I have the mutect2 vcfs for these, do you have any recommendations on how to combined these whilst retaining the 'AD' tag

Thanks for your help

**Comment by lima1** [comment]
Before we start debugging, can you try the latest version? You did not copy the version number in the output, but this looks older, right? Either stable 2.0.1 or current devel 2.1.8 would be fine.

**Comment by rbell-img** [comment]
Yep - I was following the best practices guided and I am not up to date, I will update to the latest version and I will confirm if there are still errors

**Comment by lima1** [comment]
And genomicsdb import should work well with recent GATK4 and PureCN, let me know if not.

**Comment by lima1** [comment]
No bcftools necessary, just standard GATK4 best practices

**Comment by rbell-img** [comment]
Hi,

When I generate the normal db I still run into the issue with the AD flag, they are in the original vcfs: 

Processing 1$10002719$10002813 (offset 0, length 249250621)...
Error in value_vars(value.var, names(data)) :
  value.var values [AD] are not found in 'data'.
Calls: calculateMappingBiasGatk4 ... .parseADGenomicsDb -> dcast -> dcast.data.table -> value_vars
Execution halted

I am also re-running purecn with the panel of normals I created with bcftools

**Comment by lima1** [comment]
On it! Thanks for reporting. This

```
Error in '$ <- data.frame '('tmp, "arm", value="p") :
replacement has 1 row, data has 0
```

was fixed by updating?

"Extensive noise in tumor" is relatively normal. Mean standard deviation of 0.42 is on the high side though, but 60X is also fairly low. For >100X you should get closer to 0.25, especially for fresh frozen or very young FFPE.

**Comment by rbell-img** [comment]
I still incur the same error with: 

 packageVersion("PureCN")
[1] ‘2.0.1’

**Comment by rbell-img** [comment]
Yes : 
 loh <- callLOH(rds)
Error in `$<-.data.frame`(`*tmp*`, "arm", value = "p") :
  replacement has 1 row, data has 0

**Comment by lima1** [comment]
Ok, just to be sure, that rds file was generated by 2.0.1? 

rds$version

**Comment by rbell-img** [comment]
Apologies I checked a different sample, I am not getting the error with the new version

```
_Error in `$<-.data.frame`(`*tmp*`, "arm", value = "p") :
  replacement has 1 row, data has 0_
```

I think the only possible issue is the pon, do you think the above bcftools commands used to generate the pon could be affecting the output? 

Thank you for your help

**Comment by lima1** [comment]
I’ll look into it and will update the other issue. Seems like something in dependencies changed, breaking it.

**Comment by rbell-img** [comment]
thanks!
