### ISSUE TITLE
About local optima

### ISSUE THREAD

**Issue by X1angyang** [lima1/PureCN#228]
Hi,
    I have a question about find local optima. Before SA, we use grid search and define a total-ploidy to search  max  likelihood, local optima is find in such likelihood matrix. But, actually, the total-ploidy is not equal p * tumor_ploidy + 2 * ( 1 - purity), why the true local optima is in above solution. 

   Thanks,
   XiangY.

**Comment by lima1** [comment]
Hi Xiang,

the grid search is just a simple and fast heuristic to reduce the search space. It is only using tumor vs normal coverage log2 ratios distributions. Think of it as finding purity and ploidy combinations that somehow fit to the log ratio histograms that are part of the output. These inital tumor and total ploidies are not necessarily the same as the final ones after fitting the VCF via SA. Does this answer your question? Feel free to provide particular examples you are struggling to understand.

Best,
Markus
