### ISSUE TITLE
WGS data

### ISSUE THREAD

**Issue by maxanes** [lima1/PureCN#229]
Hi,
I would like to try running PureCN on WGS data. 
Can you please tell me if it is possible to run WGS data and what should be used as an interval file?

Thank you.

**Comment by lima1** [comment]
I would probably use GATK4 for normalization and segmentation and then load those output files. The vignette lists a few other tools that are likely better for WGS. Sorry, I don’t work with WGS data, so proper support is unlikely coming anytime soon.

**Comment by maxanes** [comment]
I thought so, but it is a very nice tool for WES data :)
If I use GATK4 for segmentation and normalization, do I need an interval file when I run PureCN and what should be used in that case?

**Comment by lima1** [comment]
It will extract the information from the coverage files. So not strictly necessary.

**Comment by maxanes** [comment]
Thank you.
