### ISSUE TITLE
Allow unmatched cols in .annotatePosteriorsVcf

### ISSUE THREAD

**Issue by andrewrech** [lima1/PureCN#23]
`.annotatePosteriorsVcf` fails when gene.symbol is missing because [`match` returns NA](https://github.com/lima1/PureCN/blob/bc4259799fb4293318cd2a6bf44de271afdecfaf/R/predictSomatic.R#L118). Allow omission?

```r
idxColsMisc <- match(idxColsMisc, colnames(pp))
idxColsMisc <- na.omit(idxColsMisc)
```

Happy to explain further if unclear

Love your work, Markus, wonderful job with this package.

**Comment by lima1** [comment]
Thanks Andrew! Should be fixed. 

The inst/ext/IntervalFile.R script should automatically add gene symbols when you provide a supported reference version.

**Comment by andrewrech** [comment]
thanks
