### ISSUE TITLE
Poor GOF

### ISSUE THREAD

**Issue by rbell-img** [lima1/PureCN#230]
**Describe the issue**
For all of my samples I am seeing poor GOF. The normals are process matched, I am now using a panel of 4 PBMCs. 

"Sampleid","Purity","Ploidy","Sex","Contamination","Flagged","Failed","Curated","Comment"
"10300136984-IPSA-19036-NCGM-214-Imagen-Therapeutics-12D5-3_S211",0.83,3.22178336190441,"Coverage: F VCF: M",0,TRUE,FALSE,FALSE,"POOR GOF (53.4%);HIGH AT- OR GC-DROPOUT"

I also get excessive noise in tumour versus normals. 

**To Reproduce**

Rscript $PURECN/NormalDB.R \
--outdir normalDB \
--coveragefiles ${OUT_DIR}/coverage/normals/normal_coverages.list \
--normal_panel /home/rbell/PureCN/pon_db \
--genome  ${OUT_REF}/hg19.fa \
--assay agilent_v7

while read b; do

	# download the bam file
	aws s3 cp s3://imagen-therapeutics-ngs-datastore/${b} ${INPUT_DIR}/tumour_bams 
        aws s3 cp s3://imagen-therapeutics-ngs-datastore/${b}.bai ${INPUT_DIR}/tumour_bams
	
	echo "Calculating coverage" 
	# calculate the coverage 
	Rscript $PURECN/Coverage.R --outdir ${OUT_DIR}/coverage/tumour \
		--bam  ${INPUT_DIR}/tumour_bams/${b##*/} \
		--intervals ${OUT_REF}/baits_hg19_intervals.txt \
		--cores 4 --force

	echo "Run PureCN"
	# get the sample name itself 
	bam=${b##*/}
	samp=${bam%.final.bam}
	# run PureCN on the bam file 
	mkdir ${OUT_DIR}/purecn/${samp}
        Rscript $PURECN/PureCN.R --out ${OUT_DIR}/purecn/${samp}  \
        --tumor $OUT_DIR/coverage/tumour/${samp}.final_coverage_loess.txt.gz \
        --sampleid ${samp} \
        --vcf ${INPUT_DIR}/tumour_bams/${samp}.final-filtered.vcf \
        --funsegmentation PSCBS \
        --normaldb ${OUT_DIR}/normalDB/normalDB_agilent_v7_hg19.fa.rds \
        --mappingbiasfile ${OUT_DIR}/normalDB/mapping_bias_agilent_v7_hg19.rds \
        --intervals ${OUT_REF}/baits_hg19_intervals.txt \
        --genome hg19 --force --postoptimize --seed 123
       

done < "$bam_list"

**Expected behavior**
I did expect high purity for this sample which is confirmed by the output however this is inconsistent across samples 

**Log file**

INFO [2022-03-24 19:08:33] Arguments: -tumor.coverage.file /home/rbell/PureCN/output_CNA/coverage/tumour/10300136984-IPSA-19036-NCGM-214-Imagen-Therapeutics-12D5-3_S211.final_coverage_loess.txt.gz -log.ratio  -seg.file  -vcf.file /home/rbell/PureCN/inputs/tumour_bams/10300136984-IPSA-19036-NCGM-214-Imagen-Therapeutics-12D5-3_S211.final-filtered.vcf -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf /home/rbell/PureCN/output_CNA/normalDB/mapping_bias_agilent_v7_hg19.fa.rds -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid 10300136984-IPSA-19036-NCGM-214-Imagen-Therapeutics-12D5-3_S211 -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file /home/rbell/PureCN/output_CNA/reference_files/baits_hg19_intervals.txt -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model beta -post.optimize TRUE -log.file /home/rbell/PureCN/output_CNA/purecn/10300136984-IPSA-19036-NCGM-214-Imagen-Therapeutics-12D5-3_S211/10300136984-IPSA-19036-NCGM-214-Imagen-Therapeutics-12D5-3_S211.log -normal.coverage.file <data> -normalDB <data> -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2022-03-24 19:08:33] Using BiocParallel for parallel optimization.
INFO [2022-03-24 19:08:33] Loading coverage files...
INFO [2022-03-24 19:08:37] Mean target coverages: 113X (tumor) 110X (normal).
INFO [2022-03-24 19:08:38] Mean coverages: chrX: 59.45, chrY: 1.04, chr1-22: 108.06.
INFO [2022-03-24 19:08:38] Mean coverages: chrX: 109.50, chrY: 1.05, chr1-22: 105.09.
INFO [2022-03-24 19:08:51] Removing 986 intervals with missing log.ratio.
INFO [2022-03-24 19:08:51] Removing 6272 intervals excluded in normalDB.
INFO [2022-03-24 19:08:51] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2022-03-24 19:08:51] Removing 4816 low count (< 100 total reads) intervals.
INFO [2022-03-24 19:08:51] Removing 1 low coverage (< 0.0015X) intervals.
INFO [2022-03-24 19:08:52] Using 215004 intervals (215004 on-target, 0 off-target).
INFO [2022-03-24 19:08:52] No off-target intervals. If this is hybrid-capture data, consider adding them.
INFO [2022-03-24 19:08:52] AT/GC dropout: 1.04 (tumor), 1.02 (normal), 1.06 (coverage log-ratio).
WARN [2022-03-24 19:08:52] High GC-bias in normalized tumor vs normal log2 ratio.
INFO [2022-03-24 19:08:52] Loading VCF...
INFO [2022-03-24 19:08:58] Found 245044 variants in VCF file.
INFO [2022-03-24 19:08:59] Removing 1138 triallelic sites.
INFO [2022-03-24 19:09:00] Maximum of POPAP INFO is > 1, assuming -log10 scaled values
WARN [2022-03-24 19:09:00] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2022-03-24 19:09:00] 57802 (23.7%) variants annotated as likely germline (DB INFO flag).
INFO [2022-03-24 19:09:05] 10300136984 is tumor in VCF file.
INFO [2022-03-24 19:09:06] 454 homozygous and 70 heterozygous variants on chrX.
INFO [2022-03-24 19:09:06] Sex from VCF: M (Fisher's p-value: < 0.0001, odds-ratio: 9.84).
WARN [2022-03-24 19:09:06] Sex mismatch of coverage and VCF. Could be because of noisy data, contamination, loss of chrY or a mis-alignment of coverage and VCF.
INFO [2022-03-24 19:09:06] Detected MuTect2 VCF.
INFO [2022-03-24 19:09:08] Removing 179773 Mutect2 calls due to blacklisted failure reasons.
INFO [2022-03-24 19:09:11] Initial testing for significant sample cross-contamination: unlikely
INFO [2022-03-24 19:09:12] Removing 35560 variants with AF < 0.030 or AF >= 0.970 or less than 4 supporting reads or depth < 15.
WARN [2022-03-24 19:09:12] Variant ids contain NAs at filter step BQ.
INFO [2022-03-24 19:09:12] Removing 0 low quality variants with BQ < 25.
INFO [2022-03-24 19:09:12] Total size of targeted genomic region: 44.47Mb (62.48Mb with 50bp padding).
INFO [2022-03-24 19:09:12] 11.5% of targets contain variants.
INFO [2022-03-24 19:09:12] Removing 2012 variants outside intervals.
INFO [2022-03-24 19:09:12] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2022-03-24 19:09:13] Loading mapping bias file mapping_bias_agilent_v7_hg19.fa.rds...
INFO [2022-03-24 19:09:13] Found 1200127 variants in mapping bias file.
INFO [2022-03-24 19:09:14] Imputing mapping bias for 13362 variants...
INFO [2022-03-24 19:10:47] Excluding 12038 novel or poor quality variants from segmentation.
INFO [2022-03-24 19:10:47] Sample sex: F
INFO [2022-03-24 19:10:47] Segmenting data...
INFO [2022-03-24 19:10:47] Interval weights found, will use weighted PSCBS.
INFO [2022-03-24 19:10:47] MAPD of 10482 allelic fractions: 0.09 (0.10 adjusted).
INFO [2022-03-24 19:10:48] Setting undo.SD parameter to 1.000000.
INFO [2022-03-24 19:11:26] Setting prune.hclust.h parameter to 0.200000.
INFO [2022-03-24 19:11:28] Found 260 segments with median size of 1.44Mb.
INFO [2022-03-24 19:11:28] Removing 1 variants outside segments.
INFO [2022-03-24 19:11:28] Using 26560 variants.
INFO [2022-03-24 19:11:29] Mean standard deviation of log-ratios: 0.29 (MAPD: 0.24)
INFO [2022-03-24 19:11:29] 2D-grid search of purity and ploidy...
INFO [2022-03-24 19:11:50] Local optima: 0.45/2.8, 0.29/2, 0.31/2.4, 0.58/3.6, 0.65/2.8, 0.48/2.1,
0.88/4, 0.58/2, 0.85/2.8, 0.88/4.8, 0.52/1.4, 0.78/2
INFO [2022-03-24 19:11:50] Testing local optimum 1/12 at purity 0.45 and total ploidy 2.80...
INFO [2022-03-24 19:11:50] Testing local optimum 2/12 at purity 0.29 and total ploidy 2.00...
INFO [2022-03-24 19:11:50] Testing local optimum 3/12 at purity 0.31 and total ploidy 2.40...
INFO [2022-03-24 19:11:50] Testing local optimum 4/12 at purity 0.58 and total ploidy 3.60...
INFO [2022-03-24 19:11:50] Testing local optimum 5/12 at purity 0.65 and total ploidy 2.80...
INFO [2022-03-24 19:11:50] Testing local optimum 6/12 at purity 0.48 and total ploidy 2.10...
INFO [2022-03-24 19:11:50] Testing local optimum 7/12 at purity 0.88 and total ploidy 4.00...
INFO [2022-03-24 19:11:50] Testing local optimum 8/12 at purity 0.58 and total ploidy 2.00...
INFO [2022-03-24 19:11:50] Testing local optimum 9/12 at purity 0.85 and total ploidy 2.80...
INFO [2022-03-24 19:11:50] Testing local optimum 10/12 at purity 0.88 and total ploidy 4.80...
INFO [2022-03-24 19:11:50] Testing local optimum 11/12 at purity 0.52 and total ploidy 1.40...
INFO [2022-03-24 19:11:50] Testing local optimum 12/12 at purity 0.78 and total ploidy 2.00...
INFO [2022-03-24 19:11:56] Recalibrating log-ratios...
INFO [2022-03-24 19:11:56] Testing local optimum 11/12 at purity 0.52 and total ploidy 1.40...
INFO [2022-03-24 19:12:01] Recalibrating log-ratios...
INFO [2022-03-24 19:12:01] Testing local optimum 11/12 at purity 0.52 and total ploidy 1.40...
INFO [2022-03-24 19:12:01] Recalibrating log-ratios...
INFO [2022-03-24 19:12:01] Testing local optimum 3/12 at purity 0.31 and total ploidy 2.40...
INFO [2022-03-24 19:12:06] Recalibrating log-ratios...
INFO [2022-03-24 19:12:06] Testing local optimum 11/12 at purity 0.52 and total ploidy 1.40...
INFO [2022-03-24 19:12:11] Recalibrating log-ratios...
INFO [2022-03-24 19:12:11] Testing local optimum 9/12 at purity 0.85 and total ploidy 2.80...
INFO [2022-03-24 19:12:17] Recalibrating log-ratios...
INFO [2022-03-24 19:12:17] Testing local optimum 5/12 at purity 0.65 and total ploidy 2.80...
INFO [2022-03-24 19:12:20] Recalibrating log-ratios...
INFO [2022-03-24 19:12:20] Testing local optimum 8/12 at purity 0.58 and total ploidy 2.00...
INFO [2022-03-24 19:12:22] Recalibrating log-ratios...
INFO [2022-03-24 19:12:22] Testing local optimum 1/12 at purity 0.45 and total ploidy 2.80...
INFO [2022-03-24 19:12:25] Recalibrating log-ratios...
INFO [2022-03-24 19:12:25] Testing local optimum 7/12 at purity 0.88 and total ploidy 4.00...
INFO [2022-03-24 19:12:33] Recalibrating log-ratios...
INFO [2022-03-24 19:12:33] Testing local optimum 12/12 at purity 0.78 and total ploidy 2.00...
INFO [2022-03-24 19:12:33] Recalibrating log-ratios...
INFO [2022-03-24 19:12:33] Testing local optimum 4/12 at purity 0.58 and total ploidy 3.60...
INFO [2022-03-24 19:12:33] Recalibrating log-ratios...
INFO [2022-03-24 19:12:33] Testing local optimum 6/12 at purity 0.48 and total ploidy 2.10...
INFO [2022-03-24 19:12:47] Recalibrating log-ratios...
INFO [2022-03-24 19:12:47] Testing local optimum 9/12 at purity 0.85 and total ploidy 2.80...
INFO [2022-03-24 19:12:56] Recalibrating log-ratios...
INFO [2022-03-24 19:12:56] Testing local optimum 1/12 at purity 0.45 and total ploidy 2.80...
INFO [2022-03-24 19:13:00] Recalibrating log-ratios...
INFO [2022-03-24 19:13:00] Testing local optimum 5/12 at purity 0.65 and total ploidy 2.80...
INFO [2022-03-24 19:13:03] Recalibrating log-ratios...
INFO [2022-03-24 19:13:03] Testing local optimum 2/12 at purity 0.29 and total ploidy 2.00...
INFO [2022-03-24 19:13:05] Recalibrating log-ratios...
INFO [2022-03-24 19:13:05] Testing local optimum 7/12 at purity 0.88 and total ploidy 4.00...
INFO [2022-03-24 19:13:11] Recalibrating log-ratios...
INFO [2022-03-24 19:13:11] Testing local optimum 4/12 at purity 0.58 and total ploidy 3.60...
INFO [2022-03-24 19:13:23] Recalibrating log-ratios...
INFO [2022-03-24 19:13:23] Testing local optimum 4/12 at purity 0.58 and total ploidy 3.60...
INFO [2022-03-24 19:13:37] Recalibrating log-ratios...
INFO [2022-03-24 19:13:37] Testing local optimum 1/12 at purity 0.45 and total ploidy 2.80...
INFO [2022-03-24 19:13:42] Recalibrating log-ratios...
INFO [2022-03-24 19:13:42] Testing local optimum 2/12 at purity 0.29 and total ploidy 2.00...
INFO [2022-03-24 19:13:47] Recalibrating log-ratios...
INFO [2022-03-24 19:13:47] Testing local optimum 7/12 at purity 0.88 and total ploidy 4.00...
INFO [2022-03-24 19:14:28] Skipping 1 solutions that converged to the same optima.
INFO [2022-03-24 19:14:28] Skipping 1 solutions exceeding max.non.clonal (0.20): 0.42/2.16 (purity/tumor ploidy)
INFO [2022-03-24 19:14:28] Fitting variants with beta model for local optimum 1/12...
INFO [2022-03-24 19:14:28] Fitting variants with beta model for local optimum 2/12...
INFO [2022-03-24 19:14:28] Fitting variants with beta model for local optimum 3/12...
INFO [2022-03-24 19:14:28] Fitting variants with beta model for local optimum 5/12...
INFO [2022-03-24 19:14:28] Fitting variants with beta model for local optimum 6/12...
INFO [2022-03-24 19:14:28] Fitting variants with beta model for local optimum 7/12...
INFO [2022-03-24 19:14:28] Fitting variants with beta model for local optimum 8/12...
INFO [2022-03-24 19:14:28] Fitting variants with beta model for local optimum 9/12...
INFO [2022-03-24 19:14:29] Fitting variants with beta model for local optimum 10/12...
INFO [2022-03-24 19:14:29] Fitting variants with beta model for local optimum 12/12...
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.51, tumor ploidy 5.04 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.37, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.42, tumor ploidy 4.59 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.64, tumor ploidy 4.56 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.61, tumor ploidy 3.56 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.81, tumor ploidy 5.32 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.47, tumor ploidy 2.74 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.83, tumor ploidy 3.22 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.95, tumor ploidy 5.95 and contamination 0.01.
INFO [2022-03-24 19:14:30] Fitting variants for purity 0.60, tumor ploidy 2.24 and contamination 0.01.
INFO [2022-03-24 19:16:44] Rare karyotype solution. Skipping post-optimization.
INFO [2022-03-24 19:16:44] Optimized purity: 0.51
INFO [2022-03-24 19:16:44] Rare karyotype solution. Skipping post-optimization.
INFO [2022-03-24 19:16:44] Optimized purity: 0.81
INFO [2022-03-24 19:16:45] Poor goodness-of-fit (0.706). Skipping post-optimization.
INFO [2022-03-24 19:16:45] Optimized purity: 0.61
INFO [2022-03-24 19:16:45] Poor goodness-of-fit (0.680). Skipping post-optimization.
INFO [2022-03-24 19:16:45] Optimized purity: 0.47
INFO [2022-03-24 19:16:45] Poor goodness-of-fit (0.385). Skipping post-optimization.
INFO [2022-03-24 19:16:45] Optimized purity: 0.60
INFO [2022-03-24 19:16:45] Rare karyotype solution. Skipping post-optimization.
INFO [2022-03-24 19:16:45] Optimized purity: 0.42
INFO [2022-03-24 19:16:46] Rare karyotype solution. Skipping post-optimization.
INFO [2022-03-24 19:16:46] Optimized purity: 0.64
INFO [2022-03-24 19:16:46] Poor goodness-of-fit (0.534). Skipping post-optimization.
INFO [2022-03-24 19:16:46] Optimized purity: 0.83
INFO [2022-03-24 19:16:46] Rare karyotype solution. Skipping post-optimization.
INFO [2022-03-24 19:16:46] Optimized purity: 0.95
INFO [2022-03-24 19:16:46] Fitting variants for purity 0.33, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:19:02] Fitting variants for purity 0.34, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:21:18] Fitting variants for purity 0.35, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:23:34] Fitting variants for purity 0.36, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:25:49] Fitting variants for purity 0.38, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:28:06] Fitting variants for purity 0.39, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:30:22] Fitting variants for purity 0.40, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:32:38] Fitting variants for purity 0.41, tumor ploidy 4.26 and contamination 0.01.
INFO [2022-03-24 19:34:55] Optimized purity: 0.39
INFO [2022-03-24 19:34:55] Done.
INFO [2022-03-24 19:34:55] ------------------------------------------------------------
INFO [2022-03-24 19:35:05] Generating output files...
INFO [2022-03-24 19:35:30] Tumor/normal noise ratio: 13.902
WARN [2022-03-24 19:35:30] Extensive noise in tumor compared to normals.
INFO [2022-03-24 19:35:30] Using BiocParallel for parallel optimization.

**B-allele frequency plot**

![image](https://user-images.githubusercontent.com/92730922/160119694-1bc42d95-5efb-4474-9cc5-1394a3f1b191.png)

Additional info: 

Coverage from loess.txt

PBMC1:
mean.coverage.ontarget mean.coverage.offtarget mean.duplication.ontarget mean.duplication.offtarget mom.raw.ontarget mom.raw.offtarget mom.post.gc.ontarget mom.post.gc.offtarget mom.post.reptiming.ontarget mom.post.reptiming.offtarget
72.5941883560167  0.54299063158207  0.944767300768795  0.940291615335126  0.940291615335126

PBMC2:
mean.coverage.ontarget mean.coverage.offtarget mean.duplication.ontarget mean.duplication.offtarget mom.raw.ontarget mom.raw.offtarget mom.post.gc.ontarget mom.post.gc.offtarget mom.post.reptiming.ontarget mom.post.reptiming.offtarget
85.1058077064394  0.573190826645468  0.930463865180932  0.933829249391519  0.933829249391519

PBMC3:
mean.coverage.ontarget mean.coverage.offtarget mean.duplication.ontarget mean.duplication.offtarget mom.raw.ontarget mom.raw.offtarget mom.post.gc.ontarget mom.post.gc.offtarget mom.post.reptiming.ontarget mom.post.reptiming.offtarget
45.1083830133847  0.51011925457268  0.924617492664817  0.928424222220793  0.928424222220793

PBMC4:
mean.coverage.ontarget mean.coverage.offtarget mean.duplication.ontarget mean.duplication.offtarget mom.raw.ontarget mom.raw.offtarget mom.post.gc.ontarget mom.post.gc.offtarget mom.post.reptiming.ontarget mom.post.reptiming.offtarget
89.8301828978843  0.561431138818597  0.933530744693964  0.932766463936515  0.932766463936515

Would you advise removing PBMC3 from my panel?

**Comment by rbell-img** [comment]
Hi I am just adding the B allele frequency plot with copy number - thanks in advance 

![image](https://user-images.githubusercontent.com/92730922/160120380-05ae89b6-4b44-429d-9676-6108e3a5471c.png)

**Comment by rbell-img** [comment]
I also find that the coverage in the log file does not align with coverage in the pdf, am I interpreting this correctly?

Thanks in advance

**Comment by lima1** [comment]
Sure. What I do first is look at regions with balanced SNPs around 0.5: End of 1q, large parts of 4-11, 14, 20p.  These should have even copy numbers 2 (1+1, 1 copy ref, 1 copy alt), 4 (2+2), 6 (3+3), ... . Unbalanced are more complex, i.e. more solutions can fit the data, for example copy number of 4 can be 0+4, 1+3 instead of just 2+2.

If you are lucky, there are cases with different copy numbers, here for example 7 and 11. This shows that the algorithm found a good fit to align integer copy numbers to the data. If there is no 1+1 balanced state, only 2+2 and 3+3, then the ploidy is most certainly too high. 

Looks like ch2 is also balanced, but somehow assigned a copy number of 3. I guess the segmentation algorithm somehow forced the coverage up or down. Maybe there is some sub-clonal gains, confusing the algorithm (coverage too high for 2 copies, but not enough for 3), but hard to see in the sampling noise.

**Comment by lima1** [comment]
With that many SNPs and high purity, you also try fun-segmentation GATK4. Maybe the segmentation looks a bit cleaner. PSCBS is what we use for our high coverage, low purity, panel data. GATK4 is probably more tuned towards WES.

**Comment by rbell-img** [comment]
Perfect - thank you for your advice I appreciate it

**Comment by rbell-img** [comment]
Although some of our samples are low purity - some are flagged, this is a high purity sample and most are ~0.5, would you still recommend using GATK4 segmentation in this case?
