### ISSUE TITLE
parameter settiing for low-coverage whole genome sequencing data

### ISSUE THREAD

**Issue by hfl112** [lima1/PureCN#231]
Hi,
I am recently using pureCN based on cnvkit segments. I found many samples have not enough germline mutations to estimate ploidy and purity. 
Is this because the parameter I set is too strict to call? or because of the pretty low coverage of some samples? I have many samples only have ~5X-10X depth.

command:
`Rscript R/library/PureCN/extdata/PureCN.R --out /pureCN/purecn_output/1979_WGS --sampleid 1979_WGS --tumor pureCN/cnr_cnvkit/1979_WGS.T.cnr --seg-file pureCN/SEG_cnvkit/1979_WGS.seg --mapping-bias-file /pureCN/WGS_mapping_bias.rds --vcf /pureCN/mutect/1979_WGS.raw.vcf --snp-blacklist /pureCN/hg38_simpleRepeats.bed --genome hg38 --fun-segmentation none --force --post-optimize --seed 123 --sex M`

> INFO [2022-04-06 10:12:40] Loading coverage files...
> WARN [2022-04-06 10:12:42] Multiple chromosomes with very low coverage: chr15_KI270851v1_alt,chr22_KI270879v1_alt,chr7_KI270803v1_alt
> INFO [2022-04-06 10:12:43] Provided log2-ratio looks too noisy, using segmentation only.
> WARN [2022-04-06 10:12:43] Provided sampleid (1979_WGS) does not match 1979_WGS.T found in segmentation.
> INFO [2022-04-06 10:12:45] Removing 5 intervals with missing log.ratio.
> INFO [2022-04-06 10:12:45] Removing 6 intervals on non-standard chromosomes not listed in centromeres (chr1_KI270711v1_random,chr7_KI270803v1_alt,chr15_KI270850v1_alt,chr15_KI270851v1_alt,chr17_KI270909v1_alt,chr22_KI270879v1_alt).
> INFO [2022-04-06 10:12:45] Using 160335 intervals (160335 on-target, 0 off-target).
> INFO [2022-04-06 10:12:45] No off-target intervals. If this is hybrid-capture data, consider adding them.
> INFO [2022-04-06 10:12:45] Loading VCF...
> INFO [2022-04-06 10:15:47] Found 3042948 variants in VCF file.
> INFO [2022-04-06 10:15:59] Removing 8553 triallelic sites.
> WARN [2022-04-06 10:16:02] Found GERMQ info field with Phred scaled germline probabilities.
> INFO [2022-04-06 10:16:18] Maximum of POPAP INFO is > 1, assuming -log10 scaled values
> WARN [2022-04-06 10:16:21] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
> INFO [2022-04-06 10:16:27] 2563776 (84.5%) variants annotated as likely germline (DB INFO flag).
> WARN [2022-04-06 10:17:51] Found 183134 variants with missing allelic fraction starting with chr1:39143_C/A. Removing them.
> INFO [2022-04-06 10:18:28] 1979_WGS is tumor in VCF file.
> INFO [2022-04-06 10:18:47] 1 homozygous and 4 heterozygous variants on chrX.
> INFO [2022-04-06 10:18:47] Sex from VCF: NA (Fisher's p-value: 0.261, odds-ratio: 4.02).
> INFO [2022-04-06 10:18:47] Detected MuTect2 VCF.
> INFO [2022-04-06 10:19:07] Removing 0 Mutect2 calls due to blacklisted failure reasons.
**> INFO [2022-04-06 10:19:13] Removing 2592950 non heterozygous (in matched normal) germline SNPs.**
> INFO [2022-04-06 10:19:15] Removing 86733 low quality variants with non-offset BQ < 25.
> INFO [2022-04-06 10:19:15] Base quality scores range from 24 to 32 (offset by 1)
> INFO [2022-04-06 10:19:15] Minimum number of supporting reads ranges from 2 to 15, depending on coverage and BQS.
> INFO [2022-04-06 10:19:53] Removing 168898 variants with AF < 0.030 or AF >= 1.000 or insufficient supporting reads or depth < 15.
> INFO [2022-04-06 10:19:59] Removing 1389 blacklisted variants.
> INFO [2022-04-06 10:19:59] Total size of targeted genomic region: 28.60Mb (44.53Mb with 50bp padding).
> INFO [2022-04-06 10:20:00] 0.0% of targets contain variants.
> INFO [2022-04-06 10:20:00] Removing 1289 variants outside intervals.
> INFO [2022-04-06 10:20:00] Found SOMATIC annotation in VCF.
> INFO [2022-04-06 10:20:00] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
> INFO [2022-04-06 10:20:00] Found SOMATIC annotation in VCF. Setting mapping bias to 0.651.
> INFO [2022-04-06 10:20:00] Loading mapping bias file WGS_mapping_bias.rds...
> INFO [2022-04-06 10:28:36] Found 80418457 variants in mapping bias file.
> INFO [2022-04-06 10:29:48] Imputing mapping bias for 0 variants...
> INFO [2022-04-06 10:29:51] Excluding 1 novel or poor quality variants from segmentation.
> INFO [2022-04-06 10:29:51] Excluding 0 variants not in pool of normals from segmentation.
> INFO [2022-04-06 10:29:51] Sample sex: M
> INFO [2022-04-06 10:29:51] Segmenting data...
> INFO [2022-04-06 10:29:51] Loaded provided segmentation file 1979_WGS.seg (format DNAcopy).
> WARN [2022-04-06 10:29:51] Provided sampleid (1979_WGS) does not match 1979_WGS.T found in segmentation.
> INFO [2022-04-06 10:29:51] Re-centering provided segment means (offset -0.1328).
> INFO [2022-04-06 10:29:51] Found 55 segments with median size of 42.53Mb.
> INFO [2022-04-06 10:29:51] Using 2 variants.
> INFO [2022-04-06 10:29:51] Mean standard deviation of log-ratios: 0.40 (MAPD: 0.00)
> INFO [2022-04-06 10:29:51] 2D-grid search of purity and ploidy...
> ERROR in: Rscript R/library/PureCN/extdata/PureCN.R --out /pureCN/purecn_output/1979_WGS --sampleid 1979_WGS --tumor pureCN/cnr_cnvkit/1979_WGS.T.cnr --seg-file pureCN/SEG_cnvkit/1979_WGS.seg --mapping-bias-file /pureCN/WGS_mapping_bias.rds --vcf /pureCN/mutect/1979_WGS.raw.vcf --snp-blacklist /pureCN/hg38_simpleRepeats.bed --genome hg38 --fun-segmentation none --force --post-optimize --seed 123 --sex M

Any suggestions might be appreciated.
Thanks,
Funan

**Comment by lima1** [comment]
Hi Funan, I don’t think PureCN is the best tool for your data. In your case a tool that uses SNP phasing would be much more powerful because it can efficiently summarize SNPs in segments. Thus can much better extract information that is hidden in the low coverage. See for example Battenberg from the Sanger. PureCN currently does not support phasing because it’s not worth in panel data.

**Comment by hfl112** [comment]
> Hi Funan, I don’t think PureCN is the best tool for your data. In your case a tool that uses SNP phasing would be much more powerful because it can efficiently summarize SNPs in segments. Thus can much better extract information that is hidden in the low coverage. See for example Battenberg from the Sanger. PureCN currently does not support phasing because it’s not worth in panel data.

Thanks lima for the reply. I am also thinking it's the problem of this low coverage data. Actually, I have corresponding WES data, pureCN works perfectly well for those data. I just wondering whether the WGS data will have a better performance in predicting purity and ploidy. cuz in general, I found even though these WGS data have low coverage, those data still have a very decent CNV segment prediction using cnvkit. I found for some WGS samples, I have the predicted purity and ploidy, it mostly correlates with WES results, but for samples with low purity or high ploidy, the correlation is bad. Nevertheless, I think it should be hard to estimate the purity and ploidy for low purity or high ploidy cases. I think I will use the results from  WES.

Thanks ~
Funan

**Comment by lima1** [comment]
PureCN is not really utilizing the benefit of WGS. Battenberg would be the fair comparison with PureCN WES. If both are from the same DNA sample, you can try using the CNVkit WGS with WES VCF, but I never tried this. Battenberg and PureCN and manually curating discrepancies would be my approach.
