### ISSUE TITLE
PureCN with CNVkit output - Cannot find valid purity/ploidy solution

### ISSUE THREAD

**Issue by Jwong684** [lima1/PureCN#232]
I recently got PureCN to work quite well with several of my exomes. I noticed that for some cnvkit output that over-segmented the sample, PSCBS instead of Hclust in PureCN gave me really clean results. However, for a couple samples, I could not get PureCN to run no matter what. For the most part, my pipeline to run pureCN from cnvkit follows this thread quite closely: https://www.biostars.org/p/472617/

I created a panel of normals for mutect2 to be used for all the tumours, and I used bcftools merge to create a panel of normals for normalDB.R.

In general my run looks like this:
` 
Rscript $PURECN/PureCN.R --out results/cnvkit-1.0_masked/pureCN/06-pureCN/idt/CLC01362/                  --sampleid CLC01362                 --tumor results/cnvkit-1.0_masked/pureCN/05-cnvkit-cnr/idt/CLC01362.cnr                 --seg-file results/cnvkit-1.0_masked/pureCN/03-cnvkit_seg/idt/CLC01362.seg                 --stats-file results/cnvkit-1.0_masked/pureCN/04-mutect2/idt/CLC01362/CLC01362.stats                 --vcf results/cnvkit-1.0_masked/pureCN/04-mutect2/idt/CLC01362/CLC01362.vcf.gz                 --snp-blacklist results/cnvkit-1.0_masked/pureCN/00-bam/repeatmasker.grch37.bed                 --mappingbiasfile results/cnvkit-1.0_masked/pureCN/02-pon/mapping_bias_idt_hg19.rds                 --genome hg19                 --fun-segmentation PSCBS                --max-copy-number 8                 --model betabin                 --cores 3                 --force --post-optimize --seed 123
`

From the 21 samples that failed, the error logs either look like this:
**Log file 1**
WARN [2022-04-28 20:36:43] Deprecated arguments, use --mapping-bias-file instead.
[1] "/projects/dscott_scratch/CCSRI_1500/exomes/results_local/cnvkit-1.0_masked/pureCN/06-pureCN/idt/CLC01362"
INFO [2022-04-28 20:36:43] Loading PureCN 2.0.1...
Warning messages:
1: package ‘DNAcopy’ was built under R version 4.1.2
2: package ‘VariantAnnotation’ was built under R version 4.1.2
3: package ‘IRanges’ was built under R version 4.1.2
4: package ‘Biobase’ was built under R version 4.1.2
5: package ‘Rsamtools’ was built under R version 4.1.2
6: package ‘Biostrings’ was built under R version 4.1.2
7: package ‘XVector’ was built under R version 4.1.2
INFO [2022-04-28 20:36:44] Using BiocParallel MulticoreParam backend with 3 cores.
INFO [2022-04-28 20:36:44] ------------------------------------------------------------
INFO [2022-04-28 20:36:44] PureCN 2.0.1
INFO [2022-04-28 20:36:44] ------------------------------------------------------------
INFO [2022-04-28 20:36:44] Arguments: -normal.coverage.file  -tumor.coverage.file results/cnvkit-1.0_masked/pureCN/05-cnvkit-cnr/idt/CLC01362.cnr -log.ratio  -seg.file results/cnvkit-1.0_masked/pureCN/03-cnvkit_seg/idt/CLC01362.seg -vcf.file results/cnvkit-1.0_masked/pureCN/04-mutect2/idt/CLC01362/CLC01362.vcf.gz -normalDB  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf results/cnvkit-1.0_masked/pureCN/02-pon/mapping_bias_idt_hg19.rds -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid CLC01362 -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file  -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model betabin -post.optimize TRUE -log.file results/cnvkit-1.0_masked/pureCN/06-pureCN/idt/CLC01362//CLC01362.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2022-04-28 20:36:44] Using BiocParallel for parallel optimization.
INFO [2022-04-28 20:36:44] Loading coverage files...
INFO [2022-04-28 20:36:48] Provided log2-ratio looks too noisy, using segmentation only.
INFO [2022-04-28 20:36:49] Mean coverages: chrX: 10.98, chrY: 15.89, chr1-22: 22.57.
INFO [2022-04-28 20:36:49] Mean coverages: chrX: 10.98, chrY: 15.89, chr1-22: 22.57.
INFO [2022-04-28 20:36:49] Removing 30 intervals with missing log.ratio.
INFO [2022-04-28 20:36:49] Using 227596 intervals (193310 on-target, 34286 off-target).
INFO [2022-04-28 20:36:49] Ratio of mean on-target vs. off-target read counts: NaN
INFO [2022-04-28 20:36:49] Mean off-target bin size: 31623
INFO [2022-04-28 20:36:49] Loading VCF...
INFO [2022-04-28 20:36:56] Found 244079 variants in VCF file.
INFO [2022-04-28 20:36:57] Removing 1729 triallelic sites.
INFO [2022-04-28 20:36:58] Maximum of POPAP INFO is > 1, assuming -log10 scaled values
WARN [2022-04-28 20:36:58] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2022-04-28 20:36:58] 105610 (43.6%) variants annotated as likely germline (DB INFO flag).
INFO [2022-04-28 20:37:03] CLC01362 is tumor in VCF file.
INFO [2022-04-28 20:37:06] 170 homozygous and 105 heterozygous variants on chrX.
INFO [2022-04-28 20:37:06] Sex from VCF: NA (Fisher's p-value: < 0.0001, odds-ratio: 3.07).
WARN [2022-04-28 20:37:06] MuTect stats file lacks contig and position columns.
INFO [2022-04-28 20:37:17] Initial testing for significant sample cross-contamination: unlikely
INFO [2022-04-28 20:37:18] Removing 211672 variants with AF < 0.030 or AF >= 0.970 or less than 3 supporting reads or depth < 15.
INFO [2022-04-28 20:37:24] Removing 2193 blacklisted variants.
WARN [2022-04-28 20:37:25] Variant ids contain NAs at filter step BQ.
INFO [2022-04-28 20:37:25] Removing 0 low quality variants with BQ < 25.
INFO [2022-04-28 20:37:25] Total size of targeted genomic region: 31.70Mb (50.24Mb with 50bp padding).
INFO [2022-04-28 20:37:25] 8.0% of targets contain variants.
INFO [2022-04-28 20:37:25] Removing 9458 variants outside intervals.
INFO [2022-04-28 20:37:25] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2022-04-28 20:37:25] Loading mapping bias file mapping_bias_idt_hg19.rds...
INFO [2022-04-28 20:38:20] Found 14273459 variants in mapping bias file.
INFO [2022-04-28 20:38:30] Imputing mapping bias for 3369 variants...
INFO [2022-04-28 20:43:42] Excluding 5315 novel or poor quality variants from segmentation.
INFO [2022-04-28 20:43:42] Excluding 3369 variants not in pool of normals from segmentation.
INFO [2022-04-28 20:43:42] Sample sex: M
INFO [2022-04-28 20:43:42] Segmenting data...
INFO [2022-04-28 20:43:42] Loaded provided segmentation file CLC01362.seg (format DNAcopy).
INFO [2022-04-28 20:43:42] Re-centering provided segment means (offset 0.0111).
INFO [2022-04-28 20:43:42] Setting prune.hclust.h parameter to 0.150000.
INFO [2022-04-28 20:43:42] Found 142 segments with median size of 6.38Mb.
INFO [2022-04-28 20:43:42] Removing 27 variants outside segments.
INFO [2022-04-28 20:43:42] Using 19000 variants.
INFO [2022-04-28 20:43:44] Mean standard deviation of log-ratios: 0.40 (MAPD: 0.00)
INFO [2022-04-28 20:43:44] Mean standard deviation of on-target log-ratios only: 0.00 (MAPD: 0.00)
INFO [2022-04-28 20:43:44] Mean standard deviation of off-target log-ratios only: 0.00 (MAPD: 0.00)
INFO [2022-04-28 20:43:44] 2D-grid search of purity and ploidy...
INFO [2022-04-28 20:47:32] Local optima: 0.17/2.4, 0.25/2.1, 0.33/2.8, 0.29/3, 0.88/5.8, 0.55/4.4,
0.52/3.2, 0.45/2.6, 0.45/4, 0.29/1.8, 0.85/4.8, 0.23/1.9, 0.21/2,
0.62/2.8, 0.45/1.6, 0.88/3, 0.58/2, 0.72/5.8, 0.78/2, 0.62/1.4
INFO [2022-04-28 20:47:32] Testing local optimum 1/20 at purity 0.17 and total ploidy 2.40...
INFO [2022-04-28 20:47:45] Recalibrating log-ratios...
INFO [2022-04-28 20:47:45] Testing local optimum 1/20 at purity 0.17 and total ploidy 2.40...
INFO [2022-04-28 20:47:56] Recalibrating log-ratios...
INFO [2022-04-28 20:47:56] Testing local optimum 1/20 at purity 0.17 and total ploidy 2.40...
INFO [2022-04-28 20:48:07] Recalibrating log-ratios...
INFO [2022-04-28 20:48:07] Testing local optimum 1/20 at purity 0.17 and total ploidy 2.40...
INFO [2022-04-28 20:48:19] Testing local optimum 2/20 at purity 0.25 and total ploidy 2.10...
INFO [2022-04-28 20:48:28] Recalibrating log-ratios...
INFO [2022-04-28 20:48:28] Testing local optimum 2/20 at purity 0.25 and total ploidy 2.10...
INFO [2022-04-28 20:48:38] Recalibrating log-ratios...
INFO [2022-04-28 20:48:38] Testing local optimum 2/20 at purity 0.25 and total ploidy 2.10...
INFO [2022-04-28 20:48:49] Recalibrating log-ratios...
INFO [2022-04-28 20:48:49] Testing local optimum 2/20 at purity 0.25 and total ploidy 2.10...
INFO [2022-04-28 20:48:59] Testing local optimum 3/20 at purity 0.33 and total ploidy 2.80...
INFO [2022-04-28 20:49:08] Recalibrating log-ratios...
INFO [2022-04-28 20:49:08] Testing local optimum 3/20 at purity 0.33 and total ploidy 2.80...
INFO [2022-04-28 20:49:18] Recalibrating log-ratios...
INFO [2022-04-28 20:49:18] Testing local optimum 3/20 at purity 0.33 and total ploidy 2.80...
INFO [2022-04-28 20:49:28] Recalibrating log-ratios...
INFO [2022-04-28 20:49:28] Testing local optimum 3/20 at purity 0.33 and total ploidy 2.80...
INFO [2022-04-28 20:49:39] Testing local optimum 4/20 at purity 0.29 and total ploidy 3.00...
INFO [2022-04-28 20:49:47] Recalibrating log-ratios...
INFO [2022-04-28 20:49:47] Testing local optimum 4/20 at purity 0.29 and total ploidy 3.00...
INFO [2022-04-28 20:49:57] Recalibrating log-ratios...
INFO [2022-04-28 20:49:57] Testing local optimum 4/20 at purity 0.29 and total ploidy 3.00...
INFO [2022-04-28 20:50:07] Recalibrating log-ratios...
INFO [2022-04-28 20:50:07] Testing local optimum 4/20 at purity 0.29 and total ploidy 3.00...
INFO [2022-04-28 20:50:17] Testing local optimum 5/20 at purity 0.88 and total ploidy 5.80...
INFO [2022-04-28 20:50:25] Recalibrating log-ratios...
INFO [2022-04-28 20:50:25] Testing local optimum 5/20 at purity 0.88 and total ploidy 5.80...
INFO [2022-04-28 20:50:34] Recalibrating log-ratios...
INFO [2022-04-28 20:50:34] Testing local optimum 5/20 at purity 0.88 and total ploidy 5.80...
INFO [2022-04-28 20:50:46] Recalibrating log-ratios...
INFO [2022-04-28 20:50:46] Testing local optimum 5/20 at purity 0.88 and total ploidy 5.80...
INFO [2022-04-28 20:50:54] Testing local optimum 6/20 at purity 0.55 and total ploidy 4.40...
INFO [2022-04-28 20:51:01] Recalibrating log-ratios...
INFO [2022-04-28 20:51:01] Testing local optimum 6/20 at purity 0.55 and total ploidy 4.40...
INFO [2022-04-28 20:51:08] Recalibrating log-ratios...
INFO [2022-04-28 20:51:08] Testing local optimum 6/20 at purity 0.55 and total ploidy 4.40...
INFO [2022-04-28 20:51:16] Recalibrating log-ratios...
INFO [2022-04-28 20:51:16] Testing local optimum 6/20 at purity 0.55 and total ploidy 4.40...
INFO [2022-04-28 20:51:24] Testing local optimum 7/20 at purity 0.52 and total ploidy 3.20...
INFO [2022-04-28 20:51:31] Recalibrating log-ratios...
INFO [2022-04-28 20:51:31] Testing local optimum 7/20 at purity 0.52 and total ploidy 3.20...
INFO [2022-04-28 20:51:39] Recalibrating log-ratios...
INFO [2022-04-28 20:51:39] Testing local optimum 7/20 at purity 0.52 and total ploidy 3.20...
INFO [2022-04-28 20:51:48] Recalibrating log-ratios...
INFO [2022-04-28 20:51:48] Testing local optimum 7/20 at purity 0.52 and total ploidy 3.20...
INFO [2022-04-28 20:47:32] Testing local optimum 8/20 at purity 0.45 and total ploidy 2.60...
INFO [2022-04-28 20:47:52] Recalibrating log-ratios...
INFO [2022-04-28 20:47:52] Testing local optimum 8/20 at purity 0.45 and total ploidy 2.60...
INFO [2022-04-28 20:48:09] Recalibrating log-ratios...
INFO [2022-04-28 20:48:09] Testing local optimum 8/20 at purity 0.45 and total ploidy 2.60...
INFO [2022-04-28 20:48:29] Recalibrating log-ratios...
INFO [2022-04-28 20:48:29] Testing local optimum 8/20 at purity 0.45 and total ploidy 2.60...
INFO [2022-04-28 20:48:49] Testing local optimum 9/20 at purity 0.45 and total ploidy 4.00...
INFO [2022-04-28 20:49:05] Recalibrating log-ratios...
INFO [2022-04-28 20:49:05] Testing local optimum 9/20 at purity 0.45 and total ploidy 4.00...
INFO [2022-04-28 20:49:23] Recalibrating log-ratios...
INFO [2022-04-28 20:49:23] Testing local optimum 9/20 at purity 0.45 and total ploidy 4.00...
INFO [2022-04-28 20:49:40] Recalibrating log-ratios...
INFO [2022-04-28 20:49:40] Testing local optimum 9/20 at purity 0.45 and total ploidy 4.00...
INFO [2022-04-28 20:49:59] Testing local optimum 10/20 at purity 0.29 and total ploidy 1.80...
INFO [2022-04-28 20:50:13] Recalibrating log-ratios...
INFO [2022-04-28 20:50:13] Testing local optimum 10/20 at purity 0.29 and total ploidy 1.80...
INFO [2022-04-28 20:50:29] Recalibrating log-ratios...
INFO [2022-04-28 20:50:29] Testing local optimum 10/20 at purity 0.29 and total ploidy 1.80...
INFO [2022-04-28 20:50:45] Recalibrating log-ratios...
INFO [2022-04-28 20:50:45] Testing local optimum 10/20 at purity 0.29 and total ploidy 1.80...
INFO [2022-04-28 20:51:01] Testing local optimum 11/20 at purity 0.85 and total ploidy 4.80...
INFO [2022-04-28 20:51:15] Recalibrating log-ratios...
INFO [2022-04-28 20:51:15] Testing local optimum 11/20 at purity 0.85 and total ploidy 4.80...
INFO [2022-04-28 20:51:30] Recalibrating log-ratios...
INFO [2022-04-28 20:51:30] Testing local optimum 11/20 at purity 0.85 and total ploidy 4.80...
INFO [2022-04-28 20:51:46] Recalibrating log-ratios...
INFO [2022-04-28 20:51:46] Testing local optimum 11/20 at purity 0.85 and total ploidy 4.80...
INFO [2022-04-28 20:52:01] Testing local optimum 12/20 at purity 0.23 and total ploidy 1.90...
INFO [2022-04-28 20:52:09] Recalibrating log-ratios...
INFO [2022-04-28 20:52:09] Testing local optimum 12/20 at purity 0.23 and total ploidy 1.90...
INFO [2022-04-28 20:52:18] Recalibrating log-ratios...
INFO [2022-04-28 20:52:18] Testing local optimum 12/20 at purity 0.23 and total ploidy 1.90...
INFO [2022-04-28 20:52:30] Recalibrating log-ratios...
INFO [2022-04-28 20:52:30] Testing local optimum 12/20 at purity 0.23 and total ploidy 1.90...
INFO [2022-04-28 20:52:37] Testing local optimum 13/20 at purity 0.21 and total ploidy 2.00...
INFO [2022-04-28 20:52:44] Recalibrating log-ratios...
INFO [2022-04-28 20:52:44] Testing local optimum 13/20 at purity 0.21 and total ploidy 2.00...
INFO [2022-04-28 20:52:50] Recalibrating log-ratios...
INFO [2022-04-28 20:52:50] Testing local optimum 13/20 at purity 0.21 and total ploidy 2.00...
INFO [2022-04-28 20:52:57] Recalibrating log-ratios...
INFO [2022-04-28 20:52:57] Testing local optimum 13/20 at purity 0.21 and total ploidy 2.00...
INFO [2022-04-28 20:47:33] Testing local optimum 14/20 at purity 0.62 and total ploidy 2.80...
INFO [2022-04-28 20:47:53] Recalibrating log-ratios...
INFO [2022-04-28 20:47:53] Testing local optimum 14/20 at purity 0.62 and total ploidy 2.80...
INFO [2022-04-28 20:48:11] Recalibrating log-ratios...
INFO [2022-04-28 20:48:11] Testing local optimum 14/20 at purity 0.62 and total ploidy 2.80...
INFO [2022-04-28 20:48:30] Recalibrating log-ratios...
INFO [2022-04-28 20:48:30] Testing local optimum 14/20 at purity 0.62 and total ploidy 2.80...
INFO [2022-04-28 20:48:51] Testing local optimum 15/20 at purity 0.45 and total ploidy 1.60...
INFO [2022-04-28 20:49:07] Recalibrating log-ratios...
INFO [2022-04-28 20:49:07] Testing local optimum 15/20 at purity 0.45 and total ploidy 1.60...
INFO [2022-04-28 20:49:24] Recalibrating log-ratios...
INFO [2022-04-28 20:49:24] Testing local optimum 15/20 at purity 0.45 and total ploidy 1.60...
INFO [2022-04-28 20:49:42] Recalibrating log-ratios...
INFO [2022-04-28 20:49:42] Testing local optimum 15/20 at purity 0.45 and total ploidy 1.60...
INFO [2022-04-28 20:50:00] Testing local optimum 16/20 at purity 0.88 and total ploidy 3.00...
INFO [2022-04-28 20:50:14] Recalibrating log-ratios...
INFO [2022-04-28 20:50:14] Testing local optimum 16/20 at purity 0.88 and total ploidy 3.00...
INFO [2022-04-28 20:50:29] Recalibrating log-ratios...
INFO [2022-04-28 20:50:29] Testing local optimum 16/20 at purity 0.88 and total ploidy 3.00...
INFO [2022-04-28 20:50:46] Recalibrating log-ratios...
INFO [2022-04-28 20:50:46] Testing local optimum 16/20 at purity 0.88 and total ploidy 3.00...
INFO [2022-04-28 20:51:01] Testing local optimum 17/20 at purity 0.58 and total ploidy 2.00...
INFO [2022-04-28 20:51:16] Recalibrating log-ratios...
INFO [2022-04-28 20:51:16] Testing local optimum 17/20 at purity 0.58 and total ploidy 2.00...
INFO [2022-04-28 20:51:32] Recalibrating log-ratios...
INFO [2022-04-28 20:51:32] Testing local optimum 17/20 at purity 0.58 and total ploidy 2.00...
INFO [2022-04-28 20:51:48] Recalibrating log-ratios...
INFO [2022-04-28 20:51:48] Testing local optimum 17/20 at purity 0.58 and total ploidy 2.00...
INFO [2022-04-28 20:52:03] Testing local optimum 18/20 at purity 0.72 and total ploidy 5.80...
INFO [2022-04-28 20:52:13] Recalibrating log-ratios...
INFO [2022-04-28 20:52:13] Testing local optimum 18/20 at purity 0.72 and total ploidy 5.80...
INFO [2022-04-28 20:52:23] Recalibrating log-ratios...
INFO [2022-04-28 20:52:23] Testing local optimum 18/20 at purity 0.72 and total ploidy 5.80...
INFO [2022-04-28 20:52:34] Recalibrating log-ratios...
INFO [2022-04-28 20:52:34] Testing local optimum 18/20 at purity 0.72 and total ploidy 5.80...
INFO [2022-04-28 20:52:42] Testing local optimum 19/20 at purity 0.78 and total ploidy 2.00...
INFO [2022-04-28 20:52:49] Recalibrating log-ratios...
INFO [2022-04-28 20:52:49] Testing local optimum 19/20 at purity 0.78 and total ploidy 2.00...
INFO [2022-04-28 20:52:55] Recalibrating log-ratios...
INFO [2022-04-28 20:52:55] Testing local optimum 19/20 at purity 0.78 and total ploidy 2.00...
INFO [2022-04-28 20:53:03] Recalibrating log-ratios...
INFO [2022-04-28 20:53:03] Testing local optimum 19/20 at purity 0.78 and total ploidy 2.00...
INFO [2022-04-28 20:53:10] Testing local optimum 20/20 at purity 0.62 and total ploidy 1.40...
INFO [2022-04-28 20:53:17] Recalibrating log-ratios...
INFO [2022-04-28 20:53:17] Testing local optimum 20/20 at purity 0.62 and total ploidy 1.40...
INFO [2022-04-28 20:53:24] Recalibrating log-ratios...
INFO [2022-04-28 20:53:24] Testing local optimum 20/20 at purity 0.62 and total ploidy 1.40...
INFO [2022-04-28 20:53:32] Recalibrating log-ratios...
INFO [2022-04-28 20:53:32] Testing local optimum 20/20 at purity 0.62 and total ploidy 1.40...
INFO [2022-04-28 20:53:41] Skipping 4 solutions that converged to the same optima.
INFO [2022-04-28 20:53:41] Skipping 16 solutions exceeding max.non.clonal (0.20): 0.66/733853548730.78, 0.61/831288636877.29, 0.82/670664672594.41, 0.78/822384016887.87, 0.95/483425316938.89, 0.95/151298065501.38, 0.15/508789115927.57, 0.95/417626848681.16, 0.15/676236070295.88, 0.39/1101604614794.06, 0.95/345701682242.99, 0.95/249885827089.28, 0.78/434832441773.93, 0.95/99932992340.11, 0.86/375762933953.84, 0.15/323299241819.74 (purity/tumor ploidy)
WARN [2022-04-28 20:53:41] Could not find valid purity and ploidy solution.
Error in results[[1]] : subscript out of bounds
Calls: runAbsoluteCN -> grepl -> is.factor
Execution halted

or this

** Log file 2 **
WARN [2022-04-28 20:36:43] Deprecated arguments, use --mapping-bias-file instead.
[1] "/projects/dscott_scratch/CCSRI_1500/exomes/results_local/cnvkit-1.0_masked/pureCN/06-pureCN/idt/CCS_0898"
INFO [2022-04-28 20:36:43] Loading PureCN 2.0.1...
Warning messages:
1: package ‘DNAcopy’ was built under R version 4.1.2
2: package ‘VariantAnnotation’ was built under R version 4.1.2
3: package ‘IRanges’ was built under R version 4.1.2
4: package ‘Biobase’ was built under R version 4.1.2
5: package ‘Rsamtools’ was built under R version 4.1.2
6: package ‘Biostrings’ was built under R version 4.1.2
7: package ‘XVector’ was built under R version 4.1.2
INFO [2022-04-28 20:36:44] Using BiocParallel MulticoreParam backend with 3 cores.
INFO [2022-04-28 20:36:44] ------------------------------------------------------------
INFO [2022-04-28 20:36:44] PureCN 2.0.1
INFO [2022-04-28 20:36:44] ------------------------------------------------------------
INFO [2022-04-28 20:36:44] Arguments: -normal.coverage.file  -tumor.coverage.file results/cnvkit-1.0_masked/pureCN/05-cnvkit-cnr/idt/CCS_0898.cnr -log.ratio  -seg.file results/cnvkit-1.0_masked/pureCN/03-cnvkit_seg/idt/CCS_0898.seg -vcf.file results/cnvkit-1.0_masked/pureCN/04-mutect2/idt/CCS_0898/CCS_0898.vcf.gz -normalDB  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf results/cnvkit-1.0_masked/pureCN/02-pon/mapping_bias_idt_hg19.rds -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid CCS_0898 -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file  -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model betabin -post.optimize TRUE -log.file results/cnvkit-1.0_masked/pureCN/06-pureCN/idt/CCS_0898//CCS_0898.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2022-04-28 20:36:44] Using BiocParallel for parallel optimization.
INFO [2022-04-28 20:36:44] Loading coverage files...
INFO [2022-04-28 20:36:48] Found log2-ratio in tumor coverage data.
INFO [2022-04-28 20:36:48] Mean coverages: chrX: 65.32, chrY: 72.17, chr1-22: 98.63.
INFO [2022-04-28 20:36:48] Mean coverages: chrX: 65.32, chrY: 72.17, chr1-22: 98.63.
INFO [2022-04-28 20:36:49] Using 225707 intervals (193440 on-target, 32267 off-target).
INFO [2022-04-28 20:36:49] Ratio of mean on-target vs. off-target read counts: NaN
INFO [2022-04-28 20:36:49] Mean off-target bin size: 31696
INFO [2022-04-28 20:36:49] Loading VCF...
INFO [2022-04-28 20:36:55] Found 256791 variants in VCF file.
INFO [2022-04-28 20:36:57] Removing 4407 triallelic sites.
INFO [2022-04-28 20:36:57] Maximum of POPAP INFO is > 1, assuming -log10 scaled values
WARN [2022-04-28 20:36:57] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2022-04-28 20:36:58] 156989 (62.2%) variants annotated as likely germline (DB INFO flag).
WARN [2022-04-28 20:37:03] Found 1 variants with missing allelic fraction starting with 19:53302899_G/C. Removing them.
INFO [2022-04-28 20:37:05] CCS_0898 is tumor in VCF file.
INFO [2022-04-28 20:37:07] 990 homozygous and 296 heterozygous variants on chrX.
INFO [2022-04-28 20:37:07] Sex from VCF: M (Fisher's p-value: < 0.0001, odds-ratio: 5.83).
WARN [2022-04-28 20:37:07] MuTect stats file lacks contig and position columns.
INFO [2022-04-28 20:37:18] Initial testing for significant sample cross-contamination: maybe
INFO [2022-04-28 20:37:19] Removing 180792 variants with AF < 0.030 or AF >= 0.970 or less than 3 supporting reads or depth < 15.
INFO [2022-04-28 20:37:24] Removing 7093 blacklisted variants.
WARN [2022-04-28 20:37:24] Variant ids contain NAs at filter step BQ.
INFO [2022-04-28 20:37:25] Removing 0 low quality variants with BQ < 25.
INFO [2022-04-28 20:37:25] Total size of targeted genomic region: 31.72Mb (50.27Mb with 50bp padding).
INFO [2022-04-28 20:37:26] 11.6% of targets contain variants.
INFO [2022-04-28 20:37:26] Removing 34652 variants outside intervals.
INFO [2022-04-28 20:37:26] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2022-04-28 20:37:26] Loading mapping bias file mapping_bias_idt_hg19.rds...
INFO [2022-04-28 20:38:14] Found 14273459 variants in mapping bias file.
INFO [2022-04-28 20:38:27] Imputing mapping bias for 2288 variants...
INFO [2022-04-28 20:41:14] Excluding 7055 novel or poor quality variants from segmentation.
INFO [2022-04-28 20:41:14] Excluding 2288 variants not in pool of normals from segmentation.
INFO [2022-04-28 20:41:14] Sample sex: M
INFO [2022-04-28 20:41:14] Segmenting data...
INFO [2022-04-28 20:41:14] Loaded provided segmentation file CCS_0898.seg (format DNAcopy).
INFO [2022-04-28 20:41:14] Re-centering provided segment means (offset 0.0191).
INFO [2022-04-28 20:41:15] Setting prune.hclust.h parameter to 0.150000.
INFO [2022-04-28 20:41:15] Found 113 segments with median size of 9.03Mb.
INFO [2022-04-28 20:41:15] Removing 101 variants outside segments.
INFO [2022-04-28 20:41:15] Using 29745 variants.
INFO [2022-04-28 20:41:16] Mean standard deviation of log-ratios: 1.33 (MAPD: 0.32)
INFO [2022-04-28 20:41:16] Mean standard deviation of on-target log-ratios only: 0.35 (MAPD: 0.26)
INFO [2022-04-28 20:41:16] Mean standard deviation of off-target log-ratios only: 2.62 (MAPD: 1.30)
INFO [2022-04-28 20:41:16] 2D-grid search of purity and ploidy...
FATAL [2022-04-28 20:44:51] Cannot find valid purity/ploidy solution. This happens when input

FATAL [2022-04-28 20:44:51] segmentations are garbage, most likely due to a catastrophic sample QC

FATAL [2022-04-28 20:44:51] failure. Re-check standard QC metrics for this sample.

FATAL [2022-04-28 20:44:51]

FATAL [2022-04-28 20:44:51] This is most likely a user error due to invalid input data or

FATAL [2022-04-28 20:44:51] parameters (PureCN 2.0.1).

Error: Cannot find valid purity/ploidy solution. This happens when input
segmentations are garbage, most likely due to a catastrophic sample QC
failure. Re-check standard QC metrics for this sample.

This is most likely a user error due to invalid input data or
parameters (PureCN 2.0.1).
Execution halted

** More information ** 
Since they both stop at the same step, I was wondering if there was any relationship with the errors.

I believe it may be from relatively low read depth in off-target sites. Notably, I have also tried to remove any cnvkit segments from the *.cnr files that were smaller than -8. Removing chrX and chrY did nothing. Neither did setting --sex M. I have also tried to raise --max-non-clonal to 0.4. I did notice that for these samples, there was very little coverage in AntiTarget regions in general (at least relative to the samples that did work).

Ideally I hope there is a fix that would let me just stick with my cnvkit output as input to pureCN. I have been using the pureCN conda environment.

Thanks for your help!

**Comment by lima1** [comment]
Hi Jasper,

yes, looks like your off-targets are too low. For WES, they might do more harm than good. There is an argument in PureCN.R to remove them.

The first sample has low coverage in general and a very noisy log ratio stored in the cnvkit file. PSCBS might fail in that case, not sure.

If you run PSCBS, I would try the PureCN coverage normalization and compare though, especially those rows:

```
INFO [2022-04-28 20:41:16] Mean standard deviation of log-ratios: 1.33 (MAPD: 0.32)
INFO [2022-04-28 20:41:16] Mean standard deviation of on-target log-ratios only: 0.35 (MAPD: 0.26)
INFO [2022-04-28 20:41:16] Mean standard deviation of off-target log-ratios only: 2.62 (MAPD: 1.30)
```

I should be well below 0.25 for high quality WES data. If off-target is always higher, it will add more noise than signal.

Markus

**Comment by Jwong684** [comment]
Thanks for your prompt response Markus - the servers on my end are down for maintenance for around two weeks, so I'll have to try pureCN's coverage normalization a bit later and get back to you on that. To clarify about removing off-target consideration, did you mean this setting:
`        --min-fraction-offtarget=MIN-FRACTION-OFFTARGET
                Interval Filter: Ignore off-target internals when only the specified fraction of all intervals are off-target intervals  [default 0.05]`
I guess to omit off-target consideration, I would set to a very high value like 0.9

I was very impressed by pureCN's PSCBS method of segmentation - shown here on this igv screenshot. It definitely solved the noisy segmentation that I've seen for some of my cnvkit samples:
![image](https://user-images.githubusercontent.com/22081472/166118788-2c063a7f-f6b8-4106-9695-6e93cbcfba0c.png)
(1) is pureCN PSCBS with cnvkit input, (2) is cnvkit default output, (3) is copywriteR output, which only takes off-target regions into account
However, there are still specks of recurrent focal amplification (that starts and end at the same bases) that I suspect are artifacts from pureCN. Is there a way to account for these regions within the tool?

**Comment by lima1** [comment]
Yes, set this value to 1 to ignore offtarget.

I spent some time reducing artifacts in our internal workflow. See how it compares. There are always a few that make it through and need to be blacklisted. 

The GATK4 segmentation is also worth testing with WES. Never tested it with CNVkit though.
