### ISSUE TITLE
Noisy BAF plot

### ISSUE THREAD

**Issue by dst53** [lima1/PureCN#233]
Hello,

Thank you for making such a great tool. I'm trying to interpret the results I am getting (using CNVkit + pureCN pipeline with VCF germline/somatic calling by mutect2). I have WES from matched FFPE tumor/normal at 100x/50x. For all of the samples but one, I am seeing very noisy BAF plots with no gaps in BAF around 0.5 for areas of predicted gain/loss. I am not sure if this is due to lower coverage of either tumor/normal and/or if it is something to be concerned about in interpreting the confidence of the pureCN segmentation results. I have included below the outputs for the sample that I think looks as expected, and one of the many that look quite noisy.

For cnvkit, I am using the standard batch workflow with tumor and matched normal, setting a larger target and antitarget size corresponding to the mean calculated bin size from the cnvkit autobin function, and applying --drop-low-coverage. 

For mutect2, I am following the standard pipeline including creating a somatic panel of normals: https://gatk.broadinstitute.org/hc/en-us/articles/360035531132--How-to-Call-somatic-mutations-using-GATK4-Mutect2 with the addition of setting both --genotype-germline-sites and --genotype-pon-sites to true. I am also following recommendations for accounting for read orientation bias in FFPE samples.

The following is my input to PureCN.R:

`		Rscript PureCN.R --out   \
		    --sampleid tumor \
		    --tumor tumor \
		    --seg-file tumors.seg \
		    --vcf filtered.vcf \
		    --genome hg19 \
		    --fun-segmentation Hclust \
		    --force \
		    --post-optimize \
		    --seed 123 \
		    --cores 32`

This is the log file for a sample I believe to be of good quality/results:

INFO [2022-04-29 18:47:43] PureCN 2.0.2
INFO [2022-04-29 18:47:43] ------------------------------------------------------------
INFO [2022-04-29 18:47:43] Arguments: -normal.coverage.file  -tumor.coverage.file tumor.cnr -log.ratio  -seg.file tumors.seg -vcf.file filtered.vcf -normalDB  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid tumor -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file  -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model beta -post.optimize TRUE -log.file tumor.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2022-04-29 18:47:43] Using BiocParallel for parallel optimization.
INFO [2022-04-29 18:47:43] Loading coverage files...
INFO [2022-04-29 18:47:50] Provided log2-ratio looks too noisy, using segmentation only.
WARN [2022-04-29 18:47:50] Expecting numeric chromosome names in seg.file, assuming file is properly sorted.
INFO [2022-04-29 18:47:51] Mean coverages: chrX: 100.19, chrY: 0.48, chr1-22: 119.68.
INFO [2022-04-29 18:47:51] Mean coverages: chrX: 100.19, chrY: 0.48, chr1-22: 119.68.
INFO [2022-04-29 18:47:52] Using 267562 intervals (207826 on-target, 59736 off-target).
INFO [2022-04-29 18:47:52] Ratio of mean on-target vs. off-target read counts: NaN
INFO [2022-04-29 18:47:52] Mean off-target bin size: 40314
INFO [2022-04-29 18:47:52] Loading VCF...
INFO [2022-04-29 18:48:06] Found 200535 variants in VCF file.
INFO [2022-04-29 18:48:07] Removing 3820 triallelic sites.
WARN [2022-04-29 18:48:07] Found GERMQ info field with Phred scaled germline probabilities.
WARN [2022-04-29 18:48:10] vcf.file has no DB info field for membership in germline databases. Found and used somatic status instead.
INFO [2022-04-29 18:48:11] 61182 (31.1%) variants annotated as likely germline (DB INFO flag).
WARN [2022-04-29 18:48:21] Found 1417 variants with missing allelic fraction starting with 1:1219524_CG/C. Removing them.
INFO [2022-04-29 18:48:22] tumor is tumor in VCF file.
INFO [2022-04-29 18:48:26] 341 homozygous and 613 heterozygous variants on chrX.
INFO [2022-04-29 18:48:26] Sex from VCF: F (Fisher's p-value: 0.632, odds-ratio: 1.03).
INFO [2022-04-29 18:48:26] Detected MuTect2 VCF.
INFO [2022-04-29 18:48:28] Removing 138991 Mutect2 calls due to blacklisted failure reasons.
INFO [2022-04-29 18:48:29] Removing 21595 non heterozygous (in matched normal) germline SNPs.
INFO [2022-04-29 18:48:32] Initial testing for significant sample cross-contamination: unlikely
INFO [2022-04-29 18:48:34] Removing 5119 variants with AF < 0.030 or AF >= 1.000 or less than 4 supporting reads or depth < 15.
WARN [2022-04-29 18:48:34] Variant ids contain NAs at filter step BQ.
INFO [2022-04-29 18:48:34] Removing 0 low quality variants with BQ < 25.
INFO [2022-04-29 18:48:34] Total size of targeted genomic region: 62.36Mb (81.49Mb with 50bp padding).
INFO [2022-04-29 18:48:35] 11.5% of targets contain variants.
INFO [2022-04-29 18:48:35] Removing 1965 variants outside intervals.
INFO [2022-04-29 18:48:35] Found SOMATIC annotation in VCF.
INFO [2022-04-29 18:48:35] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2022-04-29 18:48:36] Found SOMATIC annotation in VCF. Setting mapping bias to 0.981.
INFO [2022-04-29 18:48:36] Excluding 9439 novel or poor quality variants from segmentation.
INFO [2022-04-29 18:48:36] Sample sex: F
INFO [2022-04-29 18:48:36] Segmenting data...
INFO [2022-04-29 18:48:36] Loaded provided segmentation file batch2_tumors.seg (format DNAcopy).
WARN [2022-04-29 18:48:36] Expecting numeric chromosome names in seg.file, assuming file is properly sorted.
INFO [2022-04-29 18:48:36] Re-centering provided segment means (offset -0.0394).
INFO [2022-04-29 18:48:37] Setting prune.hclust.h parameter to 0.150000.
INFO [2022-04-29 18:48:37] Found 39 segments with median size of 62.90Mb.
INFO [2022-04-29 18:48:37] Using 27628 variants.
INFO [2022-04-29 18:48:39] Mean standard deviation of log-ratios: 0.40 (MAPD: 0.00)
INFO [2022-04-29 18:48:39] Mean standard deviation of on-target log-ratios only: 0.00 (MAPD: 0.00)
INFO [2022-04-29 18:48:39] Mean standard deviation of off-target log-ratios only: 0.00 (MAPD: 0.00)
INFO [2022-04-29 18:48:39] 2D-grid search of purity and ploidy...
INFO [2022-04-29 18:49:22] Local optima: 0.25/2.1, 0.27/2, 0.45/2.8, 0.55/3, 0.52/3.4, 0.82/5,
0.85/3.4, 0.52/2, 0.78/2, 0.15/2
INFO [2022-04-29 18:49:22] Testing local optimum 1/10 at purity 0.25 and total ploidy 2.10...
INFO [2022-04-29 18:49:22] Testing local optimum 2/10 at purity 0.27 and total ploidy 2.00...
INFO [2022-04-29 18:49:22] Testing local optimum 3/10 at purity 0.45 and total ploidy 2.80...
INFO [2022-04-29 18:49:22] Testing local optimum 4/10 at purity 0.55 and total ploidy 3.00...
INFO [2022-04-29 18:49:22] Testing local optimum 5/10 at purity 0.52 and total ploidy 3.40...
INFO [2022-04-29 18:49:23] Testing local optimum 6/10 at purity 0.82 and total ploidy 5.00...
INFO [2022-04-29 18:49:23] Testing local optimum 7/10 at purity 0.85 and total ploidy 3.40...
INFO [2022-04-29 18:49:23] Testing local optimum 8/10 at purity 0.52 and total ploidy 2.00...
INFO [2022-04-29 18:49:23] Testing local optimum 9/10 at purity 0.78 and total ploidy 2.00...
INFO [2022-04-29 18:49:23] Testing local optimum 10/10 at purity 0.15 and total ploidy 2.00...
INFO [2022-04-29 18:50:40] Skipping 2 solutions that converged to the same optima.
INFO [2022-04-29 18:50:41] Fitting variants with beta model for local optimum 1/10...
INFO [2022-04-29 18:50:41] Fitting variants with beta model for local optimum 2/10...
INFO [2022-04-29 18:50:41] Fitting variants with beta model for local optimum 3/10...
INFO [2022-04-29 18:50:41] Fitting variants with beta model for local optimum 4/10...
INFO [2022-04-29 18:50:41] Fitting variants with beta model for local optimum 5/10...
INFO [2022-04-29 18:50:41] Fitting variants with beta model for local optimum 6/10...
INFO [2022-04-29 18:50:41] Fitting variants with beta model for local optimum 7/10...
INFO [2022-04-29 18:50:41] Fitting variants with beta model for local optimum 9/10...
INFO [2022-04-29 18:50:50] Fitting variants for purity 0.45, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 18:50:50] Fitting variants for purity 0.30, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 18:50:50] Fitting variants for purity 0.31, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 18:50:51] Fitting variants for purity 0.50, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 18:50:51] Fitting variants for purity 0.54, tumor ploidy 4.75 and contamination 0.01.
INFO [2022-04-29 18:50:51] Fitting variants for purity 0.82, tumor ploidy 5.80 and contamination 0.01.
INFO [2022-04-29 18:50:51] Fitting variants for purity 0.59, tumor ploidy 2.19 and contamination 0.01.
INFO [2022-04-29 18:50:52] Fitting variants for purity 0.65, tumor ploidy 3.81 and contamination 0.01.
INFO [2022-04-29 18:55:01] Fitting variants for purity 0.46, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 18:55:15] Fitting variants for purity 0.26, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 18:55:24] Rare karyotype solution. Skipping post-optimization.
INFO [2022-04-29 18:55:24] Optimized purity: 0.82
INFO [2022-04-29 18:55:24] Poor goodness-of-fit (0.689). Skipping post-optimization.
INFO [2022-04-29 18:55:24] Optimized purity: 0.65
INFO [2022-04-29 18:55:25] Fitting variants for purity 0.41, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 18:55:58] Fitting variants for purity 0.27, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 18:56:05] Poor goodness-of-fit (0.418). Skipping post-optimization.
INFO [2022-04-29 18:56:05] Optimized purity: 0.59
INFO [2022-04-29 18:56:07] Rare karyotype solution. Skipping post-optimization.
INFO [2022-04-29 18:56:07] Optimized purity: 0.54
INFO [2022-04-29 18:58:56] Fitting variants for purity 0.47, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 18:59:23] Fitting variants for purity 0.27, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 18:59:33] Fitting variants for purity 0.42, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:00:00] Fitting variants for purity 0.28, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 19:02:52] Fitting variants for purity 0.48, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:03:31] Fitting variants for purity 0.28, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 19:03:42] Fitting variants for purity 0.43, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:03:57] Fitting variants for purity 0.29, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 19:06:47] Fitting variants for purity 0.49, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:07:38] Fitting variants for purity 0.29, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 19:07:47] Fitting variants for purity 0.44, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:07:53] Fitting variants for purity 0.30, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 19:10:42] Fitting variants for purity 0.51, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:11:33] Fitting variants for purity 0.31, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 19:11:42] Fitting variants for purity 0.46, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:11:51] Fitting variants for purity 0.32, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 19:14:39] Fitting variants for purity 0.52, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:15:29] Fitting variants for purity 0.32, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 19:15:38] Fitting variants for purity 0.47, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:15:52] Fitting variants for purity 0.33, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 19:18:38] Fitting variants for purity 0.53, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:19:34] Fitting variants for purity 0.33, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 19:19:46] Fitting variants for purity 0.48, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:20:09] Fitting variants for purity 0.34, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 19:23:12] Fitting variants for purity 0.54, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:24:11] Fitting variants for purity 0.34, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-04-29 19:24:18] Fitting variants for purity 0.49, tumor ploidy 3.79 and contamination 0.01.
INFO [2022-04-29 19:24:44] Fitting variants for purity 0.35, tumor ploidy 2.91 and contamination 0.01.
INFO [2022-04-29 19:27:51] Optimized purity: 0.46
INFO [2022-04-29 19:28:46] Optimized purity: 0.28
INFO [2022-04-29 19:28:52] Optimized purity: 0.41
INFO [2022-04-29 19:29:29] Optimized purity: 0.30
INFO [2022-04-29 19:29:30] Done.
INFO [2022-04-29 19:29:30] ------------------------------------------------------------
INFO [2022-04-29 19:29:45] Generating output files...

The corresponding plots for the best selected solution:

![image](https://user-images.githubusercontent.com/75229061/166301825-02e26da2-59e2-4c72-bbbe-b14992f835ef.png)

In contrast, this is the log file for a sample that had a very noisy VAF plot (most samples):

INFO [2022-04-29 14:43:11] ------------------------------------------------------------
INFO [2022-04-29 14:43:11] PureCN 2.0.2
INFO [2022-04-29 14:43:11] ------------------------------------------------------------
INFO [2022-04-29 14:43:11] Arguments: -normal.coverage.file  -tumor.coverage.file tumor.cnr -log.ratio  -seg.file tumors.seg -vcf.file filtered.vcf -normalDB  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid tumor -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file  -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model beta -post.optimize TRUE -log.file tumor.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2022-04-29 14:43:11] Using BiocParallel for parallel optimization.
INFO [2022-04-29 14:43:11] Loading coverage files...
INFO [2022-04-29 14:43:20] Provided log2-ratio looks too noisy, using segmentation only.
INFO [2022-04-29 14:43:20] Mean coverages: chrX: 55.73, chrY: 4.52, chr1-22: 46.94.
INFO [2022-04-29 14:43:20] Mean coverages: chrX: 55.73, chrY: 4.52, chr1-22: 46.94.
INFO [2022-04-29 14:43:22] Using 334337 intervals (207929 on-target, 126408 off-target).
INFO [2022-04-29 14:43:22] Ratio of mean on-target vs. off-target read counts: NaN
INFO [2022-04-29 14:43:22] Mean off-target bin size: 20022
INFO [2022-04-29 14:43:22] Loading VCF...
INFO [2022-04-29 14:43:28] Found 99816 variants in VCF file.
INFO [2022-04-29 14:43:29] Removing 1463 triallelic sites.
WARN [2022-04-29 14:43:29] Found GERMQ info field with Phred scaled germline probabilities.
WARN [2022-04-29 14:43:30] vcf.file has no DB info field for membership in germline databases. Found and used somatic status instead.
INFO [2022-04-29 14:43:30] 69124 (70.3%) variants annotated as likely germline (DB INFO flag).
WARN [2022-04-29 14:43:35] Found 7879 variants with missing allelic fraction starting with 1:173730_C/A. Removing them.
INFO [2022-04-29 14:43:36] tumor is tumor in VCF file.
INFO [2022-04-29 14:43:37] 311 homozygous and 670 heterozygous variants on chrX.
INFO [2022-04-29 14:43:37] Sex from VCF: F (Fisher's p-value: 0, odds-ratio: 1.28).
WARN [2022-04-29 14:43:37] Sex mismatch of coverage and VCF. Could be because of noisy data, contamination, loss of chrY or a mis-alignment of coverage and VCF.
INFO [2022-04-29 14:43:38] Detected MuTect2 VCF.
INFO [2022-04-29 14:43:39] Removing 39428 Mutect2 calls due to blacklisted failure reasons.
INFO [2022-04-29 14:43:40] Removing 26567 non heterozygous (in matched normal) germline SNPs.
INFO [2022-04-29 14:43:41] Initial testing for significant sample cross-contamination: unlikely
INFO [2022-04-29 14:43:42] Removing 2015 variants with AF < 0.030 or AF >= 1.000 or less than 4 supporting reads or depth < 15.
WARN [2022-04-29 14:43:42] Variant ids contain NAs at filter step BQ.
INFO [2022-04-29 14:43:42] Removing 0 low quality variants with BQ < 25.
INFO [2022-04-29 14:43:42] Total size of targeted genomic region: 62.34Mb (81.46Mb with 50bp padding).
INFO [2022-04-29 14:43:43] 9.3% of targets contain variants.
INFO [2022-04-29 14:43:43] Removing 740 variants outside intervals.
INFO [2022-04-29 14:43:43] Found SOMATIC annotation in VCF.
INFO [2022-04-29 14:43:43] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2022-04-29 14:43:44] Found SOMATIC annotation in VCF. Setting mapping bias to 0.983.
INFO [2022-04-29 14:43:44] Excluding 2802 novel or poor quality variants from segmentation.
INFO [2022-04-29 14:43:44] Sample sex: M
INFO [2022-04-29 14:43:44] Segmenting data...
INFO [2022-04-29 14:43:44] Loaded provided segmentation file batch1_tumors.seg (format DNAcopy).
INFO [2022-04-29 14:43:44] Re-centering provided segment means (offset 0.0061).
INFO [2022-04-29 14:43:44] Setting prune.hclust.h parameter to 0.100000.
INFO [2022-04-29 14:43:45] Found 36 segments with median size of 61.20Mb.
INFO [2022-04-29 14:43:45] Using 21724 variants.
INFO [2022-04-29 14:43:47] Mean standard deviation of log-ratios: 0.40 (MAPD: 0.00)
INFO [2022-04-29 14:43:47] Mean standard deviation of on-target log-ratios only: 0.00 (MAPD: 0.00)
INFO [2022-04-29 14:43:47] Mean standard deviation of off-target log-ratios only: 0.00 (MAPD: 0.00)
INFO [2022-04-29 14:43:47] 2D-grid search of purity and ploidy...
INFO [2022-04-29 14:44:35] Local optima: 0.15/2.1, 0.15/1.9, 0.23/2.6, 0.29/3, 0.17/2, 0.27/2,
0.62/4.4, 0.55/3.6, 0.52/2, 0.85/3, 0.78/2, 0.58/1.4
INFO [2022-04-29 14:44:35] Testing local optimum 1/12 at purity 0.15 and total ploidy 2.10...
INFO [2022-04-29 14:44:35] Testing local optimum 2/12 at purity 0.15 and total ploidy 1.90...
INFO [2022-04-29 14:44:35] Testing local optimum 3/12 at purity 0.23 and total ploidy 2.60...
INFO [2022-04-29 14:44:35] Testing local optimum 4/12 at purity 0.29 and total ploidy 3.00...
INFO [2022-04-29 14:44:35] Testing local optimum 5/12 at purity 0.17 and total ploidy 2.00...
INFO [2022-04-29 14:44:35] Testing local optimum 6/12 at purity 0.27 and total ploidy 2.00...
INFO [2022-04-29 14:44:35] Testing local optimum 7/12 at purity 0.62 and total ploidy 4.40...
INFO [2022-04-29 14:44:36] Testing local optimum 8/12 at purity 0.55 and total ploidy 3.60...
INFO [2022-04-29 14:44:36] Testing local optimum 9/12 at purity 0.52 and total ploidy 2.00...
INFO [2022-04-29 14:44:36] Testing local optimum 10/12 at purity 0.85 and total ploidy 3.00...
INFO [2022-04-29 14:44:36] Testing local optimum 11/12 at purity 0.78 and total ploidy 2.00...
INFO [2022-04-29 14:44:36] Testing local optimum 12/12 at purity 0.58 and total ploidy 1.40...
INFO [2022-04-29 14:44:59] Recalibrating log-ratios...
INFO [2022-04-29 14:44:59] Testing local optimum 12/12 at purity 0.58 and total ploidy 1.40...
INFO [2022-04-29 14:45:25] Recalibrating log-ratios...
INFO [2022-04-29 14:45:25] Testing local optimum 12/12 at purity 0.58 and total ploidy 1.40...
INFO [2022-04-29 14:45:45] Recalibrating log-ratios...
INFO [2022-04-29 14:45:45] Testing local optimum 12/12 at purity 0.58 and total ploidy 1.40...
INFO [2022-04-29 14:46:02] Skipping 2 solutions that converged to the same optima.
INFO [2022-04-29 14:46:02] Skipping 1 solutions exceeding max.non.clonal (0.20): 0.51/1.29 (purity/tumor ploidy)
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 2/12...
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 3/12...
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 4/12...
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 5/12...
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 7/12...
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 8/12...
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 9/12...
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 10/12...
INFO [2022-04-29 14:46:03] Fitting variants with beta model for local optimum 11/12...
INFO [2022-04-29 14:46:13] Fitting variants for purity 0.23, tumor ploidy 4.68 and contamination 0.01.
INFO [2022-04-29 14:46:13] Fitting variants for purity 0.31, tumor ploidy 5.61 and contamination 0.01.
INFO [2022-04-29 14:46:14] Fitting variants for purity 0.64, tumor ploidy 6.00 and contamination 0.01.
INFO [2022-04-29 14:46:14] Fitting variants for purity 0.17, tumor ploidy 2.68 and contamination 0.01.
INFO [2022-04-29 14:46:14] Fitting variants for purity 0.20, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 14:46:15] Fitting variants for purity 0.32, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 14:46:15] Fitting variants for purity 0.57, tumor ploidy 4.98 and contamination 0.01.
INFO [2022-04-29 14:46:15] Fitting variants for purity 0.65, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 14:46:16] Fitting variants for purity 0.59, tumor ploidy 2.17 and contamination 0.01.
INFO [2022-04-29 14:49:16] Rare karyotype solution. Skipping post-optimization.
INFO [2022-04-29 14:49:16] Optimized purity: 0.23
INFO [2022-04-29 14:49:26] Rare karyotype solution. Skipping post-optimization.
INFO [2022-04-29 14:49:26] Optimized purity: 0.31
INFO [2022-04-29 14:49:32] Fitting variants for purity 0.15, tumor ploidy 2.68 and contamination 0.01.
INFO [2022-04-29 14:49:37] Rare karyotype solution. Skipping post-optimization.
INFO [2022-04-29 14:49:37] Optimized purity: 0.64
INFO [2022-04-29 14:49:44] Fitting variants for purity 0.16, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 14:49:47] Poor goodness-of-fit (0.639). Skipping post-optimization.
INFO [2022-04-29 14:49:47] Optimized purity: 0.59
INFO [2022-04-29 14:49:58] Fitting variants for purity 0.61, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 14:49:59] Fitting variants for purity 0.28, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 14:50:02] Rare karyotype solution. Skipping post-optimization.
INFO [2022-04-29 14:50:02] Optimized purity: 0.57
INFO [2022-04-29 14:52:29] Fitting variants for purity 0.16, tumor ploidy 2.68 and contamination 0.01.
INFO [2022-04-29 14:52:55] Fitting variants for purity 0.62, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 14:52:56] Fitting variants for purity 0.17, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 14:52:58] Fitting variants for purity 0.29, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 14:55:25] Fitting variants for purity 0.18, tumor ploidy 2.68 and contamination 0.01.
INFO [2022-04-29 14:55:56] Fitting variants for purity 0.30, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 14:55:59] Fitting variants for purity 0.63, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 14:56:09] Fitting variants for purity 0.18, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 14:58:22] Fitting variants for purity 0.19, tumor ploidy 2.68 and contamination 0.01.
INFO [2022-04-29 14:58:54] Fitting variants for purity 0.31, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 14:59:00] Fitting variants for purity 0.64, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 14:59:22] Fitting variants for purity 0.19, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 15:01:18] Fitting variants for purity 0.20, tumor ploidy 2.68 and contamination 0.01.
INFO [2022-04-29 15:01:51] Fitting variants for purity 0.33, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 15:02:01] Fitting variants for purity 0.66, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 15:02:32] Fitting variants for purity 0.21, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 15:04:14] Fitting variants for purity 0.21, tumor ploidy 2.68 and contamination 0.01.
INFO [2022-04-29 15:04:50] Fitting variants for purity 0.34, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 15:05:06] Fitting variants for purity 0.67, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 15:05:51] Fitting variants for purity 0.22, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 15:07:18] Optimized purity: 0.18
INFO [2022-04-29 15:07:48] Fitting variants for purity 0.35, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 15:08:11] Fitting variants for purity 0.68, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 15:09:03] Fitting variants for purity 0.23, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 15:10:46] Fitting variants for purity 0.36, tumor ploidy 1.98 and contamination 0.01.
INFO [2022-04-29 15:11:19] Fitting variants for purity 0.69, tumor ploidy 3.14 and contamination 0.01.
INFO [2022-04-29 15:12:12] Fitting variants for purity 0.24, tumor ploidy 1.87 and contamination 0.01.
INFO [2022-04-29 15:13:44] Optimized purity: 0.28
INFO [2022-04-29 15:14:24] Optimized purity: 0.61
INFO [2022-04-29 15:15:18] Optimized purity: 0.21
INFO [2022-04-29 15:15:18] Done.
INFO [2022-04-29 15:15:18] ------------------------------------------------------------
INFO [2022-04-29 15:15:30] Generating output files...

The corresponding plots for the best selected solution:

![image](https://user-images.githubusercontent.com/75229061/166306861-673ed6bb-b3e8-4e96-bdb7-238bd8b72bcb.png)

What do you think could be driving this noise in the BAF plot? Is it simply coverage is too low? Sample contamination? Should I be concerned about the validity of the copy number inference?

Also, as an aside, what is the difference between the navy-colored and black-colored segments in the middle log2 ratio plot?

Thank you

**Comment by lima1** [comment]
Hi, yes, looks like your CNVkit input is pretty noisy. PureCN is ignoring the log ratios in the CNVkit tumor file and is using only the segmentation.

It's usually much better to use a panel of normal samples for coverage normalization than the matched normal. Coverage is an issue, but you should be able to improve significantly.

You can also try our best practices from beginning to end and compare to CNVkit.
