### ISSUE TITLE
Inclusion/exclusion of genes in CSV

### ISSUE THREAD

**Issue by jje42** [lima1/PureCN#240]
Regarding the genes CSV output file, I had assumed that all genes (as defined in the interval file) were present, but on closer inspection I realise that's not the case. My CSV output files contain most but not all genes, and it is not a consistent set of genes that are missing. I thought it might have something to do with coverage, but for the samples I've checked there appears to be good coverage for the "missing" genes (>200X). Is there some criteria for inclusion or exclusion from the output CSV?

Thanks.

**Comment by lima1** [comment]
Hmm, there is no explicit filter step. The gene summary is done here: https://github.com/lima1/PureCN/blob/master/R/PureCN-internal.R#L566-L610

So unless it's outside the segmentation or log ratios are missing, it should show up.

Do you see any patterns in genes dropping out?

**Comment by lima1** [comment]
Closing now, feel free to reopen if you think there is a bug somewhere.
