### ISSUE TITLE
How are copy number thresholds defined for amplifications

### ISSUE THREAD

**Issue by rbell-img** [lima1/PureCN#241]
Hi, I would like to know why arbitrary thresholds of 6/7 were selected to label amplifications - was an internal comparison performed to define these thresholds? Is it safe to consider copy numbers > 3 as gains

Thanks

**Comment by lima1** [comment]
Hi, they are arbitrary and I’m open to improving them, i.e. open to suggestions. In some cases like Her2 you could optimize based on FISH concordance. In others that are almost always focal you can look at their copy number distributions. Others might have a strong dosing effect, where a copy number of 4 is already pathogenic. 

I would define round(ploidy)+1 as gain I guess.
