### ISSUE TITLE
NormalDB stalling

### ISSUE THREAD

**Issue by Jwong684** [lima1/PureCN#242]
**NormalDB stalls while trying to process normal vcf**
Hi Markus, I've been trying to regenerate a normalDB for my exomes for weeks now but it always stall at one specific part. I'm wondering if there is a way to speed up normalDB generation (it is currently only using one core) and if you know of any possible reason why it would stall here.

**To Reproduce**
`Rscript /projects/rmorin_scratch/conda_environments/3dff324bbbf34c5d73f8d8432add6757/lib/R/library/PureCN/extdata/NormalDB.R --out-dir results/cnvkit-1.0_masked/pureCN/02-pon/ --normal-panel results/cnvkit-1.0_masked/pureCN/02-pon/idt_database/  --assay idt --genome hg19 --force --coverage-files results/cnvkit-1.0_masked/pureCN/03-coverage/idt/cov_list.txt`

After running for around 15 hours or so, it consistently gets stuck here:

`INFO [2022-06-14 23:24:09] Clustering beta binomial fits...
INFO [2022-06-14 23:24:20] Assigning (907/50000) variants a clustered beta binomal fit.
INFO [2022-06-14 23:24:30] Processing variants 10450001 to 10500000...
INFO [2022-06-14 23:24:30] Position 14:81161866
INFO [2022-06-14 23:26:28] Clustering beta binomial fits...
INFO [2022-06-14 23:26:34] Assigning (588/50000) variants a clustered beta binomal fit.
INFO [2022-06-14 23:26:44] Processing variants 10500001 to 10550000...
INFO [2022-06-14 23:29:19] Clustering beta binomial fits...
INFO [2022-06-14 23:29:28] Assigning (764/50000) variants a clustered beta binomal fit.
INFO [2022-06-14 23:29:39] Processing variants 10550001 to 10600000...
INFO [2022-06-14 23:32:35] Clustering beta binomial fits...`

This same script has worked for my other exome set using the Agilent baits. The only difference between the two is that I have only 12 normals for Agilent and 58 normals for IDT. In terms of the total variants called for each, the Agilent had 9019778 and IDT had 14273459. Is this potentially just from a memory issue?

I could try to reduce the total number of normals or setting a max limit of normals used in the vcf generation, but I was wondering if there was a simpler solution to this.

Thank you!

**Comment by lima1** [comment]
Hi Jasper, yes, that should not take long. I would guess it's just swapping? I never ran into an issue here with similar number of normals. This is probably when it merges the results of all batches, so memory issue kind of makes sense I guess.

Let me know if it consumes a ridiculous amount of RAM and I see if there is something I can do to reduce.

**Comment by Jwong684** [comment]
I'm not sure if it really is related to memory, but I did notice that I had two normals that had particularly large vcf files (196Mb and 222Mb, whereas other normals were around 20Mb).

Once I removed those two normals before merging my normals, I was able to run the NormalDB script to completion.
