### ISSUE TITLE
Error: Only tiny segments.

### ISSUE THREAD

**Issue by asmlgkj** [lima1/PureCN#243]
Thanks a lot for this powerful tool, can you take some time to look at this error
![image](https://user-images.githubusercontent.com/50854682/174462018-0983dfcf-c92b-499e-bd36-0af6c32dafa2.png)

**Comment by lima1** [comment]
Congrats on the title, Curry fan! 

v1.16.0 is old, try updating to the latest version. See the README

Only 445 targets. PureCN is made for larger panels, 1Mb is probably the minimum. So if this is indeed a tiny hotspot panel, I'm afraid it won't work. Make sure to use the baits BED file containing the position of the baits, not the position of the exons.

For small panels, it might also make sense to experiment with different coverage normalization tools, i.e. also try our best practices tutorial from start to finish. Might improve things to what you have.

**Comment by asmlgkj** [comment]
thanks a lot for your kind help, does conda version of purecn is the lastest?

**Comment by lima1** [comment]
Looks like it’s still the previous in Conda. Not sure why, they are usually pretty quick.  Unless it gives you OCD, you can install including many dependencies via conda and then run

BiocManager::install("lima1/PureCN", ref = "RELEASE_3_15") 

to manually update PureCN.

**Comment by asmlgkj** [comment]
errors like this, thanks a lot @lima1 
![image](https://user-images.githubusercontent.com/50854682/174734230-a7074e70-4920-4b06-bc15-e2e3a8bddc60.png)
