### ISSUE TITLE
NormalDB.R not accepting panel of normals

### ISSUE THREAD

**Issue by jfreeland01** [lima1/PureCN#245]
Hello,

I am trying to build a normal database for coverage normalization using large/public panels of normals, but I am receiving an error stating my files contain only a single sample. This question may be naive, but how does PureCN/NormalDB.R determine if the vcf contains only one sample, and could this error be coming from simply a formatting issue? 

1. 1000 Genome Project: somatic-hg38_1000g_pon.hg38.vcf.gz
- Described here https://gatk.broadinstitute.org/hc/en-us/articles/360035890631-Panel-of-Normals-PON-

3. NCI GCD: gatk4_mutect2_4136_pon.vcf.gz
- Described here https://gdc.cancer.gov/about-data/gdc-data-processing/gdc-reference-files

Thank you very much for any and all help
Jack

Command Line Log

$ Rscript $PURECN/NormalDB.R \
> --out-dir $REF \
> --coverage-files $PURECN_INTCOV/Normal_Coverages \
> --normal-panel $REF/somatic-hg38_1000g_pon.hg38.vcf.gz \
> --genome hg38
INFO [2022-06-28 11:47:53] Loading PureCN 2.2.0...
INFO [2022-06-28 11:47:53] Creating mapping bias database.
[W::hts_idx_load2] The index file is older than the data file: /media/seagate/jfreeland/PureCN/References/somatic-hg38_1000g_pon.hg38.vcf.gz.tbi
INFO [2022-06-28 11:47:55] Processing variants 1 to 50000...
FATAL [2022-06-28 11:47:55] The normal.panel.vcf.file contains only a single sample. 

FATAL [2022-06-28 11:47:55]  

FATAL [2022-06-28 11:47:55] This is most likely a user error due to invalid input data or 

FATAL [2022-06-28 11:47:55] parameters (PureCN 2.2.0). 

Error: The normal.panel.vcf.file contains only a single sample.

This is most likely a user error due to invalid input data or
parameters (PureCN 2.2.0).
Execution halted

R Version: R version 4.2.0

**Comment by lima1** [comment]
This part of the normal database is to identify the bias of heterozygous SNPs towards the reference or alt allele (e.g. systematic deviations from expected allele frequency 0.5). The higher the coverage, the more important correcting for this bias, especially with the beta binomial model.  That means we need the reference and alt reads for as many normals as possible.  If you follow the GATK4 Mutect2 best practices with their germline database annotation, you all good from that side (I figure you thought that this step is used to annotate variants for germline status?). Hope that clarifies things?

**Comment by jfreeland01** [comment]
Markus, thank you for the very quick reply. I understand the math behind your answer, but I am not sure how to use that to fix my issue. After the large-public PoN's never worked, I also followed the GATK4 Mutect2 workflow and genearted my own panel of normals (w/ 3 normal samples from the same sequencing assay) using gatk Mutect2 -> GenomicsDBImport -> CreaseSomaticPanelofNormals. The resulting PoN.vcf.gz gives me the same "only one sample" error in PureCN. 

Am I misinterpretting the required input? As in, are the files I linked to above or described here from gatk not appropriate?

**Comment by lima1** [comment]
Yes, the CreateSomaticPanelOfNormals is GATK4 specific, it does not contain any read counts. Easiest would be to use the GenomicsDB directly. If you have trouble installing the genomicsdb R package, you can use the Docker image for that step.

Otherwise use any other tool that merges a set of single sample VCFs into a multi sample VCF. There is an example using GATK3 in the main vignette.
