### ISSUE TITLE
question regarding purity/AF

### ISSUE THREAD

**Issue by maxanes** [lima1/PureCN#247]
I have seen that in one reply (https://github.com/lima1/PureCN/issues/227#issuecomment-1058734178) you have suggested plotting 75 percentile against purity, could you please explain why 75 perc and not median or mean of AF?

Thank you.

**Comment by lima1** [comment]
Mean or median usually underestimate purity due to sub-clonal mutations (and potentially artifacts). 75-90% should give a better correlation on average, but this is just based on experience with large datasets.

**Comment by maxanes** [comment]
thank you very much for the fast response and explanation. 
I also got a less correlated median and mean of AF in my data set of 200 samples, but I wasn't sure what the explanation was.

**Comment by lima1** [comment]
I forgot: for high purity samples assayed with WES (and/or cancer types with lots of mutations), you can also take the median of those 75-90% over chromosomes to reduce the effect of whole arm gains and losses on AF. But for a general check, it's good enough without.
