### ISSUE TITLE
Error in PureCN.R

### ISSUE THREAD

**Issue by ykzhang2022** [lima1/PureCN#248]
**Describe the issue**
A error had happened whenI'm running PureCN.R.

**To Reproduce**
FATAL [2022-08-04 15:23:30] f not in expected range.

FATAL [2022-08-04 15:23:30]

FATAL [2022-08-04 15:23:30] This is most likely a user error due to invalid input data or

FATAL [2022-08-04 15:23:30] parameters (PureCN 2.0.2).

**Expected behavior**

**Log file**
INFO [2022-08-04 14:57:13] Loading coverage files...
INFO [2022-08-04 14:57:14] Mean target coverages: 405X (tumor) 406X (normal).
INFO [2022-08-04 14:57:15] Mean coverages: chrX: 201.04, chrY: 154.85, chr1-22: 403.43.
INFO [2022-08-04 14:57:15] Mean coverages: chrX: 208.06, chrY: 154.85, chr1-22: 407.28.
INFO [2022-08-04 14:57:22] Removing 119 intervals with missing log.ratio.
INFO [2022-08-04 14:57:22] Removing 26 low/high GC targets.
INFO [2022-08-04 14:57:22] Removing 667 intervals excluded in normalDB.
INFO [2022-08-04 14:57:22] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2022-08-04 14:57:22] Removing 1337 low count (< 100 total reads) intervals.
INFO [2022-08-04 14:57:22] Using 29201 intervals (14583 on-target, 14618 off-target).
INFO [2022-08-04 14:57:22] Ratio of mean on-target vs. off-target read counts: 6.89
INFO [2022-08-04 14:57:22] Mean off-target bin size: 173456
INFO [2022-08-04 14:57:23] AT/GC dropout: 0.97 (tumor), 0.97 (normal), 1.00 (coverage log-ratio).
INFO [2022-08-04 14:57:23] Loading VCF...
INFO [2022-08-04 14:57:25] Found 7400 variants in VCF file.
WARN [2022-08-04 14:57:25] vcf.file has no DB or POP_AF info field for membership in germline databases. Guessing it based on available dbSNP ID.
INFO [2022-08-04 14:57:26] 6441 (87.0%) variants annotated as likely germline (DB INFO flag).
INFO [2022-08-04 14:57:27] Y22S00143-B1TA is tumor in VCF file.
INFO [2022-08-04 14:57:27] 57 homozygous and 3 heterozygous variants on chrX.
INFO [2022-08-04 14:57:27] Sex from VCF: M (Fisher's p-value: < 0.0001, odds-ratio: 38.95).
INFO [2022-08-04 14:57:28] Initial testing for significant sample cross-contamination: unlikely
INFO [2022-08-04 14:57:29] Removing 13 variants with AF < 0.030 or AF >= Inf or less than 6 supporting reads or depth < 15.
WARN [2022-08-04 14:57:29] Variant ids contain NAs at filter step BQ.
INFO [2022-08-04 14:57:29] Removing 0 low quality variants with BQ < 25.
INFO [2022-08-04 14:57:29] Total size of targeted genomic region: 3.40Mb (4.58Mb with 50bp padding).
INFO [2022-08-04 14:57:30] 38.0% of targets contain variants.
INFO [2022-08-04 14:57:30] Removing 345 variants outside intervals.
INFO [2022-08-04 14:57:31] Reading COSMIC VCF...
INFO [2022-08-04 14:59:43] Found COSMIC annotation in VCF. Requiring 6 hits.
INFO [2022-08-04 14:59:43] Setting somatic prior probabilities for hits to 0.995000 or to 0.500000 if in both COSMIC and dbSNP.
INFO [2022-08-04 14:59:43] Loading mapping bias file mapping_bias_PRCC-Normal-PoN_hg19.rds...
INFO [2022-08-04 14:59:43] Found 43496 variants in mapping bias file.
INFO [2022-08-04 14:59:46] Imputing mapping bias for 937 variants...
INFO [2022-08-04 15:00:15] Excluding 1944 novel or poor quality variants from segmentation.
INFO [2022-08-04 15:00:15] Excluding 937 variants not in pool of normals from segmentation.
INFO [2022-08-04 15:00:15] Sample sex: M
INFO [2022-08-04 15:00:15] Segmenting data...
INFO [2022-08-04 15:00:15] Interval weights found, will use weighted CBS.
INFO [2022-08-04 15:00:16] Loading pre-computed boundaries for DNAcopy...
INFO [2022-08-04 15:00:16] Setting undo.SD parameter to 0.500000.
INFO [2022-08-04 15:00:20] Setting prune.hclust.h parameter to 0.100000.
INFO [2022-08-04 15:00:20] Found 43 segments with median size of 50.03Mb.
INFO [2022-08-04 15:00:20] Using 7042 variants.
INFO [2022-08-04 15:00:21] Mean standard deviation of log-ratios: 0.25 (MAPD: 0.19)
INFO [2022-08-04 15:00:21] Mean standard deviation of on-target log-ratios only: 0.18 (MAPD: 0.13)
INFO [2022-08-04 15:00:21] Mean standard deviation of off-target log-ratios only: 0.31 (MAPD: 0.28)
INFO [2022-08-04 15:00:21] 2D-grid search of purity and ploidy...
INFO [2022-08-04 15:01:16] Local optima: 0.1/2.2, 0.12/2, 0.14/2.4, 0.3/3.2, 0.18/1.8, 0.45/3.8,
0.26/2, 0.55/4.2, 0.42/2.8, 0.52/3, 0.45/2.4, 0.62/5, 0.82/6, 0.38/1.6,
0.65/2.6, 0.85/2.8, 0.58/1.4, 0.52/2, 0.78/2
INFO [2022-08-04 15:01:16] Testing local optimum 1/19 at purity 0.10 and total ploidy 2.20...
INFO [2022-08-04 15:01:20] Testing local optimum 2/19 at purity 0.12 and total ploidy 2.00...
INFO [2022-08-04 15:01:24] Testing local optimum 3/19 at purity 0.14 and total ploidy 2.40...
INFO [2022-08-04 15:01:29] Testing local optimum 4/19 at purity 0.30 and total ploidy 3.20...
INFO [2022-08-04 15:01:43] Recalibrating log-ratios...
INFO [2022-08-04 15:01:43] Testing local optimum 4/19 at purity 0.30 and total ploidy 3.20...
INFO [2022-08-04 15:01:53] Testing local optimum 5/19 at purity 0.18 and total ploidy 1.80...
INFO [2022-08-04 15:01:58] Testing local optimum 6/19 at purity 0.45 and total ploidy 3.80...
INFO [2022-08-04 15:02:01] Testing local optimum 7/19 at purity 0.26 and total ploidy 2.00...
INFO [2022-08-04 15:02:05] Testing local optimum 8/19 at purity 0.55 and total ploidy 4.20...
INFO [2022-08-04 15:02:08] Testing local optimum 9/19 at purity 0.42 and total ploidy 2.80...
INFO [2022-08-04 15:02:11] Testing local optimum 10/19 at purity 0.52 and total ploidy 3.00...
INFO [2022-08-04 15:02:14] Testing local optimum 11/19 at purity 0.45 and total ploidy 2.40...
INFO [2022-08-04 15:02:18] Testing local optimum 12/19 at purity 0.62 and total ploidy 5.00...
INFO [2022-08-04 15:02:31] Recalibrating log-ratios...
INFO [2022-08-04 15:02:31] Testing local optimum 12/19 at purity 0.62 and total ploidy 5.00...
INFO [2022-08-04 15:02:35] Recalibrating log-ratios...
INFO [2022-08-04 15:02:35] Testing local optimum 12/19 at purity 0.62 and total ploidy 5.00...
INFO [2022-08-04 15:02:41] Recalibrating log-ratios...
INFO [2022-08-04 15:02:41] Testing local optimum 12/19 at purity 0.62 and total ploidy 5.00...
INFO [2022-08-04 15:02:51] Testing local optimum 13/19 at purity 0.82 and total ploidy 6.00...
INFO [2022-08-04 15:03:02] Testing local optimum 14/19 at purity 0.38 and total ploidy 1.60...
INFO [2022-08-04 15:03:14] Recalibrating log-ratios...
INFO [2022-08-04 15:03:14] Testing local optimum 14/19 at purity 0.38 and total ploidy 1.60...
INFO [2022-08-04 15:04:19] Recalibrating log-ratios...
INFO [2022-08-04 15:04:19] Testing local optimum 14/19 at purity 0.38 and total ploidy 1.60...
INFO [2022-08-04 15:04:31] Testing local optimum 15/19 at purity 0.65 and total ploidy 2.60...
INFO [2022-08-04 15:04:35] Testing local optimum 16/19 at purity 0.85 and total ploidy 2.80...
INFO [2022-08-04 15:04:38] Testing local optimum 17/19 at purity 0.58 and total ploidy 1.40...
INFO [2022-08-04 15:04:52] Recalibrating log-ratios...
INFO [2022-08-04 15:04:52] Testing local optimum 17/19 at purity 0.58 and total ploidy 1.40...
INFO [2022-08-04 15:06:18] Recalibrating log-ratios...
INFO [2022-08-04 15:06:18] Testing local optimum 17/19 at purity 0.58 and total ploidy 1.40...
INFO [2022-08-04 15:07:59] Testing local optimum 18/19 at purity 0.52 and total ploidy 2.00...
INFO [2022-08-04 15:08:02] Testing local optimum 19/19 at purity 0.78 and total ploidy 2.00...
INFO [2022-08-04 15:08:06] Skipping 2 solutions that converged to the same optima.
INFO [2022-08-04 15:08:06] Fitting variants with betabin model for local optimum 1/19...
INFO [2022-08-04 15:08:06] Fitting variants for purity 0.12, tumor ploidy 4.42 and contamination 0.01.
INFO [2022-08-04 15:09:00] Optimized purity: 0.12
INFO [2022-08-04 15:09:00] Fitting variants with betabin model for local optimum 2/19...
INFO [2022-08-04 15:09:00] Fitting variants for purity 0.13, tumor ploidy 2.21 and contamination 0.01.
INFO [2022-08-04 15:09:54] Optimized purity: 0.13
INFO [2022-08-04 15:09:54] Fitting variants with betabin model for local optimum 3/19...
INFO [2022-08-04 15:09:54] Fitting variants for purity 0.16, tumor ploidy 5.20 and contamination 0.01.
INFO [2022-08-04 15:10:47] Optimized purity: 0.16
INFO [2022-08-04 15:10:47] Fitting variants with betabin model for local optimum 4/19...
INFO [2022-08-04 15:10:47] Fitting variants for purity 0.34, tumor ploidy 5.08 and contamination 0.01.
INFO [2022-08-04 15:11:41] Optimized purity: 0.34
INFO [2022-08-04 15:11:41] Fitting variants with betabin model for local optimum 5/19...
INFO [2022-08-04 15:11:42] Fitting variants for purity 0.10, tumor ploidy 5.30 and contamination 0.01.
INFO [2022-08-04 15:12:32] Optimized purity: 0.10
INFO [2022-08-04 15:12:32] Fitting variants with betabin model for local optimum 6/19...
INFO [2022-08-04 15:12:33] Fitting variants for purity 0.47, tumor ploidy 5.96 and contamination 0.01.
INFO [2022-08-04 15:13:26] Optimized purity: 0.47
INFO [2022-08-04 15:13:26] Fitting variants with betabin model for local optimum 8/19...
INFO [2022-08-04 15:13:26] Fitting variants for purity 0.57, tumor ploidy 5.96 and contamination 0.01.
INFO [2022-08-04 15:14:18] Optimized purity: 0.57
INFO [2022-08-04 15:14:18] Fitting variants with betabin model for local optimum 9/19...
INFO [2022-08-04 15:14:19] Fitting variants for purity 0.46, tumor ploidy 4.05 and contamination 0.01.
INFO [2022-08-04 15:15:10] Optimized purity: 0.46
INFO [2022-08-04 15:15:11] Fitting variants with betabin model for local optimum 10/19...
INFO [2022-08-04 15:15:11] Fitting variants for purity 0.55, tumor ploidy 4.00 and contamination 0.01.
INFO [2022-08-04 15:16:03] Optimized purity: 0.55
INFO [2022-08-04 15:16:03] Fitting variants with betabin model for local optimum 11/19...
INFO [2022-08-04 15:16:03] Fitting variants for purity 0.50, tumor ploidy 3.00 and contamination 0.01.
INFO [2022-08-04 15:16:56] Optimized purity: 0.50
INFO [2022-08-04 15:16:56] Fitting variants with betabin model for local optimum 12/19...
INFO [2022-08-04 15:16:56] Fitting variants for purity 0.51, tumor ploidy 5.15 and contamination 0.01.
INFO [2022-08-04 15:17:48] Optimized purity: 0.51
INFO [2022-08-04 15:17:48] Fitting variants with betabin model for local optimum 13/19...
INFO [2022-08-04 15:17:48] Fitting variants for purity 0.77, tumor ploidy 6.00 and contamination 0.01.
INFO [2022-08-04 15:18:40] Optimized purity: 0.77
INFO [2022-08-04 15:18:40] Fitting variants with betabin model for local optimum 15/19...
INFO [2022-08-04 15:18:41] Fitting variants for purity 0.69, tumor ploidy 3.00 and contamination 0.01.
INFO [2022-08-04 15:19:33] Optimized purity: 0.69
INFO [2022-08-04 15:19:33] Fitting variants with betabin model for local optimum 16/19...
INFO [2022-08-04 15:19:34] Fitting variants for purity 0.95, tumor ploidy 3.00 and contamination 0.01.
INFO [2022-08-04 15:20:25] Optimized purity: 0.95
INFO [2022-08-04 15:20:25] Fitting variants with betabin model for local optimum 17/19...
INFO [2022-08-04 15:20:25] Fitting variants for purity 0.95, tumor ploidy 0.35 and contamination 0.01.
INFO [2022-08-04 15:21:18] Optimized purity: 0.95
INFO [2022-08-04 15:21:18] Fitting variants with betabin model for local optimum 18/19...
INFO [2022-08-04 15:21:18] Fitting variants for purity 0.32, tumor ploidy 2.00 and contamination 0.01.
INFO [2022-08-04 15:22:10] Optimized purity: 0.32
INFO [2022-08-04 15:22:10] Fitting variants with betabin model for local optimum 19/19...
INFO [2022-08-04 15:22:10] Fitting variants for purity 0.59, tumor ploidy 2.00 and contamination 0.01.
INFO [2022-08-04 15:23:02] Optimized purity: 0.59
INFO [2022-08-04 15:23:02] Done.
INFO [2022-08-04 15:23:02] ------------------------------------------------------------
INFO [2022-08-04 15:23:06] Generating output files...
FATAL [2022-08-04 15:23:30] f not in expected range.

FATAL [2022-08-04 15:23:30]

FATAL [2022-08-04 15:23:30] This is most likely a user error due to invalid input data or

FATAL [2022-08-04 15:23:30] parameters (PureCN 2.0.2).

**Session Info**
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS release 6.8 (Final)

Matrix products: default
BLAS/LAPACK: /share/work4/zhangyk4498/sysoft/anaconda3/envs/PureCN2.0.2/lib/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.1

**Comment by lima1** [comment]
Thanks, haven't seen this before. Which files does it generate (so I can figure out where it crashes)?

**Comment by ykzhang2022** [comment]
> Thanks, haven't seen this before. Which files does it generate (so I can figure out where it crashes)?

Thank you for your reply。
The error happened when generate **sample.pdf**.

**PureCN.R -> plotAbs(ret, type = "all")  -> .plotTypeAF -> calculatePowerDetectSomatic** 

 <img width="727" alt="image" src="https://user-images.githubusercontent.com/110597508/185515870-50af5257-6bb9-40f4-8063-d345a10e9233.png">

Since the PureCN version 2.0.2 is required, how should I resolve this error.

Thank you very much.

**Comment by ykzhang2022** [comment]
Hi lina1:

	Thank you for your reply.
	The error happened when generate sample.pdf.
	
	PureCN.R -> plotAbs(ret, type = "all") -> .plotTypeAF -> calculatePowerDetectSomatic



	Since the PureCN version 2.0.2 is required, how should I resolve this error.
	Thank you very much.

**Comment by lima1** [comment]
Hmm, never seen this before. Any chance you can share the Sampleid.rds and Sampleid.log files by mail with me?

**Comment by ykzhang2022** [comment]
Hi:



The attachment is an RDS file. I hope to find a solution.
Thank you very much!







At 2022-08-29 22:51:26, "Markus Riester" ***@***.***> wrote:

Hmm, never seen this before. Any chance you can share the Sampleid.rds file by mail with me?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件
Y22S0033204-J1TA.rds (27.5M, 2022年9月14日 11:36 到期)
下载
