### ISSUE TITLE
Seqlevels missing in provided segmentation error  in Target Amplicon sequence samples.

### ISSUE THREAD

**Issue by leap-ahead225** [lima1/PureCN#252]
Hi Markus,

I encountered an error from PureCN Seqlevels missing in provided segmentation: chr20. VCF, seg, and cnr files contain chr20 information.  The error log is here.

NFO [2022-09-06 18:16:16] ------------------------------------------------------------
INFO [2022-09-06 18:16:16] PureCN 2.3.0
INFO [2022-09-06 18:16:16] ------------------------------------------------------------
INFO [2022-09-06 18:16:16] Arguments: -normal.coverage.file  -tumor.coverage.file /Volumes/Crucial/Remnant_PDA/cnvkit/RemPDAC_tumor_003_TY-2_prm.cnr -log.ratio  -seg.file /Volumes/Crucial/Remnant_PDA/cnvkit/RemPDAC.seg -vcf.file /Users/taito/RemPDAC_TY-2_filtered.vcf -normalDB  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid 003_TY-2_prm -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file  -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model beta -post.optimize FALSE -BPPARAM  -log.file TY-2.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2022-09-06 18:16:16] Loading coverage files...
INFO [2022-09-06 18:16:17] Found log2-ratio in tumor coverage data.
WARN [2022-09-06 18:16:17] Allosome coverage missing, cannot determine sex.
WARN [2022-09-06 18:16:17] Allosome coverage missing, cannot determine sex.
INFO [2022-09-06 18:16:17] Using 450 intervals (450 on-target, 0 off-target).
INFO [2022-09-06 18:16:17] No off-target intervals. If this is hybrid-capture data, consider adding them.
INFO [2022-09-06 18:16:17] Loading VCF...
INFO [2022-09-06 18:16:18] Found 2315 variants in VCF file.
INFO [2022-09-06 18:16:18] Removing 68 triallelic sites.
WARN [2022-09-06 18:16:18] Found GERMQ info field with Phred scaled germline probabilities.
WARN [2022-09-06 18:16:18] vcf.file has no DB info field for membership in germline databases. Found and used somatic status instead.
INFO [2022-09-06 18:16:18] 893 (39.7%) variants annotated as likely germline (DB INFO flag).
WARN [2022-09-06 18:16:18] Found 1 variants with missing allelic fraction starting with chr11:108159785_T/TG. Removing them.
INFO [2022-09-06 18:16:19] 003_TY-2_prm is tumor in VCF file.
INFO [2022-09-06 18:16:19] 0 homozygous and 53 heterozygous variants on chrX.
INFO [2022-09-06 18:16:19] Sex from VCF: F (Fisher's p-value: 1, odds-ratio: 0.00).
INFO [2022-09-06 18:16:19] Detected MuTect2 VCF.
INFO [2022-09-06 18:16:19] Removing 2059 Mutect2 calls due to blacklisted failure reasons.
INFO [2022-09-06 18:16:20] Removing 64 non heterozygous (in matched normal) germline SNPs.
INFO [2022-09-06 18:16:20] Removing 117 low quality variants with non-offset BQ < 25.
INFO [2022-09-06 18:16:20] Base quality scores range from 24 to 27 (offset by 1)
INFO [2022-09-06 18:16:20] Minimum number of supporting reads ranges from 4 to 7, depending on coverage and BQS.
INFO [2022-09-06 18:16:20] Removing 0 variants with AF < 0.030 or AF >= 1.000 or insufficient supporting reads or depth < 15.
INFO [2022-09-06 18:16:20] Total size of targeted genomic region: 0.10Mb (0.13Mb with 50bp padding).
INFO [2022-09-06 18:16:20] 0.9% of targets contain variants.
INFO [2022-09-06 18:16:20] Removing 3 variants outside intervals.
INFO [2022-09-06 18:16:20] Found SOMATIC annotation in VCF.
INFO [2022-09-06 18:16:20] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2022-09-06 18:16:21] Found SOMATIC annotation in VCF. Setting mapping bias to 1.072.
INFO [2022-09-06 18:16:21] Excluding 1 novel or poor quality variants from segmentation.
INFO [2022-09-06 18:16:21] Sample sex: ?
INFO [2022-09-06 18:16:21] Segmenting data...
INFO [2022-09-06 18:16:21] Loaded provided segmentation file RemPDAC.seg (format DNAcopy).
WARN [2022-09-06 18:16:21] Expecting numeric chromosome names in seg.file, assuming file is properly sorted.
INFO [2022-09-06 18:16:21] Re-centering provided segment means (offset -0.0081).
INFO [2022-09-06 18:16:21] Loading pre-computed boundaries for DNAcopy...
INFO [2022-09-06 18:16:21] Setting undo.SD parameter to 0.500000.
INFO [2022-09-06 18:16:21] Setting prune.hclust.h parameter to 0.100000.
FATAL [2022-09-06 18:16:21] Seqlevels missing in provided segmentation: chr20 

FATAL [2022-09-06 18:16:21]  

FATAL [2022-09-06 18:16:21] This is most likely a user error due to invalid input data or 

FATAL [2022-09-06 18:16:21] parameters (PureCN 2.3.0).

**Comment by lima1** [comment]
Hi,

I don't think a 100kb Amplicon panel will work, unfortunately. I have seen some success with ultra-deep coverage, 100-200kb hybrid capture panels with lots of off-target reads and >500 SNPs in the 200bp padding regions. Without the two (off-target reads and SNPs), you have huge gaps, which makes it impossible to get an accurate ploidy. You could probably avoid the error by removing chr20 variants from the VCF or adding a dummy chr20 region to the segmentation file, but don't think you get any helpful data out of it.
 
Markus

**Comment by leap-ahead225** [comment]
Thank you for your reply.

I can get the result from your solution.

Thank you very much.
