### ISSUE TITLE
PurecN on TSO500 capture: no valid purity and ploidy solution

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#253]
Hi Markus,

Hope you can help me, I'm trying to get PureCN to work with a TSO500 capture. I have tried running variant calling with the capture BED and without but both fail as purecn can't find a valid purity and ploidy solution. Are there any parameters I can change to try get this to process? Is there something I'm missing here? I am  running cnvkit and importing rather than running PureCN from BAM files.

log file attached:
[sample1.log](https://github.com/lima1/PureCN/files/9548584/sample1.log)

Thanks!
Warren

**Comment by lima1** [comment]
Looks like your CNVkit is rather noisy. You can plot the log2 column in your .cnr file. Probably obvious.

Make sure to use a proper panel of normals for coverage normalization, PureCN won't work without it.

**Comment by waemm** [comment]
Thanks Markus, I think you're correct the difficulty is coming from the PON. I'll investigate further.
