### ISSUE TITLE
No variants to plot error.

### ISSUE THREAD

**Issue by leap-ahead225** [lima1/PureCN#256]
Hi, 
I'm trying to calculate purity and ploidy in pancreatic cancer WES samples.
In some cases, "No variant to plot" error occored.  How can I fix it?

INFO [2022-10-04 18:13:47] ------------------------------------------------------------
INFO [2022-10-04 18:13:47] PureCN 2.3.0
INFO [2022-10-04 18:13:48] ------------------------------------------------------------
INFO [2022-10-04 18:13:48] Arguments: -normal.coverage.file  -tumor.coverage.file /Volumes/Crucial/cnvkitresult/SKH-001_INV.hs37d5.cnr -log.ratio  -seg.file /Volumes/Crucial/cnvkitresult/ePDAC.seg -vcf.file /Volumes/Crucial/ePDACMutectVCF/SKH-001_INV_filtered.vcf.gz -normalDB  -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf /Volumes/Crucial/PureCN_Itoh/mapping_bias_agilent_v6_hs37d5.rds -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid SKH-001_INV -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file  -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model beta -post.optimize TRUE -log.file /Volumes/Crucial/PureCN_Itoh/SKH-001_INV/SKH-001_INV.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2022-10-04 18:13:48] Using BiocParallel for parallel optimization.
INFO [2022-10-04 18:13:48] Loading coverage files...
INFO [2022-10-04 18:13:52] Found log2-ratio in tumor coverage data.
WARN [2022-10-04 18:13:52] log2-ratio contains outliers < -8, ignoring them...
INFO [2022-10-04 18:13:53] Mean coverages: chrX: 36.50, chrY: 39.11, chr1-22: 60.68.
INFO [2022-10-04 18:13:53] Mean coverages: chrX: 36.50, chrY: 39.11, chr1-22: 60.68.
INFO [2022-10-04 18:13:54] Removing 26 intervals with missing log.ratio.
INFO [2022-10-04 18:13:54] Using 303011 intervals (262836 on-target, 40175 off-target).
INFO [2022-10-04 18:13:54] Ratio of mean on-target vs. off-target read counts: NaN
INFO [2022-10-04 18:13:54] Mean off-target bin size: 59644
INFO [2022-10-04 18:13:54] Loading VCF...
INFO [2022-10-04 18:13:58] Found 118224 variants in VCF file.
INFO [2022-10-04 18:13:59] Removing 1641 triallelic sites.
WARN [2022-10-04 18:13:59] Found GERMQ info field with Phred scaled germline probabilities.
WARN [2022-10-04 18:14:00] vcf.file has no DB info field for membership in germline databases. Found and used somatic status instead.
INFO [2022-10-04 18:14:00] 56810 (48.7%) variants annotated as likely germline (DB INFO flag).
WARN [2022-10-04 18:14:03] Found 252 variants with missing allelic fraction starting with 1:11714443_C/CGCTGCTGTTCCGATGGTGTCTTTGATGTTGGGCTGATGAGGTCTGG. Removing them.
INFO [2022-10-04 18:14:05] SKH-001_INV is tumor in VCF file.
INFO [2022-10-04 18:14:05] 499 homozygous and 120 heterozygous variants on chrX.
INFO [2022-10-04 18:14:05] Sex from VCF: M (Fisher's p-value: < 0.0001, odds-ratio: 6.46).
INFO [2022-10-04 18:14:05] Detected MuTect2 VCF.
INFO [2022-10-04 18:14:07] Removing 69755 Mutect2 calls due to blacklisted failure reasons.
INFO [2022-10-04 18:14:07] Removing 22603 non heterozygous (in matched normal) germline SNPs.
INFO [2022-10-04 18:14:07] Removing 23074 low quality variants with non-offset BQ < 25.
INFO [2022-10-04 18:14:07] Base quality scores range from 24 to 29 (offset by 1)
INFO [2022-10-04 18:14:07] Minimum number of supporting reads ranges from 2 to 9, depending on coverage and BQS.
INFO [2022-10-04 18:14:08] Removing 685 variants with AF < 0.030 or AF >= 1.000 or insufficient supporting reads or depth < 15.
INFO [2022-10-04 18:14:19] Removing 27 blacklisted variants.
INFO [2022-10-04 18:14:19] Total size of targeted genomic region: 56.91Mb (76.96Mb with 50bp padding).
INFO [2022-10-04 18:14:19] 0.1% of targets contain variants.
INFO [2022-10-04 18:14:19] Removing 9 variants outside intervals.
WARN [2022-10-04 18:14:19] Less than half of variants in dbSNP. Make sure that VCF contains both germline and somatic variants.
INFO [2022-10-04 18:14:19] Found SOMATIC annotation in VCF.
INFO [2022-10-04 18:14:19] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2022-10-04 18:14:19] Found SOMATIC annotation in VCF. Setting mapping bias to 0.932.
INFO [2022-10-04 18:14:19] Loading mapping bias file mapping_bias_agilent_v6_hs37d5.rds...
INFO [2022-10-04 18:14:21] Found 1385518 variants in mapping bias file.
INFO [2022-10-04 18:14:21] Imputing mapping bias for 134 variants...
INFO [2022-10-04 18:14:28] Excluding 173 novel or poor quality variants from segmentation.
INFO [2022-10-04 18:14:28] Excluding 134 variants not in pool of normals from segmentation.
INFO [2022-10-04 18:14:28] Sample sex: M
INFO [2022-10-04 18:14:28] Segmenting data...
INFO [2022-10-04 18:14:28] Loaded provided segmentation file ePDAC.seg (format DNAcopy).
WARN [2022-10-04 18:14:28] Expecting numeric chromosome names in seg.file, assuming file is properly sorted.
WARN [2022-10-04 18:14:28] Removing 2 short segments with log-ratio < -8.
INFO [2022-10-04 18:14:28] Re-centering provided segment means (offset -0.0518).
INFO [2022-10-04 18:14:28] Setting prune.hclust.h parameter to 0.100000.
INFO [2022-10-04 18:14:28] Found 152 segments with median size of 4.50Mb.
INFO [2022-10-04 18:14:28] Using 178 variants.
INFO [2022-10-04 18:14:29] Mean standard deviation of log-ratios: 0.39 (MAPD: 0.32)
INFO [2022-10-04 18:14:29] Mean standard deviation of on-target log-ratios only: 0.40 (MAPD: 0.32)
INFO [2022-10-04 18:14:29] Mean standard deviation of off-target log-ratios only: 0.35 (MAPD: 0.23)
INFO [2022-10-04 18:14:29] 2D-grid search of purity and ploidy...
INFO [2022-10-04 18:15:24] Local optima: 0.15/2, 0.15/2.2, 0.25/2, 0.21/1.8, 0.29/2.6, 0.42/2.8,
0.52/3, 0.33/3, 0.42/2.4, 0.55/4.2, 0.45/3.8, 0.35/1.6, 0.82/6,
0.65/5.2, 0.62/2.6, 0.52/2, 0.78/2.8, 0.95/3, 0.62/1.4, 0.78/2
INFO [2022-10-04 18:15:25] Testing local optimum 3/20 at purity 0.25 and total ploidy 2.00...
INFO [2022-10-04 18:15:25] Testing local optimum 5/20 at purity 0.29 and total ploidy 2.60...
INFO [2022-10-04 18:15:25] Testing local optimum 9/20 at purity 0.42 and total ploidy 2.40...
INFO [2022-10-04 18:15:25] Testing local optimum 1/20 at purity 0.15 and total ploidy 2.00...
INFO [2022-10-04 18:15:25] Testing local optimum 11/20 at purity 0.45 and total ploidy 3.80...
INFO [2022-10-04 18:15:25] Testing local optimum 7/20 at purity 0.52 and total ploidy 3.00...
INFO [2022-10-04 18:15:25] Testing local optimum 13/20 at purity 0.82 and total ploidy 6.00...
INFO [2022-10-04 18:15:25] Testing local optimum 17/20 at purity 0.78 and total ploidy 2.80...
INFO [2022-10-04 18:15:25] Testing local optimum 19/20 at purity 0.62 and total ploidy 1.40...
INFO [2022-10-04 18:15:25] Testing local optimum 15/20 at purity 0.62 and total ploidy 2.60...
INFO [2022-10-04 18:15:35] Recalibrating log-ratios...
INFO [2022-10-04 18:15:35] Recalibrating log-ratios...
INFO [2022-10-04 18:15:35] Testing local optimum 13/20 at purity 0.82 and total ploidy 6.00...
INFO [2022-10-04 18:15:35] Testing local optimum 19/20 at purity 0.62 and total ploidy 1.40...
INFO [2022-10-04 18:15:44] Recalibrating log-ratios...
INFO [2022-10-04 18:15:44] Testing local optimum 19/20 at purity 0.62 and total ploidy 1.40...
INFO [2022-10-04 18:15:55] Recalibrating log-ratios...
INFO [2022-10-04 18:15:55] Testing local optimum 19/20 at purity 0.62 and total ploidy 1.40...
INFO [2022-10-04 18:16:05] Testing local optimum 20/20 at purity 0.78 and total ploidy 2.00...
INFO [2022-10-04 18:16:11] Testing local optimum 18/20 at purity 0.95 and total ploidy 3.00...
INFO [2022-10-04 18:16:20] Testing local optimum 2/20 at purity 0.15 and total ploidy 2.20...
INFO [2022-10-04 18:16:21] Testing local optimum 4/20 at purity 0.21 and total ploidy 1.80...
INFO [2022-10-04 18:16:23] Testing local optimum 6/20 at purity 0.42 and total ploidy 2.80...
INFO [2022-10-04 18:16:26] Testing local optimum 16/20 at purity 0.52 and total ploidy 2.00...
INFO [2022-10-04 18:16:26] Testing local optimum 10/20 at purity 0.55 and total ploidy 4.20...
INFO [2022-10-04 18:16:26] Testing local optimum 8/20 at purity 0.33 and total ploidy 3.00...
INFO [2022-10-04 18:16:28] Recalibrating log-ratios...
INFO [2022-10-04 18:16:28] Testing local optimum 11/20 at purity 0.45 and total ploidy 3.80...
INFO [2022-10-04 18:16:30] Recalibrating log-ratios...
INFO [2022-10-04 18:16:30] Testing local optimum 4/20 at purity 0.21 and total ploidy 1.80...
INFO [2022-10-04 18:16:36] Recalibrating log-ratios...
INFO [2022-10-04 18:16:36] Testing local optimum 13/20 at purity 0.82 and total ploidy 6.00...
INFO [2022-10-04 18:16:38] Recalibrating log-ratios...
INFO [2022-10-04 18:16:38] Testing local optimum 4/20 at purity 0.21 and total ploidy 1.80...
INFO [2022-10-04 18:16:48] Recalibrating log-ratios...
INFO [2022-10-04 18:16:48] Testing local optimum 4/20 at purity 0.21 and total ploidy 1.80...
INFO [2022-10-04 18:17:18] Recalibrating log-ratios...
INFO [2022-10-04 18:17:18] Testing local optimum 8/20 at purity 0.33 and total ploidy 3.00...
INFO [2022-10-04 18:17:21] Recalibrating log-ratios...
INFO [2022-10-04 18:17:21] Testing local optimum 10/20 at purity 0.55 and total ploidy 4.20...
INFO [2022-10-04 18:17:25] Recalibrating log-ratios...
INFO [2022-10-04 18:17:25] Testing local optimum 11/20 at purity 0.45 and total ploidy 3.80...
INFO [2022-10-04 18:17:29] Recalibrating log-ratios...
INFO [2022-10-04 18:17:29] Testing local optimum 13/20 at purity 0.82 and total ploidy 6.00...
INFO [2022-10-04 18:17:36] Testing local optimum 14/20 at purity 0.65 and total ploidy 5.20...
INFO [2022-10-04 18:17:42] Recalibrating log-ratios...
INFO [2022-10-04 18:17:42] Testing local optimum 14/20 at purity 0.65 and total ploidy 5.20...
INFO [2022-10-04 18:17:57] Recalibrating log-ratios...
INFO [2022-10-04 18:17:57] Testing local optimum 8/20 at purity 0.33 and total ploidy 3.00...
INFO [2022-10-04 18:18:00] Recalibrating log-ratios...
INFO [2022-10-04 18:18:00] Testing local optimum 10/20 at purity 0.55 and total ploidy 4.20...
INFO [2022-10-04 18:18:10] Recalibrating log-ratios...
INFO [2022-10-04 18:18:10] Testing local optimum 11/20 at purity 0.45 and total ploidy 3.80...
INFO [2022-10-04 18:18:18] Testing local optimum 12/20 at purity 0.35 and total ploidy 1.60...
INFO [2022-10-04 18:18:24] Recalibrating log-ratios...
INFO [2022-10-04 18:18:24] Testing local optimum 12/20 at purity 0.35 and total ploidy 1.60...
INFO [2022-10-04 18:18:25] Recalibrating log-ratios...
INFO [2022-10-04 18:18:25] Testing local optimum 14/20 at purity 0.65 and total ploidy 5.20...
INFO [2022-10-04 18:18:30] Recalibrating log-ratios...
INFO [2022-10-04 18:18:30] Testing local optimum 12/20 at purity 0.35 and total ploidy 1.60...
INFO [2022-10-04 18:18:35] Recalibrating log-ratios...
INFO [2022-10-04 18:18:35] Testing local optimum 12/20 at purity 0.35 and total ploidy 1.60...
INFO [2022-10-04 18:18:38] Recalibrating log-ratios...
INFO [2022-10-04 18:18:38] Testing local optimum 8/20 at purity 0.33 and total ploidy 3.00...
INFO [2022-10-04 18:18:48] Recalibrating log-ratios...
INFO [2022-10-04 18:18:48] Testing local optimum 10/20 at purity 0.55 and total ploidy 4.20...
INFO [2022-10-04 18:19:04] Recalibrating log-ratios...
INFO [2022-10-04 18:19:04] Testing local optimum 14/20 at purity 0.65 and total ploidy 5.20...
INFO [2022-10-04 18:19:32] Skipping 6 solutions that converged to the same optima.
INFO [2022-10-04 18:19:32] Skipping 6 solutions exceeding max.non.clonal (0.20): 0.23/1.11, 0.53/1.05, 0.33/1.07, 0.63/1.4, 0.65/1.18, 0.64/1.04 (purity/tumor ploidy)
INFO [2022-10-04 18:19:32] Fitting variants with beta model for local optimum 8/20...
INFO [2022-10-04 18:19:32] Fitting variants with beta model for local optimum 2/20...
INFO [2022-10-04 18:19:32] Fitting variants with beta model for local optimum 7/20...
INFO [2022-10-04 18:19:32] Fitting variants with beta model for local optimum 10/20...
INFO [2022-10-04 18:19:32] Fitting variants with beta model for local optimum 20/20...
INFO [2022-10-04 18:19:32] Fitting variants with beta model for local optimum 17/20...
INFO [2022-10-04 18:19:32] Fitting variants with beta model for local optimum 18/20...
INFO [2022-10-04 18:19:32] Fitting variants with beta model for local optimum 15/20...
INFO [2022-10-04 18:19:37] Fitting variants for purity 0.59, tumor ploidy 2.83 and contamination 0.01.
INFO [2022-10-04 18:19:37] Fitting variants for purity 0.32, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:19:37] Fitting variants for purity 0.42, tumor ploidy 2.82 and contamination 0.01.
INFO [2022-10-04 18:19:37] Fitting variants for purity 0.89, tumor ploidy 3.02 and contamination 0.01.
INFO [2022-10-04 18:19:37] Fitting variants for purity 0.15, tumor ploidy 2.86 and contamination 0.01.
INFO [2022-10-04 18:19:37] Fitting variants for purity 0.27, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:19:37] Fitting variants for purity 0.59, tumor ploidy 1.95 and contamination 0.01.
INFO [2022-10-04 18:19:37] Fitting variants for purity 0.19, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:19:44] Poor goodness-of-fit (0.725). Skipping post-optimization.
INFO [2022-10-04 18:19:44] Optimized purity: 0.42
INFO [2022-10-04 18:19:44] Fitting variants for purity 0.16, tumor ploidy 2.86 and contamination 0.01.
INFO [2022-10-04 18:19:44] Poor goodness-of-fit (0.373). Skipping post-optimization.
INFO [2022-10-04 18:19:44] Optimized purity: 0.59
INFO [2022-10-04 18:19:44] Fitting variants for purity 0.23, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:19:44] Poor goodness-of-fit (0.000). Skipping post-optimization.
INFO [2022-10-04 18:19:44] Poor goodness-of-fit (0.000). Skipping post-optimization.
INFO [2022-10-04 18:19:44] Optimized purity: 0.89
INFO [2022-10-04 18:19:44] Optimized purity: 0.59
INFO [2022-10-04 18:19:44] Fitting variants for purity 0.28, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:19:44] Fitting variants for purity 0.15, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:19:51] Fitting variants for purity 0.17, tumor ploidy 2.86 and contamination 0.01.
INFO [2022-10-04 18:19:51] Fitting variants for purity 0.24, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:19:51] Fitting variants for purity 0.29, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:19:51] Fitting variants for purity 0.16, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:19:57] Fitting variants for purity 0.25, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:19:57] Fitting variants for purity 0.17, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:19:57] Fitting variants for purity 0.30, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:19:57] Fitting variants for purity 0.18, tumor ploidy 2.86 and contamination 0.01.
INFO [2022-10-04 18:20:04] Fitting variants for purity 0.26, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:20:04] Fitting variants for purity 0.18, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:20:04] Fitting variants for purity 0.19, tumor ploidy 2.86 and contamination 0.01.
INFO [2022-10-04 18:20:04] Fitting variants for purity 0.31, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:20:10] Fitting variants for purity 0.28, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:20:10] Fitting variants for purity 0.20, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:20:11] Fitting variants for purity 0.33, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:20:11] Optimized purity: 0.15
INFO [2022-10-04 18:20:17] Fitting variants for purity 0.29, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:20:17] Fitting variants for purity 0.21, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:20:17] Fitting variants for purity 0.34, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:20:23] Fitting variants for purity 0.30, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:20:23] Fitting variants for purity 0.22, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:20:23] Fitting variants for purity 0.35, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:20:30] Fitting variants for purity 0.31, tumor ploidy 1.86 and contamination 0.01.
INFO [2022-10-04 18:20:30] Fitting variants for purity 0.23, tumor ploidy 2.10 and contamination 0.01.
INFO [2022-10-04 18:20:30] Fitting variants for purity 0.36, tumor ploidy 3.84 and contamination 0.01.
INFO [2022-10-04 18:20:36] Optimized purity: 0.27
INFO [2022-10-04 18:20:36] Optimized purity: 0.19
INFO [2022-10-04 18:20:36] Optimized purity: 0.32
INFO [2022-10-04 18:20:36] Done.
INFO [2022-10-04 18:20:36] ------------------------------------------------------------
INFO [2022-10-04 18:20:39] Generating output files...
WARN [2022-10-04 18:20:41] No variants to plot
WARN [2022-10-04 18:20:41] No variants to plot
WARN [2022-10-04 18:20:41] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot
WARN [2022-10-04 18:20:42] No variants to plot

**Comment by lima1** [comment]
Apologies for missing this. It means no variants survived filtering. The coverage is low (PureCN is made for >100X), but that alone does not explain it. Follow the GATK4 best practices closely, including germline annotation with population allele frequencies.
