### ISSUE TITLE
Coverage.R and NormalDB.R check wrong directory for write permissions

### ISSUE THREAD

**Issue by sleyn** [lima1/PureCN#258]
PureCN scripts Coverage.R, NormalDB.R check one level above output directory for write permissions rather than output directory itself.

I found that if I'm using a docker container with user id other than "root" and work directory in the root directory (e.g. `/work_dir`) scripts produce an error `Error: Permission denied to write in --outdir.`

I believe that the reason is an unnecessary usage of `dirname` function.
The scripts contain the following code:
```
outdir <- normalizePath(opt$out_dir, mustWork = TRUE)
if (file.access(dirname(outdir), 2) < 0) stop("Permission denied to write in --outdir.")
``` 

As the scripts require directory name as input the `dirname(outdir)` will cut the last level of directory.

For example":
```
outdir <- "/work_dir"
dirname(outdir)

[1] "/"
```

**Expected behavior**
Check output directory permissions.

**Comment by sleyn** [comment]
Initial post said about PureCN.R. Sorry it makes a correct test.

**Comment by lima1** [comment]
Thanks Semion, that indeed looks wrong. Thanks for reporting. I'm a bit swamped right now, but will double check and add this in the next bugfix release.

**Comment by lima1** [comment]
Should be fixed in current devel.
