### ISSUE TITLE
Sex column contents better as FEMALE / MALE

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#26]
The PureCN.R output file containing the purity and sex estimation uses "M" and "F" in the "Sex" column.  R reads "F" as "FALSE" unless you specify the type of each column.  I suggest you change the contents of the column to "MALE" and "FEMALE".

**Comment by lima1** [comment]
Since it's easy to fix that with the read_csv function from the tidyverse package, I'll close this for now.

read_csv(file, col_type=cols(Sex = col_character()))
