### ISSUE TITLE
No handling of NA values from .matrixTotalPloidyToTumorPloidy function

### ISSUE THREAD

**Issue by sleyn** [lima1/PureCN#260]
Hello,

**Describe the issue**
I was running `PureCN.R` from the 2.2.0 docker file and received an error:
```
Error in quantile.default(xc, p = 0.2) :
  missing values and NaN's not allowed if 'na.rm' is FALSE
Calls: plotAbs ... .plotTypeOverview -> quantile -> quantile -> quantile.default
```

**To Reproduce**
I can't provide a reproducible example as I can't share the data.

However there some of my investigations:

The reason of the error are couple `NA` in the results `.matrixTotalPloidyToTumorPloidy` function in `plotAbs.R`.
More specific lines 124-126:
```
  tumor.ploidy.i <- lapply(tumor.ploidy, function(x)
    sapply(ploidy, function(i) ifelse(min(abs(x-i)) < 1,
                                      which.min(abs(x-i)), NA)))
```

Subsequently these `NAs` are used to sample `res$candidates$all` matrix from the `runAbsoluteCN` output that in turn produces `NAs` in the output of `.matrixTotalPloidyToTumorPloidy`.

```
cc <- do.call(cbind, lapply(seq_along(tumor.ploidy.i), function(i)
    ca[tumor.ploidy.i[[i]],i]))
```

Then `NAs` are not handled and go to `.plotTypeOverview` function where they hit line 610 in `plotAbs.R`:
```
xc[xc < quantile(xc, p=0.2)] <- quantile(xc, p=0.2)
```

What supposed to happen with these `NAs`?
Does it mean that my results are wrong or is it ok to have couple of `NAs`?

Thanks,
Semion

**Comment by lima1** [comment]
Hi Semion,

hm, that's a new one. Can you at least share the output of the log file until it crashes?

Does it happen for all samples, or just a single one?

Were you able to follow the best practices closely or did you had to improvise? 

Markus

**Comment by sleyn** [comment]
Hi Markus,

Sorry for long time. I still was not able to figure out if I can share a log with you. Do you have anything in mind where to look in the log?

Again - the problem is only during making a plot. Results that I have look reasonable.

I don't have raw data for normals so I'm using normalDB from old runs. It was build for PureCN 1.20 and Mutect. Now I'm running PureCN 2.2.0 and Mutect2. Other things seems pretty much the same as in best practices.

**Comment by lima1** [comment]
Sorry, I totally missed this. I'll prepare a new release in the coming weeks and will revisit it. normalDB was relatively mature, so it should be ok to use with latest PureCN. Mutect2 with Mutect normals is not optimal, but I don't see how this could affect this. If you want, still feel free to post a complete log file of a run that crashes. Maybe that points me to a source of NAs. There shouldn't be any, so it's kind of puzzling.

**Comment by sleyn** [comment]
Hi! I did not run to this error in last samples. If I'll come across it again I'll send a log to you.
