### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maxanes** [lima1/PureCN#261]
Hi Markus,
I have a question related to PureCN output. When I look at the multiplicity of the mutations, all somatic mutations that have CCF less than 0.9 are a multiplicity of 1, and higher CCF than 0.9 have all multiplicities 1-7. 
Is it possible that no mutation with lower CCF has a higher than 1 multiplicity?

**Comment by lima1** [comment]
Hi,

good question. You are reaching the limits what you can do with bulk sequencing. It's like you can't distinguish a sub-clonal amplification of 8 copies in 50% of the cells from a mono-clonal gain of 4 copies, if that makes sense.

However, a sub-clonal mutation with multiplicity > 1 is highly unlikely. Multiplicity 2 means the mutation appeared before a chromosomal gain (alternatively the same mutation appeared independently twice, but that is again very unlikely). That means the mutation is old in the evolution of the tumor, thus unlikely a recent sub-clonal event.

So when reporting those numbers, PureCN implicitly makes the assumption that sub-clonality is less likely than mono-clonal.

Hope that helps.

Markus

**Comment by maxanes** [comment]
Thank you very much for the reply and clarification. 
So in a way, PureCN sets mutations with M>1 automatically to CCF =1,  if I understood well.
