### ISSUE TITLE
Minimal run for accurate purity/ploidy

### ISSUE THREAD

**Issue by ghost** [lima1/PureCN#262]
I was wondering if the following minimal steps (for a relatively quicker run) would enable accurate purity estimation with PureCN?:

1. extract manufacturer's bait intervals overlapping common SNPs (snp151Common)
2. Get allelic counts with GATK4 CollectAllelicCounts
3. Back in R, perform readAllelicCountsFile to read these counts
4. Then:
```
runAbsoluteCN(seg.file = seg.file, interval.file = interval.file, vcf.file = vcf.ac, max.candidate.solutions = 1, genome = "hg38", test.purity = seq(0.05,0.95,by = 0.05),post.optimize = TRUE, BPPARAM = multicoreParam, cosmic.vcf.file = cosmic.vcf.file, verbose = TRUE, plot.cnv = FALSE)
#seg.file = third party segmentation file
#interval.file = "ex2_gc_file.txt" from preprocessIntervals
#vcf.ac = from step 3
```

If one was only interested in purity estimation from PureCN, would this be the quickest method with relatively good accuracy? Thanks!

**Comment by lima1** [comment]
You can follow the best practices. I think I added support for GATK CollectAllelicCounts a while back. Simply provide them via --vcf (I know...). Should be documented in the best practices vignette. Should work fine for purity and ploidy. In tumor types with high TMB, there is some purity signal in the somatic variant calls, but copy number is usually >99% of the signal.

**Comment by lima1** [comment]
And don't forget to add a padding to the baits intervals in step 1, many SNPs are just outside the common exon baits.
