### ISSUE TITLE
PureCN DNAcopy.seg output

### ISSUE THREAD

**Issue by Jwong684** [lima1/PureCN#265]
Hi Markus,

I wanted to confirm something in the igv seg output as a sanity check.

In the output {sample_id}_dnacopy.seg, there are 7 columns:

```
ID      chrom   loc.start       loc.end num.mark        seg.mean        C
CL_PBL1T        1       12081   675653.5        76      0.26309240699952        2
CL_PBL1T        1       675653.5        1640337 464     -0.130242704302764      1
CL_PBL1T        1       1640338 1667719.5       31      -0.204790648698986      1.13874637873724
```

From documentation seg.mean is the log2 ratios not adjusted for purity/ploidy and C would be the segment integer copy number after using the formula `(2^(seg$seg.mean + log.ratio.offset) *  total.ploidy)/p - ((2 * (1 - p))/p)`. For downstream processes (like GISTIC), is it correct to just take the C value at face value? When compiling seg files and viewing on IGV, I've previously been just using the seg.mean, but I realize that C is probably the correct value to use. This does convert several large segments in some of my samples that were previously ~0 seg.mean into losses (CN =1) for a ploidy = 2 sample.

**Comment by lima1** [comment]
Have a look here: https://support.bioconductor.org/p/109478/

There is a paper explaining how to use purity adjusted log ratios in GISTIC, but there is an error in the formula. Have not had a chance to check myself.

**Comment by lima1** [comment]
https://github.com/lima1/PureCN/issues/40
