### ISSUE TITLE
Cellular fraction calculation

### ISSUE THREAD

**Issue by adriennebrackey** [lima1/PureCN#267]
Can someone please advise which of the functions included in this package compute cellular fraction? Additionally, if you can point out the lines of code where this calculation is done, that'd be very helpful. Thanks!

**Comment by lima1** [comment]
The predictSomatic function calculates them for predicted somatic mutations. 
https://github.com/lima1/PureCN/blob/master/R/PureCN-internal.R#L1068-L1091

It does not take any uncertainty of purity and ploidy into account. A good sanity check is looking at the distribution of CCFs within a sample. If you get a sample where pretty much all somatic mutations are sub-clonal, then your purity is wrong (too high).

**Comment by adriennebrackey** [comment]
@lima1 Thank you for the response. Just want to follow-up with one clarification: I'm assuming C stands for copy number, correct? Thank you!

**Comment by lima1** [comment]
Exactly. This code is a bit convoluted to make the CCFs bound between 0 and 1, in case you are wondering. 

I'll probably improve it by including slight uncertainty of purity (when using --post-optimize) and the betabin model when selected, but no roadmap yet. That's mostly relevant for low purity and ultra deep sequencing, respectively.

**Comment by adriennebrackey** [comment]
Gotcha, thanks again for your help.
