### ISSUE TITLE
Error in PureCN.R

### ISSUE THREAD

**Issue by WubinQ** [lima1/PureCN#274]
When I using the PureCN.R to calculate the purity and ploidy, I got the following error message:

**Error in if (is.na(posterior) || posterior < 0.5) flag <- TRUE :
  missing value where TRUE/FALSE needed
Calls: runAbsoluteCN ... .calcMsSegment -> lapply -> lapply -> FUN -> .calcMsSegmentC
Execution halted**
[PABP12.log](https://github.com/lima1/PureCN/files/11187448/PABP12.log)

I have used Mutect1 to prepare the mutation data. Among the 200 samples I  calculated, about 30 sample met the same error message.  Would you help check the log file to see which caused the error, and kindly tell me which I can do?

**Comment by lima1** [comment]
Hi @WubinQ , looks in general OK. Do you get the sex mismatch warning for many samples?

Would you be able to share one sample for debugging purposes? If yes, please reach out by email and I will send you a link to securely upload the files.

**Comment by WubinQ** [comment]
Hi @lima1. Yes, Among the 170 samples with final result, 63 were predicted as "M", 84 were predicted as "F", while others were predicted as ""Coverage: F VCF: M". Above gender information were extracted from the "*.csv" files of PureCN result.

Which kind of files is needed for debugging purpose?  very glad to prepre these files. My email is qianwubin@crownbio.com, please send link to this mail.

**Comment by lima1** [comment]
That is likely not related to the crash, but usually the sex mismatch with that many samples means either an issue with the variant calling (many false positive SNP calls, not likely here if you use Mutect1 with the stats file) or an issue with the interval file, most likely not using a mappability file.

Can you share the command line you used for IntervalFile.R?

I will send you a OneDrive link. I would need a minimal command line to reproduce the crash. Thanks a lot.

**Comment by WubinQ** [comment]
@lima1 The files are uploaded to OneDrive link,. 
The command  line for IntervalFile.R is in the file of "IntervalFile.sh".
The Mutect1 and PureCN command  line is in the files of "mutect1.sh" and "PureCN.sh". 
The bam file, fasta file and bed file used in the command is also included, pelase tell me if any other file is needed.

**Comment by lima1** [comment]
Hi @WubinQ , can you try with the very latest version and post the log file again? There were a couple of issues  with off-target and WES and the new log file should give more information here.

BiocManager::install("lima1/PureCN", ref = "RELEASE_3_17")

If you still get the error, can you provide the normalDB in the OneDrive folder? Ideally also the VCF and stats file. If you get the error only with the mapping bias database, I would also need that one.

Not relevant for the crash: Make sure to use the agilent baits file with the baits coordinates, not the exon coordinates. You might, but I'm not 100% sure and didn't look closely.

**Comment by WubinQ** [comment]
Hi, @lima1
Thanks for the help.  But I got the different error message using RELEASE_3_17:

Error in layout(level, msg, ...) : object 'n' not found
Calls: runAbsoluteCN ... .readAndCheckVcf -> flog.warn -> .log_level -> layout
Execution halted
 
[PA20072BP12.log](https://github.com/lima1/PureCN/files/11403154/PA20072BP12.log)

The normalDB of vcf format is uploaded to the OneDriver folder, the vcf is the combined file of several vcf files of normal samples, so no stats file is available for this normal DB file.

I have used the baits coordinates, not the exon coordinates.

**Comment by lima1** [comment]
Ah, we are getting closer. This n crash happens when the base quality field contains missing values. I fixed it a couple of days ago in the developer version. You can install it with the same command without the ref argument.

**Comment by WubinQ** [comment]
The new version works well. Thanks very much for your help.

**Comment by lima1** [comment]
Thanks @WubinQ , will delete all the files you sent now.
