### ISSUE TITLE
Question: Using Paired PSCBS algorithm

### ISSUE THREAD

**Issue by akaviaLab** [lima1/PureCN#275]
Hello
I'm working on (among other things) on matched tumor-normal data. My understanding is that PSCBS is good for low purity and or noisy samples.
Looking at the PSCBS package, it seems there is a Paired mode which considers normal data, and would give better results when matched data is available. However, PureCN only seems to implement the UnPaired PSCBS method. Assuming both statements are correct, how can I use Paired PSCBS? Should I use it as an external algorithm and give PureCN the segmented results?

Thank you,

Uri David

**Comment by lima1** [comment]
Uh, it's been a long time I made that design decision. I remember I tested it and it did not provide better results, most likely because PureCN is doing a lot more internally to clean things up. But happy to revisit if you find anything wrong with current implementation. 

You might be also able to tweak the GATK4 segmentation for low purity. That one should support the matched normal, but not sure I ever tested it.

**Comment by akaviaLab** [comment]
Hi
Thank you.
Is PSCBS better than the default segmentation, which I think is CBS (at
least in the function installed on the cluster I'm using)? Ignoring the
paired question for now.

Better for low-purity and/or noisy samples, that is.

Thank you,

Uri David

**Comment by lima1** [comment]
We are using PSCBS (with my weighting patch) in our pipelines with default parameters. The more SNPs you have, the better PSCBS. DNAcopy does not use SNPs. The cleaner the data, the easier the job for the segmentation, obviously. So more important to tweak there.

There are a couple of hints in the vignettes to get the data as clean as possible. In general, use the baits BED file, not the exons when running IntervalFile.R. Figure out if you need off-target (WES often does not and might make it worse - PureCN will tell you though in the log files). Maximize SNPs by including flanking regions (between 50 to 100bp). If possible, normal samples from different batches.
