### ISSUE TITLE
stucked at generating mapping_bias.rds

### ISSUE THREAD

**Issue by hfl112** [lima1/PureCN#276]
Hi,
**I was trying to generate the WES mapping bias by:**
library(PureCN)
normal.panel.vcf.file <- "PON/pon_WES.merge.vcf.gz"
bias <- calculateMappingBiasVcf(normal.panel.vcf.file, genome = "hg38")
saveRDS(bias, "/pureCN/WES_mapping_bias.rds")

**but it has been stuck since April 18:**
WARN [2023-04-18 22:11:02] Could not fit beta binomial dist for chr2:201824798 (alt 15,8,8,5,8,33,2,19,12,9,17,5,16,10, ref 0,0,0,0,0,0,0,0,0,0,0,0,0,0, fa 0.429,0.267,0.163,0.385,0.116,0.579,0.074,0.38,0.429,0.391,0.378,0.25,0.444,0.385).

INFO [2023-04-18 22:11:18] Clustering beta binomial fits...
INFO [2023-04-18 22:11:25] Assigning (1127/50000) variants a clustered beta binomal fit.
INFO [2023-04-18 22:11:31] Processing variants 2750001 to 2800000...
INFO [2023-04-18 22:12:41] Clustering beta binomial fits...
INFO [2023-04-18 22:12:47] Assigning (990/50000) variants a clustered beta binomal fit.
INFO [2023-04-18 22:12:54] Processing variants 2800001 to 2850000...
INFO [2023-04-18 22:14:30] Clustering beta binomial fits...
INFO [2023-04-18 22:14:41] Assigning (1262/50000) variants a clustered beta binomal fit.
INFO [2023-04-18 22:14:49] Processing variants 2850001 to 2900000...
INFO [2023-04-18 22:16:10] Clustering beta binomial fits...
INFO [2023-04-18 22:16:15] Assigning (907/50000) variants a clustered beta binomal fit.
INFO [2023-04-18 22:16:20] Processing variants 2900001 to 2950000...
INFO [2023-04-18 22:17:59] Clustering beta binomial fits...
INFO [2023-04-18 22:18:12] Assigning (1350/50000) variants a clustered beta binomal fit.
INFO [2023-04-18 22:18:18] Processing variants 2950001 to 3000000...
INFO [2023-04-18 22:18:18] Position chr2:237139550
INFO [2023-04-18 22:20:21] Clustering beta binomial fits...
INFO [2023-04-18 22:20:39] Assigning (1425/50000) variants a clustered beta binomal fit.
INFO [2023-04-18 22:20:47] Processing variants 3000001 to 3050000...
INFO [2023-04-18 22:22:11] Clustering beta binomial fits...
INFO [2023-04-18 22:22:18] Assigning (1005/50000) variants a clustered beta binomal fit.
INFO [2023-04-18 22:22:25] Processing variants 3050001 to 3100000...
INFO [2023-04-18 22:23:53] Clustering beta binomial fits...
INFO [2023-04-18 22:24:04] Assigning (1252/50000) variants a clustered beta binomal fit.
INFO [2023-04-18 22:24:10] Processing variants 3100001 to 3150000...
INFO [2023-04-18 22:25:16] Clustering beta binomial fits...

**It seems there are some warnings showing like this:**
There were 12 warnings (use warnings() to see them)
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  :
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.

**I can generate the mapping bias for another dataset, but for this one, it got stuck in the middle (at chromosome 2). Is there any suggestions to check the input or solve this problem?
Another question is:  can I run this step using multiple cpus?
Thanks**

**Comment by lima1** [comment]
Hm, can you try again and see if it gets stuck at the same batch? Warnings are benign.

**Comment by hfl112** [comment]
> 

Not the same batch. The first time stuck at chr2, the second time stuck at chr3

**Comment by hfl112** [comment]
> Hm, can you try again and see if it gets stuck at the same batch? Warnings are benign.

Now it stuck at chr1, what weird is it always stuck at 43%

![image](https://user-images.githubusercontent.com/33510929/234081757-4edd240b-856c-46cf-b443-d08f37d56db7.png)

**Comment by lima1** [comment]
Not sure. Any way you can try a different machine before we start debugging? Can you monitor memory usage? I think I tested this on WES data (we're mostly using panels), but possible I messed up somewhere and require too much memory.

**Comment by hfl112** [comment]
> Not sure. Any way you can try a different machine before we start debugging? Can you monitor memory usage? I think I tested this on WES data (we're mostly using panels), but possible I messed up somewhere and require too much memory.

Now I am thinking it's the problem with the memory, so I am testing it with a higher memory limit.
I will posted here if I got further errors 

Thanks

**Comment by hfl112** [comment]
It turns out indeed because of the memory problem. I set the batches to 50000, and run with 20G, and it worked!

**Comment by hfl112** [comment]
Thanks ~

**Comment by lima1** [comment]
I'll put it on my TODO list. It should not need 20GB, I guess.
