### ISSUE TITLE
Snp panel design

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#277]
Hi Markus, 

We're looking at designing a new capture panel for CNV calling. I just wanted to get your advice on the design. You mentioned before that ideally you want a snp per 1mb to improve CNV calling with PureCN. 

1. What depth do you think is reasonable for these?
2. Is it worth including more snps in a finer grain around genes of interest for improved CNV calling?
3. Is it worth reducing snps in areas we care less about and increasing those in chromosomes or regions we care about?
4. Our estimates on the number of extra megabases was around 1-2, just curious if this lines up with your experience.

Thanks!

**Comment by lima1** [comment]
Hi Warren,

I roughly picked SNPs like that:

- POP_AF > 0.3 and < 0.7
- Unique mappability
- GC content also roughly between those percentiles (percentiles of GC values of baits, can't remember the actual GC values)
- Added SNPs from previous panels and WES assay that performed well
- And yes, put as many SNPs as possible close to genes of interest, especially TSG. Homozygous deletions in particular are much easier to call if you have a few SNPs to check for normal AF (if you observe clear drop in coverage, but SNPs are normal, then likely only normal cells are left). 
- In the assay design, I think I went with a 1/3 coverage compared to exons. If it's only for LOH, even 200X is plenty. Higher coverage can give a bit more power in detecting allelic imbalance in super low purity. But that requires a decent number of normal samples to accurately calculate any mapping bias.
- SNPs do not need a lot of space and sequencing is cheap now, so in doubt, add more. I think my latest SNP backbone was about 800kb, I had to trim a bit to give space for lots of introns for heme indications. So 1Mb sounds right for reasonable cost/benefit. 

Hope that helps!

**Comment by waemm** [comment]
Thanks for your reccomendations Markus! From your past experience do you have any indication of how much improvement including a snp array would give to CNV detection (particularly amplifications) in comparison to a standard WES? 

Also, how do you calculate the  800kb ? Is it total snps * average fragment length ?

Thanks again man, really appreciate the insights!

**Comment by lima1** [comment]
800kb was what Agilent calculated, but yes, something like baits size * SNPs.

2 different benefits of SNP backbone:
- A medium sized 2-3Mb panel covers only 0.1% of the genome, filling the gaps allows us to infer the ploidy (average genome copy number) accurately. You can achieve this with off-target reads to some extend, but SNPs provide a more robust signal in addition to allele-specific information. WES provides a sufficient coverage to get ploidy accurate.
- Adding baits around genes of interest. More baits give the segmentation function more signal to find breakpoints (vs dismissing baits as outliers). Usually 7-10 baits should be sufficient to call amplifications reliably, but the more the better, obviously.

**Comment by waemm** [comment]
Thanks man, much appreciated for the insights!
