### ISSUE TITLE
different result when using same sample but with diff reference (of hg19 and hg38)

### ISSUE THREAD

**Issue by nameOnStone** [lima1/PureCN#278]
hi

I have a question,  sample P  use different reference to align -> get bam， VCF(mutect2);  then use pureCN package to get `purity` and `ploidy`,  eg: hg19 an hg38
Q： is there some difference on algorithm， maybe will get difference result?  
eg:

I get one results use `hg19` ref

```
"Sampleid","Purity","Ploidy","Sex","Contamination","Flagged","Failed","Curated","Comment"
"P1_T",0.22,1.99988171373899,"M",0,TRUE,FALSE,FALSE,"NON-ABERRANT;LOW PURITY"
```

anther result use `hg38` ref:

```
"Sampleid","Purity","Ploidy","Sex","Contamination","Flagged","Failed","Curated","Comment"
"P1_T",0.17,1.99878440469478,"M",0,TRUE,FALSE,FALSE,"NON-ABERRANT;LOW PURITY"
```

they are purity `0.05`(0.22-0.17) diff , could you tell me the reason, which result should I belive?

**Comment by lima1** [comment]
NON-ABBERANT means PureCN did not find any copy number alterations it needs to infer purity. Most likely that means the purity is very low (unless you look at heme or pediatric indications).

Feel free to post a complete log file and I make sure everything looks fine.

**Comment by nameOnStone** [comment]
[pureCN.hg19.log](https://github.com/lima1/PureCN/files/11338682/pureCN.hg19.log)

thank your reply, BUT is it enough to explain different result from hg19, hg38? I mean if `No copy number alterations found, purity estimate unreliable.` as said in log,  why have different value in result in hg19 and hg38

**Comment by lima1** [comment]
Yes, it's a stochastic algorithm, and since there is no signal, it's kind of random what you get in this case.

**Comment by nameOnStone** [comment]
how low purity should I belive the result is not random or right? for example: >=20% purity?

**Comment by lima1** [comment]
It's the purity of the sample that's relevant here, not the reported purity. High quality, deep sequencing data >10% (with some caveats, homozygous deletions will be tricky). Poor quality FFPE >= 25%.

The NON-ABBERANT flag is a clear sign that the true purity is very low. 

Have a look at the output PDF, especially the B-allele frequency plot. You will eventually get a clear understanding of the quality of the results. Have a look at our vignettes, paper (as well as the ABSOLUTE paper) for a bit more guidance.
