### ISSUE TITLE
NormalDB.R exits with status 1 when it run for CNVkit

### ISSUE THREAD

**Issue by sleyn** [lima1/PureCN#284]
**Describe the issue**
I'm trying to test PureCN with CNVkit data.
The tutorial suggests to make mapping bias file:

```
Rscript $PURECN/NormalDB.R --out-dir $OUT_REF --normal-panel $NORMAL_PANEL \
    --assay agilent_v6 --genome hg19 --force
```

However if I'm doing this I get exit status: 1.
The file `mapping_bias_hg38.rds` is generated, but if I try to incorporate this step to the pipeline engine it thinks that the script failed.

The reason for exit status 1 is this part from NormalDB.R:

```
if (is.null(opt$coverage_files)) {
    if (is.null(opt$normal_panel)) stop("need --coverage-files.")
    flog.warn("No --coverage-files provided. Skipping normal coverage database generation.")
    q(status = 1)
}
```

Should it be `q(status = 0)` as it is expected to stop script here?

**To Reproduce**
I don't have data to share but to reproduce the issue you should need to execute the command from the tutorial.

**Expected behavior**
Exit with status 0.

**Log file**
There are no errors in the log. If I would not use pipeline engine I would not know that there is anything out of order.

**Comment by lima1** [comment]
Thanks Semion. That's pretty sloppy of me, will make a new devel release tomorrow.

**Comment by lima1** [comment]
Should be fixed now in current devel.
