### ISSUE TITLE
Subsampling SNP data

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#286]
Hi Markus!

We have done some experiments with a large snpbackbone. We are interested in seeing what happens if we subsample the available SNPs to see the effect on segmentation and copy number output. I was just curious if there is a simple way to do this without having to rebuild the PON for instance. As a simple approximation I was thinking of simply removing the SNPS from the VCFs ? I'm not sure if this would work though as we would still get the offtarget coverage. Any suggestions would be appreciated though!!

Warren

**Comment by lima1** [comment]
Hm, if I had to do something like this properly, I would probably generate a BED file with the removed SNPs, add a +/- 200bp padding and remove the reads in those regions from all BAMs. No need to re-run Mutect, just remove the variants in those regions from VCF.  But yes, I would probably recalculate coverages, rebuild the coverage PoN and then re-run PureCN.

**Comment by waemm** [comment]
Thank you Markus! We have taken a look at the data, the extra snps did improve results somewhat in some genes ( although marginally). We didn't have many snps within or around these genes so I imagine the SNPs mostly improved global purity / ploidy estimates.
