### ISSUE TITLE
error/warning with NormalDB.R

### ISSUE THREAD

**Issue by bosmont** [lima1/PureCN#287]
Hi,  I am trying the create a normaldb with the following command:

Rscript /NormalDB.R --out-dir ~/work/WES/PureCN/normalDB --coverage-files ~/work/WES/PureCN/normal_coverages.list --normal-panel ~/work/WES/PureCN/germline_merged.vcf.gz --genome hg38

But I am getting the following:

############
INFO [2023-05-16 09:40:14] Loading PureCN 2.4.0...
INFO [2023-05-16 09:40:15] Creating mapping bias database.
INFO [2023-05-16 09:40:20] Processing variants 1 to 50000...
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  : 
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
WARN [2023-05-16 09:50:55] Could not fit beta binomial dist for chr1:236739260 (alt 73,64,71,47,48,64,49, ref 0,0,0,0,0,0,0, fa 0.487,0.557,0.518,0.547,0.571,0.525,0.57).
INFO [2023-05-16 09:52:19] Clustering beta binomial fits...
INFO [2023-05-16 09:53:27] Assigning (7435/50000) variants a clustered beta binomal fit.
INFO [2023-05-16 09:53:31] Processing variants 50001 to 100000...
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  : 
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
WARN [2023-05-16 09:54:12] Could not fit beta binomial dist for chr2:47161627 (alt 26,29,33,24,23,46,59,25,15,24,20,14,33,26,34,15,19, ref 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, fa 0.565,0.446,0.579,0.6,0.605,0.469,0.551,0.472,0.469,0.632,0.455,0.7,0.579,0.464,0.63,0.385,0.576).
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  : 
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
WARN [2023-05-16 09:54:37] Could not fit beta binomial dist for chr2:68217039 (alt 22,19,14,25,6,16,21, ref 0,0,0,0,0,0,0, fa 0.688,0.594,0.519,0.595,0.207,0.471,0.525).
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  : 
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
WARN [2023-05-16 09:56:26] Could not fit beta binomial dist for chr2:127637302 (alt 41,31,37,13,39,34,43,20,53,28,65,60, ref 0,0,0,0,0,0,0,0,0,0,0,0, fa 0.512,0.443,0.529,0.619,0.459,0.486,0.434,0.364,0.52,0.483,0.556,0.55).
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  : 
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
WARN [2023-05-16 10:00:55] Could not fit beta binomial dist for chr3:20099809 (alt 21,11,11,14,32,18,13, ref 0,0,0,0,0,0,0, fa 0.5,0.407,0.44,0.538,0.444,0.419,0.52).
Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  : 
  could not obtain valid initial values. Try using 'etastart', 'coefstart' or 'mustart', else family-specific arguments such as 'imethod'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
WARN [2023-05-16 10:03:01] Could not fit beta binomial dist for chr3:98264547 (alt 66,76,85,60,141,73,109,90,71,99, ref 0,0,0,0,0,0,0,0,0,0, fa 0.471,0.535,0.528,0.42,0.456,0.474,0.441,0.443,0.399,0.483).
INFO [2023-05-16 10:05:39] Clustering beta binomial fits...
################

the script still runs even with the errors and warnings.  Is this a concern?  Anything I can do to fix the problem?

Thanks so much for your help

**Comment by lima1** [comment]
The ref counts are 0. Do you see why? Is this only happening for those few, or all?

You can open the resulting mapping bias rds file and just plot rho and mu. It should be around 0.49 and 0.1 or so, with noisy regions (high rho, low mu) in between.

**Comment by bosmont** [comment]
[run_normalDB.txt](https://github.com/lima1/PureCN/files/11499792/run_normalDB.txt)
![mu_rho](https://github.com/lima1/PureCN/assets/7282525/bae87f3b-c526-44a7-bd6a-dcbb0ed3908d)

Attached please find here the entire  error message I got when running normalDB.R, also the plot of mu~rho in the mapping bias rds file.  Could you please take a look to see if there is anything wrong in them?  Your kind help is really appreciated.

Best regards,

**Comment by lima1** [comment]
Might be fine, hard to tell with the overplotting though. Can you try:

```
bias <- readRDS("mapping_bias_hg38.rds")
d_f <- data.frame(mcols(bias))
d_f$idx <- seq(nrow(d_f))

md_f <- melt(d_f, id.vars=c("idx", "bias", "mu", "pon.count"))
ggplot(md_f, aes(idx,value, color=pon.count))+geom_point(pch=".")+facet_wrap(~variable, scale="free_y", ncol=1)
```

**Comment by bosmont** [comment]
![rho](https://github.com/lima1/PureCN/assets/7282525/05b54870-6782-4658-ac71-c1ab5c260322)
Here is the plot as you instructed.  Thanks.

**Comment by lima1** [comment]
Ah, sorry, copy paste error, I also need the panel for mu. If that is largely centered around 5, you are good.

This should do it: 
md_f <- melt(d_f, id.vars=c("idx", "bias", "pon.count"))

**Comment by bosmont** [comment]
![mu_rho](https://github.com/lima1/PureCN/assets/7282525/839d2f48-84e5-4356-911b-9f8f146339e4)

Here is the updated plot.  I guess you meant that the mu should be centered around 0.5?  Thanks so much.

**Comment by lima1** [comment]
Yes, looks fine!
