### ISSUE TITLE
Instability purity/ploidy output with same seed

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#288]
Hi Markus,

We're having an issue in one of our samples with purity/ploidy instability, where running the test multiple times results in two possible outcomes occuring at roughly the same frequency ( over a sample of ~ 20 reruns)

"Sampleid","Purity","Ploidy","Sex","Contamination","Flagged","Failed","Curated","Comment"
"X1",0.65,5.05043949141049,"F",0.000322322020896157,TRUE,FALSE,FALSE,"RARE KARYOTYPE"

"Sampleid","Purity","Ploidy","Sex","Contamination","Flagged","Failed","Curated","Comment"
"X1",0.58,4.31649445691918,"F",0.00135930442034594,TRUE,FALSE,FALSE,"POTENTIAL SAMPLE CONTAMINATION"

We have set the seed but this does not seem to help. Is there anything else we can do here? 

We are using the 3rd party CNVkit input and also a relatively old version of PureCN (PureCN 1.22.2), could this be the issue?

Thanks!

**Comment by lima1** [comment]
Potential sample contamination is usually right unless there is a serious issue with artifact filtering (and lots of artifactual SNPs pass through). If you see bands of SNPs close to 0 and close to 1, there is contamination. Sometimes it might fit those bands to a high ploidy solution. Not sure why the seed is not working, I'll look into it.

If you use CNVkit, make sure that SNPs are properly used. Updating PureCN can't hurt.
