### ISSUE TITLE
The distribution of purity

### ISSUE THREAD

**Issue by WangKang-Leo** [lima1/PureCN#290]
I compared the purity result from ABSOLUTE and PureCN, here you can see there are lots of duplicated values (~0.3) in PureCN. How can I optimize the PureCN pipeline?

Here are my code (WES data, Mutect2 + CNVkit results as input)

`# Run PureCN by providing the *.cnr and *.seg files from CNVkit
Rscript $PURECN/PureCN.R --out $OUT/$SAMPLEID \
    --sampleid=$SAMPLEID \
    --tumor $SAMPLEID".converted.cnr" \
    --segfile $SAMPLEID".seg" \
    --mapping-bias-file /proj/sens2022005/nobackup/data/PREDIX_HER2_WES/PureCN/data/mapping_bias_agilent_v6_hg38.rds
    --minpurity 0.1 \
    --max-non-clonal 0.4\
    --rds=rda \
    --sex=F \
    --vcf $SAMPLEID".vcf" \
    --genome hg38 \
    --funsegmentation Hclust \
    --force --postoptimize --seed 123 \
    --cores 16

**Comment by lima1** [comment]
I would need the log file of a good example. For WES, you can also try the GATK copy number pipeline. Or our internal, which is a flavor of GATK.  If you get better results, you might need to tweak CNVkit parameters.

**Comment by WangKang-Leo** [comment]
[UE-2971-1123-0.log](https://github.com/lima1/PureCN/files/11593562/UE-2971-1123-0.log)
Thanks for your reply, can you please have a look at the log file. In order to run PureCN, I have re-run the Mutect2 to include germline mutation. As for CNVkit wraaped in nf-core sarek 3.1.2 pipeline, I almost optimized it in theory, like using bait interval and pool of normal (as reference). Are there any other parameter I should refine within CNVkit?

**Comment by lima1** [comment]
Yes, it doesn't look too bad from the numbers in the log file. Can you also share a screenshot of the B-allele frequency plot in Sampleid.pdf? The one with the 3 panels for SNP allele frequency, log2 ratio and absolute copy number?

If all samples have a high segment count > 400-500, you could/should make the segmentation a bit more stringent by lowering the significance threshold. Also make sure that CNVkit is using SNPs (I'm sure you already do).

**Comment by WangKang-Leo** [comment]
![1685465341430](https://github.com/lima1/PureCN/assets/49832670/99336c3e-085c-40c0-a25b-3da8505668ec)
Hello, here you can see there are lots of segments. There ~300 segment count per sample for current run. I tried the call.cns data from CNVkit, ~100 segment per samples, which also output lot of same purity value (~0.3).

BTW, I failed to use --mapping-bias-file, because pon from Mutect2 is not fit to NormalDB.R process.....

**Comment by lima1** [comment]
Hmmm, this looks pretty bad. Might be indeed an over-segmentation issue. The log ratio looks clean, so it's not a data quality issue.

For mapping bias, you either need to install the genomicsdb R package from GitHub (or if you can use Docker, use the latest Docker image that has it installed) to read the genomicsdb in Mutect2 or create a multi-sample VCF of all Mutect2 normal sample VCFs. I don't think that's the main issue here, although it can confuse the likelihood model. I always recommend people to run our best practices for tests when setting it up even with other copy number tools. If our internal normalization and segmentation looks better, you might see how to tweak your CNVkit pipeline.

**Comment by WangKang-Leo** [comment]
Thanks for your kind suggestions, I have optimize the bin size of CNVkit, but the purity values from PureCN are identical....Here is a parameter from CNVkit segmentation process:
`Segmentation methods
The following segmentation algorithms can be specified with the -m option:

cbs – the default, circular binary segmentation (CBS). This method performed best in our benchmarking on mid-size target panels and exomes. Requires the R package DNAcopy.
haar – a pure-Python implementation of [HaarSeg](http://webee.technion.ac.il/people/YoninaEldar/Info/software/HaarSeg.htm), a wavelet-based method. Very fast and performs reasonably well on small panels, but tends to over-segment large datasets.
hmm (experimental) – a 3-state Hidden Markov Model suitable for most samples. Faster than CBS, and slower but more accurate than Haar. Requires the Python package pomegranate, as do the next two methods.
hmm-tumor (experimental) – a 5-state HMM suitable for finer-grained segmentation of good-quality tumor samples. In particular, this method can detect focal amplifications within a larger-scale, smaller-amplitude copy number gain, or focal deep deletions within a larger-scale hemizygous loss. Training this model takes a bit more CPU time than the simpler hmm method.
hmm-germline (experimental) – a 3-state HMM with fixed amplitude for the loss, neutral, and gain states corresponding to absolute copy numbers of 1, 2, and 3. Suitable for germline samples and single-cell sequencing of samples with mostly-diploid genomes that are not overly aneuploid.
none – simply calculate the weighted mean log2 value of each chromosome arm. Useful for testing or debugging, or as a baseline for benchmarking other methods.`  

Should I selet the "none" in CNVkit? I will try to run your best practices......
