### ISSUE TITLE
Error in segmentByPairedPSCBS.default: All genotypes ('muN') are NAs

### ISSUE THREAD

**Issue by leap-ahead225** [lima1/PureCN#291]
Hello,

I'm encountering an issue while running a pipeline that uses the segmentByPairedPSCBS.default function. The error message I receive is:

INFO [2023-05-31 23:29:25] ------------------------------------------------------------
INFO [2023-05-31 23:29:25] PureCN 2.6.1
INFO [2023-05-31 23:29:25] ------------------------------------------------------------
INFO [2023-05-31 23:29:25] Arguments: -tumor.coverage.file /mnt/nas/PureCN/TAS/tumors/001_AMU-001_CIS_coverage.txt.gz -log.ratio  -seg.file  -vcf.file /mnt/nas/PCGAv3/torrentvcf/001_AMU-001_CIS_IonXpress_050_dbsnp.vcf.gz -genome hg19 -sex F -args.setPriorVcf 6 -args.setMappingBiasVcf /mnt/nas/Reference/mapping_bias_pcga_v3_hg19.rds -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid 001_AMU-001_CIS -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file /mnt/nas/Reference/baits_hg19_intervals.txt -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model betabin -post.optimize TRUE -log.file PureCN/001_AMU-001_CIS/001_AMU-001_CIS.log -normal.coverage.file <data> -normalDB <data> -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2023-05-31 23:29:25] Using BiocParallel for parallel optimization.
INFO [2023-05-31 23:29:25] Loading coverage files...
INFO [2023-05-31 23:29:25] Mean target coverages: 4537X (tumor) 4541X (normal).
INFO [2023-05-31 23:29:25] Removing 2 low/high GC targets.
INFO [2023-05-31 23:29:25] Removing 14 intervals excluded in normalDB.
INFO [2023-05-31 23:29:25] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2023-05-31 23:29:25] Using 460 intervals (460 on-target, 0 off-target).
INFO [2023-05-31 23:29:25] No off-target intervals. If this is hybrid-capture data, consider adding them.
INFO [2023-05-31 23:29:25] AT/GC dropout: 1.18 (tumor), 1.18 (normal), 1.00 (coverage log-ratio). 
INFO [2023-05-31 23:29:26] High GC-bias in normal and/or tumor coverage.
INFO [2023-05-31 23:29:26] Loading VCF...
INFO [2023-05-31 23:29:26] Found 47 variants in VCF file.
INFO [2023-05-31 23:29:26] Removing 7 triallelic sites.
INFO [2023-05-31 23:29:27] 35 (87.5%) variants annotated as likely germline (DB INFO flag).
INFO [2023-05-31 23:29:27] 001_AMU-001_CIS is tumor in VCF file.
INFO [2023-05-31 23:29:27] 0 homozygous and 2 heterozygous variants on chrX.
INFO [2023-05-31 23:29:27] Sex from VCF: F (Fisher's p-value: 0.179, odds-ratio: 0.00).
INFO [2023-05-31 23:29:27] Removing 3 low quality variants with non-offset BQ < 25.
INFO [2023-05-31 23:29:27] Global base quality score of 49
INFO [2023-05-31 23:29:27] High median base quality score (49). UMI-barcoded data?
INFO [2023-05-31 23:29:27] Minimum number of supporting reads ranges from 2 to 4, depending on coverage and BQS.
INFO [2023-05-31 23:29:28] Initial testing for significant sample cross-contamination: maybe
INFO [2023-05-31 23:29:28] Removing 18 variants with AF < 0.030 or AF >= 0.970 or insufficient supporting reads or depth < 15.
INFO [2023-05-31 23:29:41] Removing 0 blacklisted variants.
INFO [2023-05-31 23:29:41] Total size of targeted genomic region: 0.11Mb (0.14Mb with 50bp padding).
INFO [2023-05-31 23:29:41] 3.9% of targets contain variants.
INFO [2023-05-31 23:29:41] Removing 2 variants outside intervals.
INFO [2023-05-31 23:29:42] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2023-05-31 23:29:42] Loading mapping bias file mapping_bias_pcga_v3_hg19.rds...
INFO [2023-05-31 23:29:44] Found 1436959 variants in mapping bias file.
INFO [2023-05-31 23:29:44] Imputing mapping bias for 0 variants...
INFO [2023-05-31 23:29:45] Excluding 6 novel or poor quality variants from segmentation.
INFO [2023-05-31 23:29:45] Excluding 0 variants not in pool of normals from segmentation.
INFO [2023-05-31 23:29:45] Sample sex: F
INFO [2023-05-31 23:29:45] Segmenting data...
INFO [2023-05-31 23:29:45] Interval weights found, will use weighted PSCBS.
INFO [2023-05-31 23:29:45] MAPD of 11 allelic fractions: 0.02 (0.04 adjusted).
INFO [2023-05-31 23:29:45] Very clean log-ratios, will increase default undo.SD parameter by a factor of 2.0.
INFO [2023-05-31 23:29:45] Setting undo.SD parameter to 1.000000.

Error in segmentByPairedPSCBS.default(CT = CT, thetaT = thetaT, thetaN = thetaN):
All genotypes ('muN') are NAs: 1 (100%) out of 1
In addition: Warning message:
In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
Execution halted

This error occurs during the execution of the runAbsoluteCN function. I'm using data that has been sequenced on an Ion Torrent sequencer and analyzed using a Target Amplicon Sequencing approach.

I've checked my input data and it seems to be in the correct format, but I'm still encountering this issue. Could you please help me understand what might be causing this error and how I might resolve it?

Thank you in advance for your assistance.

**Comment by lima1** [comment]
Hi @leap-ahead225 . Unfortunately PureCN does require quite a larger panel than yours. You can try the default dnacopy segmentation which does not require SNPs. That should give you at least good coverage normalization and segmentation. But don't expect purity and ploidy being reliably estimated. I assume the error happens because no variant is provided in certain chromosomes (you only have 11 passing filtering it seems).

**Comment by leap-ahead225** [comment]
Hi @lima1 

Thank you very much for your prompt and detailed response.  I appreciate your suggestion to try the default dnacopy segmentation, and I understand that this might not provide reliable estimates for purity and ploidy.

Your explanation about the error makes sense, and I will look into the filtering of variants in my data. I appreciate your help in troubleshooting this issue.

Thank you again for your time and assistance.
