### ISSUE TITLE
callAlterations always outputs first solution

### ISSUE THREAD

**Issue by un-saku** [lima1/PureCN#292]
Hi,

Thank you for providing the great tool.

We can specify ID of solution in callAlterations function, but it seems to report first solution regardless of the specified ID. This is probably caused by the code below, which retrieve first solutions.
At row 54 of callAlterations.R
calls <- res$results[[1]]$gene.calls

I'm sorry if I misunderstood something.

**Comment by lima1** [comment]
Thanks @un-saku , looks indeed like a bug, will fix soon. Thanks for reporting!
