### ISSUE TITLE
Question - command to use with GATK panel of normals

### ISSUE THREAD

**Issue by akaviaLab** [lima1/PureCN#293]
**Describe the issue**
Hi.
We've been using Mutect2 to generate VCFs, which are merged by `bcftools  merge -O z -o` into one merged VCF file.
When running PureCN NormalDB.R, we've been using `--normal_panel merged.VCF.gz`
We're also creating a Genomics DB `gatk GenomicsDBImport` on all the unmerged files to use as gatk Panel of normals.

Should we run `NormalDB.R --normal_panel $GENOMICSDB-WORKSPACE-PATH/pon_db` or is this equivalent to using the merged.VCF? If not equivalent, what are the differences between the two commands please?

Thank you,

Uri David

**Comment by lima1** [comment]
Hi Uri,

I'm using GenomicsDB and it works well. There is an issue with VCFs (not GenomicsDB) and tri-allelic sites which is not 100% fixed (
https://github.com/lima1/PureCN/issues/52). It has very minimal impact, but that should be the only difference. 

Getting genomicsdb R installed is a bit of a pain. I will update the Docker image soon, but the old image should work fine with all recent GATK versions. Haven't tested the very latest one though.

Markus
