### ISSUE TITLE
Potential input for phylogenic analyses

### ISSUE THREAD

**Issue by WangKang-Leo** [lima1/PureCN#294]
I want to use allele specific copy number of multiple samples for phylogenic analyses, like PycloneIV, PhylogenicNDT. But I found the loh.csv file have some NA values on "M" column (minor copy number). Here I attached my LOH results.
[sample1_LOH.txt](https://github.com/lima1/PureCN/files/11712610/sample1_LOH.txt)

**Comment by lima1** [comment]
Have a look at the num.snps column. You need them for getting the allele-specific copy numbers. Make sure there is no significant over-segmentation to get as much calling as possible.

Happy to take a tutorial here if you are successful!

**Comment by WangKang-Leo** [comment]
Happy to contribute if I repaet my previous analyses based on PureCN output, but how to avoid over-segmentation?  Otherwise I have to ignore those segments without snp. Can you give me some hints...

**Comment by lima1** [comment]
Not saying it is over-segmented! If you follow our best practices, you should be all good. You can set segmentation parameters more aggressively when you expect high purity samples (e.g. lower --alpha), although PureCN attempts to do that already to some extend (see undo.sd messages in the log file). At least when you use our PSCBS segmentation. GATK's copy number is also very conservative in setting breakpoints. 

The cleaner your data, the easier it is for the segmentation function. If you follow the guidance in the vignettes, again, you should be good.

**Comment by WangKang-Leo** [comment]
Okay, I running the PureCN best practice from scratch as you recommended, and will let you know soon.
