### ISSUE TITLE
Strange notation in _genes.csv

### ISSUE THREAD

**Issue by Jongseong-Ahn** [lima1/PureCN#298]
I am using the output of CNVkit as pureCN input, and recently found the following problem in _genes.csv.
_______________
MRDBR-074,OR4F3,chr1,450740,181368225,2,NA,-0.351381147174662,1,6,-0.30202443974233,-0.33964643974233,-0.22678043974233,FALSE,20,NA,371,1,FALSE,FALSE
MRDBR-074,OR4F16,chr1,450740,181368225,2,NA,-0.351381147174662,1,6,-0.30202443974233,-0.33964643974233,-0.22678043974233,FALSE,20,NA,371,1,FALSE,FALSE
MRDBR-074,OR4F29,chr1,450740,181368225,2,NA,-0.351381147174662,1,6,-0.30202443974233,-0.33964643974233,-0.22678043974233,FALSE,20,NA,371,1,FALSE,FALSE
___________
It contains pretty much most of chr1, which is very strange.
I checked .cnr, the output of CNVkit, which becomes the input.
___________
chr1	450739	451208	OR4F3,OR4F16,OR4F29	0.230672	271.296	0.785925
chr1	451208	451678	OR4F3,OR4F16,OR4F29	0.207457	565.611	0.567737
chr1	685715	686184	OR4F3,OR4F29,OR4F16	0.237672	262.896	0.844498
chr1	686184	686654	OR4F3,OR4F29,OR4F16	0.217322	573.151	0.550964
chr5	181367286	181367755	OR4F16,OR4F29,OR4F3	0.220797	567.045	0.602314
chr5	181367755	181368225	OR4F16,OR4F29,OR4F3	0.184312	253.955	0.810909
________________
It seems to me that pureCN is using the start position of chr1 and the end position of chr5 of the gene.
I've been trying to find an option to isolate this but couldn't figure it out.
Is there any way to isolate this?
As a result of checking, more genes show this pattern than expected.
I think they should be separated by position, at least if they are on different chromosomes.
If the feature is already implemented, can you tell me how to handle it?

I enter the command as follows
(This is the part of the shell script that receives the variable from earlier)
______________________
Rscript ${pureCN}/PureCN.R --out ${output_dir} \\
--sampleid ${donor} \\
--tumor ${output_dir}/${donor}.cnr \\
--seg-file ${output_dir}/${donor}.seg \\
--vcf ${PBMC_vcf} \\
--snp-blacklist ${blacklist} \\
--genome hg38 \\
--fun-segmentation Hclust \\
--base-quality-offset 0 \\
--force --post-optimize --seed 765

**Comment by lima1** [comment]
Thanks, happens here: https://github.com/lima1/PureCN/blob/devel/R/PureCN-internal.R#L596-L606

I think this slipped through the radar because in my interval annotation, I try to find the most likely gene that was targeted in the assay design, so I get way fewer intervals with multiple genes. Will fix ASAP.

**Comment by lima1** [comment]
I think I fixed it in branch issue_298. Unfortunately the design requires unique symbols as they are used as rownames, so I had to add suffices for such multiple chromosome symbols. Would suggest changing the annotation to current, approved HUGO symbols only.

**Comment by Jongseong-Ahn** [comment]
I checked my annotation file according to your comments. I used refFlat in the annotations, But it doesn't seem to reflect the latest genomic references.
https://groups.google.com/a/soe.ucsc.edu/g/genome/c/SIS3Weqx9bA
I'll consider other annotation alternatives.
Thank you for your quick response.

**Comment by lima1** [comment]
Just to be clear, it should work now (now merged to the devel branch). But annotating with approved signals is probably a good idea to avoid lots of overlapping gene calls of likely little interest.
