### ISSUE TITLE
Dimension of Tangent Normal Projection

### ISSUE THREAD

**Issue by artuuge** [lima1/PureCN#300]
I was wondering, what is the motivation behind the choice of the default value num.eigen=20 in processMultipleSamples() function, i.e. the dimension of the tangent normal projection? Is there some informal rule which allows to choose this number depending on the size of the pool of normals, and the total number of targets? In my case, the available pool size is 22, and the number of targets is around 150_000.

**Comment by lima1** [comment]
You can play with it and check the impact. I can't remember if this was a default in GATK (seems like now the default is to use all) or if I picked it up here: https://academic.oup.com/bioinformatics/article/38/20/4677/6678978. 20 still seems like a good compromise of removing most noise and not too much overfitting to the PoN.

**Comment by lima1** [comment]
So if you expect your normal samples being very similar to your tumor samples, you can increase the value (although 20 vs 22 probably does not change much). Also probably worth checking if the explicit GC normalization is making things worse - usually the first eigen samples are associated with GC bias.

If you expect your normals being very different, like hiqh quality blood vs poor quality FFPE, you might check that decreasing num.eigen and/or adding GC normalization leads to lower noise and better segmentations.

**Comment by artuuge** [comment]
Thank you for clarifying this. The normal samples in my case seem to be quite similar, so the extracted log-ratio signal for the tumor samples does not vary much w.r.t. the projection dimension.
