### ISSUE TITLE
Inconsistent VCF File Validation Request for Utilizing pureCN with MuTect

### ISSUE THREAD

**Issue by DimitrisGrig** [lima1/PureCN#301]
Issue Description:
We are currently working on utilizing pureCN with MuTect, but we have encountered inconsistencies with our VCF files. To ensure the accuracy and reliability of our analysis, we are seeking assistance to validate our VCF files.

Request:
We kindly request guidance or suggestions on how to validate our VCF files effectively and transform them in pureCN friendly format. Any insights or recommended tools for validating VCF files would be greatly appreciated.

**Error log:**
`
WARN [2023-06-28 08:00:30] Allosome coverage missing, cannot determine sex.
WARN [2023-06-28 08:00:30] Allosome coverage missing, cannot determine sex.
[W::bcf_hrec_check] Invalid tag name: "."
[W::bcf_hrec_check] Invalid tag name: "."
WARN [2023-06-28 08:00:35] VCF contains both DB and POPAF INFO fields. Will ignore POPAF.
Error in if (sum(idx)) { : the condition has length > 1
Calls: runAbsoluteCN -> .readAndCheckVcf
In addition: Warning message:
In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
Execution halted
`

Thank you for your support!

**Comment by lima1** [comment]
Hi @DimitrisGrig . The DB info field only contains NAs. The referenced commit now ignores DB when it only contains NAs. So either update with BiocManager::install("lima1/PureCN", ref = "issue_301") or delete the flag from the VCF.

Will merge the branch in a few days to the devel branch in case it does not exist when you try to install.
