### ISSUE TITLE
mpileup vcf error DB info field

### ISSUE THREAD

**Issue by kristianunger** [lima1/PureCN#302]
When I call variants using the mpileup workflow and annotate my vcfs using annovar using the databases refGene,cytoBand,exac03,avsnp147,dbnsfp30a,cosmic92_noncoding,cosmic92_coding and run

Rscript $PURECN/PureCN.R --out $OUT/$SAMPLEIDOUT \
--tumor $covout/${SAMPLEID}_coverage_loess.txt.gz \
--sampleid $SAMPLEID \
--funsegmentation PSCBS \
--vcf $INPUT_VCF \
--normaldb $normal_db/normalDB_agilent_v6_hg38.rds \
--intervals $baits \
--snpblacklist $srr \
--genome hg38 \
--postoptimize \
--force --seed 123 \
--modelhomozygous True \
--minpurity=0.75\
--parallel TRUE \
--cores=4

I get the error:

Error: vcf.file has no %s or %s info field for membership in germline
databases.DBPOP_AF

This is most likely a user error due to invalid input data or
parameters (PureCN 1.22.2).

Any suggestion how to fix this?

Everything works well with Mutect2-derived vcfs - but I want to use Mpileup here since its cell lines.

**Comment by lima1** [comment]
Thanks @kristianunger. The error message is wrongly formatted (will fix soon), but this simply means it cannot figure out how to label germline variants. You can use --db-info-flag or --popaf-info-field to either provide a binary flag (present in germline database and most likely SNP) or the population allele frequency.

Also make sure --cosmic-cnt-info-field matches your annotation to set priors for hotspots, which is important for cell lines as mono-clonal somatic vs germline classification is difficult.

**Comment by lima1** [comment]
Also consider updating to latest stable version.

**Comment by kristianunger** [comment]
Thanks! That helped!
