### ISSUE TITLE
Error in PureCN Integration with Nextflow: misalignment between tumor coverage file and normalDB

### ISSUE THREAD

**Issue by aldosr** [lima1/PureCN#303]
Hi Markus,
We are currently working on integrating PureCN with Nextflow and, in particular, with nf-core tools.

In particular, to ensure reproducibility, we used the toy datasets present in repo: https://github.com/lima1/PureCN/tree/devel/inst/extdata

These datasets have proven to work smoothly for PureCN/Coverage, PureCN/Intervalfile, and PureCN/NormalDB operations, as evidenced by this successful example: https://github.com/nf-core/modules/pull/3127

However, when building the test workflow for PureCN/run, the pipeline raises the following error:

`Error: tumor.coverage.file and normalDB do not align.`

To construct the test workflow, we employed the file `ex1.bam` for generating the coverage file, utilized the `ex1_intervals.txt` file as the interval file, and employed the files `example_normal.txt.gz` and `example_normal2.txt.gz` to build the normalDB.

Is there a known solution to resolve this misalignment issue? Alternatively, should we consider avoiding the use of the toy datasets altogether?

**Comment by lima1** [comment]
Hi @aldosr,

there is unfortunately no BAM file for the toy example. In hindsight, I should have simulated BAMs, but this is based on simulated coverage. The BAM file here is only used for tests and examples.

So this error message simply says the normalDB and tumor coverage are based on different intervals. 

Markus

**Comment by aldosr** [comment]
Thanks for the quick response Markus.

I believe using simulated BAMs is a viable alternative since these simulated BAMs would serve the purpose of running the test workflow on the nf-core pipeline. I can generate them using BAMsurgeon and I'll let you know if they work!

**Comment by aldosr** [comment]
Solved using the stub in the nf-core pipeline. I'll close the issue, thanks Markus!
