### ISSUE TITLE
How to extract BAF from PureCN output files, which file to use ?

### ISSUE THREAD

**Issue by lmanchon** [lima1/PureCN#306]

**Comment by lima1** [comment]
Have a look at section 6 in the vignette that lists the output files. https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/PureCN.pdf

In particular 6.2.1 lists the allelic fraction (or ratio) in the column AR. ML.AR is the expected fraction for the most likely state. AR.ADJUSTED is what is used in the likelihood model, adjusted for any non-reference mapping bias.

**Comment by lmanchon** [comment]
yes, but the field ML.AR appear only in _variants.csv file,
i use the _dnacopy.seg file to get the CNV and in this file i haven't BAF field linked to the CNV.

**Comment by lima1** [comment]
You could use the _loh.csv file? Otherwise it should be relatively easy to merge the files, based on seg.id for example.
