### ISSUE TITLE
Question: testing additional SNPS

### ISSUE THREAD

**Issue by akaviaLab** [lima1/PureCN#309]
**Describe the issue**
We've been working on a capture kit that has coverage for WES, plus regions that we are more interested in. It turns out our capture kitS are missing some sections, so we decided to add a third one.
Due to prodcution issues when buying them, we can't just get one capture kit that will have all regions.

We're trying to run the same samples with spiking in the NEW capture kit at different attempted coverage levels - 0, 10, 25, 50, 100. The samples we are planning to run include 7 cancer samples, and one normal sample as a control.

The goal is to see which concentration/dilution of the NEW capture kit improves our results, comparing to other methods of ascertaining copy number on these samples.

Problem - we don't have a PON using the NEW capture kit. We only have PON samples using the previous two (combined).
After figuring out the optimal concentration, we will make a PON using more samples and use it going forward.

First question - do we need a PON? Opinions are divided - I think we need a PON of some samples (minimum 4). Do we need a PON? Is there a minimum number of samples considering we're doing 8 samples in total?
Second question - What will we be able to tell from this experiment with or without PON?
Third question - assuming we can only do one concentration of NEW capture kit spike in for the PON (which is what we've been discussing with the lab people), is there a best concentration of spike in to use?

I'm sorry about bombarding you with questions, but you've been super helpful, and I hope you ran into something similar.

Thank you,

Uri David

**Comment by lima1** [comment]
Hmm, we always design our own kit, never had to deal with a situation like this. As long as the normal controls are the same in regards to lab protocols, you should be fine. The more variance in the lab, the more normal samples I recommend. The normalization essentially removes the variance observed in normal samples.

Internally, we support two independent bait sets. Originally meant for on- and off-target. They are normalized independently and then aligned.  You don't need off-target for WES. I.e., you could label the new set as off-target if you want to normalize independently.

Yes, PoN is absolutely required. The more, the merrier. Same for coverage. Plateau can be reached quickly, but depends on many factors. You can always add more normals over time. This again catches more variance in the lab.

Try with and without explicit GC normalization. The PoN can sometimes do a better job at removing GC bias.
