### ISSUE TITLE
Question regarding the vcf output

### ISSUE THREAD

**Issue by mkyriak** [lima1/PureCN#312]
Hello,

I have a question about the `--out-vcf` flag when running `PureCN`. Does the output `vcf` contain only somatic variants?
After I used this flag, I got germline and somatic variants too.

Thank you in advance for your time and reply!

**Comment by lima1** [comment]
Yes, it contains all variants, but you can find INFO fields with the classification results. See section 6.2.1 in https://bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/PureCN.pdf

**Comment by mkyriak** [comment]
Thank you, I checked the output `vcf` and I am getting only a subset of the somatic variants (not all of them), but I am also getting hits from the `panel_of_normals` and `germline` variants. Is this correct?

The initial `vcf` I used to run `PureCN` was generated after running multi-sample `Mutect2` and following their best practices, although, I used `gnomad` as panel of normals because I don't have any matching normals for my samples.

I am running `PureCN == 2.6.4` using a `conda` environment (`Python 3.11.4`).

**Comment by lima1** [comment]
Yes, due to an unfortunate initial design mistake, all filtered variants are removed, not flagged and internally ignored.  The log file is detailed in which filters are applied and how many variants are affected. We need germline variants for copy number calling, so yes, they are included and annotated as such.

**Comment by mkyriak** [comment]
I see, thank you., this makes sense. I also checked the `log` file and I saw the number of the variants removed and the reason.
