### ISSUE TITLE
Error creating NormalDB from GATK CreateSomaticPanelOfNormals output

### ISSUE THREAD

**Issue by Moe94** [lima1/PureCN#315]
Hi Markus, 

so first of all thank you for providing such a valuable tool to the community. I am currently trying to create the normal reference. To create this I used GATK CreateSomaticPanelofNormal function following the instructions of GATK. I am using your newest docker image, running it with apptainer like this: 

```
BASE_DIR="/ptmp/gref/data/results_pMCL_twist/variant_calling/purecn"
PURECN_NORMAL="/opt/PureCN/NormalDB.R"
OUT_REF="/ptmp/gref/data/results_pMCL_twist/variant_calling/purecn"
NORMAL_PANEL="/ptmp/gref/data/wes/refractory/normals/pon_db/pon.vcf.gz"

#Create pureCN Normal Reference
apptainer run  --bind /ptmp/gref/data/:/ptmp/gref/data/ /u/graefm/software/purecn.sif Rscript $PURECN_NORMAL --out-dir $OUT_REF --normal-panel $NORMAL_PANEL \
    --assay twist --genome hg19 --force
```
    
Which gives me this error 
```
INFO [2023-08-17 11:26:22] Loading PureCN 2.6.4...
INFO [2023-08-17 11:26:22] Creating mapping bias database.
INFO [2023-08-17 11:26:23] Processing variants 1 to 50000...
FATAL [2023-08-17 11:26:23] The normal.panel.vcf.file contains only a single sample.

FATAL [2023-08-17 11:26:23]

FATAL [2023-08-17 11:26:23] This is most likely a user error due to invalid input data or

FATAL [2023-08-17 11:26:23] parameters (PureCN 2.6.4).

Error: The normal.panel.vcf.file contains only a single sample.

This is most likely a user error due to invalid input data or
parameters (PureCN 2.6.4).
In addition: Warning message:
In .vcf_usertag(map, tag, nm, verbose) :
  ScanVcfParam 'geno' fields not found in  header: 'AD'
Execution halted

```
This has been discussed before, the problem is that the PON normal does not contain sample ids. The files can still be used if GenomicsDB-R is installed, which also comes along with your docker image. The set up worked fine, no errors, no warnings and I can find all files in /opt/GenomicsDB. What could be the issue here? 

Thanks for your help! 

Best, 
Moritz

**Comment by lima1** [comment]
The output of both GenomicsDB and VCF in NormalDB is a mapping bias RDS file. If you got one from GenomicsDB, you are all good.

**Comment by Moe94** [comment]
Thanks for your quick reply, Markus! Sorry, I think my question might have been a little bit confusing. Within /opt/GenomicsDB within the docker image, there are all the necessary files, meaning the setup of the docker image should have worked. The output folder is still empty, there are no RDS files.

**Comment by lima1** [comment]
Got it. Can you provide a bit more information about the failed GenomicsDB attempt? At least the command line and log output of NormalDB. Is this the linux/amd64 image? I haven't fully tested the arm one yet.

**Comment by Moe94** [comment]
This is the linux/amd64 yes. Sorry, the only log file I can generate is the one posted: 

```
:~/scripts/wes/purecn> cat apptainer-log.txt
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
During startup - Warning message:
Setting LC_CTYPE failed, using "C"
INFO [2023-08-17 19:44:20] Loading PureCN 2.6.4...
INFO [2023-08-17 19:44:21] Creating mapping bias database.
INFO [2023-08-17 19:44:21] Processing variants 1 to 50000...
FATAL [2023-08-17 19:44:21] The normal.panel.vcf.file contains only a single sample.

FATAL [2023-08-17 19:44:21]

FATAL [2023-08-17 19:44:21] This is most likely a user error due to invalid input data or

FATAL [2023-08-17 19:44:21] parameters (PureCN 2.6.4).

Error: The normal.panel.vcf.file contains only a single sample.

This is most likely a user error due to invalid input data or
parameters (PureCN 2.6.4).
In addition: Warning message:
In .vcf_usertag(map, tag, nm, verbose) :
  ScanVcfParam 'geno' fields not found in  header: 'AD'
Execution halted
```

How can I get more information about the run?

**Comment by lima1** [comment]
You would provide the genomicsDB path in NormalDB.R --normal-panel pon_db (the path you specified in  --genomicsdb-workspace-path). It's essentially a replacement for CreateSomaticPanelOfNormals. It's doing similar things, but more, so the output of it is not sufficient and we need to start from the genomicsDB or a mult-sample VCF.

**Comment by Moe94** [comment]
Sorry, I seem to have misunderstood the documentation. Using the GenomicsDB created by GATK GenomicsDB Import (step 2) worked completely fine. I have used the .vcf file created by CreateSomaticPanelOfNormals. Thanks for your help, Markus!
