### ISSUE TITLE
pureCN output genes.csv vs loh.csv

### ISSUE THREAD

**Issue by hfl112** [lima1/PureCN#318]
Hi developers,
I've been curious trying to get the major CN and minor CN from the output, but both genes ouput and loh ouput have the "C" and "M" columns, so which file should I consider.
I saw something comments online, said "segment of LOH is more robust" is this correct?
Any comments about this will be appreciated
Thanks
Funan

**Comment by lima1** [comment]
C is the total copy number, M is the minor allele-specific copy number. Minor + Major = Total. 

Not sure what the robustness refers to. The larger the segment (number of SNPs), the more robust the LOH call. Therefore it's important to make the segmentation as clean as possible. That means reducing noise by using the best pool of normals that feasible, optimizing off-target reads, using the baits locations, not exon locations, balancing sensitivity and specificity of segmentation (too aggressive segmentation results in over segmentation and thus short segments).

Hope that helps and answers your question.
