### ISSUE TITLE
Encountering error while  running preprocessIntervals function

### ISSUE THREAD

**Issue by gagank4911** [lima1/PureCN#319]
>extdata<-setwd("C:/Users/gagan.kumar/")
> library(PureCN)
> intervals <- import("C:/Users/gagan.kumar/bedfile.bed")
> preprocessIntervals(intervals,"C:/Users/gagan.kumar/Homo_sapiens_assembly38.fasta", output.file = "ex2_gc_file.txt")
WARN [2023-09-04 18:40:17] Found 70970 overlapping intervals, starting at line 37.
WARN [2023-09-04 18:40:18] Target intervals were not sorted.
INFO [2023-09-04 18:41:42] Splitting 2513 large targets to an average width of 400.
WARN [2023-09-04 18:41:42] No mappability scores provided.
WARN [2023-09-04 18:41:42] No reptiming scores provided.
INFO [2023-09-04 18:41:42] Calculating GC-content...
[E::faidx_fetch_seq2] Failed to retrieve block. (Seeking in a compressed, .gzi unindexed, file?)
Error in value[[3L]](cond) : 
   record 1742 (chr14:23182954-23183343) failed
  file: C:/Users/gagan.kumar/Homo_sapiens_assembly38.fasta

i have even create .gzi file using bgzip -i Homo_sapiens_assembly38.fasta command

**Comment by lima1** [comment]
Hi, can you try samtools to index the fasta?

http://www.htslib.org/doc/samtools-faidx.html

**Comment by gagank4911** [comment]
i did create the index using samtools  but still getting the same error

**Comment by lima1** [comment]
So it works for all lines until 1742:  chr14:23182954-23183343 ?

Anything work with this particular region? Not sure if using a wrong genome version would throw this warning, but your bedfile is hg38?

**Comment by gagank4911** [comment]
yes my bed file is hg 38
