### ISSUE TITLE
Error in sapply(px.rij, sum, na.rm = TRUE) + log(prior.purity.local)

### ISSUE THREAD

**Issue by andrewrech** [lima1/PureCN#32]
See #29 for hardware and session info. I am able to consistently reproduce this error without setting a seed.

* [log](https://s3.amazonaws.com/rech-ul-1/ac550750-116a-4ef2-a369-02cf8c1a3561_H_38_GOAL_38_NA_667544-574-462-9644-39231_TN_M_R_E_T_mc-15.ip-50.mbq-25.tp-04.tc-7.mp-6.mnc-01.pcn.log)

### ERROR

```
Error in sapply(px.rij, sum, na.rm = TRUE) + log(prior.purity.local) :
  non-numeric argument to binary operator
```

* [tw (txt)](https://s3.amazonaws.com/rech-ul-1/69487124-e945-48b7-a9b6-d7852a129123_Homo_sapiens_assembly38_GOAL_hg38_probes_chr_NA_removed_tw.txt)
* [tcov (txt)](https://s3.amazonaws.com/rech-ul-1/fd1b4555-3c16-4586-82a8-d95b69237ef5_Homo_sapiens_assembly38_GOAL_hg38_probes_chr_NA_removed_6e6754c4-d574-46a2-9644-dd3f92cd31ec_TN_M_R_xE_T_dna_rg_br_loess.txt)
* [ncov via calculateTangentNormal (rds)](https://s3.amazonaws.com/rech-ul-1/08c66a3b-4ff5-4e97-a1a1-1caca7874bc8_best_nl_error.rds)
* [normal.panel.vcf.file via calculateMappingBiasVcf (rds)](https://s3.amazonaws.com/rech-ul-1/166d6def-3f22-410c-b63b-e59023a4df26_artfdet_comb5.vcf.rds)
* [bed via import (rds)](https://s3.amazonaws.com/rech-ul-1/47f0cdd1-0d40-44c4-bc8c-ab1f2a8d9814_error_bed_example.rds)
* [vcf (rds)](https://s3.amazonaws.com/rech-ul-1/ff8ed56f-af2f-4485-b306-188a080357c9_error_example_vcf.rds)
* [normalDB (rds)](https://s3.amazonaws.com/rech-ul-1/b5c5a19a-28d4-4e1d-88d3-4bc0518020da_normaldb_error_example.rds)

Thanks a lot as always!

Andrew

**Comment by lima1** [comment]
Hi Andrew, I can't access the files. 

```
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2018-05-10T19:36:40Z</Expires>
<ServerTime>2018-05-10T23:42:14Z</ServerTime>
<RequestId>027C277032407DFA</RequestId>
<HostId>
6PfGC6f0SFxH8wtEEInJ68XuqbZRZl+TmAsEMJGsimMb0/OUg48vUkZHFsITZ/OBURFZ+U1cM8I=
</HostId>
</Error>
```

**Comment by andrewrech** [comment]
Sorry, fixed.
