### ISSUE TITLE
FFPE Tumor Samples: Poor Goodness of Fit

### ISSUE THREAD

**Issue by Moe94** [lima1/PureCN#327]
Dear Marcus, 

once again thank you for providing this tool and the great effort you put into this project. 

I am currently struggling to set up PureCN correctly and/or to interpret the results. I have WES data of tumor patients without matched normal. The tumor material is FFPE derived and for quite a lot of these samples I also see quite a lot of noise. Some parameters of my workflow: 
- variant calling is done with Mutect2, I use a padded target interval file (50bp), the flags --genotype-germline-sites true --genotype-pon-sites true are used, I use a PoN with 30 samples
- PureCN is then run with the internal segmentation, a bait bed file could not be provided by the manufacturer, so I had to use the target bed file, the NormalDB was created with the PoN generated with Mutect2, there were too few off target counts so I had to remove the --off-target flag and re-run.

For all of my samples I get a poor goodness of fit flag. A log file of representative samples is attached and here is a snippet: 
![image](https://github.com/lima1/PureCN/assets/235535/ad430a9d-0ff2-47e2-a7c7-2f548cc8e800)

Do you have an idea what might cause this issue? Thank you so much for your help!

Best, 
Moritz
[S81_copy.log](https://github.com/lima1/PureCN/files/12717382/S81_copy.log)

**Comment by lima1** [comment]
Another #320 related issue. The log ratio noise is not too bad for FFPE.

Install the latest devel branch and re-run PureCN.R with --min-base-quality 20.
