### ISSUE TITLE
UMI affect on PureCN estimates

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#328]
Hi Markus,

We are busy testing some datasets using umi barcodes, given that these have lower coverage than our non-umi data we seem to see a trend for lower CNV estimates compared to before. I am not sure if there is a way to correct for this or if there are any parameters we can look at including to improve PureCN outputs? 

Thanks!
Warren

**Comment by lima1** [comment]
Hi Warren, I don't think there is anything to correct. We actually switched to UMIs a while ago and I haven't noticed a difference. What exactly do you observe? Lower number of segments? I would need to see log files of two comparable samples to say more.

**Comment by lima1** [comment]
Feel free to re-open if you find some issues that need attention from my side. As always, it's best to use exactly the same assay for the normal samples. Especially for the coverage normalization. For mapping bias, I can be beneficial to add samples from a closely related assay, but needs double checking.
