### ISSUE TITLE
How to cite in the manuscript if running PureCN with GATK segmentation

### ISSUE THREAD

**Issue by WangKang-Leo** [lima1/PureCN#330]
Hi, I recently ran the WES using PureCN, and GATK segmentation was applied. Could you please clarify that GATK represents GATK-gCNV (https://www-nature-com.proxy.kib.ki.se/articles/s41588-023-01449-0) or conventional GATK (https://gatk.broadinstitute.org/hc/en-us/articles/360035535892-Somatic-copy-number-variant-discovery-CNVs-)? 

Thanks in advance!
Kang

**Comment by lima1** [comment]
It's just a wrapper around ModelSegments: https://github.com/lima1/PureCN/blob/devel/R/segmentationGATK4.R#L103C3-L110C38

Coverage was normalized using the Tangent normalization (https://pubmed.ncbi.nlm.nih.gov/36040167/) implemented in PureCN.

**Comment by WangKang-Leo** [comment]
Thanks for your pormpt reply!

I see now. BTW, maybe it is also great to add  GATK-gCNV into PureCN for WES data in the future. 

Best regards
Kang

**Comment by lima1** [comment]
PureCN is a somatic caller, so most of the germline specific functionality we don't really need.  But I'll have a look, maybe some ideas we can borrow.
