### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mazzalab** [lima1/PureCN#334]
**Description**
I'm in a Ubuntu (latest) Docker container. I've just installed R through conda:
`RUN mamba install -y -c conda-forge r-base=4.3.2`

When I run this command:
`RUN R -e 'BiocManager::install("PureCN", dependencies=TRUE, ask = F)'`

I get the error below.

```
...
ranlib libstreamvbyte.a 
make[2]: ranlib: No such file or directory
make[2]: *** [Makefile:27: libstreamvbyte.a] Error 127
make[2]: Leaving directory '/tmp/RtmpSR9TfQ/R.INSTALL12d7724e3388c/rhdf5filters/src/vbz/third_party/streamvbyte'
make[1]: *** [Makefile:30: streamvbyte] Error 2
make[1]: Leaving directory '/tmp/RtmpSR9TfQ/R.INSTALL12d7724e3388c/rhdf5filters/src/vbz'
make: *** [Makevars:29: libH5Zvbz.so] Error 2
ERROR: compilation failed for package ‘rhdf5filters’
* removing ‘/root/miniforge3/lib/R/library/rhdf5filters’
ERROR: dependency ‘rhdf5filters’ is not available for package ‘rhdf5’
* removing ‘/root/miniforge3/lib/R/library/rhdf5’
ERROR: dependency ‘rhdf5’ is not available for package ‘PureCN’
* removing ‘/root/miniforge3/lib/R/library/PureCN’

The downloaded source packages are in
        ‘/tmp/RtmpDvJHJY/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages(...) :
  installation of package ‘rhdf5filters’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘rhdf5’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘PureCN’ had non-zero exit status
```

What am I doing wrong?

** Env **
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.2 (2023-10-31)

**Session Info**
R version 4.3.2 (2023-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS/LAPACK: /root/miniforge3/lib/libopenblasp-r0.3.25.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: NA
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocManager_1.30.22

loaded via a namespace (and not attached):
[1] compiler_4.3.2 tools_4.3.2

**Comment by mazzalab** [comment]
OK I've the solution:

For some reason, *ranlib* was not installed on my Docker machine. I've then just installed it:
`apt-get install binutils`

and then I could install Purecn flawlessly.

**Comment by lima1** [comment]
See also here our Dockerfile: https://github.com/lima1/PureCN/blob/RELEASE_3_18/Dockerfile

**Comment by mazzalab** [comment]
great thanks!
