### ISSUE TITLE
question about cfDNA run

### ISSUE THREAD

**Issue by maxanes** [lima1/PureCN#340]
Hi Markus,

I'm planning to run PureCN on some cfDNA samples (WES), and I've set up the following configuration. Any suggestion is welcome :)
```
Rscript ${{CONDA_PREFIX}}/lib/R/library/PureCN/extdata/PureCN.R \
            --out ${{out_FOLDER}} \
            --vcf {inputs['purecn_vcf_file']} \
            --tumor {inputs['purecn_tumor_coverage_file']} \
            --normaldb {inputs['panel_of_normals']} \
            --intervals {inputs['bait_intervals']} \
            --sampleid {manager.config['sample-names']['tumor']} \
            --fun-segmentation PSCBS \
            --min-purity 0.1 \
            --min-af 0.001 \
            --genome hg38 \
            --model betabin \
            --force \
            --post-optimize \
            --seed 42
```
thank you

**Comment by lima1** [comment]
Happy new year!

Looks good. If you don't have a lot of baits around MTAP/CDKN2A, you might want to increase --max-homozygous-loss to something like "0.09,1.3e+07" (edit: just saw you say WES, so not an issue). This makes sure that such huge homozygous deletions are not filtered out. Base quality scores in UMI data can be overly optimistic, so you can either do all filtering upstream and then turn any filtering based on supporting reads, base-quality score off, or be a bit more conservative in retaining borderline calls. 
A few options:

- Lower all BQs by 3: --base-quality-offset 3
- Don't do any filtering by number of supporting reads (if BQs available, these are used to calculate them): --min-supporting-reads 0
- Don't filter by low base quality score --min-base-quality 0

Have a look at the amplification_pvalues.csv file for a simple way of calling amplifications in low purity samples.

**Comment by maxanes** [comment]
Happy New Year! :)

Thanks for your response and valuable advice :)

Regarding additional options, are they particularly beneficial when UMIs or for WES data as well (coverage range of 600x to 1000x)?

BR
Marijana

**Comment by lima1** [comment]
Really depends on your pipeline, how it's tuned towards sensitivity/specificity. These are just a few options to tune that in PureCN. Mostly important for TMB where you don't want a too sensitive pipeline overestimate TMB by including lots of artifacts. You will have plenty of 0% ctDNA samples to check and calibrate if necessary.
