### ISSUE TITLE
plotting error with cell line samples and --min-purity 0.98 --max-purity 0.99

### ISSUE THREAD

**Issue by ThomasGro** [lima1/PureCN#344]
with the following settings I get a plotting error for all my ~400 cell line samples and Mutect2 VCF:

	--genome GRCh38
	--min-af 0.03
	--min-purity 0.98
	--max-purity 0.99
	--min-ploidy 1.4
	--max-ploidy 6.0
	--max-copy-number 7
	--max-segments 300
	--max-non-clonal 0.2
	--min-total-counts 100
	--model-homozygous 
	--model beta
	--fun-segmentation CBS
	--post-optimize 
	--seed 42 

example SDTOUT,SDTERR:
...
Generating output files...
Warning message:
In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
Error in plot.window(...) : need finite 'ylim' values
Calls: plotAbs ... .plotTypeBAF -> plot -> plot.default -> localWindow -> plot.window
In addition: Warning messages:
1: In .Call(.make_vcf_geno, filename, fixed, names(geno), as.list(geno),  :
  converting NULL pointer to R NULL
2: In plot.default(xLogRatio, logRatio$log.ratio, ylab = "Copy Number log-ratio",  :
  NaNs produced
Execution halted

PureCN did not finish successfully for sample CELL_143B!

Any idea what the problem could be or how I can track the problem?

**Comment by lima1** [comment]
Hmm, can't remember seeing this one before. Not sure it's related, but do you run into (other) issues with --genome hg38? PureCN pulls some genome specific annotation files from Bioconductor, and not sure GRC38 works here. I'm might have addressed it, but can't remember.

If not, can you share the full log file of this sample?

**Comment by lima1** [comment]
Actually, before you change anything, can you make sure that you use the latest stable version? I vaguely remember fixing a crash similar to that.

**Comment by ThomasGro** [comment]
Unfortunately this version is part of a workflow systen and cannot easily and quickly be updated.
But I have received a hint in the same direction from a colleague: a newer version of PureCN fixed the issue.
Thank you for following up.

**Comment by lima1** [comment]
Looks like this is the previous bug: https://github.com/lima1/PureCN/issues/260

Maybe try reducing the max-ploidy to something lower if you can't update now. 6 should be super rare.
