### ISSUE TITLE
Applicable for WES (not hybridization capture) 

### ISSUE THREAD

**Issue by jennyp76** [lima1/PureCN#345]
Hi, 
Thanks for the useful tool and continous updates.
My question is how is the performance of PureCN in WES data that used for example SureSelect Human All Exon V6?
I read that PureCN was first developed for hybridization capture-targeted sequencing which is totally different.
Would it be okay to use PureCN for analyzing tumor-only WES data that used SureSelect Human All Exon V6? What should be aware of if so?

If I understood anything wrong, please correct me.
Thanks,
jen

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Copy and paste your complete command line arguments from PureCN.R. If possible and potentially relevant, also copy the output of NormalDB.R and Coverage.R.

**Expected behavior**

**Log file**
Please copy and paste the log file (Sampleid.log) of a representative example

**B-allele frequency plot**
Please take a screenshot of the B-allele frequency plot of the maximum likelihood solution
(Sampleid.pdf).

**Session Info**
Please start R, type sessionInfo() and paste the output.

**Comment by lima1** [comment]
PureCN works well with WES (you still hybridize baits and then capture them in their protocol). PureCN is not optimal for WGS and there are better tools for it. Amplicon sequencing can work with UMI protocol and larger panels with sufficient number of SNPs.

Just follow the best practices vignette. You don't necessarily need --off-target in IntervalFile.R with WES and you can keep it simpler without them.
