### ISSUE TITLE
Commercial use of PureCN

### ISSUE THREAD

**Issue by jennyp76** [lima1/PureCN#346]
Hi, 
Can PureCN be used as a CNV caller for commercial pipeline? 

Thanks, 
jen

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Copy and paste your complete command line arguments from PureCN.R. If possible and potentially relevant, also copy the output of NormalDB.R and Coverage.R.

**Expected behavior**

**Log file**
Please copy and paste the log file (Sampleid.log) of a representative example

**B-allele frequency plot**
Please take a screenshot of the B-allele frequency plot of the maximum likelihood solution
(Sampleid.pdf).

**Session Info**
Please start R, type sessionInfo() and paste the output.

**Comment by lima1** [comment]
Yes, it comes under the standard open source license used by most R packages. If you make non trivial changes and share the modifications outside your company, you are technically expected to make the code available under same license etc.

**Comment by jennyp76** [comment]
@lima1 
Thank you for the quick reply. 
Just for double-checking...so there's no groundwork that needs to be done for using PureCN in return for cost?

Thank you

**Comment by lima1** [comment]
Nope, you all good. If you change the PureCN code, the license says you should publicly provide the code when you share it. Otherwise you can do what you want with it.
