### ISSUE TITLE
IntervalFile.R

### ISSUE THREAD

**Issue by gagank4911** [lima1/PureCN#348]
Rscript $PURECN/IntervalFile.R --in-file OncoMonitor_targets.bed \
    -
-fasta Homo_sapiens_assembly38.fasta --out-file $OUT_REF/baits_hg19_intervals.txt \
    --off-target --genome hg38 \
    --export $OUT_REF/OncoMonitor_targets_optimized.bed \
    --mappability GCA_000001405.15_GRCh38_no_alt_analysis_set_100.bw \
    --reptiming GCA_000001405.15_GRCh38_no_alt_analysis_set_76.bw
Usage: /home/gagan_indx/R/x86_64-pc-linux-gnu-library/4.1/PureCN/extdata/IntervalFile.R [options]

/home/gagan_indx/R/x86_64-pc-linux-gnu-library/4.1/PureCN/extdata/IntervalFile.R: error: Error in getopt(spec = spec, opt = args) :
  " " is not a valid option, or does not support an argument

--fasta: command not found

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Copy and paste your complete command line arguments from PureCN.R. If possible and potentially relevant, also copy the output of NormalDB.R and Coverage.R.

**Expected behavior**

**Log file**
Please copy and paste the log file (Sampleid.log) of a representative example

**B-allele frequency plot**
Please take a screenshot of the B-allele frequency plot of the maximum likelihood solution
(Sampleid.pdf).

**Session Info**
Please start R, type sessionInfo() and paste the output.

**Comment by lima1** [comment]
Hi, that‘s not a PureCN issue. A new line in Bash is a new command. The backslash is used to prevent this. https://stackoverflow.com/questions/3871332/how-to-tell-bash-that-the-line-continues-on-the-next-line
