### ISSUE TITLE
Seems forgotten assignmet operator

### ISSUE THREAD

**Issue by sleyn** [lima1/PureCN#356]
Hello!

I was looking on implementation of tangent normalization and found an operaton without an assignment operator: `fcnts_std_final - median(apply(fcnts_std_final,2,median))` in `createNormalDatabase.R`.

It looks like it should be `fcnts_std_final <- fcnts_std_final - median(apply(fcnts_std_final,2,median))`

https://github.com/lima1/PureCN/blob/c7fddf087671538c995cd665b85a5d354a3aa9ef/R/createNormalDatabase.R#L217C5-L217C62

**Comment by lima1** [comment]
Oh. That's an important part of the code base. Will have a look. I benchmarked against GATK4 back then and got identical results, so hopefully that value is expected to be 0 most of the time. Thanks again!

**Comment by lima1** [comment]
Was indeed close to 0 in all of my datasets. Should be fine now though.
