### ISSUE TITLE
Small panel triggers an error in the `.getAverageWeightPV` function

### ISSUE THREAD

**Issue by tinyheero** [lima1/PureCN#363]
Hi,

I've got a small panel (< 800 targets) that I am trying to run through PureCN just to see if it would work (I recognize that it isn't the best dataset to use). 

I've hit the following error:

```r
cannot take a sample larger than the population when 'replace = FALSE'
```

I've traced the issue down to the [.getAverageWeightPV()](https://github.com/lima1/PureCN/blob/devel/R/segmentationCBS.R#L438-L451) function that is called during CBS segmentation. In particular, the line:

```r
permutations <- lapply(num_marks, function(l)
        sapply(sample(length(weights), perm), .do_permutation, l))
```

is causing this issue as `perm` is hardcoded to 2000. As such, it can't sample 2000 without replacement since we have < 800 targets. 

I am not sure what these weights are being used for. I am just curious as to whether lowering this parameter is a good idea or not to get past this issue?

**Comment by lima1** [comment]
Thanks @tinyheero . I'll have a look. My toy examples are pretty small and they run through, so it should work.

**Comment by lima1** [comment]
Should be fixed now in the issue_363 branch I will merge when it runs through. Should make it into the next stable version next week.

This p-value is used for flagging segments that consist of baits that have a high variance in the pool of normal samples (requires the normaldb).

**Comment by tinyheero** [comment]
Thanks @lima1!
