### ISSUE TITLE
PureCN.R Error

### ISSUE THREAD

**Issue by toddcreasy75** [lima1/PureCN#37]
I'm trying to run PureCN.R after Coverage.R and I'm getting a cryptic error (see at the very bottom) that I can't debug. I notice there's a lot of warnings for low coverage but I'm not sure if this is what is causing the error. Any thoughts?

-todd

INFO [2018-06-29 11:17:15] Loading PureCN 1.11.10...
WARN [2018-06-29 11:17:34] Multiple chromosomes with very low coverage: 1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,3,4,5,6,7,8,9,X,Y
INFO [2018-06-29 11:17:58] Mean coverages: chrX: 0.08, chrY: 0.05, chr1-22: 0.12.
INFO [2018-06-29 11:17:58] Sample sex: M
INFO [2018-06-29 11:18:06] ------------------------------------------------------------
INFO [2018-06-29 11:18:06] PureCN 1.11.10
INFO [2018-06-29 11:18:06] ------------------------------------------------------------
INFO [2018-06-29 11:18:06] Arguments: -tumor.coverage.file /ts18/ngs/studies/ngs_000261/bwa/G04971TB02_S24.sorted_pos.dedup.recal_coverage_loess.txt -seg.file  -vcf.file /ts18/ngs/studies/ngs_000261/bwa/G04971TB02_S24.mutect2_sel.dbsnp.vcf.gz -genome hg19 -sex ? -args.setMappingBiasVcf NULL -args.segmentation NULL,/Biomarker/sih/Databases/PureCN_data/NormalDB/b37/target_weights_SS_v6_b37.txt,0.005,NULL -sampleid G04971TB02_S24 -min.ploidy 1 -max.ploidy 6 -max.non.clonal 0.2 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file /Biomarker/ngs/database/pureCN/b37/baits_b37_V6_intervals.txt -max.segments 300 -plot.cnv TRUE -DB.info.flag DB -model beta -post.optimize FALSE -BPPARAM  -log.file /ts18/ngs/studies/ngs_000261/bwa/G04971TB02_S24.log -normal.coverage.file <data> -normalDB <data> -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2018-06-29 11:18:06] Loading coverage files...
WARN [2018-06-29 11:18:15] Multiple chromosomes with very low coverage: 1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,3,4,5,6,7,8,9,X,Y
INFO [2018-06-29 11:18:20] Mean target coverages: 0X (tumor) 0X (normal).
WARN [2018-06-29 11:18:20] Large difference in coverage of tumor and normal.
INFO [2018-06-29 11:18:23] Mean coverages: chrX: 0.08, chrY: 0.05, chr1-22: 0.12.
INFO [2018-06-29 11:18:25] Mean coverages: chrX: 0.00, chrY: 0.03, chr1-22: 0.00.
INFO [2018-06-29 11:19:10] Removing 232918 intervals with missing log.ratio.
INFO [2018-06-29 11:19:29] Removing 492 intervals excluded in normalDB.
INFO [2018-06-29 11:19:29] Removing 54020 intervals with low total coverage in normal (< 150.00 reads).
INFO [2018-06-29 11:19:29] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2018-06-29 11:19:29] Using 0 intervals (0 on-target, 0 off-target).
INFO [2018-06-29 11:19:29] No off-target intervals. If this is hybrid-capture data, consider adding them.
Error in sort(abs(diff(genomdat)))[1:n.keep] :
  only 0's may be mixed with negative subscripts
Calls: runAbsoluteCN -> smooth.CNA -> trimmed.variance
Execution halted

**Comment by lima1** [comment]
Are you sure the input BAM files for Coverage.R are fine? This usually happens with corrupt BAM files.
Coverage.R assumes a standard BAM file generated following GATK best practices, with duplicates marked.

**Comment by toddcreasy75** [comment]
You were right. I was using a bad sequencing sample that had very low coverage. I meant to move it out of the way but forgot to. Everything ran fine when I used a good sample.

Thanks!

-todd
