### ISSUE TITLE
Cancer Cell Fraction for CNVs

### ISSUE THREAD

**Issue by jberg1999** [lima1/PureCN#374]
Hi Markus,

Thank you for your help with my previous issue! I am now interested calculating the cancer cell fraction of CNVs called by PureCN. I know this information is available for SNPs, and I found that there is a subclonal probability in the C.Posterior dataframe. However I am interested in the equivalent of the SNP columns CELLFRACTION, CELLFRACTION.95.LOWER, and CELLFRACTION.95.UPPER except for the CNVs. Is this data computed by PureCN or available anywhere in the PureCN output? 

Thanks!

**Comment by lima1** [comment]
Hi @jberg1999 , it's unfortunately not as easy as you don't know the number of copies of the sub-clonal alteration. For LOH, it should be possible to get the CIs with reasonable accuracy, but for amplifications you would have a huge CI I assume. So, for SNVs, you can kind of suspect that the sub-clonal mutation only has a copy of one. But a copy number of 2.5 could be 50% normal, 50% 3 copies, or 75% nomral, 25% 4 copies etc.

On top of that, the detection of sub-clonal alterations is currently not as accurate as it could be. I started to improve it a few years ago, but it didn't go very far yet.

Ludwig Geistlinger worked quite a bit on that topic here: https://aacrjournals.org/cancerres/article/80/20/4335/645870/Multiomic-Analysis-of-Subtype-Evolution-and 

Maybe you can find some inspiration there.

**Comment by jberg1999** [comment]
Thank you for the recommendation Markus! Since it is not currently possible to call copy number CCFs in PureCN I will close this issue.

**Comment by jberg1999** [comment]
Thank you for the recommendation Markus! Since it is not currently possible to call copy number CCFs in PureCN I will close this issue.
