### ISSUE TITLE
Pass explicit tab separator when reading CNVkit files

### ISSUE THREAD

**Issue by lbeltrame** [lima1/PureCN#38]
Some CNVkit files have missing data in the RepeatMasker column (in particular `cnn` files) when the data is not available for that position. 
PureCN uses `read.table` to load them, however it uses the default separator (`sep=""`) which means that all whitespace is treated as separator. In case of these missing data, there is nothing in the column, so it ends up being as `\t\t`. This is processed by `read.table` as a single field, and thus parsing files (header has 9 fields, the collapsed field makes them 8 in that specific line).
Setting an explicit tab separator (which is what CNVkit outputs to, anyway) should fix this behavior.

**Comment by lima1** [comment]
Thanks Luca!
