### ISSUE TITLE
NormalDB.R has different requirements to its CLI despite what it is written in the documentation

### ISSUE THREAD

**Issue by lbeltrame** [lima1/PureCN#39]
The docs ( "Quick.pdf" from the current Bioconductor release) state:

> See the main vignette for more details and file formats.
> For a production pipeline run we provide again more information about the assay and genome.
> Here an CNVkit example (CNVkit runs without normal reference samples are not recom-
> mended):

```
# Provide a normal panel VCF to remove mapping biases, pre-compute
# position-specific bias for much faster runtimes with large panels
# This needs to be done only once for each assay
Rscript $PURECN/NormalDB.R --outdir $OUT_REF --normal_panel $NORMAL_PANEL \
--assay agilent_v6 --genome hg19 --force
```

But trying to do something similar:

```
Rscript /usr/lib64/R/library/PureCN/extdata/NormalDB.R --normal_panel normals.vcf.gz --assay agilent_oneseq --genome hg19 --outdir purecn
INFO [2018-07-30 11:47:58] Loading PureCN 1.10.0...
INFO [2018-07-30 11:48:11] Creating mapping bias database.
INFO [2018-07-30 11:48:14] Processing variants 1 to 5000...
INFO [2018-07-30 11:48:18] Processing variants 5001 to 10000...
INFO [2018-07-30 11:48:22] Processing variants 10001 to 15000...
INFO [2018-07-30 11:48:27] Processing variants 15001 to 20000...
INFO [2018-07-30 11:48:31] Processing variants 20001 to 25000...
INFO [2018-07-30 11:48:35] Processing variants 25001 to 30000...
INFO [2018-07-30 11:48:40] Processing variants 30001 to 35000...
INFO [2018-07-30 11:48:49] Processing variants 35001 to 40000...
INFO [2018-07-30 11:48:54] Processing variants 40001 to 45000...
INFO [2018-07-30 11:48:58] Processing variants 45001 to 50000...
INFO [2018-07-30 11:48:58] Position chr17:78934088
INFO [2018-07-30 11:49:02] Processing variants 50001 to 55000...
WARN [2018-07-30 11:49:05] No --coveragefiles provided. Cannot generate normal database.
```

**Comment by lima1** [comment]
Hi Luca, 

If you use CNVkit for coverage normalization and segmentation, you don't need the coverage files. The NormalDB.R script should have created the mapping bias database and that's all you need.

I realize that there is some confusion with --normal_panel, normalDB, mapping bias database and pool of normals. I'll try to clean up this historic mess for the next release (the developer version is btw safe to use, there were no new features, just cleanups and minor bugfixes).

For your benchmarking and if you have the bandwidth, would be great if you can compare CNVkit's and PureCN's normalization.  PureCN is doing a few extra steps to avoid wrong breakpoints and clusters segments. If this improves things, I'm happy to add this to the CNVkit import.

Markus
