### ISSUE TITLE
PureCN.R --rds option no change in output files

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#41]
After running PureCN.R once on a sample, I edited the .csv file that holds the purity/ploidy and Curated flag, and changed the purity and ploidy to a different PureCN solution than the maximum-likelihood solution, and set the Curated flag TRUE.  I used readCurationFile() to read the .rds file so that it would reorder the solutions (but I did not save the new rds object, maybe that's the problem).  Then I moved all PureCN output files except the .rds and curation .csv files to another location and reran PureCN.R, this time specifying the --rds option.  PureCN.R regenerated all the output files.  However, when I compared them to the original files, they were identical (except the curation .csv file was left untouched and still had the curated values in it).

Is this expected???  I expected that some values in some of the output .csv files would be a function of the selected solution's purity and ploidy, and that some plots in the .pdf files would be based on the selected solution's purity and ploidy.  For example, the _segmentation.pdf file I expected to be different, but it wasn't.

**Comment by lima1** [comment]
There is no need for readCurationFile(). Just edit the CSV file to another solution and then rerun PureCN.R with --rds. It will use readCurationFile and recreate the output files. Not all output files will change, segmentation.pdf for example is the DNAcopy output, which is not dependent on purity/ploidy.
The Curated flag will protect the file from overwriting in case you re-run PureCN in the same directory.

**Comment by tedtoal** [comment]
I did just that, but the files did not change.  I copied all files to another directory, then deleted all but the one .csv and the .rds, then ran PureCN with --rds, then did:

```
diff -q PureCN_output_dir  Saved_file_dir
```

and it showed only the .pdf files being different. None of the .csv files were different.  And when I looked at the pdfs, they appeared to be unchanged also.

**Comment by lima1** [comment]
So when you load the RDS file in R with 

rds <- readCurationFIle("Sample.rds")
plotAbs(rds, 1, type="hist")

You get the solution most closest to the one in the curated CVS file?

If you now load the file with 

rds <- readRDS("Sample.rds")
plotAbs(rds, 1, type="hist")

You get the default maximum likelihood solution? If that doesn't work, then somehow readCurationFile picks the maximum likelihood solution, maybe because the curated one does not exist?

The RDS file is unchanged from a successful PureCN.R run?

**Comment by tedtoal** [comment]
That is correct.  I get two separate solutions plotted when I do the above, depending on which function I used to read the .rds files.  And yet all output files created by PureCN are identical, including the .rds file, when I run it the two different ways.  The first run did not specify --rds option, and at that time the curation .csv file did not exist.  The second run specified the --rds option, with the .rds filename equal to the name of the .rds file created in the first run, and all other arguments the same.  The .log file at the beginning lists arguments but I don't see --rds listed.  Also, searching the log file for "rds" or "RDS" turns up nothing.  I added an output to my pipeline to display the PureCN command line so I could be sure it was definitely using the --rds option.

**Comment by lima1** [comment]
Try running it with only the --rds option, nothing else (e.g. PureCN.R --rds Sample1.rds) . It's possible when you specify all arguments, it will try to re-run PureCN and will stop because the output already exists.

**Comment by tedtoal** [comment]
Running it with only the --rds option caused it not to produce any output files.  Here is the log output:

```
PureCN command:
env -i LD_LIBRARY_PATH=/share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs/LCC_Pipeline/lib/R/library/rJava/libs:/share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs/LCC_Pipeline/jre/lib/amd64/server /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs/LCC_Pipeline/bin/Rscript /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs/LCC_Pipeline/lib/R/library/PureCN/extdata/PureCN.R             --rds DATA/VO-56/T2/PureCN_TumorOnly/VO-56T2.rds
[1] "/share/carvajal-archive/SEQ_DATA/PANELS/MSEQ_GC_Panel_03_28_2017/DATA/VO-56/T2/PureCN_TumorOnly"
INFO [2018-09-21 11:24:55] Loading PureCN 1.11.11...
INFO [2018-09-21 11:24:56] DATA/VO-56/T2/PureCN_TumorOnly/VO-56T2.rds already exists. Skipping... (--force will overwrite)
INFO [2018-09-21 11:24:56] Reading DATA/VO-56/T2/PureCN_TumorOnly/VO-56T2.rds...
Warning message:
In createCurationFile(file.rds) :
  DATA/VO-56/T2/PureCN_TumorOnly/VO-56T2.csv already exists and seems to be edited. Will not overwrite it.
```

**Comment by tedtoal** [comment]
I was wrong.  I didn't notice that my workflow manager had deleted all the files.  It did so because it thought that one expected output file had not been created.  It had in fact been created, but for some reason it is empty.  The file is the "*_segmentation.pdf" file.  Why would it be empty?

**Comment by lima1** [comment]
That file isn't changed by PureCN.R --rds (it's the output plot of DNAcopy and independent of purity/ploidy). It would be empty most likely when the normal PureCN.R file wasn't finished properly.

**Comment by tedtoal** [comment]
Ok, I see what happened, my workflow manager overwrote the original file and created an empty one.  I need to modify the rule to leave out that file when the --rds option is used.

**Comment by tedtoal** [comment]
If the segmentation plot file is created as an early operation within PureCN, it might make more sense to move it to a different (new) .R program (or possibly to Coverage.R???), to make the implementation of workflow manager rules easier.

My workflow manager (snakemake) doesn't allow multiple rules specifying the same output files, so I need to implement the two different forms of PureCN.R command (with and without --rds) in the same rule.  In the one case, the segmentation pdf file is produced, in the other it is not.

**Comment by lima1** [comment]
The segmentation plot is still dependent on various PureCN.R input arguments. If snakemake cannot handle such a case where selected files are updated, maybe copying to a different location first might work? I'm sorry, I don't have a lot of experience with snakemake.

One could outsource the generation of most output files to a new downstream script similar to PureCN --rds, but this would break all existing PureCN pipelines. I'm a little bit hesitant to do that, since it's also hard to pick a better solution by scripting than PureCN.R will (except maybe in situations like yours where you have many samples per patient - and we might add functionality for that special case to PureCN at some point). So I feel like automating PureCN.R --rds won't be that useful for most.

But let me know if there is absolutely no workaround in snakemake.

**Comment by tedtoal** [comment]
I've already got a solution in snakemake, not a big problem.  It seems like each bioinformatics program presents a new problem for a workflow management pipeline.  In PureCN's case, the new problem is that you have one set of files produced initially, then an updated version of the same files generated after manual curation.  Your suggestion of copying to a different location might be the right way to do it - keep around the original uncurated files, and generate new curated files too.
