### ISSUE TITLE
VCF output is not generated

### ISSUE THREAD

**Issue by berguner** [lima1/PureCN#43]
Hello,

I ran PureCN 1.10 with `--outvcf` parameter but it did not generate any VCF files. I want to know which somatic variants are clonal or subclonal. Here is the script that I use to construct the running command:

> Rscript --vanilla /scratch/users/berguener/bin/PureCN/inst/extdata/PureCN.R \
> 	--out $SAMPLE_NAME \
> 	--tumor "${SAMPLE_NAME}_realigned_coverage_loess.txt" \
> 	--sampleid $SAMPLE_NAME \
> 	--vcf mutect1/$SAMPLE_NAME.vcf \
> 	--statsfile mutect1/$SAMPLE_NAME.mutect \
> 	--normaldb ref_bam/purecn_coverage/normalDB_TruSeq_b37.rds \
> 	--normal_panel ref_bam/purecn_coverage/mapping_bias_TruSeq_b37.rds \
> 	--intervals TruSeq_Exome_targeted_regions_b37_intervals_annotated.txt \
> 	--targetweightfile ref_bam/purecn_coverage/target_weights_TruSeq_b37.txt \
> 	--outvcf "${SAMPLE_NAME}_purecn.vcf" \
> 	--minpurity 0.75 \
> 	--genome b37 --force --postoptimize --seed 123

Can you please check. 
Best, bekir

**Comment by lima1** [comment]
Hi Bekir,

--outvcf is a flag, it will automatically name the VCF like you requested. So try removing "${SAMPLE_NAME}_purecn.vcf". If that does not work, please post the log-file. 

And for the genome version, please use hg19 instead of b37. PureCN uses this to annotate intervals and it's using Bioconductor databases for that. These assume hg19/hg38 for human. 

Hope that helps,
Markus

**Comment by berguner** [comment]
Hello Markus, thanks for commenting.

I removed the "${SAMPLE_NAME}_purecn.vcf" and now I have the vcf outputs.

However changing b37 to hg19 caused an error related to chromosome names so I changed it back to b37. I am not really interested in the gene name annotations but I don't know if I am missing anything else.

Best,
Bekir

**Comment by lima1** [comment]
Okay, I might add aliases like b37 to the list. The --signatures flag in Dx.R might require hg19. But it should be easy to edit this script to make it work. It just calls the deconstructSigs package with the corresponding annotation database.  I'll close for now.
