### ISSUE TITLE
Overlapping reads

### ISSUE THREAD

**Issue by psavas** [lima1/PureCN#45]
Thank you for this very well designed and tested software, it is greatly appreciated.

I have a question about PureCN's function for calculating coverage in a bam file - does this function count the overlapping ends of a paired read twice? In FFPE samples, the fragments are often short so the ends of the read overlap.
Reading the source code I can't tell if the coverage function takes this into account or not.
GATK3 DepthOfCoverage apparently does not count overlapping reads twice.

**Comment by lima1** [comment]
It counts reads, so fairly sure it counts overlaps.  I didn’t see a huge difference in our coverages compared to cleaner fragment counts, but haven’t done a thorough benchmarking. You could use GATK4 to get fragment counts. PureCN will take its hdf5 output files, which you can normalize for GC using Coverage.R. Let me know if you find improvements over the default!

**Comment by lima1** [comment]
I think I should add that the average coverages are now only used for filtering. If coverage files contain counts, these are used to calculate log ratios.
