### ISSUE TITLE
calculateMappingBiasVcf with pool of normals containing duplicate samples

### ISSUE THREAD

**Issue by psavas** [lima1/PureCN#47]
Dear Markus,

I have a pool of processed matched normals that I am including in a workflow where there are no tumour-normal pairs. Some of these normals are the same sample sequenced in different batches.

My question is - if I am including duplicate samples in the normal panel vcf, should I alter the parameters of  calculateMappingBiasVcf?

Thank you.

**Comment by lima1** [comment]
No, you should be all good. The only affected parameter is max.pon in runAbsoluteCN. By default, variants found 4 or more times in the pool are removed when they are not in dbSNP, assuming those must be artifacts.

**Comment by psavas** [comment]
Thanks! I will assume therefore that if a common germline variant is flagged as being in dbSNP in the tumour vcf, then the same variant found multiple times in the PON will not be removed as an artifact.

**Comment by lima1** [comment]
Added a comment to the vignette in https://github.com/lima1/PureCN/commit/2d6a6f268a7c8fe558332ea9e5d7fc2dcbd5e1de
