### ISSUE TITLE
CNV burden and duplication homologous chromosomes

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#48]
I want to calculate CNV burden, which is fraction of genome containing a CNV.  However, I realized that in some cases a CNV segment might be present on two homologous chromosomes, so its length would need to be counted twice.  

For example, if  region 10-30 Mbp of one copy of chr1 is duplicated, and region 20-40 Mbp of the OTHER copy of chr1 is duplicated, I presume PureCN would produce 3 CNV segments:

1. 10-20 Mbp at copy number = 3
2. 20-30 Mbp at copy number = 4
3. 30-40 Mbp at copy number = 3

Is there any output from PureCN that would let me distinguish whether a segment is a CNV on both homologous chromosomes?  I would think the germline het SNPs in the region could help distinguish this, although you are already pushing those to find purity and ploidy.  Still, once a purity/ploidy solution is obtained, it should be possible to do this.  Or maybe this is already done?

And of course, clones in the sample further mess with this.

**Comment by lima1** [comment]
Yes, PureCN reports allele-specific copy number. That's actually the main reason we need germline SNPs. For all segments with SNPs (not possible for short segments without them), you get this information from the callLOH output. M is the minor copy number, (C is M+N, M <= N). 

PureCN does not provide the minimum number of copy number events to explain the observed allele-specific copy numbers. You need for example include genome duplication for high ploidy solutions. See the ABSOLUTE paper where they calculate a p-value for genome duplications using related calculations.
