### ISSUE TITLE
Accuracy of LOH "WHOLE ARM" annotation

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#57]
The LOH output data (from callLOH) seems to say that a segment is WHOLE ARM when it is nowhere near such.  For example:

chr18 12678487 15460899   p 2 0 WHOLE ARM COPY-NEUTRAL LOH

In this case, chr18 has a length of 80 Mbp with a p arm of 15 Mbp and a q arm of 60 Mbp, allowing 5 Mbp for the centromere region.  This segment is in the p arm, as annotated, and its length is under 3 Mbp, so it spans about 18% of the p arm.  So why is it called WHOLE ARM COPY-NEUTRAL LOH?  I checked and there are no other segments called on that arm.

**Comment by lima1** [comment]
This is fairly old code and uses the first and last SNP on a chromosome to approximate start and stop. I'll change this soon, thanks for reporting.

**Comment by lima1** [comment]
Actually, now I remember why this is implemented that way. For LOH, SNPs define the resolution, so first and last SNP provide the area where we can call LOH. 

So not a bug, but I will add a warning in case the LOH resolution is poor.
