### ISSUE TITLE
Purity reliability and the FLAGGED flag

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#58]
My samples have rather low purity, because these are gastric cancer tumors and it is typical for the tumor to be diffuse.  Consequently, PureCN makes a lot of calls of purity = 0.15, and many of my samples are FLAGGED (although even those with much higher purity are flagged, not sure why).  Not a single one of the samples is marked FAILED, but I believe you said somewhere in the manual that that flag is for use during manual curation.

Despite the FLAGGED samples, it appears that the CNV results are good for most of them.  However, for some it looks like maybe not.  I have one sample that looks very maginal, and it was called as purity 0.15.  I looked at it in my own experimental algorithm to call copy number and purity, and I see that I kicked it out because it had some problem, probably too few SNVs.

I have two questions.  First, do you think I might be able to lower the lowest purity threshold for PureCN and get better purity estimates for some samples?  Second, is there some way I could get out of PureCN an estimate of how reliable it thinks its purity call is?

**Comment by tedtoal** [comment]
Sorry, I really should have posted this on the forum instead of as a bug, I wasn't paying enough attention.  But it could be flagged as an enhancement suggestion.

**Comment by tedtoal** [comment]
I have never seen NON-ABERRANT

ted

—
Ted Toal, Postdoctoral Researcher
Carvajal-Carmona Lab
Dept. of Biochemistry and Molecular Medicine
4502 GBSF, One Shields Ave
Davis, CA  956626  (530) 263-5986
twtoal@ucdavis.edu

**Comment by lima1** [comment]
Closing it now, keep an eye on #11 for related improvements.
