### ISSUE TITLE
Germline CNV

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#59]
I previously asked if PureCN could be used to call CNV in a germline sample, and you suggested use of a different caller, but if I wanted to try PureCN anyway, to be sure to remove the sample from the pool of normals.  Doing this would require that I make a separate pool of normals for testing each normal sample.  Is it really necessary?  Shouldn't the large number of samples in the pool (33 in my case) make the contribution of any one sample fairly small, and its CNVs have a minimal impact?

Further, I would think a good enhancement to PureCN would be for it to use the pool of normals to try to estimate CNV in each normal, which would then provide a BETTER pool of normals for calling CNV in tumor samples.

**Comment by lima1** [comment]
You can try, but I would recommend to benchmark against other germline callers. 
We're not a germline group, so I'm not fully aware of the latest developments there.

PureCN will project the tumor coverage into the normal coverage space and will then subtract the first 20 eigenvectors, assuming that the main variance in the pool is largely technical noise. If you use a normal that was used in the PCA as tumor,  it might remove signal, not only noise. But not sure.

We rarely have matched normals, so this wasn't on my priority list. But yes, if available it might make sense to run it separately on the normals and remove common segments.  I think that's what TCGA did with their SNP6 data. PureCN should however ignore most CNV sites automatically, especially with larger pools of normals.
