### ISSUE TITLE
Suggestion for chromosome arm output

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#61]
Suggestion: provide output that gives the estimated copy ratio (and minor allele copy number?) for each chromosome arm, whether or not it is detected to vary from the normal.

**Comment by tedtoal** [comment]
I guess not minor allele copy number, not possible to phase reads across chromosome arm with panel data.

**Comment by lima1** [comment]
Not sure I completely understand, but callLOH now gives a  far more detailed output .   The ratio (seg.mean) and minor copy number  (M) is among the output.
