### ISSUE TITLE
Support for haplotypecaller-created VCF

### ISSUE THREAD

**Issue by seedgeorge** [lima1/PureCN#62]
Hi,

I've generated .vcfs for copy number calling from Haplotypecaller, supplying it with normal and a tumour .bams, and running it in genotype mode with the variants from the 1000genome project. Currently this isn't being accepted by PureCN as a valid .vcf (it may not be detecting the tumour sample - defining it by sampleID does not seem to work?), is there any scope to include this? I have found that the germline variant calls produced in this manner (assuming standard filters such as minimum depth etc etc) look ideal for copy number calling.

For clarity, the command used to generate this was: 

```
$java -Xmx4g -jar $gatk4 \
HaplotypeCaller \
-R $assembly \
-I $bamDataDir/$SampleName.tumour.recalibrated.bam \
-I $bamDataDir/$SampleName.normal.recalibrated.bam \
-L $target_intervals \
-ip 200 \
--dbsnp $known_snp \
--alleles $known_snp_hc \
--genotyping-mode GENOTYPE_GIVEN_ALLELES \
-O $gatkDir/VCF/Germline_Calls/Initial/$SampleName.genotyped1000G_bothTN.vcf.gz
```

I've attached an example .vcf (trimmed down substantially)
[example_vcf_trimmed.genotyped1000G_bothTN.vcf.gz](https://github.com/lima1/PureCN/files/2654245/example_vcf_trimmed.genotyped1000G_bothTN.vcf.gz)

My pureCN run was as follows:

```
runAbsoluteCN(tumor.coverage.file  = "cnvkit_output/example_pattumour.recalibrated.cnr",
              seg.file = "cnvkit_output/example_pat.tumour.recalibrated.seg",
              vcf.file = "gatk_output/HaplotypeCaller/example_pat.genotyped1000G_bothTN.vcf.gz",
              genome = "hg38",sex = "M",
              sampleid = "example_pat.tumour",
              args.filterVcf =  list("tumor.id.in.vcf" = "example_pat.tumour"),
              args.segmentation =  list("tumor.id.in.vcf" = "example_pat.tumour")) 
```

All help gladly appreciated.

**Comment by lima1** [comment]
Thanks George, can you try 1.13.9?  Shouldn't be necessary to specify tumor.id.in.vcf anymore.

Problem was that PureCN currently assumes a SOMATIC info flag. I added some code to make a good guess from FORMAT GT.

**Comment by lima1** [comment]
The relevant line in the referenced commit to automatically generate the SOMATIC flag from your VCF is:

info(vcf)$SOMATIC <- apply(geno(vcf)$GT,1,function(x) x[1]!=x[2])

Feel free to change, happy to accept a pull request. The existing code is definitely very basic.

**Comment by seedgeorge** [comment]
At first glance this seems to have done the trick!

**Comment by lima1** [comment]
Closing for now, but please reopen when you find problems.

**Comment by seedgeorge** [comment]
Hi, sorry to reopen this after a long time - any chance you could take another look?
I'm finally implementing this into a pipeline at a large scale, so reviewed the pureCN process that I had piloted before - trying to get my test dataset (as above) to work and I'm getting the following:

```
WARN [2019-07-12 13:14:28] Sampleid looks like a normal in VCF, not like a tumor.
INFO [2019-07-12 13:14:28] example_pat.normal is tumor in VCF file.
```

Which is odd, as I called the command using:
`runAbsoluteCN(tumor.coverage.file  = "cnvkit_output/example_pat.tumour.cnr",
              seg.file = "cnvkit_output/example_pat.tumour.cns",
              vcf.file = "gatk_output/HaplotypeCaller/example_vcf_trimmed.genotyped1000G_bothTN.vcf.gz",
              genome = "hg38",sex = "M",sampleid = "example_pat.tumour")`

I've tried specifying sampleid and leaving that parameter blank, to no avail. 
Is the order of samples in the .vcf a problem? 

I updated pureCN to version 1.15.2 if that matters.
Thanks,
George

**Comment by lima1** [comment]
Hi George, too bad the fix didn't work. 

I'll try to run HC on one of my test samples. If you can share (by email if you prefer) a small test VCF containing a handful of germline and somatic calls, I can look at it quickly.

**Comment by seedgeorge** [comment]
Sending one shortly!

Thanks so much,
George
