### ISSUE TITLE
Mutect2 out of beta verison

### ISSUE THREAD

**Issue by xiucz** [lima1/PureCN#67]
The new release of GATK 4.1.0.0 comes, also, the mutect2 is out of beta version.  I think we should integrate the mutect2 result with purecn more better now.

**Comment by lima1** [comment]
Hi xiucz,

I'l test 4.1.0.0, but is there anything in particular you see that needs improvements? In general, properly filtered Mutect2 VCFs should work fine with PureCN.

Unfortunately some of the GATK3 tools we use haven't been ported to GATK4, like CombineVariants and CallableLoci, but there are replacements in the making.

Markus

**Comment by andrewrech** [comment]
Markus,

Have you looker at the GATK4 workflow with CreateSomaticPanelOfNormals for use with Mutect2 -> PureCN?


Andrew

**Comment by andrewrech** [comment]
Hmm looks like no

https://github.com/broadinstitute/gatk/blob/67f0f0f2e59185b721398b17c24eba487a2ac76c/src/main/java/org/broadinstitute/hellbender/tools/walkers/mutect/CreateSomaticPanelOfNormals.java#L83

**Comment by lima1** [comment]
I'll open an issue with them when I have a chance.

**Comment by lima1** [comment]
Thanks @andrewrech !

**Comment by andrewrech** [comment]
@lima1  Markus, when you tested this, did you add a SOMATIC flag for paired calling using Mutect2?

**Comment by lima1** [comment]
Yes, I added quick and dirty code for this at: https://github.com/lima1/PureCN/blob/aa4c865b93e05f4958f9c60602790dbd07afe6da/R/filterVcf.R#L412 

This was immediately after the added support for germline genotyping, not sure it still works with recent versions.

**Comment by lima1** [comment]
Closing this one. There is another ticket for GATK4 support that will be updated.
