### ISSUE TITLE
recommendations for matched vs unmatched tumors 

### ISSUE THREAD

**Issue by sahilseth** [lima1/PureCN#75]
I have a set of samples, where majority (~40) samples are paired, however, another ~7 are unmatched. As of now, I was thinking of using `FACETS` for matched tumors and `pureCN` for unmatched. However, would ideally like all samples to be processed as consistently as possible. 

I see you have a matched normal mode mentioned in the vignette, but it is highlighted as test case only.

Thanks!

**Comment by lima1** [comment]
We recommend not using the coverage of the matched normal for coverage normalization. It's usually much better to use all normals for normalization. See the preprint of the underlying method https://www.biorxiv.org/content/10.1101/566505v1?rss=1.

PureCN will automatically use the normal information in the input VCFs when available. So for the matched cases, provide Mutect the normal BAM, for unmatched only tumor.

**Comment by lima1** [comment]
Closing it now, feel free to open a new issue when you run into problems or have additional questions.
