### ISSUE TITLE
Dx.R error "Error: subscript contains out-of-bounds indices"

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#82]
In PureCN V1.13.21 I get this error from Dx.R:

```Error: subscript contains out-of-bounds indices```

I traced it to function callMutationBurden(), where there are two statements:

```
p <- p[overlapsAny(p, callable)]
and
vcf <- vcf[overlapsAny(vcf, p)]
```

The length of p after above is one less than the length of vcf, and this leads to the error with this statement:

```
p <- p[which(fun.countMutation(vcf))]
```

I believe the error may be caused by the fact that the BED file I provide Dx.R is a SUBSET of the BED file I provided IntervalFile.R, which I presume is allowable (I only want the mutation burden computed on a subset of the regions).  The one locus which is different between vcf and p above is located at the position given by the start column of one row of the Dx.R BED file, so it should be excluded since adding 1 to 0-based start puts it out of range.  And it IS excluded, p doesn't have it, but vcf does have it.  It seems like vcf should also be intersected with "callable".

**Comment by lima1** [comment]
"since adding 1 to 0-based start puts it out of range."

Can you confirm the callable BED file you provide is 0-based? PureCN (or underlying rtracklayer::import) will automatically convert to 1-based GRanges.

But yes, the callable file can be a subset and usually is.

**Comment by tedtoal** [comment]
Does it matter?  No matter what it is, it should not cause the error.


—
Ted Toal, Postdoctoral Researcher
Carvajal-Carmona Lab
Dept. of Biochemistry and Molecular Medicine
4502 GBSF, One Shields Ave
Davis, CA  956626  (530) 263-5986
twtoal@ucdavis.edu

**Comment by lima1** [comment]
Probably not. I have trouble understanding why "vcf <- vcf[overlapsAny(vcf, p)]" does not remove the filtered variant. Are there maybe indels at that locus?

**Comment by tedtoal** [comment]
Good point.  I went back and looked - still have it loaded into R.  It seems to me the problem is that you are using vcd[] indexes to index into p[]:

p = p[which(fun.countMutation(vcf))]

I’m thinking the above should instead be:

        vcf <- vcf[which(fun.countMutation(vcf))]
        p <- p[overlapsAny(p, vcf)]

**Comment by lima1** [comment]
Probably more robust, yes, although p and VCF should be the same. But there appears to be a corner case leading to a misalignment of both. Thanks for reporting!

**Comment by lima1** [comment]
Sorry for the long delay. But I think BiocManager::install("lima1/PureCN", ref="issue_82") should fix this. Let me know when you have a chance and I will merge into current developer and stable versions.

**Comment by tedtoal** [comment]
I'm just not going to have any time to test that, sorry.

**Comment by lima1** [comment]
No problem.

**Comment by lbeltrame** [comment]
I was affected by this and updating from master I can confirm the issue is gone.
