### ISSUE TITLE
Support for allele-specific copy number in variant results

### ISSUE THREAD

**Issue by lbeltrame** [lima1/PureCN#85]
Rationale: this allows to feed the variant data from PureCN into other programs like PyClone. Given CN segments with known allele CN one could always intersect the data between variants and CN segments, but if these information are already available, why not make use of them?

**Comment by lima1** [comment]
Hi Luca,

the output is probably a little bit confusing, but at least the CSV output should have all the information you need (can add to the VCF output though if something is missing).

ML.M in predictSomatic() lists the most likely number of chromosomes harboring the variant or mutation. For predicted somatic mutations, you also get the CCFs (now with confidence intervals in the latest version 1.14.0). Some tools can use CCFs directly.

Is this what you are looking for?

**Comment by lima1** [comment]
And the minor copy number of the segment is in ML.M.SEGMENT.

**Comment by lbeltrame** [comment]
Well, what I'm looking at is, given for example mutation A>G on a specific coordinate, the copy number of the minor allele (G in this case) and the copy number of the major allele (A in this case). At least from a skim in the docs I wasn't sure that the output would contain these information. 

An alternative would be to intersect the coordinate of the segments with the ones of the variants and associate the major and minor copy number to the variant themselves.

Why all of this? Because PyClone is very specific in what input it wants and (sadly) no one has written up something decent on how to obtain what it needs. (Not blaming PureCN for this: just stating a fact).

**Comment by lima1** [comment]
Okay, yes, then should be all there. 

The copy number of G would be listed in the ML.M column. The copy number of A would be ML.C-ML.M. 
By looking at the ML.M for germline SNPs, we can figure out the paternal and maternal copy numbers. The smaller one of those two is ML.M.SEGMENT. Make sure that PyClone is indeed requiring the variant copy number, not the segment copy number. (Never used PyClone because of the license.)

**Comment by lbeltrame** [comment]
As far as I can understand, it wants the variant copy number. I agree on PyClone, I am not a fan of the license as well (I got "asked" to do so because apparently a lot of groups are using it).

**Comment by lima1** [comment]
If it asks for major and minor copy number (maybe mentions b-allele or SNP array), it is almost certainly ML.C-ML.M.SEGMENT and ML.M.SEGMENT, respectively.

**Comment by lima1** [comment]
What's probably also important for you is the POSTERIOR.SOMATIC column. For PyClone, you probably want to be more on the conservative side so that you don't get clones driven by unfiltered germline variants. Maybe 0.9 or so.

**Comment by lima1** [comment]
Closing now. Feel free to re-open if something is missing for running PyClone. One thing I forgot: I would highly recommend to generate and provide a mapping bias file in case this is tumor-only. Otherwise variants from regions with biased allelic fractions could confuse PyClone.
