### ISSUE TITLE
Getting the "Please add a column 'Gene'" to interval file when i have already added it.

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#88]
Hi there,

I have been trying to get PureCN running and am having some issues with the interval file. As far as I can tell I'm running the right command for creating the interval file and it seems to work fine ( see below - the Gene column is present). But when I run my test sample it complains that the column is not present in the file. Any thoughts? 

Thanks!
Warren

`head /shared/pipeline-user/tools/extra_files/baits_hg38_intervals.txt
Target  gc_bias mappability     reptiming       Gene    on_target
chr1:36557-62252        0.373949252801993       0.374878172194484       NA      .       FALSE
chr1:65572-65897        0.343558282208589       0.5     NA      .       TRUE
chr1:69181-69526        0.459537572254335       0.583333159486453       NA      OR4F5   TRUE
chr1:70719-111939       0.396399893258291       0.142124789385276       NA      .       FALSE`

Command i used:

`Rscript $PURECN/IntervalFile.R --infile /shared/pipeline-user/bcbio/genomes/Hsapiens/hg38/coverage/capture_regions/Exome-NGv3.bed \
--fasta /shared/pipeline-user/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --outfile /shared/pipeline-user/tools/extra_files/baits_hg38_intervals.txt \
--offtarget --genome hg38 \
--export  /shared/pipeline-user/tools/extra_files/baits_Exome-NGv3.bed \
--mappability /shared/pipeline-user/tools/extra_files/GCA_000001405.15_GRCh38_no_alt_analysis_set_100.bw `

` Rscript $PURECN/PureCN.R --out $OUT/$SAMPLEID --sampleid $SAMPLEID --segfile NA12878-1-somatic-cnvkit-call.seg --vcf /shared/pipeline-user/examples/NA12878-exome-eval_somatic_only/final/2019-05-18_project/NA12878-1-somatic-ensemble-annotated.vcf.gz --intervals /shared/pipeline-user/tools/extra_files/baits_hg38_intervals.txt --genome hg38 --parallel
[1] "/shared/pipeline-user/examples/NA12878-exome-eval_somatic_only/final/2019-05-18_project/test"
INFO [2019-05-30 15:59:09] Loading PureCN 1.12.2...
INFO [2019-05-30 15:59:10] test/NA12878-1-somatic.rds already exists. Skipping... (--force will overwrite)
INFO [2019-05-30 15:59:10] Reading test/NA12878-1-somatic.rds...
null device
          1
null device
          1
FATAL [2019-05-30 15:59:51] This function requires gene-level calls. Please add a column 'Gene'

FATAL [2019-05-30 15:59:51] containing gene symbols to the interval.file.

FATAL [2019-05-30 15:59:51]

FATAL [2019-05-30 15:59:51] This is most likely a user error due to invalid input data or

FATAL [2019-05-30 15:59:51] parameters (PureCN 1.12.2).

Error: This function requires gene-level calls. Please add a column 'Gene'
containing gene symbols to the interval.file.

This is most likely a user error due to invalid input data or
parameters (PureCN 1.12.2).
Execution halted`

**Comment by lima1** [comment]
Hi Warren, 

can you post the output of IntervalFile.R? Do you maybe get a warning that annotation packages are missing? You will need TxDb.Hsapiens.UCSC.hg38.knownGene and org.Hs.eg.db.

I would also recommend updating to PureCN 1.14.0 - if you don't want to update Bioconductor, you can install it directly from Github using BiocManager::install("lima1/PureCN", ref="RELEASE_3_9")

And looks like you are using CNVkit? Then I would recommend following the Quick vignette (there is a CNVkit example at the end). You won't need the interval file for CNVkit.

Markus
