### ISSUE TITLE
RFE: Clarify the meaning of the pie charts when using Dx.R

### ISSUE THREAD

**Issue by lbeltrame** [lima1/PureCN#97]
I ran into this because I wanted to show some results generated by Dx.R to biologists, in particular the COSMIC signatures. I wasn't able to find many information on the topic, however.

The main two questions from the signature results in Dx.R are:

- In the CSV output: what do the numbers mean? Are they the results of cosine similarity like other R packages do when using NMF to calculate signatures?
- What does the pie chart represent? A percentage (and of what)?

These are questions that I expect to be made when trying to interpret the results.

**Comment by lima1** [comment]
Hi Luca,

the signatures are described here:
https://cancer.sanger.ac.uk/cosmic/signatures_v2

PureCN is simply calling the deconstructSigs package. Compared to other NMF tools, this package is deconvoluting existing signatures.

Pie chart is percentage of all called signatures. Roughly the fraction of mutations generated by the corresponding signature. The CSV is the same as pie-chart for all signatures.

I'll add a pointer to the vignette.

**Comment by lbeltrame** [comment]
Thanks for the explanation. Related to the same output: Are the signature plots in the first page of the PDF (the ones that come before the pie-chart, I mean) ordered from most prevalent to least prevalent?

I'll have a look at what deconstructSigs does.

**Comment by lima1** [comment]
If I remember correctly, yes. Here the paper: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0893-4

**Comment by lbeltrame** [comment]
I read a bit, and figured it out. The plots are observed signatures, expected signatures, and difference between observed and expected.
