### ISSUE TITLE
Clarify the meaning of the columns for the chromosomal instability scores

### ISSUE THREAD

**Issue by lbeltrame** [lima1/PureCN#99]
I've looked at the documentation and the repository and I wasn't able to find many information on them, at least on what the measures represent.

**Comment by lima1** [comment]
Hi Luca,

Have a look at section 10.5 in the main vignette:
https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/PureCN.pdf

Should be all there.

**Comment by lbeltrame** [comment]
Weird, that didn't come up when searching in the PDF...

**Comment by lima1** [comment]
Yep, it's a new feature in devel.

**Comment by kunstner** [comment]
Hi,
I have a question related to the interpretation of the output of callCIN. I ran callCIN as suggested in the Vignette (point 10.5). The resulting dataframe shows a rather uniform estimate of ~0.8 for CIN. However, what is the interpretation of this value? Are there any cutoffs to divide a sample into stable or instable?
Many thanks,
 Axel

**Comment by lima1** [comment]
Hi Axel,

I don't think there is an established universal cutoff, if you find a relevant paper let me know!

Some cancer types are fairly uniform, late stage breast or lung cancer for example would be probably close to 0.8. Not sure this metric is that useful in those cancer types. In other cancer types such as gastric or bladder cancers you will see more variability and could do some gaussian mixture modeling to assign into high and low.

Markus

**Comment by kunstner** [comment]
Hi @lima1,

many thanks for your quick reply. In the actual case I have a liver sample (metastasis) from a breast tumor.

I haven't done much research on chromosomal instability but your answers is very helpful. I'll do some more literature research on the topic.

Best,
 Axel

**Comment by lima1** [comment]
@kunstner This is often called "fraction of genome altered" in the literature. I checked our samples, 0.8 is on the higher end of metastatic breast cancer, but still pretty common. 

The B-allele frequency plot gives you a good explanation: you should see that most chromosomes have copy number events - unbalanced SNPs and shifts in coverage. Breast cancer is driven by chromosomal instability (usually early genome duplication and then semi-random arm gains and losses), so you should see them almost everywhere in the genome.

**Comment by kunstner** [comment]
@lima1 Many thanks!
